### ISSUE TITLE
Game crash when i want to take out diorite

### ISSUE THREAD

**Issue by GitCodMaster** [P3pp3rF1y/SophisticatedBackpacks#1004]
I was just clearing out my backpacks and then the game keeps crashing when i try to shift click items to get them out of my backpack into my inventory, but then the game crashes. i think it has something to do with the crafting plugin because if i close it the game doesn't crash
Clip: https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/158101468/10dc63e5-0bf7-4df4-b9d2-4ae563637d24

Crash Log: The game crashed whilst mouseclicked event handler
Error: java.lang.IndexOutOfBoundsException: Index 64 out of bounds for length 0
 EXIT CODE -1
[crash-2024-03-13_15.29.56-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14589140/crash-2024-03-13_15.29.56-client.txt)

I am using this Modpack: https://legacy.curseforge.com/minecraft/modpacks/realism-minecraft/relations/dependencies but there should be no confligts because it has nothing to do with any mod then the backpacks thierself.

**To Reproduce**
1. Open backpack
2. make shure to have the crafting addon applied and opened
3. now try to shiftclick Granit out of the Inventory
4. you will see the crash

**Expected behavior**
i expect the Granite to go out of the backpack to go into my inventory.

**Screenshots**
clip: ⏫

**Versions**
I am using Java 17 on 1.19.2 with the newest version available of the S Backpack and S core mod.

**Comment by GitCodMaster** [comment]
I have even more:
It can't be sth with the crafting plugin because i had another crash with a backpack where no plugin was on it and it crashed, but it only crashes with stacked items.

**Comment by P3pp3rF1y** [comment]
Just don't use smooth swapping it's buggy and hasn't fixed this issue for almost a year now.

**Comment by GitCodMaster** [comment]
thank you i won't use it anymore.
Should i Report it in the Git hub of smooth swapping tho?
