### ISSUE TITLE
Can't put milk into fluid container

### ISSUE THREAD

**Issue by morgantic** [P3pp3rF1y/SophisticatedBackpacks#1005]
**Describe the bug**
Despite being able to put water and lava into the fluid tank upgrade, it doesn't accept milk. This seems like a bug, if not, sorry for mislabling a feature request.

**To Reproduce**
1. Open backpack
2. Insert fluid tank upgrade
3. Try to empty milk bucket into tank
4. It's not emptied

**Expected behavior**
I expected to be able to empty milk into the fluid tank since it's a fluid.

**Screenshots**
-

**Versions**
Backpacks v 3.20.1.1012
Forge 47.2.0

**Comment by P3pp3rF1y** [comment]
Is milk a fluid in your modpack? Meaning is there some other mod in your modpack that add milk fluid? Sophisticated definitely doesn't add that.

**Comment by morgantic** [comment]
Hmm. I'm not a huge modded player so I'm not sure if I understand your question correctly.
Would I need a mod that somehow adds milk as a fluid? I would have understood the fluid tank so it allows me to trade a few storage slots for 20 buckets of - well, anything that exists in a bucket, like milk.
But I'm starting to suspect that I'm misunderstanding the way the fluid tank works quite drastically!

Edit, I think I understood the questions, yes, it is, according to JEI:
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/126607370/2319b048-8c58-4c58-a6f1-e26080587db5)

**Comment by TeamSpen210** [comment]
In vanilla, milk isn't a fluid - it doesn't exist as a liquid block or anything, just the bucket item. Honey is the same way. So there isn't a definition for a liquid that can be added to a tank. Forge does actually add a milk fluid, but it's only enabled if a mod requests it to ensure the base install doesn't change gameplay. Maybe Sophisticated should call [`enableMilkFluid()`](https://github.com/neoforged/NeoForge/blob/4064a81df8028ee0fd26610e01a5b7abab8ca6de/src/main/java/net/neoforged/neoforge/common/NeoForgeMod.java#L559)?

If you have another mod that's done that (try placing milk in-world), it should work then.

**Comment by morgantic** [comment]
Ok, I tested more. Since I had milk as a fluid according to JEI (I suppose through create, because I don't think any of the few other mods I have would add that) I tried various things.

I had the fluid upgrade in a copper backpack. Putting a bucket of milk into the input slot did nothing.

I now put the fluid tank module into my gold backpack. Putting a bucket of milk into the fluid tank input slot filled the fluid tank and emptied the bucket!

I then realized I can also right click the bucket into the fluid area to empty and fill. That works **both** in the copper and the gold backpack! 

EDIT, I upgraded the copper backpack to an iron backpack and it works like expected in the gold backpack. 

EDIT2, I tested with a copper tank in creative and I can add milk into the fluid tank by dropping a bucket in the input slot. I can't recreate the issue, but it's behaving like expected now. Thanks y'all for the help!

**Comment by P3pp3rF1y** [comment]
Just tested and even with copper backpack and tank in it if milk is registered as fluid I can get bucket drained into it. So I would need steps how to recreate to be able to do anything here.

**Comment by morgantic** [comment]
Yeah, as I said, I can't recreate it anymore myself. It definitely didn't work with the first copper backpack, but any other copper backpack I now tested with, it works fine. I don't think it's worth trying to investigate this any further, so thanks for your help, I really appreciate it, feel free to close this as solved!

**Comment by P3pp3rF1y** [comment]
Thanks, closing ...
