### ISSUE TITLE
backpacks get dropped on death with keepinventory true

### ISSUE THREAD

**Issue by Mafia-King-90** [P3pp3rF1y/SophisticatedBackpacks#1007]
**backpacks ignore keepinventory true**
My friends and i like to play Minecraft with keepinventory on, because we don't like to get insane after dying and lossing hours of progress. The problem with Sophisticated Backpacks on mc version 1.18.2 is that the backpacks get lost when you die. It would be great if the command could work on the backpacks too.

**To Reproduce**
1. equip backpack
2. die

**Expected behavior**
Drop off your backpack on death

**Versions**
Minecraft: 1.18.2
Forge: 40.2.17
Modpack: DawnCraft - Echos of Legends

**Comment by Mafia-King-90** [comment]
Found a fix for the problem. The problem isn't the mod. It's the modpack DawnCraft with the setting: hard keepinventory of fractured souls.

**Comment by ssaidu001** [comment]
Hey what command did you use to fix the issue? I can't find that setting at all.
