### ISSUE TITLE
Backpack loosing slots more and more

### ISSUE THREAD

**Issue by Bablela26** [P3pp3rF1y/SophisticatedBackpacks#1009]
The Netherite backpack I use for 2 fluid tank upgrades permanently looses its slots more and more from time to time idk when it happens, maybe when server restarts.
It removes the slots that the tank upgrades replace 2 times, I think.

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/80642972/ce3e0800-4c30-4982-aa23-c60062ad3fbf)

sophisticatedbackpacks-1.20.1-3.20.3.1029
sophisticatedcore-1.20.1-0.6.9.569
(happened in previous version)

Edit : I've put the upgrades back into it, and it crashes my game every time I try top open it, at least shift viewing it doesn't crash and all 
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/80642972/abd8038d-85e6-48a1-b506-e2e2cf526948)

**Comment by Bablela26** [comment]
oh and it crashed my game when I placed the 2nd 2 tank back (plus 3 diamond stack upgrades and 1 other tank upgrade)

**Comment by P3pp3rF1y** [comment]
Have you crafted this with the version you have mentioned here or updated to latest since the backpack / upgrades were crafted. Are you able to recreate with that version? If so I will need steps to recreate?

But this really sounds like a bug that was resolved about 2-3 months ago so if you updated from a version older than that your backpack may have already been affected and just getting a new one and using that backpack is the fix for that issue.

**Comment by Bablela26** [comment]
This backpack was crafted and had these problems before I updated to the last version, I don't know the exact update it was on but it was from at least 1 month ago.

I am not sure what is needed for the slots to disappear, but this backpack didn't live a smooth life, I pumped a lot of liquids through it as fast as 60B/s using Create pumps, so I could reproduce it's use, but it isn't it's use directly that causes the bug, there are no problems in normal uses, when leaving and joining the server, and even when the server restarts, the problem isn't immediately noticeable. It's just randomly sometimes when I join the server after a while. 

Edit : Actually I took a screenshot before updating lol
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/80642972/1286e92f-0749-4eff-a4fa-9a4c98c558d5)

**Comment by P3pp3rF1y** [comment]
I will need steps to recreate then as otherwise there's nothing else I can do here. Just seems odd that it would happen on world join sometimes as there's nothing that's done to backpacks there and this really looks like something that's caused by upgrades that remove columns of slots so it should only be happening in relation to adding / removing these upgrades. If you manage to get steps to recreate let me know and I will take a look

**Comment by Bablela26** [comment]
Update :
new backpack, same bug happening again
again with a backpack having only a tank upgrade and stacks upgrades, and no inventory
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/80642972/4c038b4b-7520-4f51-9048-e6a8dc90a6b1)

I might have an idea what is causing this, maybe it's when I remove the tank upgrade that is full, but the Create Pumps continue to work 

(not on the very latest version because the server hasn't updated)

**Comment by P3pp3rF1y** [comment]
Ok @Bablela26 what version are you on then and are the steps to recreate really just keep something pumping fluid into backpack and simply remove tank upgrade?

**Comment by Bablela26** [comment]
Hi!
Current version : Core = 1.20.1-0.6.9.569; backpacks = 1.20.1-3.20.3.1029

Steps I tried to recreate in my solo creative world :
I used 16 pumps and 4 hose pulley linked to 4 sides of a identical backpack, filling it at approx. 44 bucket a second, waited for the 20k tank to fill, and nothing happened when removing the upgrade, reloaded the world and still nothing, so idk it seem to be something else
and yeah... crashing and restarting the game didn't cause that problem either so server crash doesn't seem to be an issue either)

(I love crashing when shift clicking 2 tank upgrades into the backpack XD gonna see if the problem hasn't been reported already and make a issue)

**Comment by P3pp3rF1y** [comment]
I have fixed a few bugs related to how shift clicking stack of upgrades works and how mouse tweaks stack dragging interaction works as well and given your latest unsuccessful effort I am going to close. If a new similar issue comes up please open a new issue for that.
