### ISSUE TITLE
Multiplication Glitch

### ISSUE THREAD

**Issue by Valestro1011** [P3pp3rF1y/SophisticatedBackpacks#101]
If the craft upgrade is set to place the result into the players inventory and is shift clicked it will produce a stack of 64 in the inventory. I have managed to do this to gold and netherite ingots

**To Reproduce**
1. Open backpack
2. set crafting table upgrade to "Shift click result to players inventory"
3. Create an Ingot our of nuggets (ex. Gold or Netherite)

version:1.16.5

**Comment by P3pp3rF1y** [comment]
what version of the mod are you using? there was a bug in there that used to put full stack in player's on shift click which is fixed in the last few versions

**Comment by P3pp3rF1y** [comment]
I can't recreate it in either dev environment or in modpack I am playing so I am going to assume the version where it happened was one before this issue was fixed a few versions back.
