### ISSUE TITLE
Etched compatibility

### ISSUE THREAD

**Issue by SlytherTheUndertaker** [P3pp3rF1y/SophisticatedBackpacks#1010]
For some reason, whenever I put my custom music disc (Specifically from the mod Etched), I can't put it in, yet the discs from Vanilla Minecraft (And probably other modded discs but I haven't investigated that yet) can. I think this might be some sort of incompatibility between Sophisticated Backpacks and Etched.

**To Reproduce**
1. Open backpack
2. Click on custom music disc
3. Drag it to the Jukebox upgrade slot
4. The same custom music disc does not go in the slot

**Expected behavior**
The custom music disc from Etched to be put on the jukebox upgrade slot and also play music

**Versions**
3.20.3.1029
forge: 47.2.0

**Comment by P3pp3rF1y** [comment]
This specifically requires adding compatibility layer because etched adds that to vanilla classes but obviously doesn't to sophisticated ones. I have that on my list to add in the future.

**Comment by P3pp3rF1y** [comment]
Given that we now have sounds stored in components in 1.21 if Etched ports it should use those and custom disks should just work in jukebox upgrade so I am closing this.

**Comment by EarthKone** [comment]
> Given that we now have sounds stored in components in 1.21 if Etched ports it should use those and custom disks should just work in jukebox upgrade so I am closing this.

Is it possible to add compatibility for it in earlier versions? Specifically 1.20.1?

**Comment by P3pp3rF1y** [comment]
@EarthKone 
> > Given that we now have sounds stored in components in 1.21 if Etched ports it should use those and custom disks should just work in jukebox upgrade so I am closing this.
> 
> Is it possible to add compatibility for it in earlier versions? Specifically 1.20.1?

I don't want to spend a lot of time on implementation that's going to work only in that version so no that's definitely not happening.

**Comment by troller2705** [comment]
Etched is on 1.21.1 and it doesn't work in the backpacks still im on 1.21.1 neoforge using etched-4.0.0 and sophisticatedbackpacks-1.21.1-3.24.15.1264

**Comment by P3pp3rF1y** [comment]
yup, I need to take a look at the etched implementation at some point and likely add some compat. Still curious about the reason etched decided to not use vanilla way of adding new records, but I will see once I have time for this.

**Comment by VRaptor436** [comment]
Has this been looked at yet. Im on 1.21 neoforge and wanted to see if this has been implemented or at least seen

**Comment by CB2707** [comment]
It has been years. I yearn for compatibility.
