### ISSUE TITLE
contents of bags disappear when opening the game

### ISSUE THREAD

**Issue by XIII-Knight** [P3pp3rF1y/SophisticatedBackpacks#1014]
so I am playing the Cobblemon modded pack I've seen other people talk about this I've lost so much stuff to this its not even funny 
this is on the most recent version of the pack with a few additions like quark oddities and withering boon for tetra being the most recent  (the command to get the uuid shows different ones for 2 different bags that where from the creative inventory and even one from a mob gets wiped) 

**To Reproduce**

1. open netherite or other backpack 
2. add any upgrades and items
3. close game 
4. open game again
5. open backpack to find it empty and slots from where the tank would be contain nothing and are not even there

**Expected behavior**
items and liquid storage to be there

**Screenshots**
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/1009. has a good screenshot and I don't wanna go through that again if I have to open the game again

**Versions**
sophisticated backpacks version 1.20.1-3.20.3.1034
sophisticated core version 1.20.1-0.6.11.578
forge version  47.2.17
launcher is curseforge launcher if that means anything

**Comment by P3pp3rF1y** [comment]
I can't recreate so I will need info on how I can recreate. Seems like you have some mod in that pack that causes data to not save properly on world close. But if you are able to recreate with just sophisticated let me know how I can do that.

**Comment by ghost** [comment]
I made my own Cobblemon pack, so I wonder if it's a mod related to Cobblemon that causes these issues...can you post your entire mod list so I can compare?

**Comment by XIII-Knight** [comment]
I will try but I never found a good way to get a mod list

**Comment by XIII-Knight** [comment]
here is all the mods and resource packs
[[MODIFIED] Cobblemon (mods and resourcepacks)-v6.4.zip](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14729971/MODIFIED.Cobblemon.mods.and.resourcepacks.-v6.4.zip)

**Comment by P3pp3rF1y** [comment]
I haven't responded to this one in a while, but I don't have time to try to debug random modpacks just to figure out what mod may be causing this issue. If you are still experiencing this issue I will need more details on how to recreate - the smallest set of mod with which this happens. Otherwise I am going to close this in the near future as no one else seems to be experiencing the issue.

**Comment by XIII-Knight** [comment]
I figured it out awhile ago it was the quickstart they added
