### ISSUE TITLE
Weights of items and slowness

### ISSUE THREAD

**Issue by alexeik** [P3pp3rF1y/SophisticatedBackpacks#1015]
Maybe its time to include some wieghts ratio table for ores,tools and other items that influence on slowness?

**Comment by P3pp3rF1y** [comment]
? I am not sure what you mean so I will need more of a description what you are referring to and what you are suggesting.

**Comment by alexeik** [comment]
i mean to inroduce some built-in table with weights of tools,ores
and respect it in slowness factor

**Comment by P3pp3rF1y** [comment]
Well, I feel like this would require extra code that's not really warranted. Having slowness be done based on number of backpacks seems enough to me unless you have some convincing argument why this should be added.

**Comment by alexeik** [comment]
hardcore mode for mining with Terralith mode

**Comment by P3pp3rF1y** [comment]
What is Terralith mode (I am only aware of terralith world gen mod)? Sounds very specific to some mod and they could implement it themselves. I would need a reason that's more general than that.

**Comment by alexeik** [comment]
Yes, it is Terralith mod, not mode:)
I got you

**Comment by P3pp3rF1y** [comment]
closing this one as I am not going to add the functionality and Terralith can tackle it themselves if they need to.
