### ISSUE TITLE
[1.16.5] Log spam issue: "sophisticatedbackpacks-common.toml is not correct. Correcting"

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/SophisticatedBackpacks#102]
**Describe the bug**
I'm getting the following error in my latest.log, and there's a correlation (but no proven causation) with random CTDs during gameplay when this issue is happening. In the config folder, there are a number of .bak files that populate. 

Latest.log: https://pastebin.com/sAa0nBCU (in this example I am able to safely close the game)

**Screenshots**
![image](https://user-images.githubusercontent.com/10929796/112762985-67e85a80-8fb7-11eb-9c22-cd4eef7d8123.png)

**Versions**
1.16.5 v2.2.7.227
Forge: 36.1.2

**Comment by Alaberti** [comment]
Note: The issue seems to go away after entering and exiting a SSP world. I also see this problem on my dedicated server, but there doesn't seem to be an easy fix action for the user.

**Comment by P3pp3rF1y** [comment]
I am just fixing an issue that causes the incorrect config (incorrect regex) so I know why you would get that message once during load, but it should really only be once when configs are loaded and looking at my test server I have seen it in total about 6/7 times so it seems to me that you must have some mod or something there that is aggressively trying to sync config over when it's not correct or something like that. Anyway I believe that once I have this fix this should all go away for you.

**Comment by P3pp3rF1y** [comment]
the latest version on CF should fix this for you https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/3254223

**Comment by P3pp3rF1y** [comment]
btw, the bak files are not something that sbp does, sbp just uses regular config implementation provided by forge and I don't see any such files in my environment or pack that I play with sbp.
