### ISSUE TITLE
Crafting duplication

### ISSUE THREAD

**Issue by de-araujo** [P3pp3rF1y/SophisticatedBackpacks#1020]
**The bug**
The bug is that when 2 people are accessing the crafting bench in one backpack, you can duplicate items by having the other person take one of the items from the crafting recipe out, and the other person who originally placed the items in to make an item takes the crafted item. The rest of the items in the recipe that were left in when the other player took the item out are remaining

**To Reproduce**
Steps to reproduce the behaviour:
1. Open backpack
2. Click on the crafting tab
3. Place items in as if you were going to craft
4. Have a friend take one item out of the crafting bench
5. Shift-click the crafted item out
6. See bug

**Expected behaviour**
When the friend takes out the item from the crafting bench, the recipe is cleared.

**Screenshots**
unfortunately don't have any.

**Versions**
1.20.1

**Comment by P3pp3rF1y** [comment]
This was fixed in the latest release
