### ISSUE TITLE
[1.20.1] Backpack Won't Close After Being Opened

### ISSUE THREAD

**Issue by kraftw** [P3pp3rF1y/SophisticatedBackpacks#1022]
**Description of Issue**
My backpack won't close when I press B, E, or ESC, and I can't press ESC to go to the pause menu causing a soft lock (I checked my key binds and there shouldn't be any issues)

**Mods**
Some of the mods I'm using include Curios, JEI+EMI, & Inventorio which are my guesses to what could be messing with this (If you want a full modlist lmk since its very long)

**Steps to reproduce the behavior:**
0. Put Backpack in back slot [Curios] / Put Backpack in hotbar [Non-Curios]
1. Open Backpack with B [Curios] / Open Backpack with Right-Click [Non-Curios]
2. Try to close with B, E, or ESC
-> Can move mouse to look around
3. Backpack GUI is still open

**Expected behavior**
Backpack to close, ability to access the pause menu, and the ability to move around

**Screenshots**
![2024-04-04_23 54 37](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/87578370/0f02c450-f21f-4246-b945-8bdc13aab161)
*Full mouse control in picture above*
*Also to be noted, the JEI+EMI sprites aren't being rendered*

**Versions**
Mod Version: 3.20.3.1034
Forge Version: 47.2.23

**Comment by P3pp3rF1y** [comment]
I don't think it's either of the mods you have mentioned, but it's definitely caused by some mod in your modpack so you will need to test out removal of which mod make this work again. 

This works for all the other players and I am also playing with it in 1.20.1 in TNP limitless 7 modpack which has 500+ mods and yet it still works. 

Feel free to let me know what the mod is that is causing this but you will need to report to them that they are doing this so that they can fix.

**Comment by kraftw** [comment]
I figured out why you've never seen this issue

It seems to be a compat issue with Flow which is a Fabric mod I'm using via Sinytra Connector
I haven't had any issues with any other GUI's (modded & unmodded) but it may just be because they have Fabric counterparts

I don't expect you to make a fix for this if you don't deem it necessary due to it being a collection of mods and modloaders. I will mention I do see an issue made for this compat issue made 1/31 and tagged a bug last week. Maybe it'll be fixed without you having to do anything.

Thank you for your timely response! I hope this was helpful! :)

Here's a link to the modrinth page for Flow:
https://modrinth.com/mod/flow

**Comment by P3pp3rF1y** [comment]
Yeah in that case please report to them if they even want to fix it given that you're running their mod on forge. and yeah the other option is Sinytra having issues which I saw in the past as well and that can easily produce odd issues / crashes.
