### ISSUE TITLE
[1.19.2] Inventory disappears when sorting

### ISSUE THREAD

**Issue by ThatMFCalledBoRed** [P3pp3rF1y/SophisticatedBackpacks#1024]
**Describe the bug**
whenever my backpack is full it's like everything stacks on each other for just a second resulting in one item being left in the top left slot

**To Reproduce**
1. Open backpack
2. fill slots with many items (possibly from different mobs)
3. input/click sort

**Expected behavior**
backpack inventory sorts accordingly

**Screenshots**
![Screenshot 2024-04-06 143813](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/158995314/1f626c98-a888-4635-b763-27d962ec46f4)

![image_2024-04-06_144109425](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/158995314/f08410cd-2fe8-4da5-bc2c-3ca929cd425f)

**Versions**
sophisticatedbackpacks-1.19.2-3.20.2.1035.jar 
Forge - 43.3.9

**Comment by ThatMFCalledBoRed** [comment]
sometimes it works, sometimes a handful of items stay, sometimes everything deletes

**Comment by P3pp3rF1y** [comment]
Are you able to recreate with only SB in the pack?

**Comment by ThatMFCalledBoRed** [comment]
i'm not able to replicate it

**Comment by ThatMFCalledBoRed** [comment]
it seems to work just fine isolated

**Comment by ThatMFCalledBoRed** [comment]
should i post a list of the mods i'm currently using it with?

**Comment by ThatMFCalledBoRed** [comment]
i did some testing and i believe it's the recent sophisticated core version

**Comment by P3pp3rF1y** [comment]
I will need steps how I can recreate and instead of list of all the mods I would need a minimal list of mods with which it you are able to recreate.

**Comment by ThatMFCalledBoRed** [comment]
here's the modlist i'm using
[Bo_Red's Modlist.zip](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14910617/Bo_Red.s.Modlist.zip)

**Comment by P3pp3rF1y** [comment]
I can't do anything with that list, if you can get me the minimal one with which that issue happens I can take a look

**Comment by ThatMFCalledBoRed** [comment]
the issue is with bigger stacks

**Comment by P3pp3rF1y** [comment]
Right yeah, they do intrusive incompatible changes to sophisticated as far as I recall and I am pretty sure it's not just when you are sorting but in other situations as well. You have to decide whether you want to use sophisticated or bigger stacks and just use one of them.

**Comment by ThatMFCalledBoRed** [comment]
know of any other mods bigger stacks doesnt work well with?

**Comment by P3pp3rF1y** [comment]
I have no idea, but I would guess any gui mod that allows transfering stacks between inventories, mods that allow having larger stack sizes those would be prime examples of mods that could have issues.
