### ISSUE TITLE
Smoked flesh from Born in chaos works but not properly with auto eating

### ISSUE THREAD

**Issue by Aquiles089** [P3pp3rF1y/SophisticatedBackpacks#1026]
If you add smoked flesh to your backpack and select it for auto feeding, the quantity of flesh will not lower, but it'll keep providing an infinite source of food.

Ps: I don't know if it'll make a difference, but im using the upgraded version of the auto feeder.

Mod version: 1.20.1-3.20.3.1039

**Comment by P3pp3rF1y** [comment]
what is smoked flesh? I am guessing it's an item from some mod, but I would need to understand which one._

**Comment by P3pp3rF1y** [comment]
Ahh right you actually mentioned the mod's name in the issue name, let me see what I can see from their code if I will even be able to see anything given that they are closed source.

**Comment by P3pp3rF1y** [comment]
And I tested and am unable to recreate the issue so I will need more info on how I can recreate.

**Comment by P3pp3rF1y** [comment]
And just fyi tested with Smoked Flesh, Smoked Monster Flesh and Smoked Fish just in case these got mixed up. all 3 of them get properly reduced count each time it is fed to player.

**Comment by P3pp3rF1y** [comment]
closing given no response
