### ISSUE TITLE
My Backpack yeeted it's self into oblivion 

### ISSUE THREAD

**Issue by Sereglin** [P3pp3rF1y/SophisticatedBackpacks#1027]
I was taking things out of the backpack and I think I swaped it with the last one. I'm not sure and I can't recreate whatever happened but the backpack disappeared. Yes I looked all around me.  I would think I would just throw it but it's just gone.

I am using version 1.19.2-3.20.1025

**Comment by P3pp3rF1y** [comment]
I will need steps how I can recreate, but this sounds either like it may have automatically been put into some curios slot or picked up by some magnet or something like that. Anyway if you figure out steps how I can recreate I can take a look.

**Comment by Sereglin** [comment]
Looked in the slots. Not there. I looked in all my mine colonies inventories in case is got picked up by a passing NPC. Not there. It's hard to give you specifics because I was just going about playing and then it was gone. But given what happened at the time it either got swaped with some eggs and failed to throw or something or I clicked on a block with it in my hand and it did some interaction that I can't get it to do with another (now empty) backpack that I tried see if it would happen again with. 

I was mostly hoping someone would be able to help figure out what happened so I could avoid it in the future and/or it was an actual bug so it could get fixed

**Comment by Sereglin** [comment]
the only thing with a magnet around was the backpack. Do you think it could have suck in itself?

**Comment by P3pp3rF1y** [comment]
unless you have inception upgrade backpacks can't even go into other backpacks and it would require some mod to break some fundamental things for backpack to already be an item entity and at the same time still exist in player's inventory for the magnet upgrade to trigger

What mods do you have there and are you in single player or in mp? There are some broken multiplayer frameworks that cause all kinds of odd issues so that could be a possibility as well if you're in multiplayer

**Comment by Sereglin** [comment]
single player. But I'm playing with a mod pack that was pre-made for multiplayer

 and oh boy here we go 

 Abnormals Delight 4.1.1
Advancement Plaques 1.4.7
Akashic Tome 1.6-23
Alex's Delight 1.4.1
Alex's Mobs 1.21.1
Amplified Nether 1.2.1
ApexCore 7.3.1
AppleSkin 2.4.2+mc1.19
Aquaculture 2 1.19.2-2.4.8
Architectury 6.6.92
Armourer's Workshop 2.1.0
Art of Forging 1.7.3-1.19.2
Artifacts 1.19.2-5.0.5
AttributeFix 17.2.8
Auto Third Person 2.1
AutoRegLib 1.8.2-55
Autumnity 4.0.1
BHMenu 2.4.1
Balm 4.6.0
Beautify 1.4.3
Better Advancements 0.3.0.148
Better Combat 1.7.1+ 1.19
Better Safe Bed 4
Better Statistics Screen 2.2.2+1.19.2
Biomancy 2 2.3.2.0
Biomes O' Plenty 17.1.2.544
Blueprint 6.2.0
Bone Equipment 1.0.6
BoneZone 1.0.5
Bookshelf 16.3.20
Brewin' and Chewin' 1.19-2.0
Builder's Delight 1.1
Builder's Crafts & Addition 1.19.2-20220926a
Buzzier Bees 5.0.1
Caelus API 1.19.2-3.0.0.6
Catalogue 1.7.0
Chalk 1.6.3
Charm of Undying 6.2.1+1.19.2
Chefs Delight 1.0.2-forge-1.19.2
Cherished Worlds 6.0.5+1.19.4
Chimes 2.0.1
Chipped 2.1.5
Chunk Pregennerator 1.19-4.4.2
Citadel 2.1.4
Cloth Config v8 API 8.3.115
Clumps 9.0.0+14
Collector's Album 1.5.5
Collector's Reap 1.2.4
Comforts 6.0.7+1.19.2
Commonality 4.2.1
Completonist's Index 4.0.0
Configuration 2.2.1
Configured 2.1.1
ConnectedTexturesMod 1.19.2-1.1.6+8
Connectivity Mod 1.19.2-4.6
Construction Wand 1.19.2-2.10
Controlling 10.0+7
CookingForBlockheads 13.3.4
Copper Drops 1.1
Corail Tombstone 8.2.15
CorgiLib 1.0.0.34
CosmeticArmorReworked 1.19.2-v1a
Create 0.5.1.f
Create Enchantment Industry 1.2.8
Create Slice & Dice 2.3.2 
Create Stuff & Additions 2.0.4
Create Bells & Whistles 0.4.4 
Create: Central Kitchen 1.3.10
Create: Dragon Lib 1.2.3
Create: Steam 'n' Rails 1.5.3+forge-mc1.19.2
Creative Core 2.9.3
Creeper Overhaul 2.0.9
Croptopia 2.2.2 
Cucumber Library 6.0.10
Cupboard utilities 1.19.2-2.6
Curios API 1.19.2-5.1.6.1
Daily Rewards 5.3.0
DarkPaintings  13.1.5
Deep Pouches 1.19-1.0.0
Default Options 15.0.2
Detail Armor Bar 2.6.4+1.19.2-forge
Doggy Talents 2 2.6.10
Domestication Innovation 1.6.1 
Domum Ornamentum 1.19-1.0.146-BETA
Drawers Tooltip 6.0.2
Drippy Loading Screen 2.2.2
Dynamic view distance 2.3
Easier Sleeping 2.1.2
Elytra Slot 6.1.1+1.19.2
Embeddium 0.3.5+mc1.19.2
Embeddium++ 1.2.4
EnchantmentDescriptions 13.0.20
Entity Collision FPS Fix 2.0.0.0
Everything is Copper 1.19.2-2.3.4
Ex Nihilo: Sequentia 4.2.0
ExpandAbility 7.0.0
Explorer's Compass 1.19.2-1.3.0-forge
Extreme Sound Muffler 3.39-forge-1.19.2
FTB Essentials 1902.3.5-build.120
FTB Library 1902.4.1-build.236
FTB Quests 1902.5.8-build.345
FTB Teams 1902.2.14-build.123
FTB Ultimine 1902.4.1-build.90
FancyMenu 2.14.9
Fantasy's Furniture 6.7.0
Farmer's Delight 1.19.2-1.2.4
Farmer's Respite 1.19-2.0
Farsight mod 1.19.2-3.6
Fast Suite 4.1.1
Fast Workbench 7.1.4
FastFurnace 7.0.0
FastLeafDecay 30
Fastload-Reforged 3.4.0
Ferrite Core 5.0.3 
Floor Mats 1.19.2-v1.5.6
Flywheel 0.6.10-20
Forge 43.3.2
Forgiving Void 7.0.0
FramedBlocks 6.8.6
Gadgets Against Grind 2.1.0-build.20
GeckoLib 3.1.40
Goblin Traders 1.8.0
Golems Are Friends Not Fodder 1.19.2-0.1.01
Guard Villagers 1.19.2-1.5.9
HalsPirateMod 2.6.4
Handcrafted 2.0.6
Haunted Harvest 1.19.2-3.1.9 
Health Overlay 7.2.1
Hey Berry! SHUT UP 1.19-0.2.0.3
Highlighter 1.1.4
Human Companions 1.19.2-1.7.4
I Know What I'm Doing 5.1.1
Iceberg 1.1.4 
Immersive Aircraft 0.7.5+1.19.2
Immersive Melodies 0.1.0+1.19.2
Incubation 3.0.1
InsaneLib 1.7.5
Integrated API 1.2.7-1.19.2
Integrated Dungeons and Structures 1.7.6+1.19.2
It Takes A Pillage 1.0.3
Italian Delight 1.19.2-2.0
Item Borders 1.2.0
Item Filters 1902.2.9-build.51
Item Production Lib 1.0.2a
Item Physics Lite 1.5.2
Jade 8.9.2
Jade Addons 3.6.0
Jade Colonies 1.0.1
Jumpy Boats1.19-0.1.0.5
Just Enough Items 11.6.0.1019
Just Enough Professions 2.0.2
KleeSlabs 12.3.0
Konkrete 1.6.1
Kotlin for Forge 3.12.0
KubeJS 1902.6.2-build.63
LazyDFU 0.1.3
Leather Overhaul 1.2.0
Legendary Tooltips 1.4.0
LibX 1.19.2-4.2.8
Light Overlay 7.0.1
Little Contraptions 1.19.2.2
Little Logistics 1.4.0
Logprot 1.4
Lootbeams 1.0
Lootr 0.4.26.68
Macaw's Bridges - BOP 1.19.2-1.3
Macaw's Fences and Walls 1.1.1
Macaw's Lights and Lamps 1.0.6
Macaw's Paintings 1.0.5
Macaw's Paths and Pavings 1.0.4
Macaw's Roofs 2.3.0
Macaw's Roofs - BOP 1.19.2-1.4
Macaw's Windows 2.2.1
Marjrusz Library 5.1.2
Marjirusz Progressive Difficulty 1.8.1
ManyIdeas Christmas 1.0.0
ManyIdeas Core 1.4.1
ManyIdeas Halloween 1.0.0
MaxHealthFix 8.0.2
Meet Your Fight 1.19.2-1.3.4
Merchant Markers 1.3.1
MineColonies 1.19.2-1.1.498
MixinExtras 0.2.0
ModernFix 5.14.0+mc1.19.2
Money and Sign Shops 1.19.2-0.0.2
MonsterPlus 1.0
Moonlight Library 1.19.2-2.3.6
More Villagers 4.0.3
Mouse Tweaks 2.23
Multi-Piston 1.19.2-1.2.25-ALPHA
Nature's Compass 1.19.2-1.10.0-forge
Neapolitan 4.1.0
Neko's Enchanted Books 1.8.0
Nether's Delight 1.19-3.1
Nomadic Tents 19.2.0
Nullscape 1.2.2
OAuth 1.1.15
Oculus 1.6.9
Open Parties and Claims 0.20.4
Overflowing Bars 4.0.1
Passive Skill Tree 0.6.10a
Patchouli 1.19.2-77
Paxi 1.19.2-forge-3.0.1
Phantasmic 0.2.5
Placebo 7.3.5
Player Animator 1.0.2
Polymorph 0.46.5+1.19.2
Prism 1.0.2
Productive Bees 1.19.2-0.10.7.2
Productive Villagers 1.0.3
Progressive Bosses 3.7.5
Puzzles Lib 4.4.3
Quark 3.4-418
Quests Additions 1.4.2
Raided 0.1.4
Randomite Classic 1.1.2
Remodifier 1.19.2-2.2.3
Repurposed Structures 6.3.28+1.19.2
Resourceful Lib 1.1.24
Resourceful.config 1.0.20
Respiteful 1.1.2c
Rhino 1902.2.3-build.284
Rotten Creatures 1.0.1
RottenMod 1.0.0
Rubidium (Embeddium) 0.6.2c
Sapience 1.19.2-1.0.1
Second Chance Forge 1.5.1
ServerConfig Updater 3.2
Shield Mechanics 1.19.2-3.5
Shulker Box Slot 5.0.0-beta.2+1.19.2
Simple Inventory Sorter 22.0.0
SimpleHats 1.19.2-0.1.6
Snowy Spirit 1.19.2-2.2.0
Sooty Chimneys 1.2.1
Sophisticated Backpacks 1.19.2-3.20.2.1025
Sophisticated Core 1.19.2-0.6.3.566
Sophisticated Storage 1.19.2-0.9.7.743
SpectreLib 0.12.8+1.19.2
Storage Drawers 11.1.2
Storage Racks 1.19.2-1.5
Structurize 1.19.2-1.0.689-RELEASE
Stylish Effects 4.3.4
SuperMartijn642's Core 1.1.17
Supplementaries 1.19.2-3.4.20
TCF Commons API 2.2+1.19.2
Tectonic 1.1.10
TerraBlender 2.0.1.166
Tetra 5.6.0
Tetratic Combat 2.6.3
TexTrue's Embeddium Options 0.1.1+mc1.19.2
TexTrue's Rubidium Options (TexTrue's Embeddium Options) 1.0.7
Tom's Simple Storage Mod 1.5.9
Tool Belt 1.19.7
Towns and Towers 1.10
Trading Post 4.2.0
TrashSlot 12.1.0
Traveler's Titles 1.19.2-Forge-3.1.2
UI Library Mod 1.19.2-1.0.140-BETA
Upgrade Aquatic 5.1.0
Upgraded Core 1.19.2-4.1.0.1-release
Upgraded Netherite 1.19.2-5.1.0.9-release
Uppers 0.5.1
Useful Hats 1.19.2-3.0.2.0
V-Tweaks 4.0.13
Visual Workbench 4.2.4
Water Strainer 1.19-14.1.1
Waystones 11.4.2
Xaero's Minimap 23.9.7
Xaero's World Map 1.37.8
YUNG's API 1.19.2-Forge-3.8.10
YUNG's Better Desert Temples 1.19.2-Forge-2.2.2
YUNG's Better Dungeons 1.19.2-Forge-3.2.2
YUNG's Better Mineshafts 1.19.2-Forge-3.2.1
YUNG's Better Nether Fortresses 1.19.2-Forge-1.0.6
YUNG's Better Ocean Monuments 1.19.2-Forge- 2.1.1
YUNG's Better Strongholds 1.19.2-Forge-3.2.0
YUNG's Better Witch Huts 1.19.2-Forge-2.1.0
YUNG's Extras 1.19.2-Forge-3.1.0
Yeetus Experimentus 1.0.1-Build.2+mc1.19.1
Zume 0.12.1
clickadv mod 1.19.2-3.6
mutil 5.2.0
stylecolonies mod 1.2.2
villagertools 1.19-1.0.3

**Comment by P3pp3rF1y** [comment]
Nothing really stands out to me out of those mods though I don't know all of them. Anyway I can't do anything with this ticket unless I have steps to recreate and minimal set of mods with which I can do so. If you can provide that I can take a further look.

**Comment by P3pp3rF1y** [comment]
given no additional info was provided I am closing the issue
