### ISSUE TITLE
Backpack Closes while Typing in the Anvil Upgrade after hitting the Backback Keybind

### ISSUE THREAD

**Issue by FeatheredPhantom** [P3pp3rF1y/SophisticatedBackpacks#1030]
Strictly speaking I don't know if I'd call it a bug per say, but while using the Anvil Upgrade within the backpack to rename items, the backpack GUI closes after hitting "B". While I've since personally rebound the keybind to "V", the same issue still occurs when naming anything with a "V".

To replicate, just try to rename any item with a B or whatever corresponding key the Open Backpack hotkey is bound to.

Ideally it wouldn't close just because of hitting the Open Backpack key while trying to rename nametags or any other item. I understand realistically I could just rebind it to a key that I wouldn't normally type with, but it would be nice to not have to.

Sophisticated Backpacks version 1.18.2-3.20.2.1036

**Comment by P3pp3rF1y** [comment]
I have this fixed in dev for 1.20 and 1.21, don't really support 1.18 with anything but critical fixes at the moment and I don't consider this one critical.
