### ISSUE TITLE
Backpack change id in inventory

### ISSUE THREAD

**Issue by NicolasLasch** [P3pp3rF1y/SophisticatedBackpacks#1031]
**Describe the bug**
The backpack changes his idea when a player use the button (from another mod) to sort his bp.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Click on sort
3. See error

**Expected behavior**
The backpack id will have changed

**Screenshots**

**Versions**
Last one

**Comment by P3pp3rF1y** [comment]
When you say ID I am assuming it's UUID, can you share a video of what's happening to you because I am sure I can't recreate this one. Also double check that you are sorting using sophisticated sort button / keybind not using some other mod.

**Comment by P3pp3rF1y** [comment]
closing given no additional info provided
