### ISSUE TITLE
Display bug: Backpack do not display the correct contents when they are in motion

### ISSUE THREAD

**Issue by SourcierDeVerite** [P3pp3rF1y/SophisticatedBackpacks#1033]
**Describe the bug**
I made an automatic tree farm with Create, with a backpack to collect the items, and the items displayed are not the same depending on whether the bag is moving or not. It's just a visual bug, because when the machine stops, the items are back in the bag.

**To Reproduce**
1. Attach the bag to a moving structure (With Create)
2. Activate the machine
3. Look in the bag while the machine is running

**Expected behavior**
See the same items as when the bag is not moving

**Screenshots**
Motionless
![2024-04-13_16 19 53](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/78081509/0b8de94a-2c03-493b-8daf-e7b38666b6a9)

Moving
![2024-04-13_16 20 03](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/78081509/a4639d95-281e-4848-bb46-f2ad77ce0dcf)

**Versions**
Minecraft: 1.20.1
Forge: 47.2.0

**Comment by P3pp3rF1y** [comment]
This is create "issue" or rather that create just converts whatever inventory is attached to it to create's interpretation of that inventory. For this to work as you expect would require an addition of compatibility layer in create that I could then implement compatbility for on SB side. I may try to approach create about that anyway, but this really isn't a bug on my side so closing.
