### ISSUE TITLE
Item transfer

### ISSUE THREAD

**Issue by Pepalela12** [P3pp3rF1y/SophisticatedBackpacks#1037]
Randomly when i try to move items by Shift+Left Click it crashes my game

**To Reproduce**
1. Open backpack
2. Try to transer items by using Shift+Left Click
3. Game crashes

**Expected behavior**
NO CRASH

Crash code:
-805306369

**Versions**
Mod version 1.19.2-3.19.4.977

**Comment by P3pp3rF1y** [comment]
I would need a crash log but I am guessing you're using smooth swapping mod which is incompatible in which case just removing it will fix the issue

**Comment by Pepalela12** [comment]
in fact i was using that mod and it solved the issue. Thanks for the fast response
