### ISSUE TITLE
Game crash when attempting to take out item with shift click

### ISSUE THREAD

**Issue by DarkMarkus0** [P3pp3rF1y/SophisticatedBackpacks#1038]
The game crash when I try take out item from Sophisticated Backpacks thats higher tier than iron or more diferent type of items in it.

Forge ver.: 43.3.5
Minecraft ver.: 1.19.2

[crash-2024-04-22_12.35.24-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/15062011/crash-2024-04-22_12.35.24-client.txt)

**Comment by Lyintrix** [comment]
It's caused by the smooth swapping mod. Delete or disable it to fix the issue.

**Comment by P3pp3rF1y** [comment]
yup that's the case smooth swapping is the issue so just remove it to fix. You can speak to them about fixing their issue but they haven't for a very long time so not sure if that's ever going to happen.
