### ISSUE TITLE
Game Crashes when adding refill upgrade

### ISSUE THREAD

**Issue by HazelsStupid** [P3pp3rF1y/SophisticatedBackpacks#1039]
**Describe the bug**
Crash log if it's a crash.
Info on what other mods you're using that may cause a conflict here if applicable.
over 100 mods from a modpack (i can send screen shot of all the mods if needed)
Crash: 
The game crashed whilst mousereleased event handler
Error: java.lang.AbstractMethodError: Receiver class net.p3pp3rf1y.sophisticatedbackpacks.upgrades.refill.RefillUpgradeItem does not define or inherit an implementation of the resolved method 'abstract java.util.List getUpgradeConflicts()' of interface net.p3pp3rf1y.sophisticatedcore.upgrades.IUpgradeItem.
exit code: -1

**To Reproduce**
1. Open backpack
2. place refill upgrade into upgrade slot
3. game crash :(

**Expected behavior**
refill to work :<

**Screenshots**

**Versions**
1.20.1

**Comment by HazelsStupid** [comment]
LOL NVM IM DUMB I DOWNLOADED THE NEWEST VERSION WORKS FINE 10/10 :3

**Comment by P3pp3rF1y** [comment]
in general when you get AbstractMethodError that means that either the library (in this case sophisticatedcore) or the mod that's using the library (sophisticatedbackpacks) can't see a correct version of some code on the other side which means those versions are incompatible and you should update
