### ISSUE TITLE
1.20.1 forge server doesnt tick backpack when placed

### ISSUE THREAD

**Issue by lolpowerluke** [P3pp3rF1y/SophisticatedBackpacks#1040]
**Describe the bug**
I have a copper backpack with a magnet upgrade in it, when I have it in my inventory it works as intended, but when I place it, it acts like the upgrade isnt there, also when placing the backpack down, the server gives this in the console.

`[24Apr2024 22:44:03.196] [Server thread/WARN] [net.minecraft.world.level.chunk.LevelChunk/]: Block entity sophisticatedbackpacks:backpack @ BlockPos{x=102, y=63, z=323} state Block{sophisticatedbackpacks:copper_backpack}[battery=false,facing=north,left_tank=false,right_tank=false,waterlogged=false] invalid for ticking:`

**To Reproduce**
1. Open backpack
2. add magnet upgrade
3. place backpack down

**Expected behavior**
backpack continues picking up items

**Versions**
backpacks: 3.20.5.1039
core: 0.6.18.597
forge: 1.20.1-47.2.17

**Comment by P3pp3rF1y** [comment]
yes this is known bug that I will have fixed for the next release

**Comment by lolpowerluke** [comment]
I see ty

**Comment by Tejty** [comment]
Is this bug possible to "crash" minecraft server? I have a server with CABIN modpack, that includes this mod, and I ran into issue where if I join, it kicks me, but the server is saying it runs, and I found this thing in the log. There is also a problem with some inventory sorting command, but idk if it's related to backpacks, or if it is the reason of the server not working

**Comment by P3pp3rF1y** [comment]
> Is this bug possible to "crash" minecraft server? I have a server with CABIN modpack, that includes this mod, and I ran into issue where if I join, it kicks me, but the server is saying it runs, and I found this thing in the log. There is also a problem with some inventory sorting command, but idk if it's related to backpacks, or if it is the reason of the server not working

Have you got the exact same message in log? (`state Block{sophisticatedbackpacks:copper_backpack} ... invalid for ticking:`)
Have you updated sophisticated backpacks to fix that?

If you are still getting that error after update I would need more info and very likely new issue logged with the details

**Comment by Tejty** [comment]
Thanks for quick response.
Yes it is the same message. I didn't updated, because my server has it in the modpack, and I have it via the auto forge that automatically downloads the modpack, and I really don't want to remake it. I am mainly asking if it is able to don't let me join the server, or if is it only a small harmless bug

**Comment by P3pp3rF1y** [comment]
> Thanks for quick response. Yes it is the same message. I didn't updated, because my server has it in the modpack, and I have it via the auto forge that automatically downloads the modpack, and I really don't want to remake it. I am mainly asking if it is able to don't let me join the server, or if is it only a small harmless bug

No that only stops the placed copper backpack from having it's tickable upgrades run (so something like magnet wouldn't pickup items around backpack), but there's no way that can prevent player from joining.

**Comment by Tejty** [comment]
Thanks
