### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by yuma-dev** [P3pp3rF1y/SophisticatedBackpacks#1041]
**Describe the bug**
Game crashes on startup when adding Sophisticated Backpacks
Crash log: https://gist.github.com/yuma-dev/612b21542aca9bdff62a23f6b8210327
Travelers Backpack does not seem to cause the issue

**To Reproduce**
1. Add newest Version to Forge(maybe with my mods?)
2. Start

**Expected behavior**
Game Starts

**Versions**
Sophisticated Backpacks 1.20.1 3.20.5.1039
Forge 1.20.1 47.2.17

**Comment by P3pp3rF1y** [comment]
this is definitely not sophisticated as it looks like some mod has modified vanilla code with mixin and sophisticated doesn't use any at all
