### ISSUE TITLE
`BackpackAcccessLogger` uses formatted player name instead of plain username

### ISSUE THREAD

**Issue by andriihorpenko** [P3pp3rF1y/SophisticatedBackpacks#1046]
**Describe the bug**
`BackpackAcccessLogger` creates log entries using player's display name, which often includes prefix, suffix and other server-defined things. This makes using `/sophisticatedbackpacks list <player>` command essentially unusable in various cases.

Regarding prefixes: server owners often map symbols to `.png` textures. This is how custom image prefixes are done. Hence, when I need to access player's backpack via a `/sophisticatedbackpacks list <player>` command, I have to know that special symbol. The chat box becomes unusable due to how Minecraft interprets these symbols.

https://github.com/P3pp3rF1y/SophisticatedBackpacks/blob/cb27ae272ccb65684caa454f361a8f983ab57fee/src/main/java/net/p3pp3rf1y/sophisticatedbackpacks/backpack/BackpackAccessLogger.java#L24

**To Reproduce**
1. Give a player some prefix or suffix using arbitrary characters. You can skip a custom symbol-texture mapping setup and just add a plain text prefix.
2. Use `/sophisticatedbackpacks list <player>` on that player.

**Expected behavior**
Use `Player#getName` instead. This returns a pure player's name from the `GameProfile`.

**Screenshots**
**User prefix**
<img width="284" alt="image" src="https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/13716167/ef4a8914-8b9c-47d5-955c-1d94cce91446">

**Command after pressing on the suggestion or using TAB:**
<img width="457" alt="image" src="https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/13716167/5565ec24-c845-4561-a9e2-2f131cc97bce">

**Added quotes to force command accept space between a special symbol and a username:**
<img width="472" alt="image" src="https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/13716167/15c8c2a3-26b5-44d9-99ba-c13556f7631d">

**Versions**
All versions are affected as the code snippet attached above hasn't changed.

**Comment by P3pp3rF1y** [comment]
I have fixed this in 1.21 dev just now so from there on the access logging will use just plain player name
