### ISSUE TITLE
Can it mod support to prism launcher?

### ISSUE THREAD

**Issue by yanfangxin** [P3pp3rF1y/SophisticatedBackpacks#1047]
Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

My launcher is Prism,it isn't support in there。

**Comment by P3pp3rF1y** [comment]
sounds like you need to raise this with them, there's nothing that mods do about supporting launchers. Mods just support minecraft versions and mod loaders and launchers are then supposed to show mods based on loader / mc version you have selected.
