### ISSUE TITLE
Game crashes on startup!

### ISSUE THREAD

**Issue by SmoothieCubie** [P3pp3rF1y/SophisticatedBackpacks#1049]
Every time I install Sophisticated Backpacks or Sophisticated Core, my game just crashes on startup.
 Crash Report
[crash-2024-04-30_15.00.44-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/15176548/crash-2024-04-30_15.00.44-client.txt)

Mods:
The Aether
Create
Storage Drawers
Create: Steam 'n Rails
Create: Encased
Create: Dreams & Desires
Create: Deco
Create: Ore Excavation
Create: New Age
Create: Crafts & Additions
Storage Drawers
JEI
Jade
Create Enchantment Industry
Create: Misc and Things
Create: Chromatic Return
Curios API
Create: Design 'n Decor
Farmer's Delight
Fastload
Framed Blocks
Journey Map
Dave's BE
Macaw's Bridges
Chipped
Not Enough Crashes
Rechisled
Rechisled: Create
Rubidium Extra
Create: Slice 'n Dice
Create: Track Map
Supplementaries
Create: The Factory Must Grow
Waystones
World Edit

Please help me fix this because the Minecraft crash reports can be really hard to understand.

Version:
I'm play Minecraft 1.20.1 with Forge

**Comment by P3pp3rF1y** [comment]
you need to update chipped
