### ISSUE TITLE
Putting music disk in a backpack upgrade slot, causes server to crash.

### ISSUE THREAD

**Issue by uwuscutely** [P3pp3rF1y/SophisticatedBackpacks#105]
**Describe the bug**
Info on what other mods you're using that may cause a conflict here if applicable.
This was accidentally discovered when a server member was trying to use the jukebox upgrade but in process of doing so accidentally put a music disk in the upgrade slot instead of the jukebox upgrade itself. This caused the server to crash.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Put music disk into backpack upgrade slot. Not sure if the specific disk matters, but the one that was used was "C418 - 13".
3. Server crashes

**Expected behavior**
The backpack should reject the item or have nothing happen if it is not an upgrade module.

**Screenshots**

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
Sophisticated Backpacks 1.16.4-2.2.7.222
Forge 36.1.0

The crash log has been attached.
[crash-2021-03-30_18.00.25-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6231200/crash-2021-03-30_18.00.25-server.txt)

**Comment by P3pp3rF1y** [comment]
You have actually put a dics in backpak upgrade slot - the one to the left of inventory? Disc is supposed to go in jukebox upgrade slot in tab on the right and I am going to check how it is possible to put discs in upgrade slots.

Edit: just reread your description and I can see that it went into the wrong slot. I am going to check how that is possible. as it shouldn't be at all.

**Comment by P3pp3rF1y** [comment]
So I am unable to recreate this in either dev environment or in Enigmatica 6 modpack so it must be some mod that overrides checks on what could go in what slots allowing the disc to go in upgrade slot or more complicated way of getting the disc there other than clicking or shift clicking it or dragging it in.
I will need more details on how I can recreate or more specific info on addition of what mod in your modpack is causing this issue.

**Comment by P3pp3rF1y** [comment]
Found the issue - the items would only go in upgrade slot if there was already upgrade in there - only when its supposed to swap one upgrade for another. I will have a fixed release up for this soon.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
