### ISSUE TITLE
crash when using the anvil upgrade

### ISSUE THREAD

**Issue by Buungle** [P3pp3rF1y/SophisticatedBackpacks#1051]
whenever i leave something in the anvil upgrade slots the backpack is inaccessible and crashes upon attempting to open it

[Render thread/ERROR]:
 Unreported exception thrown!
java.lang.StackOverflowError: null
	at net.p3pp3rf1y.sophisticatedbackpacks.upgrades.anvil.AnvilUpgradeContainer$PersistableAnvilMenu.getItemName(AnvilUpgradeContainer.java:100) ~[sophisticatedbackpacks-3.19.4+mc1.20.1-SNAPSHOT-build.39%20(1).jar:?]

this could be a problem with a mod in my modpack

1. use the anvil upgrade
2. leave any item in the anvil slots
3. exit the backpack
4. reopen backpack, crash

sophisticatedbackpacks-3.19.4+mc1.20.1-SNAPSHOT-build.39.jar

**Comment by P3pp3rF1y** [comment]
Where have you got the mod from? that is definitely not a version I have ever put publicly and even for dev builds I use different versioning.

**Comment by P3pp3rF1y** [comment]
Ah right, you're playing with the unofficial fabric version of the mod. You would want to log the issue here https://github.com/Salandora/SophisticatedBackpacks/issues
