### ISSUE TITLE
Can't insert more than 1 bucket of liquid at a time

### ISSUE THREAD

**Issue by rumpled** [P3pp3rF1y/SophisticatedBackpacks#1053]
**Describe the bug**

Using Refined Storage, trying to automate GT recipe(s) by sending items + fluids into a backpack.
The Refined Storage Crafter shows the error "Machine doesn't accept item" if the recipe uses >1B of fluid.

**Initial Configuration**
Started with a basic Backpack with tank upgrade with capacity of 12B.
Tested reducing the recipe to 1B, everything is inserted successfully (4 items of various quantities, plus the 1B of fluid).

**Other Configurations**
Netherite Backpack, 2 tank upgrades with capacity of 40B each
- Recipe with 1B of fluid is successful
- Recipe with 2B of fluid puts 1B in each tank
- Recipe with 3B+ of fluid fails

Tested with basic Water as well, not just GT fluids.

**Expected behavior**
With 1 tank, any single fluid up to the capacity of the tank should be able to be inserted by a crafter.
With 2 tanks, any two fluids up to the capacity of each tank should be able to be inserted by a crafter.

**Optional behavior**
If identical fluid is inserted into each tank, maybe it could be consolidated? Doesn't seem to be a good way to make that deterministic so maybe not.

**Screenshots**
![2024-05-13_18 00 01](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/563582/f058bd2a-f899-44c4-a5ab-c47e84467f37)
Recipe with 3 buckets fails

![2024-05-13_18 00 37](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/563582/52cb8ae1-460c-456b-b4d8-3b8ebad1c76e)
Test recipe with 2 buckets succeeds

![2024-05-13_18 00 50](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/563582/40a1171b-e8e2-4473-b07b-9e9c24f65c71)
1 bucket inserted into each tank

**Versions**
This is all on ATM9 0.2.58
- Sophisticated Core 0.6.18.597
- Sophisticated Backpacks 3.20.5.1039
- Sophisticated Storage 0.10.20.778
- Refined Storage 1.12.4
- Forge 47.2.20

**Comment by P3pp3rF1y** [comment]
This is working correctly - there's a limit of how fast you can insert `maxInputOutput` in tank config section. That value is per row and if it's lower than 1 bucket then 1 bucket is used as a minimum. If default of 20 is used then in your case you would get max transfer rate of 200 mB which is lower than 1 bucket so 1 bucket is used as max transfer. 
However the other part is that you can use stack upgrades to both increase capacity and with the same multiplier the transfer rate. so with 1 tier 4 upgrade you will get max of 3200 mB per operation here and obviously that gets much higher if you use multiple of stack upgrades.
