### ISSUE TITLE
anvil upgrade causing crashes when books are left in it 

### ISSUE THREAD

**Issue by iGuessImWill** [P3pp3rF1y/SophisticatedBackpacks#1060]
the steps in recreating this are as follows 

1. Add an Anvil Upgrade in the Netherite Backpack.
2. Add two enchanted books in the anvil config inside the Netherite Backpack.
3. Close the inventory menu of the Netherite Backpack.
4. Try to open the Netherite Backpack again.
5. Client crashes and Exit Code: 255 shows up.
---- Minecraft Crash Report ----

as far as i can see it happens in both multi and single player,

[New Compressed (zipped) Folder.zip](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/15442572/New.Compressed.zipped.Folder.zip)

**Comment by P3pp3rF1y** [comment]
This is an issue with the unofficial fabric port so you want to report it here https://github.com/Salandora/SophisticatedBackpacks/issues

**Comment by iGuessImWill** [comment]
thank you il move it to there right now!
