### ISSUE TITLE
1.20.4 forge not suported

### ISSUE THREAD

**Issue by iokoPT** [P3pp3rF1y/SophisticatedBackpacks#1070]
the mod shopisticated backpack on 1.20.4 when trying to download it from curseforge it says i dont have the correct version for it, i try to download online and send it to mods file but it gives me an error when starting minecraft, can i get some help?

1. try to install the mod shopisticated backpack on 1.20.4 but it says forge not suported diferent version

sophisticated backpack version 1.20.4

**Comment by P3pp3rF1y** [comment]
Are you running this with neoforge?

**Comment by P3pp3rF1y** [comment]
Actually just realized you're saying forge in title and no forge isn't supported only neoforge from 1.20.4 going forward
