### ISSUE TITLE
Backpack changes to a model with a battery and vanishes when you shift right click it

### ISSUE THREAD

**Issue by FulotG** [P3pp3rF1y/SophisticatedBackpacks#1071]
I THINK I found how the problem persists! See **BOLDED**

**Describe the bug**
When placing down a backpack (w/ or w/out stuff in) there is an anomaly that happens that is visible by the model it changes into.
This works for any backpack w/ upgrades aswell, and visibly shows the added "battery bank" upgrade on it, this bug doesnt let you open the bag and when shift right clicking to pick up, seemingly diapears, not in hand, nowhere.
No crash, the modpack is *Valhelsia 6* and it is multiplayer on an 8 gig server.

**To Reproduce**
The placement seems to be where I placed each of these shingles previously
1. Place the bag in spot previously having a BlockEntity on it
2. if bugged, the model will change to "See Attached"
![Valhelsia 6 6_8_2024 11_04_36 AM](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/172128408/2297fcb6-af49-4b0d-b6e7-a9966eb0d7ec)
after rightclicking it (Backpack1), it was gone note: when chunk was unloaded and reloaded, the backpack was changed to white
**To reproduce it, place a block with BlockEntities (I used shingles from the mod [Domus Ornamentum](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)) in the place you would like to put the backpack, then remove the BlockEntity block and place the backpack. My guess, the backpack reads a sort of NBT data that block leaves and corrupts the backpack.** 

3. if broken, drops backpack
4. if rightclicked, gain nothing, bye bye backpack

**Expected behavior**
If backpack is placed on a spot prevously occupied with that type of block the change should be apperent

**Screenshots**
SC1
![Valhelsia 6 6_8_2024 11_07_04 AM](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/172128408/77feb041-c4c8-411d-9586-7313530c2ad7)
_Backpack2 placed after right clicking Backpack1(seen above as the white backpack) perfectly normal, almost overwrighting the previous block data_

SC2
![Valhelsia 6 2024-06-08 11-16-38 - frame at 0m35s](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/172128408/cdc0a47a-3be5-491f-9b62-046fbf0c581b)
_Trying to open backpack giving 1 of 2 bugged inventories (duped items in inventory) for 1 frame and the other bugged inventory is a backpack with no slots still only opening for 1 frame_

**Versions**
Sophisticated Backpacks: 3.20.5.1044
Forge: 47.2.30

Thank you and sorry for the Screenshot spam! Much love for the amazing mod aswell!
Edit: tons of edits as I tested this myself, it was kinda fun

**Comment by P3pp3rF1y** [comment]
No worries about sharing many screenshots, but from what you're saying it sounds like this is only recreatable in that specific position so I won't be able to recreate and potentially fix. Though it really sounds like there's some kind of remaining block data in that place that gets messed up together with backpack data which is causing this issue and from the sound of it also server/client desyncs (disappearing backpack / "dupes" of items in inventory). 

if you are able to recreate this in a place where backpack works at the moment please let me know the steps (meaning something like place the shingles, break them, place backpack, ...) otherwise I can't do anything here.

**Comment by iishrnika** [comment]
the same happens to me, i have this problem all over the map sadly, with the backpacks and with the cages from supplementaries too

**Comment by iishrnika** [comment]
My modpack https://www.curseforge.com/minecraft/modpacks/lstb-forge-v2.

**Comment by P3pp3rF1y** [comment]
@iishrnika can you reliably recreate this in any place and what are the steps? And if they are as simple as just placing backpack down I know for sure that just works so I will need to understand minimal set of mods with which it doesn't. (which is likely going to tell you which mod is the actual cause)

**Comment by P3pp3rF1y** [comment]
Also one thing that may be helpful is checking the log at the time the backpack is placed down - are there any errors/warnings logged there at that time?

**Comment by iishrnika** [comment]
I can replicate it, there are no errors when i place the backpack, i don't know how to explain it very good, if you want i can send you the world and the mods for the server.

**Comment by P3pp3rF1y** [comment]
I have no time to debug random modpacks which is why I am asking for the additional info. Basically understand that the issue is either caused by the modpack or server you play on and you would need to figure out what's causing it. Especially given that it's affecting other mods in similar way.

**Comment by iishrnika** [comment]
I have very little information, Basically everything was fine until last week when i added 3 mods, i removed the mods but the problem is still here, no error, no ideea how to debug the problem, the travelers backpacks mod has the same issue on the world.

**Comment by iishrnika** [comment]
nevermind, my problem is slightly different, when placed the backpack dissapears.

**Comment by P3pp3rF1y** [comment]
Can you retry in new world then? Sounds like your world got corrupted.

**Comment by FulotG** [comment]
Sorry for late response
How I replicated it was as followed

1: Using the mods "Donum Ornamentum" and this mod, I would make a shingle block and place it anywhere you need. 
2: After placing it, break it and place your backpack in the spot the shingle was broken
3: The backpack should change model to one that has the "battery pack" upgrade.
Note; Trying to open the backpack would kick you out of bag, and shift right clicking will make the bag vanish. Also if you break the bag to pick it up, you GET the bag, just not any of the contents or upgrades inside

**Comment by P3pp3rF1y** [comment]
Yeah just report this to Domum Ornamentum. I tried breaking shingles and placing vanilla blocks with tile entities (chest and hopper) in its place and they can't be interacted with. So this is not related to SB at all.
