### ISSUE TITLE
[Feature Request] WTHDIPT? Where the heck did I put that?

### ISSUE THREAD

**Issue by bkoee** [P3pp3rF1y/SophisticatedBackpacks#1073]
In my most recent modded server playthough my friends and I can not live without your awesome mod. I started this new world slaying mobs and getting backpacks but now with 7 different BP's I am losing track of my items and which backpack has what in it. Is there a way to implement an inventory search bar? I open my backpack and at the top there is a search bar and if I type "Iron Ingot" it highlights which backpack its in?

Thank you for all of the hard work!

**Comment by P3pp3rF1y** [comment]
I have a feature on the list to add a search bar into sophisticated guis but that's only going to search within that single inventory. What you want doesn't fit the mod and is already part of other mods like https://www.curseforge.com/minecraft/mc-mods/findme
