### ISSUE TITLE
Magnet upgrade can put exp in fluid tank without exp tank upgrade

### ISSUE THREAD

**Issue by Acat1234** [P3pp3rF1y/SophisticatedBackpacks#1081]
**Describe the bug**
Even without the exp tank upgrade the magnet can put exp in the tank and its hard to get out

**To Reproduce**
1. get advanced magnet
2. get fluid tank
3. go near exp
4. it puts exp in tank without exp tank

**Expected behavior**
It doesn't put it in until you get exp tank (also make the upgrade not remove until you get the exp out)
 
**Versions** (That I tested)
5.20.5.1044

**Comment by P3pp3rF1y** [comment]
This is not a bug, but expected behavior.  You should be able to use magnet in backpack to pickup xp as fluid so that you can pipe it out into something else. And if you really don't want magnet picking up xp into tank you can turn that off using a switch in magnet's gui.
