### ISSUE TITLE
1.20.1 tank upgrades not in the right location and crash when first input

### ISSUE THREAD

**Issue by rshtg7776** [P3pp3rF1y/SophisticatedBackpacks#1083]
**Describe the bug**
[relavent_information.txt](https://github.com/user-attachments/files/15937824/relavent_information.txt)

**To Reproduce**
Steps I did before crash (works normally when i did it 1 at a time)
1. Open backpack
2. have xp pump upgrade in upgrade slot 1
3. right click drag tank upgrade into upgrade slots 2 and 3
4. crash

**Expected behavior**
tank visual on left and right of backpack or 2 tanks on right, and no crash

**Screenshots**
![Capture](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/147229785/fabc560a-6ece-4522-85cf-43583ee45a3f)

**Versions**
Forge - 47.2.0
sophisticatedbackpacks-1.20.1-3.20.5.1044
sophisticatedcore-1.20.1-0.6.22.611

**Comment by P3pp3rF1y** [comment]
I can't recreate in dev so I am guessing this is an incompatibility with mouse tweaks that you have there, but I don't in dev. I will see if I can even somehow handle this on my side or call it an incompatibility and that would be it.

**Comment by P3pp3rF1y** [comment]
This was fixed a few weeks back so closing
