### ISSUE TITLE
About copper backpack bug

### ISSUE THREAD

**Issue by SMFDrummer** [P3pp3rF1y/SophisticatedBackpacks#1087]
When installing a magnet upgrade or advanced magnet upgrade on a copper backpack and placing it on the ground, it is unable to absorb surrounding objects, while other backpacks are functioning normally.

That's it.

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/61400112/4f951922-3cb6-4bec-9707-19855c549f3f)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/61400112/e4ed4c1f-4d9b-4148-9995-560a8046f87c)

**Comment by P3pp3rF1y** [comment]
Was fixed in 1.20+, now it's also fixed in 1.18
