### ISSUE TITLE
[1.18.2]Magnet upgrade will copy the item on the ground to the backpack by exponential in Mohist server core build 178 and older

### ISSUE THREAD

**Issue by OldPilot0930** [P3pp3rF1y/SophisticatedBackpacks#1090]
**Describe the bug**
As the title say.

**To Reproduce**
1. Open backpack
2. Install the magnet upgrade
3. Close backpack ui and drop an item
4. Get near by the item

**Screenshots**
[No, but a video](https://1drv.ms/v/c/930853be98f27dd7/EZ8Ki-q6RIVHoVM_3sUP1tUBxbqfR1IvZi9x8ic8kKSWFQ?e=eM5RC1)

**Versions**
[Sophisticated Backpacks 3.20.2.1036](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks),[Sophisticated Core 0.6.4.604](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)

**Detailed of issue**
This bug is triggered not only when the player has a backpack in their inventory, but also when the backpack has placed as a block, and the EXP that have not been collect by the player will also have the same duplication behavior. When the backpack space is full, the number of drops on the ground will also become a set.

**Comment by P3pp3rF1y** [comment]
You need to report this to mohist. That's on them to fix because this is not a bug with forge server

**Comment by OldPilot0930** [comment]
> You need to report this to mohist. That's on them to fix because this is not a bug with forge server

Already reported in a few weeks ago, and Mohist creator has tried to fix it, but no progress untill today...

**Comment by P3pp3rF1y** [comment]
good that you reported it because this definitely needs to be fixed on their side, nothing I can do on mine except for just dropping magnet altogether, which I guess you could do by disabling it as well
