### ISSUE TITLE
Backpack "eats" certain objects when I press "sort"[1.19.2]

### ISSUE THREAD

**Issue by TheRealDoomSlayer69** [P3pp3rF1y/SophisticatedBackpacks#1091]
I use the latest version of spohisticated backpacks along with ice and fire and many other mods. However when I put enchanted items
 in it, such as my enchanted shovel with effiiciency 3 or my dragon horn with my ice dragon and other dragon related items, they disappear and don't reappear. I don't want my progress to go to waste so please fix it

Steps to reproduce:
1.open backpack
2.put inside any enchanted item or anything related to ice and fire that can be bound to an entity
3.press sort

Versions
iceandfire: iceandfire-1.19.2-2.1.13-beta-3
sophisticated backpacks: sophisticatedbackpacks-1.19.2-3.20.2.1035
sophisticated core: sophisticatedcore-1.19.2-0.6.4.605

**Comment by P3pp3rF1y** [comment]
Are you sure you're using backpack sort or have another mod sort it.

You can test if you can recreate it using button at the top of gui or making sure that you're using sophisticated keybind to sort

**Comment by TheRealDoomSlayer69** [comment]
Yes I use sophisticated backpacks and no other backpack mod and I sorted it with the button on the gui

**Comment by P3pp3rF1y** [comment]
I am unable to recreate with vanilla enchanted items in backpack.
And so I need the exact steps I can use to recreate the issue - that is exactly what items should I put in the backpack and sort for this to happen.

**Comment by TheRealDoomSlayer69** [comment]
Also add the mod ice and fire. You need an enchanted vanilla or modded item, and from the ice and fire items you need to put either a dragon horn with any dragon inside, a dragon command staff, a dragon stone bound to said dragon , or a dragon flute.

**Comment by TheRealDoomSlayer69** [comment]
This also happened to me on a server but I tried again on a singleplayer world and the same happened

**Comment by P3pp3rF1y** [comment]
I am unable to recreate with just the items as they are, I am not sure sure how to get dragon inside horn or similar so I can't test with that if you can provide me quick steps I can test that out, but otherwise I will need more info on how to recreate.
Also this is starting to seem to me like you may have some other mod in the pack that messes with sophisticated inventories and causes loss of the items like Bigger Stacks. Could you confirm that you can really recreate with pack that only has sophisticated + ice and fire?

**Comment by TheRealDoomSlayer69** [comment]
Yes I have bigger stacks. Is this the cause of the bug?

**Comment by P3pp3rF1y** [comment]
very likely, try removing it and see if you can recreate

**Comment by P3pp3rF1y** [comment]
I am going to assume bigger stacks was the culprit and close this issue
