### ISSUE TITLE
Holding a backpack in hand breaks Anti Aliasing 

### ISSUE THREAD

**Issue by SudoTronic** [P3pp3rF1y/SophisticatedBackpacks#1092]
**Describe the bug**
No crash, just holding the backpack in your hand (Any backpack) causes anti aliasing to break for the Shrimple shader. Im not sure if this is an issue with backpacks or the shader. 

**To Reproduce**
1: Have the following things installed: 
 1a: Forge for Game version 1.20.1
 1b: Oculus
 1c: Embeddium 
 1d: Shrimple v0.11 (Most recent) 
2: Go in game, use RTX preset for shrimple
3: Hold a backpack in your hand and view the visual bug. 
4: Disable TAA , to observe the bug being fixed. 

**Expected behavior**
No visual problems. 

**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/61809199/73e8d3ca-1eb6-4017-9d4c-d8bc6fa7bff6)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/61809199/a1953d20-e5d9-4517-92cc-d23a177893cf)

**Versions**
sophisticatedbackpacks-1.20.1-3.18.50.853.jar
Forge v47.3.0

**Comment by P3pp3rF1y** [comment]
I don't see how this could be a SB bug as I am not adding anything for RTX / anti aliasing and shrimple appears to have at least one other bug logged for something like this so I would suggest reporting to them first.

**Comment by P3pp3rF1y** [comment]
closing, if this somehow ends up being a SB issue feel free to reopen
