### ISSUE TITLE
Sophisticated backpack sorter bug

### ISSUE THREAD

**Issue by RegnarvsMiiCtA** [P3pp3rF1y/SophisticatedBackpacks#1098]
Everytime I use my backpact tier gold without any other upgrades ans I sort the inventory some items get deleted (iron, gold, swords, shovel, etc..) i don`t know why. And another issue  i have with the backpack is that i can`t get any tool inside by moving it with the mouse but if i click control and left clik it lets me

1. Open backpack
2. Click on sort items

Steps to reproduce the second behavior:
1. Open backpack
2. Click any tool
3. Drag it to the backpack
4. Click to left the item

In the first escenario some items get deleted
In the second escenario u can`t left the tool inside

Im using minecraft 1.19.2 and the version  sophisticatedbackpacks-1.19.2-3.20.2.1035.jar (from 3/19/2024) of sophisticated backpack

**Comment by P3pp3rF1y** [comment]
sounds like you have another inventory mod that does sorting / management of how items get moved between inventory and backpack. Are you able to recreate this with just sophisticated backpacks in the pack (+ sophisticated core of course)

**Comment by P3pp3rF1y** [comment]
closing given no response
