### ISSUE TITLE
Auto smelt Upgrade is Duping Ore's to 64 Stack

### ISSUE THREAD

**Issue by smallerYeet** [P3pp3rF1y/SophisticatedBackpacks#11]
Minecraft Version: 1.16.3
Forge Version: 34.1.42
Mod Version:  0.11.1.81
The Auto smelt is dragging my (modded) Ores into the slot to burn them. 
This dupes them to a full stack.

There is no complicated things needed to reproduce this bug, just let your ore smelt and enjoy

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this. Fairly trivial omission which I got fixed in the new version on curseforge.
