### ISSUE TITLE
does not open the game [better minecaft 1.18.2 forge v20]

### ISSUE THREAD

**Issue by kourgholi** [P3pp3rF1y/SophisticatedBackpacks#1100]
**better minecraft 1.18.2 forge it self does not have much of backpack options
so i tried to add this mod to the modlist and when i try to open minecraft through tlauncher it does not open anything but when i checked the task manager there was a openJDK platform binary task open that it is for mc and when i ended the task tlauncher opened up and said some shit about incompatibility with some mods
if somone tell me what is the mod that its incompatible with i would really apriciate it.

here is the log:**

[log.txt](https://github.com/user-attachments/files/16317674/log.txt)

**Comment by P3pp3rF1y** [comment]
I don't support pirated versions
