### ISSUE TITLE
Backpack inventory disappearing when clicking the sort button.

### ISSUE THREAD

**Issue by JoeMama985** [P3pp3rF1y/SophisticatedBackpacks#1102]
Whenever I open my backpack and click the sort button, the entire inventory jsut disappears. Only UI mods I have are durability tooltip, legendary tooltip, mod name tooltip, modern UI. I can send a full modlist if needed. Obviously the expected behavior is the backpack sorting itself.

I'm on forge 40.2.21, Sophisticated backpacks ver 3.20.2.1036 on 1.18.2
Another lesser issue is the deposit button added by the controlling mod doesn't work

**Comment by P3pp3rF1y** [comment]
Are you using some sort of/ inventory management mod? This definitely looks like some other mod is sorting the inventory

**Comment by JoeMama985** [comment]
I have controlling, cosmetic armor, I can't think of anything else off the top of my head

**Comment by P3pp3rF1y** [comment]
Looking at this now and I am puzzled what the deposit button added by controlling is? controlling as far as I know is mod that allows searching for keybinds I am not aware that it would do any kind of deposit stuff which tells me you have another mod that does that. 
And sorting in other packs in 1.18.2 works like a charm (well unless people use different mods to sort and they run into issues not understanding SB features) so it must be a different mod sorting here.

**Comment by P3pp3rF1y** [comment]
I will assume a mod that has inventory sort functionality was used here and given no additional reports close. but feel free to reopen with steps to recreate / which mods (minimal list) I need to use to recreate the issue
