### ISSUE TITLE
Lag when placing sophisticated backpack on a block.

### ISSUE THREAD

**Issue by biloujay** [P3pp3rF1y/SophisticatedBackpacks#1104]
I get lots of lag when looking at a placed backpack on a block (On the ground and On the wall). When I look away, all the lag disappears. It seems to happen no matter what type of backpack tier it is. It is annoying because I can neither create a storage room or a showcase room with sophisticated backpacks.

1. Place Backpack on the ground in Minecraft Forge 1.19.2.
2. Look at the backpack.
3. Lag occurs.
4. Look away.
5. All of the lag disappears.

I'm not at all of an expert, but I would think its because the model needs abnormally a lot of rendering.

This bug is on Minecraft Java 1.19.2.

**Comment by P3pp3rF1y** [comment]
Have you got any other mods in the modpack like potentially a mod that shows you contents of various blocks with inventories?
