### ISSUE TITLE
Compatibility with Feathers

### ISSUE THREAD

**Issue by MaxWasUnavailable** [P3pp3rF1y/SophisticatedBackpacks#1106]
Also reported at Feathers, here: https://github.com/ElenaiDev/Feathers/issues/50

It seems backpacks cause significant log spam with Feathers, since they're not classified as armour. Is there any chance you could provide compatibility from your end for this?

**Comment by P3pp3rF1y** [comment]
No I can't provide any "compatibility" there's all kinds of items that can go into chest slot that are not armor, like prime example being vanilla elytra. That mod needs to be prepared for non armor items going into chest slot so they need to fix on their side. 
I mean the only "compatibility" I could create would be fixing their code with some mixin.
