### ISSUE TITLE
Right Clicking a backpack inside of ProjectE Tablet DUPE

### ISSUE THREAD

**Issue by ChosenArchitect** [P3pp3rF1y/SophisticatedBackpacks#1109]
**Describe the bug**
https://github.com/ChosenArchitect/Project-Architect-2/issues/101

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Right Click with backpack in hand into a ProjectE Tablet
2. Items will then go into the bag without using EMC
3. You can then take the item out of the backpack
4. DUPE

**Expected behavior**
Have the ability not to click the backpack into the tablet and collect the items (cant find a config to turn off shulker box the right clicking ability)

**Screenshots**

**Versions**
1.20.1-0.10.24.804

**Comment by P3pp3rF1y** [comment]
Fixed this properly by using a more safe way of taking items out of slots so now you can still use backpack in the tablet gui, but it will also use the appropriate EMC. There's new download of Core, SB as well as Storage (because shulker had the same issue) on CF.

**Comment by ChosenArchitect** [comment]
You the best <3
