### ISSUE TITLE
Quark-Related Stacking Issue Upon Reloading World

### ISSUE THREAD

**Issue by Takaska** [P3pp3rF1y/SophisticatedBackpacks#1110]
Hello, I hope you are well! I saw old conversations relating to something similar to this, but none of the ones I saw called out Quark specifically, let alone on 1.20.1, and are unfortunately closed- sorry if there is somewhere else I should have put this!

Yesterday, I created a new Survival world on 1.20.1, in the latest version of Curseforge, spent a few hours collecting and sorting a lot of resources, and then quit- nothing unusual yet. However, logging back into the world today, I found that newly acquired items began to start over in new stacks, but in the correct backpack for what material they were. I could restack everything by manually combining the stacks, but this is the first time I have run into this issue- which I pinpointed to being Quark-exclusive (in my personal modpack at least).

I have no idea if this part will help narrow anything down, but I tested this by throwing both vanilla and modded items (Sophisticated Backpacks and otherwise) out of my inventory to see if Any would be picked up properly; the auto-sorting *only* seems to function as expected when the backpack is *open* while the items are pulled into it.

Perhaps I should note that for Quark, I believe I have everything that could mess with my inventory sorting turned off. Please let me know if you need any further information, or if I should head to Quark's page with this error!

**To Reproduce:**
1. Launch new world (Survival and Creative both have this issue)
2. Add the Magnet and Pickup upgrades to any backpack (I had Netherite when I noticed this issue)
3. Set them both to Match Backpack Contents
4. Place any items inside the backpack
5. Save and Quit
6. Re-enter the world
7. Find more of the items contained within the backpack, or throw part a stack outside of the inventory screen
8. If the backpack is closed, the auto-stacking error will persist

**Comment by P3pp3rF1y** [comment]
I am unable to recreate using these steps so I will need more info. Also when you are able to recreate it would be worth to check if perhaps nbt of the items is different.

**Comment by Takaska** [comment]
Well, I'm afraid that's because I hastily pointed the finger in the wrong direction- while removing Quark did stop the issue for one play session, I found not long afterward that it persisted upon relaunch once more. I admittedly gave up for a while, but today, I updated Forge to the latest installation (being three or four behind likely didn't help) and copied a functional modpack to tweak. This time, I narrowed it to Origins Classes and Medieval Origins- or perhaps the libraries used for them? Once I removed those two as well as deleting their libraries from the folder (searched for on my laptop proper- as they don't show up on curseforge's listing) it started to work again. Entirely unsure both why the two new libraries aren't in Curseforge's list, and What the hell they do to the NBT or other data to get it to not stack right anymore.
Apologies for not being more thorough the first time around, especially since I'm not terribly sure if this is fixable or not (I am rather fine not having those mods, the backpacks are far more important!)

**Comment by P3pp3rF1y** [comment]
I was able to recreate in test pack and can't really see any difference between the stacks once they end up in the backpack so there must be some difference in them when they are being magnetted inside before their copy is placed in backpack. This would require more digging and debugging which is very time consuming and I would like to spend that time on fixing other stuff / adding new features. Also likely result of that investigation would be that there's still an issue on origins side of things and they would need to fix. 

So my recommendation at this point is to remove the mods and I am going to close this ticket. In case that it comes up with something else again I will be taking a closer look at why that is happening.
