### ISSUE TITLE
ATM10 0.32 - sophisticatedbackpacks-1.21-3.20.6.1055 crash

### ISSUE THREAD

**Issue by seals55** [P3pp3rF1y/SophisticatedBackpacks#1112]
**Describe the bug**
Dedicated server of ATM10 0.30, upgraded to 0.32 to pick up the newly added Sophisticated* mods. Also deleted Nether dimension as per discussion in #atm10-general discord.

I logged in to server, used my nether portal, nether loaded and server crashed. Restarted server, I log in and I can see I'm in the nether and the server crashes a second later.

Based on the crash report, disabled all three sophisticated*.jar files and the server works without crashing.

[https://mclo.gs/OT6BBzH](https://mclo.gs/OT6BBzH)

Info on what other mods you're using that may cause a conflict here if applicable.
All the mods in ATM10 0.32.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. ATM10 server 0.30 upgraded to 0.32
2. Manually deleted Nether 
3. Started server, logged in, went to nether, crashed server
4. Restarted server, logged in, crashed
5. disabled loading of sophisticated* mods, started server
6. Server seems fine, crash-wise

**Expected behavior**
I want to stop manually feeding myself :)

**Versions**
Minecraft 1.21.1
Neoforge 21.1.8
Sophisticated Storage 0.10.24
Sophisticated Core 0.6.24
Sophisticated Backpacks 3.20.6

**Comment by P3pp3rF1y** [comment]
Thanks for reporting, I have just uploaded a new version of sophisticated core with the fix for this. 

https://www.curseforge.com/minecraft/mc-mods/sophisticated-core/files/5623839
