### ISSUE TITLE
[Bug] ATM10 0.33 crash when rings and necklace in curio slot and I open backpack

### ISSUE THREAD

**Issue by seals55** [P3pp3rF1y/SophisticatedBackpacks#1116]
**Describe the bug**
I opened this under https://github.com/iron431/irons-spells-n-spellbooks/issues/537 but they blame SophisticatedBackpacks. 

Upgraded ATM10 server to 0.33 today. Made a Sophisticated backpack, put it in curio back slot. After 1 or 2 openings, the client crashes. If I remove backpack from curios slot it works fine. If I remove all iron rings and necklace from curios backpack works fine from curios slot.

`Client disconnected with reason: Failed to open a screen with advanced data: java.lang.ClassCastException: class io.redspace.ironsspellbooks.item.curios.CurioBaseItem cannot be cast to class net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem (io.redspace.ironsspellbooks.item.curios.CurioBaseItem is in module irons_spellbooks@1.21-3.4.4 of loader 'TRANSFORMER' @3be3e76c; net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem is in module sophisticatedbackpacks@3.20.6 of loader 'TRANSFORMER' @3be3e76c)`

[Crash log if it's a crash.](https://mclo.gs/Apdosfv)

Info on what other mods you're using that may cause a conflict here if applicable.
ATM10 0.33, no additional mods

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Have iron poison and fire ring, and a necklace in curios.
2. Put sophisticated netherite backpack in curios.
3. open backpack with hotkey, crash

**Expected behavior**
No crash :)

**Screenshots**

**Versions**
Neoforge 21.1.8
sophisticatedbackpacks-1.21-3.20.6.1055
irons_spellbooks-1.21-3.4.4-all

**Comment by P3pp3rF1y** [comment]
The crash happens because on server there's backpack in the slot, but on client it isn't in that same slot for some reason??? 
I am unable to recreate when testing on dedicated server, the only guess I have is that you have different configs between server and client and the curios mod isn't able to reconcile that for some reason? 

Anyway I will need exact steps how I can recreate otherwise I am not able to do anything here.

**Comment by seals55** [comment]
Let me get my server admin to verify the config between client and server for curios.

The way we typically play is to add as many curios slots as we need, to be able to equip found items.
/curios add ring @s 10
etc.

**Comment by seals55** [comment]
Changing the setting on the server seems to have fixed the issue. Thanks again!
