### ISSUE TITLE
Placing Backpack in Anvil Backpack Upgrade Crashes Game, Eats Backpack

### ISSUE THREAD

**Issue by AlgebraManiacABC** [P3pp3rF1y/SophisticatedBackpacks#1118]
### Description
Backpacks placed in the anvil upgrade tab are eaten and crash the game in 1.21.

[Crash Log Here](https://pastebin.com/bFvaK5Cr)

### To Reproduce

**Need:**
* Backpack A (Backpack with Anvil Upgrade)
* Backpack B (Any other backpack)

**Steps:**
1. Open Backpack A
2. Click on Anvil tab
3. Place Backpack B into anvil upgrade
4. Crash. On reload, Backpack B will be gone.

Something else to note: I have tried the above steps with an Inception upgrade in Backpack A.

### Expected behavior
One of two things:
* No backpacks allowed in anvil upgrade, seeing as it would allow a workaround to the inception upgrade
* Backpacks placed in anvil tab can be renamed (my goal here).

### Versions
Minecraft 1.21
NeoForge 21.0.167
Sophisticated Backpacks 1.21-3.20.6.1055 (Latest on CurseForge as of this report)

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF
