### ISSUE TITLE
Duplication of Upgrades via Vanilla Crafting

### ISSUE THREAD

**Issue by AlgebraManiacABC** [P3pp3rF1y/SophisticatedBackpacks#1121]
### Description

Backpack upgrades can be placed in the vanilla crafting grid to reset their settings. However, when multiple upgrades are placed in the grid at once, the output is also increased. This makes a single upgrade return multiple, leading to duplication.

### To Reproduce

**Need:**
* Two of any one backpack upgrade which can be "cleared" in a crafting grid

**Steps:**
* Clear both upgrades so they are stackable
* Place both in the crafting grid and take the duped result

### Video

https://github.com/user-attachments/assets/69f71c29-cbbd-415d-bb42-5ca684f06968

### Expected behavior

Either all upgrades should be removed from the grid once crafted, or only clear one upgrade at a time.

### Versions

Minecraft 1.21
NeoForge 21.0.167
Sophisticated Backpacks 1.21-3.20.6.1055

**Comment by P3pp3rF1y** [comment]
This is already fixed in the version that was released yesterday
