### ISSUE TITLE
Smelting Upgrade deletes items.

### ISSUE THREAD

**Issue by JasonDayspring** [P3pp3rF1y/SophisticatedBackpacks#1122]
Smelting upgrade.  (Unsure if this applies to all backpacks, but tested in Gold and Diamond)
When I try to insert an item to be smelted, all 3 boxes are labeled "Delete Item".  I lost some coal to testing, it does delete, no fuel or items can be inserted.

Edit:  Trying to use a filter does the same.  I'm now assuming all slots added by this mod delete anything placed in them.  It has to be a mod conflict, but I don't know what could be doing it.

I don't believe any of my mods affect smelting or the furnace.  
![modlist](https://github.com/user-attachments/assets/9a60b009-46bc-4ee1-b45e-061834925e83)

neoforge-21.1.21 - sophisticatedbackpacks-1.21-3.20.9.1060
![Backpack](https://github.com/user-attachments/assets/f7b4ac3a-106c-4ea6-84cf-f16285679acd)

**Comment by P3pp3rF1y** [comment]
That's not SB showing / doing that but the mod that you use that shows you the items on the right. Not sure which one it is, if it was JEI it would move out of the way properly and allow you to interact with the tab, other mods should have compatibility with it, but not sure what you have there.
