### ISSUE TITLE
When shift-clicking on backpack crafting menu, game crashes

### ISSUE THREAD

**Issue by Nota-user334** [P3pp3rF1y/SophisticatedBackpacks#1126]
**Describe the bug**
When I shift-click crafting items to my inventory or backpack, the game crashes.

I am not using conflicting mods here.

1. craft backpack crafting "upgrade"
2. try crafting anything with it (e.g. sticks, planks, etc.)
3. press shift while you're crafting.

Am using Forge for minecraft 1.19.2, forge version: 43.3.5

**Comment by P3pp3rF1y** [comment]
I will need the crash log

**Comment by zeziba** [comment]
Have a similar issue in 1.20 on Project Architect 2 pack where when crafting in the inventory of the backpack I get the following error.



```
The game crashed whilst container click
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41619_()" because "itemstack1" is null
```

Here are two crash logs from two different times


[crash-2024-08-26_10.50.18-client.txt](https://github.com/user-attachments/files/16750869/crash-2024-08-26_10.50.18-client.txt)
[crash-2024-08-25_22.39.46-client.txt](https://github.com/user-attachments/files/16750870/crash-2024-08-25_22.39.46-client.txt)

The older log crash-2024-08-25_22.39.46-client, I was crafting with the backpack in the curio slot and was crafting framed blocks with one click each time getting stacked into the hand.

The second log crash-2024-08-26_10.50.18-client I was attempting to craft an upgraded backpack from sophisticated backpacks. The first backpack level was completed without issues it was when I attempted to craft the second tier (iron) that it crashed after I picked it up with a regular left click.

**Comment by zeziba** [comment]
Just had the crash again upgrading the sophisticated backpack from gold to diamond, on left click to collect the result the game crashed.

[crash-2024-08-26_10.59.46-client.txt](https://github.com/user-attachments/files/16750938/crash-2024-08-26_10.59.46-client.txt)

**Comment by P3pp3rF1y** [comment]
Handling of erroneous recipes like this was released several weeks back so closing
