### ISSUE TITLE
From my understanding, crashed when trying to move an item with a keybind from mouse tweaks mod into a backpack

### ISSUE THREAD

**Issue by EmmaRavens** [P3pp3rF1y/SophisticatedBackpacks#1129]
**Describe the bug**
From my understanding, crashed when trying to move an item with a keybind from mouse tweaks mod into a backpack
[crash-2024-08-28_17.23.18-client.txt](https://github.com/user-attachments/files/16786329/crash-2024-08-28_17.23.18-client.txt)

**To Reproduce**
1. Open backpack
2. Hold 'Shift+LMB'
3. Hover mouse over multiple items

**Expected behavior**
Minecraft crashes

**Screenshots**

**Versions**
Minecraft: 1.21.1
Neoforge: 21.1.23
Sophisticated Backpacks: 3.20.9
Sophisticated Core: 0.6.31
Mouse Tweaks: 2.26.1

**Comment by P3pp3rF1y** [comment]
Are you actually able to reliably recreate this? From what I can see this crashed because there was item put into backpack which has count of -1 which definitely is invalid. It's either that specific item needs fixing or possibly mouse tweaks if it happens to somehow calculate count of -1 but I doubt that would be the case.

**Comment by EmmaRavens** [comment]
Tried the move the items I moved previously but it didn't crash this time. The items I tried to move when it crashed where the Supremium Armor and Tools from Mystical Agriculture

**Comment by P3pp3rF1y** [comment]
I have fixed a bug in a mouse drag interaction with mouse tweaks so this should hopefully be fixed, feel free to report new issue if you are still seeing something here

**Comment by P3pp3rF1y** [comment]
actually let me reopen as I only released the fix for 1.20.1 will be releasing the fix for 1.21 soon

**Comment by P3pp3rF1y** [comment]
the fix for 1.21 is released as well so closing
