### ISSUE TITLE
Shift+Click Crash

### ISSUE THREAD

**Issue by Wenzelgood** [P3pp3rF1y/SophisticatedBackpacks#1132]
**Describe the bug**
Crash when Shift + Click on item in backpack inventory
Crash log: https://mclo.gs/LQetUR6

**To Reproduce**
1. Open backpack
2. Click on item in backpack with Shift + L. Click
3. Game crash

**Expected behavior**
No crashes

**Versions**
sophisticatedbackpacks-1.19.2-3.20.2
sophisticatedcore-1.19.2-0.6.4.605

**Comment by P3pp3rF1y** [comment]
Just don't use smoothswapping. it's been this buggy for a very long time or report this bug to them so they finally fix
