### ISSUE TITLE
Stack Upgrades delete items when unsorted (1.19.2)

### ISSUE THREAD

**Issue by Auxid3** [P3pp3rF1y/SophisticatedBackpacks#1133]
**Describe the bug**
When "unstacking" in Sophisticated Backpacks with the stack upgrades, All stacks return to 64 item stacks, causing other items to be removed because they no longer fit in the bounds of the backpack. This is exactly the same as issue #260.

**To Reproduce**
1. Open backpack
2. Ensure backpack has a stack upgrade
3. Fill backpack
4. Do Ctrl + Mouse wheel Click (Unstack)
5. Restack Items 
6. Now the backpack isn't full.

**Expected behavior**
I expected that the backpack would not allow this to occur, and even if it did, I'd expect items to fall out onto the floor or overflow into the player's inventory. If you can't fit something in your backpack IRL, You either carry it, or leave it behind.

**Screenshots**
![2024-09-07_21 24 52](https://github.com/user-attachments/assets/fd5fa6d3-d62c-4a0d-9426-7cf89c49e7c7)
This is the full backpack with the Stack Upgrade lvl 2, before "unstacking"

![2024-09-07_21 25 07](https://github.com/user-attachments/assets/fa122f9c-422d-48a4-8976-5d9f5376fb37)
This is the backpack after "restacking." please note that items seen prior are now missing. No items in the backpack have been moved to inventory, nor spat out onto the floor.

**Versions**
Version 1.12.2-3.20.2.1035 Forge, previous versions may be affected.

(Note: This bug has caused distrust in my friend group. We've been blaming the new guy in the server for theft lol)

**Comment by P3pp3rF1y** [comment]
I have no idea what Unstack means, but I am guessing it's some other mod providing that functionality (there's nothing like ctrl + mouse wheel in vanilla) so you will want to report this to them. if they can fix or prevent their mod from working in sophisticated gui if they can't
