### ISSUE TITLE
Auto Pickup not filtering as intended

### ISSUE THREAD

**Issue by akitasiffu** [P3pp3rF1y/SophisticatedBackpacks#1138]
Not sure exactly what is happening, everything worked as intended for awhile. I Lost all my backpacks due to a corpse glitch. Before that I was using like 12 bags inside of 1 main bag. Every incepted bag had auto pickup set to match contents and it worked perfectly. I lost all my bags and pulled them back through creative. all same set ups. Now the filter isn't working and everything goes into the first  bag instead of the main bag inventory. I'm not sure if having the backpack setting set to PLayer is the issue, but it wont let me switch that anyway. I'm currently using _**sophisticatedbackpacks-1.19.2-3.20.2.1035**_ in Cisco's Fantasy RPG Ultimate modpack V5d for MC 1.19.2. everything is current within the modpack and nothing has really changed.

**Comment by P3pp3rF1y** [comment]
Have you got pickup in the main backpack?

**Comment by akitasiffu** [comment]
Yes, I also noticed later that my pumps and tanks don't work. I have advanced pump turned off and it was siphoning my experience I had to make an experience upgrade just to get it all back. Then I tried filling them with lava and they won't keep anything in them. They fill up and then instantly drain.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by akitasiffu** [comment]
![Desktop Screenshot 2024 09 15 - 12 39 08 33](https://github.com/user-attachments/assets/b87441a7-e937-4c8c-93bc-709a03e0d733)

**Comment by akitasiffu** [comment]
working on some recordings for you

**Comment by akitasiffu** [comment]
my recording is to big to send on here

**Comment by P3pp3rF1y** [comment]
based on that screenshot you have magnet picking up stuff so now it depends on how you have inception upgrade setup (put stuff in main backpack or incepted first) and whether you have anything else that would filter what can go in what incepted backpack and that can't be done with pickup there but would need to be a filter upgrade or memorized slots.
Also magnet is likely picking up xp from world and putting it in that backpack with tank, pump itself can't take player's xp directly that's only doable with xp pump

**Comment by akitasiffu** [comment]
I took off the magnet and it's still happening, i have a video but id have to send it on discord.

Main Bag worn in curios slot. Has Adv Pick up with filters to block certain items. Has inception which is set to Inventory First. Contains 12 other backpacks.

Each incepted backpack also has Adv Pickup with filter set to match contents.

I might be wrong, but shouldn't the loot not enter a backpack with Adv Pickup set to match container conyent? With inception set to inner bags first it should run against their filter first, then the main bag right? This is seemingly how it worked the other day.

**Comment by P3pp3rF1y** [comment]
no that's not how it works, in your case that would mean main backpacks pickup runs first and can put stuff into any of the incepted ones, then if that can't pickup items (because of filter) the incepted backpack pickup upgrades run next and try to pickup into their backpack.

**Comment by akitasiffu** [comment]
it seems like you are misunderstanding what i'm typing. The incepted bags inventories are set to run first. Meaning their pickups should have first grab as long as the filter doesn't block the item. Then the main backpacks Adv Pick up runs. Bottom line, either way without regards to anything else....the incepted bags filters are not working. They are set to _**Match Backpack Contents**_ , this filter is the main thing that isn't working for me. every item enters the backpack regardless to that being set.

**Comment by P3pp3rF1y** [comment]
There's nothing like a setting that makes incepted upgrades run first, the only setting is whether the upgrades in the main backpack should work with inventories of incepted backpacks first which is what I am guessing you have this set to and that's why items appear in those backpacks. You would have to use filter upgrades (not pickup upgrades) in those backpacks to prevent main backpack from putting items in tehm that do not match their inventory. Anyway this is working as expected so I am closing and feel free to jump on our discord server if you need help setting up those upgrades.
