### ISSUE TITLE
Settings not working(Furnace upgrade)

### ISSUE THREAD

**Issue by MakiTsuki** [P3pp3rF1y/SophisticatedBackpacks#114]
Hello!
Been testing your backpack mod a little while now, I noticed there where some setting for the different upgrades. So I was playing around in the settings for the furnace upgrade, and noticed that none of the settings did anything(the multipliers at least, didn't change the other settings)

Many thanks!

**Comment by P3pp3rF1y** [comment]
I will need more than this report as I can clearly see in code they are used - could you show your settings in config and clarify which exact upgrade you're looking at - there are two of them one is just manual Smelting Upgrade, the other is Auto Smelting Upgrade - each of them have their own section in the config.

**Comment by MakiTsuki** [comment]
Oh yeah sorry, should have provided more clarification to it. Will look at it and get back to you, asap.

**Comment by MakiTsuki** [comment]
I did some testing now and yes it was just me being stupid. I should not poke at settings in config files while tired. Only problems haha XD. Sorry for wasting your time.

**Comment by P3pp3rF1y** [comment]
no problem, glad it works for you and closing this issue then.
