### ISSUE TITLE
Upgrade Tier 5 (netherite)

### ISSUE THREAD

**Issue by AstreSolaire** [P3pp3rF1y/SophisticatedBackpacks#1143]
Hello there !

My problem is i can't upgrade my diamond backpack to netherite.

i play on 1.20.1, i tried to upgrade in tablecraft, in anvil, in smithing table... no one works.
put some screenshot, maybe i do something wrong 😭
![1](https://github.com/user-attachments/assets/17d7af9c-41a5-45d9-bc59-5dd41d28f5d9)
![2](https://github.com/user-attachments/assets/1d04577b-7bb2-4734-8b1e-b5bda855021c)
![3](https://github.com/user-attachments/assets/9c4b163f-3a22-448b-bb61-50cbbd14a2b7)
![4](https://github.com/user-attachments/assets/9801f18e-a699-4991-9c04-8c5fb8befdc7)

i use some other mod.
- world edit
- JEI
- Falling tree
- Yungs Desert Temple
- Yungs End island
- Yungs Nether Fortresses
- Yungs Ocean Monuments
- Yungs Bridge
- Wormhole
- Paraglider
- Journey map
- ChoiceTheorem’s Overhauled Village

It's a bug or i'm a dumbass ?

thank for help =)

**Comment by P3pp3rF1y** [comment]
You just need to use the smithing template in the smithing table. JEI should show you the same.
