### ISSUE TITLE
Hide cape while wearing backpack

### ISSUE THREAD

**Issue by Foozey** [P3pp3rF1y/SophisticatedBackpacks#1145]
A config option for this would be nice to avoid significant clipping through the backpack.

![image](https://github.com/user-attachments/assets/076b9d48-f347-4c49-a41b-835e1b9444ec)
![image](https://github.com/user-attachments/assets/d96f788d-8426-401b-b1ef-bd4f42eee9b1)

**Comment by P3pp3rF1y** [comment]
I may be wrong but don't you have vanilla option to hide the cape?

**Comment by P3pp3rF1y** [comment]
actually yes it is under skin customizations so there's your option to do that.

**Comment by Foozey** [comment]
The title of the issue is hide cape _while_ wearing backpack, disabling it entirely is not a solution to the issue. Will you accept a PR that creates this config option for you?

**Comment by QianFuv** [comment]
@Foozey Hey! Please implement this feature, it's something I think players often have problems with!
