### ISSUE TITLE
Autofeed Consumes All Vampire's Delight Food Even When Blood Is Full

### ISSUE THREAD

**Issue by CoolFreeze23** [P3pp3rF1y/SophisticatedBackpacks#1146]
Hey,

I’ve noticed an issue when using the Autofeed feature in Sophisticated Backpacks alongside the Vampire's Delight mod. When I transform into a vampire, the autofeed keeps eating all the food in the backpack even though my blood level is already at maximum. It seems like the backpack is trying to fill a hunger bar that vampires don’t use, causing all the Vampire's Delight food to be wasted quickly.

Steps to Reproduce:

1.  Install both Sophisticated Backpacks and Vampire's Delight mods.
2.  Become a Vampire; Use Vampire's Delight to transform your character into a vampire.
3.  Enable Autofeed; Equip a Sophisticated Backpack and turn on the Autofeed feature.
4.  Add Food; Put blood-based foods from Vampire's Delight into the backpack.
5.  Observe: With blood at max, watch as the autofeed continues to consume all the food in the backpack.

What I Expect:

The Autofeed should recognize that as a vampire, my character doesn't use the standard hunger bar but relies on blood instead. It should stop consuming food once my blood is full to prevent unnecessary depletion of resources.

What’s Happening:

Instead of stopping, the Autofeed keeps eating all the Vampire's Delight food even when my blood is full. It looks like it's trying to manage a hunger bar that vampires don't have, leading to rapid food consumption.

**Comment by P3pp3rF1y** [comment]
I am not going to add compatibility for vampirism mod as that would open a huge can of worms of requests for adding compatibilities for tens of other mods and spending most of my time just maintaining compatibilities instead of improving my mods.

You have the option of filtering the food you want the feeding upgrade to feed you or just stop using it altogether when you convert to vampire.

**Comment by CoolFreeze23** [comment]
Issue is that vampires can't eat regular food, so if i filter out all the food from vampire's delight, i couldn't auto feed. So it looks like option number 2 is the way to go. Fair enough though, appreciate you even responding. Have a good day.
