### ISSUE TITLE
backpack becomes completely disorganized when filled by hoppers or other similar blocks

### ISSUE THREAD

**Issue by Shady0935** [P3pp3rF1y/SophisticatedBackpacks#1147]
Hi, I'm using backpacks with the Toms Simple Storage and Create mod, and whenever a funnel or a hopper or any other external system puts an item into the backpack it takes up a new slot in the backpack instead of joining the other existing items, is there any way to fix this?

I tried with vanilla hoppers too and the same thing happens

Sorry if my English is not very good >u<

Version: Minecraft 1.20.1 Forge 47.3.5
![imagen_2024-09-19_164502901](https://github.com/user-attachments/assets/8b8cb56b-10d6-403b-b078-077e70c7ea7e)
![imagen_2024-09-19_164524682](https://github.com/user-attachments/assets/466cbfdd-787a-464d-8b7e-7ec569d9632c)

**Comment by P3pp3rF1y** [comment]
This is not a default behavior with just sophisticated or even with create in a modpack. So I will need to understand how I can recreate and what minimum set of mods I need to use for that.

**Comment by Shady0935** [comment]
Well... after many tests removing mods and testing I came to the conclusion that it is the fault of some plugin that the server has, but I have no idea why it could be, I will have to keep trying things, so yeah, sorry to bother you bro

**Comment by P3pp3rF1y** [comment]
> Well... after many tests removing mods and testing I came to the conclusion that it is the fault of some plugin that the server has, but I have no idea why it could be, I will have to keep trying things, so yeah, sorry to bother you bro

a few days back I was looking into why hopper wouldn't put items into limited barrel with those same exact items and there the issue was Origins mod that was attaching some data to stacks making them different from the ones in the barrel. Perhaps you have that mod in pack which is causing this for you?

**Comment by Shady0935** [comment]
> a few days back I was looking into why hopper wouldn't put items into limited barrel with those same exact items and there the issue was Origins mod that was attaching some data to stacks making them different from the ones in the barrel. Perhaps you have that mod in pack which is causing this for you?

I don't think so, because I click the sort button in the backpack and everything stacks up normally.
i need to test again removing some plugins and see what happens

It's actually curious, because the problem solves after moving the backpack upgrades and clicking the sort button a few times, but when the server restarts everything gets messed up again.

**Comment by P3pp3rF1y** [comment]
I just had someone else report a similar kind of issue where if they have tslateffectslib mod in the modpack it causes this. You have that by any chance? anyway I will need steps I can use to recreate with the minimum set of mods to be able to do anything here.

**Comment by Shady0935** [comment]
> I just had someone else report a similar kind of issue where if they have tslateffectslib mod in the modpack it causes this. You have that by any chance? anyway I will need steps I can use to recreate with the minimum set of mods to be able to do anything here.

Nope, we don't use that mod. In fact I don't think it's any mod's fault because it only happens to me on the server, in singleplayer it works fine.

I don't know if it's because of some plugin or directly because of the server software, which is mohist.

**Comment by P3pp3rF1y** [comment]
ok Mohist at least like half a year ago had really bad bugs that caused duplication issues and similar so yeah I would agree that's the very likely culprit here. I am going to close, if you happen to get the same bug on a different server feel free to reopen.
