### ISSUE TITLE
Backpack with advanced Pickup/Magnet Upgrade fills up unused slots of Mob drops instead of stacking them.

### ISSUE THREAD

**Issue by AIDSmitAIganzWichtig** [P3pp3rF1y/SophisticatedBackpacks#1149]
**Describe the bug**
My Backpack with an advanced pickup/magnet Upgrade (same for the normal pickup upgrade) thats filtered to pickup Backpack content fills up unused slots of Mob drops instead of stacking them to the existing slots.

**Comment by AIDSmitAIganzWichtig** [comment]
Screenshots here because it was messed up in my post

How it looks:
![How it looks](https://github.com/user-attachments/assets/a869de62-60c7-48c2-8dec-d4d430ae5678)

How it should look:
![How it should look](https://github.com/user-attachments/assets/2c6b283c-2520-41a7-bedb-ba8ac7888121)

<details><summary>Modlist</summary>
<p>
[15:16:56] [main/INFO]: Loading 342 mods:

- 	- ad_astra 1.15.18
- 	- advancementplaques 1.5.1
- 	- ae2 15.2.9
- 	- ae2wtlib 15.2.3-forge
- 	- aether 1.20.1-1.4.2-neoforge
- 	- cumulus_menus 1.20.1-1.0.0-neoforge
- 	- mixinextras 0.2.0-beta.9
- 	- nitrogen_internals 1.20.1-1.0.7-neoforge
- 	- alexscaves 1.1.5
- 	- alexscavesdelight 1.0.13-1.20.1
- 	- alexsdelight 1.5
- 	- alexsmobs 1.22.8
- 	- amendments 1.20-1.2.8
- 	- apotheosis 7.4.2
- 	- apotheotic_additions 2.0.1
- 	- apotheoticcreation 1.0.1
- 	- apothic_sups_enchanting 0.1.2
- 	- apothiccurios 1.0.3d
- 	- appleskin 2.5.1+mc1.20.1
- 	- appmek 1.4.2
- 	- aquaculture 2.5.2
- 	- aquaculturedelight 1.0.0
- 	- architectury 9.2.14
- 	- ars_creo 4.0.1
- 	- ars_elemental 1.20.1-0.6.5.0.1
- 	- ars_nouveau 4.12.4
- 	- ars_ocultas 1.2.2
- 	- arseng 1.2.0
- 	- arsnouveaudelight 1.0.0-1.20.1
- 	- artifacts 9.5.11
- 	- expandability 9.0.4
- 	- athena 3.1.2
- 	- attributefix 21.0.4
- 	- attributeslib 1.3.7
- 	- bagus_lib 1.20.1-5.2.3
- 	- balm 7.3.7
- 	- kuma_api 20.1.8
- 	- bclib 3.0.14
- 	- betterdeserttemples 1.20-Forge-3.0.3
- 	- betterdungeons 1.20-Forge-4.0.4
- 	- betterend 4.0.11
- 	- betterendisland 1.20-Forge-2.0.6
- 	- betterfortresses 1.20-Forge-2.0.6
- 	- betterjungletemples 1.20-Forge-2.0.5
- 	- bettermineshafts 1.20-Forge-4.0.4
- 	- betternether 9.0.10
- 	- betteroceanmonuments 1.20-Forge-3.0.4
- 	- betterstrongholds 1.20-Forge-4.0.3
- 	- betterwitchhuts 1.20-Forge-3.0.3
- 	- bhc 1.20.1-1.0.5
- 	- biomesoplenty 18.0.0.598
- 	- biomespawnpoint 2.3
- 	- biomeswevegone 1.1.0-Beta
- 	- bloodmagic 3.3.3-45
- 	- blue_endless_jankson 1.2.2
- 	- blue_skies 1.3.31
- 	- bookshelf 20.1.8
- 	- botania 1.20.1-446-FORGE
- 	- botarium 2.3.4
- 	- bountiful 6.0.3+1.20.1
- 	- carbonconfig 1.20-1.2.6
- 	- cataclysm 1.99.5
- 	- catalogue 1.8.0
- 	- cavernous 2.1.3
- 	- cavesanddepths 1.2.7
- 	- chefsdelight 1.0.3-forge-1.20.1
- 	- cherishedworlds 6.1.6+1.20.1
- 	- chesttracker 1.1.23
- 	- chipped 3.0.6
- 	- chunkpregen 1.20-4.4.4
- 	- citadel 2.6.0
- 	- cleanswing 1.20-1.5
- 	- cloth_config 11.1.118
- 	- cofh_core 11.0.2
- 	- collective 7.84
- 	- com_github_llamalad7_mixinextras 0.1.1
- 	- commoncapabilities 2.9.1
- 	- configured 2.2.3
- 	- conjurer_illager 1.1.6
- 	- connectormod 1.0.0-beta.33+1.20.1+dev-00000000
- 	- controlling 12.0.2
- 	- corgilib 4.0.2.0
- 	- cosmeticarmorreworked 1.20.1-v1a
- 	- craftingstation 1.20.1-1.2.2
- 	- create 0.5.1.f
- 	- flywheel 0.6.10-7
- 	- create_ad_astra_compat 1.0.0
- 	- create_enchantment_industry 1.2.9.d
- 	- create_dragon_lib 1.4.3
- 	- create_eureka 1.0.0+forge-1.20.1
- 	- create_jetpack 4.2.1
- 	- flightlib 2.1.0
- 	- create_mechanical_extruder 1.20.1-1.5.7.e-22
- 	- create_new_age 1.1.2
- 	- create_questing 1.0.0
- 	- createaddition 1.20.1-1.2.4c
- 	- createappliedkinetics 1.3.2-1.20.1
- 	- createbigcannons 0.5.4-nightly-8b9cea6
- 	- ritchiesprojectilelib 1.0.0-369e88d+1.20.1-forge
- 	- createdeco 2.0.2-1.20.1-forge
- 	- crystal_clear 2.1-Beta
- 	- cucumber 7.0.11
- 	- curios 5.9.0+1.20.1
- 	- cyclopscore 1.19.2
- 	- darkutils 17.0.3
- 	- deeperdarker 1.3.0
- 	- dimdoors 5.4.1
- 	- double_hotbar 1.3.2.1-mc1.20.1-forge
- 	- eccentrictome 1.20.1-1.10.2
- 	- ecologics 2.2.0
- 	- ecologicsdelight 1.0.2.1-1.20.1
- 	- embeddium 0.3.21+mc1.20.1
- 	- rubidium 0.7.1
- 	- enchantwithmob 1.20.1-11.13.1
- 	- enchdesc 17.0.13
- 	- enderio 6.1.8-beta
- 	- endrem 5.3.3-R-1.20.1
- 	- enhancedcelestials 5.0.0.4
- 	- equipmentcompare 1.3.7
- 	- explorerscompass 1.20.1-1.3.3-forge
- 	- extendedcrafting 6.0.7
- 	- extremesoundmuffler 3.47
- 	- fabric_api 0.92.2+1.11.8+1.20.1
- 		|-- fabric_api_base 0.4.31+ef105b4977
- 		|-- fabric_api_lookup_api_v1 1.6.36+67f9824077
- 		|-- fabric_biome_api_v1 13.0.13+dc36698e77
- 		|-- fabric_block_api_v1 1.0.11+0e6cb7f777
- 		|-- fabric_block_view_api_v2 1.0.1+0767707077
- 		|-- fabric_blockrenderlayer_v1 1.1.41+1d0da21e77
- 		|-- fabric_client_tags_api_v1 1.1.2+5d6761b877
- 		|-- fabric_command_api_v1 1.2.34+f71b366f77
- 		|-- fabric_command_api_v2 2.2.13+561530ec77
- 		|-- fabric_content_registries_v0 4.0.11+a670df1e77
- 		|-- fabric_convention_tags_v1 1.5.5+fa3d1c0177
- 		|-- fabric_data_attachment_api_v1 1.0.0+30ef839e77
- 		|-- fabric_data_generation_api_v1 12.3.4+369cb3a477
- 		|-- fabric_dimensions_v1 2.1.54+8005d10d77
- 		|-- fabric_entity_events_v1 1.6.0+6274ab9d77
- 		|-- fabric_events_interaction_v0 0.6.2+0d0bd5a777
- 		|-- fabric_game_rule_api_v1 1.0.40+683d4da877
- 		|-- fabric_item_api_v1 2.1.28+4d0bbcfa77
- 		|-- fabric_item_group_api_v1 4.0.12+c9161c2d77
- 		|-- fabric_key_binding_api_v1 1.0.37+561530ec77
- 		|-- fabric_lifecycle_events_v1 2.2.22+afab492177
- 		|-- fabric_loot_api_v2 1.2.1+eb28f93e77
- 		|-- fabric_message_api_v1 5.1.9+52cc178c77
- 		|-- fabric_mining_level_api_v1 2.1.50+561530ec77
- 		|-- fabric_model_loading_api_v1 1.0.3+6274ab9d77
- 		|-- fabric_models_v0 0.4.2+7c3892a477
- 		|-- fabric_networking_api_v1 1.3.11+503a202477
- 		|-- fabric_object_builder_api_v1 11.1.3+2174fc8477
- 		|-- fabric_particles_v1 1.1.2+78e1ecb877
- 		|-- fabric_recipe_api_v1 1.0.21+514a076577
- 		|-- fabric_registry_sync_v0 2.3.3+1c0ea72177
- 		|-- fabric_renderer_api_v1 3.2.1+1d29b44577
- 		|-- fabric_renderer_indigo 1.5.2+b5b2da4177
- 		|-- fabric_rendering_data_attachment_v1 0.3.37+a6081afc77
- 		|-- fabric_rendering_fluids_v1 3.0.28+4ac5e37a77
- 		|-- fabric_rendering_v1 3.0.8+66e9a48f77
- 		|-- fabric_resource_conditions_api_v1 2.3.8+9ad825cd77
- 		|-- fabric_resource_loader_v0 0.11.10+bcd08ed377
- 		|-- fabric_screen_api_v1 2.0.8+45a670a577
- 		|-- fabric_screen_handler_api_v1 1.3.30+561530ec77
- 		|-- fabric_sound_api_v1 1.0.13+4f23bd8477
- 		|-- fabric_transfer_api_v1 3.3.5+631c9cd677
- 		\-- fabric_transitive_access_wideners_v1 4.3.1+1880499877
- 	- farlanders 1.4.1
- 	- farmersdelight 1.20.1-1.2.4
- 	- fastload 3.4.0
- 	- fastquit 3.0.01.20
- 	- flickerfix 4.0.1
- 	- forge 47.2.17
- 	- framework 0.7.6
- 	- friendsandfoes 2.0.16
- 	- ftbchunks 2001.3.1
- 	- ftblibrary 2001.2.4
- 	- ftbquests 2001.4.8
- 	- ftbteams 2001.3.0
- 	- fusion 1.1.1
- 	- geckolib 4.4.9
- 	- globalpacks 1.16.2_forge
- 	- glowingraidillagers 1.0.0
- 	- gravestone 1.20.1-1.0.21
- 	- graveyard 3.1
- 	- graveyarddelight 1.0.2-1.20.1
- 	- hexerei 1.20.1-0.4.1
- 	- highlighter 1.1.9
- 	- hunters_return 1.20.1-11.5.0
- 	- iceandfire 2.1.13-1.20.1
- 	- iceberg 1.1.21
- 	- ichunutil 1.0.0
- 	- idas 1.10.1+1.20.1
- 	- illageandspillage 1.1.0
- 	- illager_additions 1.20.1-0.0.2-alpha
- 	- illager_trader 3.0.0
- 	- illagerinvasion 8.0.5
- 	- incendium 5.3.5
- 	- industrialforegoing 3.5.19
- 	- infernalmobs 1.20.1.3
- 	- insanelib 1.13.5
- 	- integrated_api 1.5.1+1.20.1-forge
- 	- integrated_stronghold 1.1.1+1.20.1-forge
- 	- integrated_villages 1.0.1+1.20.1-forge
- 	- integratedcrafting 1.1.7
- 	- integrateddynamics 1.22.1
- 	- integrateddynamicscompat 1.22.1
- 	- integratedterminals 1.4.15
- 	- integratedterminalscompat 1.4.15
- 	- integratedtunnels 1.8.28
- 	- integratedtunnelscompat 1.8.28
- 	- interiors 0.5.3+forge-mc1.20.1
- 	- inventoryhud 3.4.18
- 	- item_despawn_timer 0.1.2-1.20.1
- 	- itemborders 1.2.1
- 	- jade 11.9.4+forge
- 	- jankson 5.0.1j1.2.2
- 	- jearchaeology 1.20.1-1.0.3
- 	- jeed 1.20-2.1.7
- 	- jei 15.2.0.27
- 	- jei_mekanism_multiblocks 4.2
- 	- jeresources 1.4.0.247
- 	- jerintegration 5.5.0
- 	- journeymap 5.9.18
- 	- justenoughbreeding 1.0.12
- 	- justenoughprofessions 3.0.1
- 	- kambrik 6.1.1+1.20.1
- 	- kotlinforforge 4.10.0
- 	- legendarytooltips 1.4.5
- 	- libgui 8.0.01.20
- 	- libninepatch 1.2.0
- 	- lionfishapi 1.9
- 	- lootbeams 1.20.1
- 	- lootr 0.7.29.68
- 	- mekanism 10.4.8
- 	- mekanism_turrets 1.1.1
- 	- mekanismexplosives 1.0.0
- 	- mekanismgenerators 10.4.8
- 	- mekanismtools 10.4.8
- 	- mekaweapons 1.5
- 	- merchantmarkers 1.3.3
- 	- minecraft 1.20.1
- 	- missingmodswarning 0
- 	- mob_grinding_utils 1.20.1-1.1.0
- 	- mobbattle 1.20.1-2.4.9
- 	- modnametooltip 1.20.0
- 	- modonomicon 1.74.0
- 	- moonlight 1.20-2.12.13
- 	- mousetweaks 2.25
- 	- mowziesdelight 1.0.3-1.20.1
- 	- mowziesmobs 1.6.4
- 	- mr_lukis_grandcapitals 1.0
- 	- mutant_iceologer 2.0.1
- 	- mutantmonsters 8.0.7
- 	- mysticalagriculture 7.0.12
- 	- mysticalagriculturedelight 1.0.1-1.20.1
- 	- naturescompass 1.20.1-1.11.2-forge
- 	- neat 1.20-35-FORGE
- 	- necronomicon 1.4.2
- 	- no_telemetry 1.8.0
- 	- nullscape 1.2.7
- 	- observable 4.4.1
- 	- occultism 1.134.1
- 	- occultismdelight 1.0.1-1.20.1
- 	- oculus 1.7.0
- 	- ohthetreesyoullgrow 1.20.1-1.3.0
- 	- overflowingbars 8.0.0
- 	- paraglider 20.1.3
- 	- patchouli 1.20.1-84-FORGE
- 	- pigpen 15.0.2
- 	- placebo 8.6.2
- 	- polymorph 0.49.5+1.20.1
- 	- spectrelib 0.13.15+1.20.1
- 	- prism 1.0.5
- 	- puzzleslib 8.1.21
- 	- puzzlesaccessapi 8.0.7
- 	- quark 4.0-460
- 	- quarkdelight 1.0.0
- 	- quarkoddities 1.20.1
- 	- railways 1.6.4+forge-mc1.20.1
- 	- reblured 1.20.1-1.3.0
- 	- rechiseled 1.1.6
- 	- rechiseledcreate 1.0.2
- 	- recruits 1.12.1
- 	- refinedpolymorph 0.1.1-1.20.1
- 	- refinedstorage 1.12.4
- 	- refinedstorageaddons 0.10.0
- 	- resourcefulconfig 2.1.2
- 	- resourcefullib 2.1.25
- 	- rpghud 3.10
- 	- rsrequestify 2.3.3
- 	- runelic 18.0.2
- 	- saturation_plus 1.0.1-1.20
- 	- searchables 1.0.3
- 	- simplehealthbar 1.0.2
- 	- sliceanddice 3.2.1
- 	- smartbrainlib 1.14.2
- 	- sophisticatedbackpacks 3.20.7.1075
- 	- sophisticatedcore 0.6.26.668
- 	- sophisticatedstorage 0.10.26.817
- 	- sound_physics_remastered 1.20.1-1.4.2
- 	- starterkit 7.0
- 	- storagedrawers 12.0.3
- 	- structure_gel 2.16.2
- 	- supermartijn642configlib 1.1.8
- 	- supermartijn642corelib 1.1.17
- 	- supplementaries 1.20-2.8.17
- 	- mixinsquared 0.1.1
- 	- suppsquared 1.20-1.1.14
- 	- tectonic 2.3.5a
- 	- terrablender 3.0.1.7
- 	- terralith 2.5.4
- 	- the_bumblezone 7.4.18+1.20.1-forge
- 	- thermal_cultivation 11.0.1
- 	- thermal_dynamics 11.0.1
- 	- thermal_expansion 11.0.1
- 	- thermal_foundation 11.0.6
- 	- thermal 11.0.6
- 	- thermal_innovation 11.0.1
- 	- thermal_integration 11.0.1
- 	- thermal_locomotion 11.0.1
- 	- titanium 3.8.32
- 	- tmttd 1.0.0
- 	- toastcontrol 8.0.3
- 	- tomeofblood 0.4.4
- 	- totw_additions 1.3.1
- 	- totw_modded 1.0.5
- 	- trader_announcement 1.0.4
- 	- treechop 0.18.8
- 	- tslateffectslib 1.8.5
- 	- tslatentitystatus 1.5.1
- 	- twilightforest 4.3.2508
- 	- undergarden 0.8.14
- 	- valkyrienskies 2.3.0-beta.5
- 	- villagerdeathmessages 3.5
- 	- voidbound 1.0.0
- 	- vs_eureka 1.5.1-beta.3
- 	- waystones 14.1.4
- 	- whats_that_slot 1.3.4
- 	- whereisit 1.14.17
- 	- workers 1.7.8
- 	- wunderlib 1.1.5
- 	- wwoo_forge 2.0.0
- 	- yungsapi 1.20-Forge-4.0.5
- 	- yungsbridges 1.20-Forge-4.0.3
- 	- yungsextras 1.20-Forge-4.0.3
- 	- zeta 1.0-24</p>

</details>

**Comment by P3pp3rF1y** [comment]
some mod is attaching the data to those new stacks (or was to old and isn't to new ones), but doesn't seem to do so when they are loaded in the backpack, saw this one with origins mod, which doesn't seem to be the issue here. The only way to figure out what is doing that is removing mods until it stops happening. If you can let me know what mod that is I can take a quick look likely just confirming that they are doing this and you will need to follow up with them to fix the issue where they are not initializing the capabilities properly.

**Comment by AIDSmitAIganzWichtig** [comment]
> some mod is attaching the data to those new stacks (or was to old and isn't to new ones), but doesn't seem to do so when they are loaded in the backpack, saw this one with origins mod, which doesn't seem to be the issue here. The only way to figure out what is doing that is removing mods until it stops happening. If you can let me know what mod that is I can take a quick look likely just confirming that they are doing this and you will need to follow up with them to fix the issue where they are not initializing the capabilities properly.

Ok i try to check out the mod, who could be responsible for this, TY 4 quick responding, much love!

Edit: I believe, that switching dimensions (Nether/Overworld atm) triggers this.

**Comment by AIDSmitAIganzWichtig** [comment]
> some mod is attaching the data to those new stacks (or was to old and isn't to new ones), but doesn't seem to do so when they are loaded in the backpack, saw this one with origins mod, which doesn't seem to be the issue here. The only way to figure out what is doing that is removing mods until it stops happening. If you can let me know what mod that is I can take a quick look likely just confirming that they are doing this and you will need to follow up with them to fix the issue where they are not initializing the capabilities properly.

Hi! It seems that FTB Library caused this!
https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge

**Comment by P3pp3rF1y** [comment]
So I created a small pack with sophisticated + ftb library and I am unable to recreate the issue. Are you sure that you are able to recreate with just these mods in the pack?

**Comment by AIDSmitAIganzWichtig** [comment]
> So I created a small pack with sophisticated + ftb library and I am unable to recreate the issue. Are you sure that you are able to recreate with just these mods in the pack?

With just those 2 Mods it works as it should. Guess I look for another Mod, that could be responsible for it. But it worked in my modpack without the FTB mods. Much love.

Edit: Atm the only thing I can say it arent the Fabric Mods.

**Comment by AIDSmitAIganzWichtig** [comment]
Same thing with Oh the Biomes We've Gone, works without the mod but can't recreate it with just Oh the Biomes, sophisticated and FTB. I guess there should be another mod causing this?

**Comment by P3pp3rF1y** [comment]
I can't recreate with that mod either, but just noticed your note on fabric mods and sinytra connector in the mod list I recall there used to be issues with using mods with that. I can't recreate with just Sinytra, potentially the fabric mods are adding stuff here no idea. anyway I really need  a set that works as I don't have time to keep retesting all kinds of modpacks that may work. And by "work" I mean modlist that allows me to recreate the issue.

**Comment by AIDSmitAIganzWichtig** [comment]
> I can't recreate with that mod either, but just noticed your note on fabric mods and sinytra connector in the mod list I recall there used to be issues with using mods with that. I can't recreate with just Sinytra, potentially the fabric mods are adding stuff here no idea. anyway I really need a set that works as I don't have time to keep retesting all kinds of modpacks that may work. And by "work" I mean modlist that allows me to recreate the issue.

Well ... this can take a few days, since I'm finding mods that let it work after removal but i can't recreate the problem with the mod (now with Ad Astra joining Oh the Biomes and FTB). I have the Fabric Mods in the recreation Modpack but it works perfectly fine.

**Comment by AIDSmitAIganzWichtig** [comment]
> I can't recreate with that mod either, but just noticed your note on fabric mods and sinytra connector in the mod list I recall there used to be issues with using mods with that. I can't recreate with just Sinytra, potentially the fabric mods are adding stuff here no idea. anyway I really need a set that works as I don't have time to keep retesting all kinds of modpacks that may work. And by "work" I mean modlist that allows me to recreate the issue.

Hi! I was able to recreate to problem with just the sophisticated mods and TslatEffectsLib: https://www.curseforge.com/minecraft/mc-mods/tslateffectslib

It also effects Sophisticated Storage

<details><summary>Screenshots</summary>
<p>

![2024-09-24_08 26 49](https://github.com/user-attachments/assets/3f234ffa-bca6-41df-9d5f-8cc33418f180)

![2024-09-24_08 12 39](https://github.com/user-attachments/assets/b8da0e4e-6dde-4bfe-86dd-3f181d30c139)

</p>
</details>

**Comment by P3pp3rF1y** [comment]
So yeah that mod seems to attach some capability to item stacks. I was going to try to see in dev what exactly it is doing that this doesn't work, but it's impossible to do so with the latest version (well I could make it work if I spent at least hours maybe days changing my dev environment completely which I am not going to do) and I spent too much time already trying to find a version that would work and then again it may have different code from the one you're running. I am pretty sure other mods also attach capabilities to stacks and they don't cause this issue in backpacks so there's something going on here specifically. At this point I would just call it incompatibility or you can report to them if they want to spend time figuring out what's wrong.

**Comment by chesspiece203-glitch** [comment]
Ok so 2026 comment here, had this exact same issue but in 1.16.5, I have discovered the source was from updating "Dungeon Mobs" mod in my heavily modified version of the valhelsia 3 modpack. Updating the mod from "dungeon_mobs-1.16.5-1.0.10.jar" to "dungeon_mobs-1.16.5-2.2.3.jar" installed the mod library "dungeons_libraries-1.16.5-1.0.6", and duplicated the exact bug from this thread. undoing that update and uninstalling the library fixed the issue. Thought i'd comment on this thread so u have this info :)
