### ISSUE TITLE
Pasting recipe from emi caused crash

### ISSUE THREAD

**Issue by mxnmnm** [P3pp3rF1y/SophisticatedBackpacks#1152]
**Describe the bug**
I had a bookmarked recipe in emi and I tried to craft it in a backpack with the crafting upgrade and I crashed. I'm not sure if mods other than emi and jei are involved, but I do have many other mods installed (aka idk the minimum number of mods required other than emi, jei, and sophisticated backpacks). I was playing on a server and my client crashed.

Crash: https://gist.github.com/mxnmnm/22efbef8f4c994de0ba50661880a8dd9

**To Reproduce**
1. Open backpack with crafting upgrade
2. Bookmark recipe with emi (I had an apotheosis salvaging table as the recipe)
3. Try to craft it
4. Crash

**Expected behavior**
No crash

**Versions**
Minecraft: 1.20.1
Forge: 47.3.6
Sophisticated Core: 0.6.26.668
Sophisticated Backpacks: 3.20.7.1075 (haven't gotten around to updating yet)

**Comment by P3pp3rF1y** [comment]
Update sophisticatedcore to the latest release that has a compat for that version of JEI you have there.
