### ISSUE TITLE
Chipped Upgrades missing texture

### ISSUE THREAD

**Issue by MrEizy** [P3pp3rF1y/SophisticatedBackpacks#1157]
**Describe the bug**
So when you have sophisticated backpacks, Chipped and JEI It will make missing textures when trying to look at chipped recipes and you go to the backpack tab. Not sure if i can be more precise. theres no crash though

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Get Chipped & JEI
2. press R on a chipped block
3. Go over to the JEI Tab for Chipped upgrades on the backpack and it will show missing texture

**Expected behavior**
Not missing texture

**Screenshots**

**Versions**
Mod version (1.21-3.20.12.1095) Neoforge (21.1.61)

**Comment by P3pp3rF1y** [comment]
could you show screenshot of that? I can see purple / magenta background (which kind of looks like broken texture) in chipped jei tab that shows recipes you can use in chipped blocks and consequently in chipped upgrades for backpack, but that tab is added by chipped and sophisticated doesn't change it in any way.

**Comment by P3pp3rF1y** [comment]
any update on this or should I just close?

**Comment by P3pp3rF1y** [comment]
closing given no response
