### ISSUE TITLE
neoforge 1.21.1 unable to load

### ISSUE THREAD

**Issue by VaporeonScripts** [P3pp3rF1y/SophisticatedBackpacks#1162]
**Describe the bug**
![image](https://github.com/user-attachments/assets/57cc7fcb-3074-46bc-89ec-17812f1e189d)

**To Reproduce**
use latest of the 3 mods 

**Expected behavior**
![image](https://github.com/user-attachments/assets/38ee68dd-9f4b-4d20-a3cb-520fa0224dff)

**Screenshots**
![image](https://github.com/user-attachments/assets/f3efd1ff-d40b-4de3-856e-ebce9052e53c)

**Versions**
1.21.1, .61, latest of all 3 mods

**Comment by VaporeonScripts** [comment]
specifically, using this https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/5765481 caused the issue

**Comment by P3pp3rF1y** [comment]
latest release fixes this
