### ISSUE TITLE
[1.21.1} New Version requesting incorrect depency

### ISSUE THREAD

**Issue by Periam** [P3pp3rF1y/SophisticatedBackpacks#1163]
**Describe the bug**
After installing the latest version of the mod, the same is requesting a newer version for Core, that is installed.
[latest.log](https://github.com/user-attachments/files/17176028/latest.log)

**To Reproduce**
1. Install Mods
2. launch instance
3. See error

**Expected behavior**
That the game launch.

**Screenshots**
![image](https://github.com/user-attachments/assets/c40f4d10-c7c0-4d30-abcb-e790af5f8048)

![image](https://github.com/user-attachments/assets/03a242c3-302d-43c7-bf72-98a1e143cf1f)

**Versions**
See screen shots.

**Comment by BrandonPotter0** [comment]
Just updated and can confirm this is an issue currently.

**Comment by BrainInBlack** [comment]
```[[dependencies.sophisticatedbackpacks]]
modId="sophisticatedcore"
type="required"
versionRange="[0.6.39.+,)"
ordering="NONE"
side="BOTH"```

The excess dot in the versionRange seems to be the issue here... though no clue why it got appended to the versionRange

**Comment by P3pp3rF1y** [comment]
latest release fixes this
