### ISSUE TITLE
[Crash]: Moving the items into the crafting table of the backpack with JEI

### ISSUE THREAD

**Issue by HenrikoMagnifico** [P3pp3rF1y/SophisticatedBackpacks#1167]
**Describe the bug**
Moving items into a crafting table of a backpack from Sophisticated Backpacks with JEI causes the client to crash.

**To Reproduce**
1. Create Creative World
2. Give youself a backback, a crafting upgrade and a stack of logs
3. Open backpack and open crafting interface.
4. An JEI check the recipe for planks and click [+]

**Expected behavior**
For the game to not crash.

**Versions**
sophisticatedcore-1.20.1-0.6.26.668
sophisticatedbackpacks-1.20.1-3.20.7.1075
jei-1.20.1-forge-15.19.5.99

Forge version: fmlloader-1.20.1-47.3.10

[crash-2024-09-29_13.33.19-client.txt](https://github.com/user-attachments/files/17179126/crash-2024-09-29_13.33.19-client.txt)

**Comment by P3pp3rF1y** [comment]
just updated to latest and issue solved
