### ISSUE TITLE
(1.19.2) Refill upgrade wasting items when Off Hand "disappears" from HotBar (Conflict Mod Ex: Better Combat)

### ISSUE THREAD

**Issue by GuiGuitozao** [P3pp3rF1y/SophisticatedBackpacks#1173]
**Describe the bug**
I installed Better Combat in my modpack and I had a backpack with refill configured so that the totems would go to my Off hand slot, however, when you equip a special melee (Ex: Nightmare scythe from born in chaos) that makes the "Off hand Hot Bar" disappear, it makes the refill upgrade use up all the totems and they go nowhere, so there is no way to use off hand refill and better combat with meless from born in chaos for example. I'm not sure, but I bet this must happen with several other mods that add "special melees" animations

Doesn't crash at all

I didn't found any issue here that looked like this

Mods ver:
Sophisticated backpacks 1.19.2-30.2.1035
Better Combat 1.7.1+1.19
Born in Chaos 1.0.0

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Have Better combat installed and Born in chaos (or other  mod that add "special melees")
2. Add the Refill upgrade inside the backpack and configure an item to refill "Off Hand Slot"
3. With the upgrade Refilling the Off Hand slot, grab a Nightmare Scythe from born in chaos for exemple, you will notice the item in the off hand hotbar disappearing
4. Open the backpack and you will see the items (for me i used totems) disappearing pretty fast

**Expected behavior**
Despite the Totem disappearing from my off hand hotbar, i expected for it to behave like the mod usually does, and Refill upgrade not wasting and disappearing the totems inside the backpack because of the off hand hotbar going off when using nightmare scythe with better combat

**Screenshots**
I didnt screenshot this, however i uploaded a video on Streamable for better view:
(https://streamable.com/i8950y)

**Versions**
Sophisticated backpacks 1.19.2-30.2.1035
Better Combat 1.7.1+1.19
Born in Chaos 1.0.0
Forge: 43.4.4

**Comment by P3pp3rF1y** [comment]
You will need to report this to Better Combat - refill just checks if there's item in offhand and puts the item in there if it is not there. And the changes they are making appear to very likely change the underlying vanilla code to report there's nothing in offhand at all.
