### ISSUE TITLE
Items Aren't Stacking Properly in Player Inventory

### ISSUE THREAD

**Issue by Coraline774477** [P3pp3rF1y/SophisticatedBackpacks#1174]
Steps to Reproduce the Bug:
1. Have a stackable item in your hot bar
2. Place the item (say a fence piece)
3. Break it and pick it up
4. It'll not stack and it's a new item stack

Expected Behavior:
Items stacking like before

Actual Behavior:
When breaking stackable items (E.G: Oak Fences) they apparently have a different NBT tag and will not stack properly anymore like how they should.

Mod Pack URL (Optional):
No response

Mod Pack Version (Optional):
No response

Extra Notes (Optional):
Minecraft: 1.20.1
Forge: 1.20.1-47.3.10
Sophisticated Core 1.20.1-0.6.33.711 or older
Sophisticated Backpacks 1.20.1-3.20.11.1115 or older

Items are not stacking like they should when I break and pick them up.
Like say I miss placed a oak plank and I break it, it won't stack with the existing stack and make a new stack of oak planks instead..
Also when I have any stackable item in my hot bar that when I right click with it that an animation happens.
The item moves up and down but that's only it.
Which is when I place that item and then break it and pick it up that it will not stack.

This issue started happening after I've remade my MineColonies world (my initial MineColonies world was made before Sophisticated Core 1.20.1-0.6.33.711 and Sophisticated Backpacks 1.20.1-3.20.11.1115 I presume) and I'm on my new world called Cora World: TACZ w/Epic Fight (made after Sophisticated Core 1.20.1-0.6.33.711 and Sophisticated Backpacks 1.20.1-3.20.11.1115)...

So on my initial Minecolonies world before the remake world that items were stacking when I break and pick them up but sometime between then and now as of the updates that you might have borked/broken something to cause this issue to happen.
I bet that this issue isn't going away anytime soon..
However it's just an annoyance but a problem that needs fixing neither the less.

One more thing, that's not the latest log, however that log should provide the vital information needed in order to potentially find a solution to this bug.
Also I think that this log was made during my last gaming session.
Since my gaming sessions tends to last till the next day sometimes.

Since the actual latest log doesn't show very much information because I literally just got to the title screen of Minecraft that I'm not in any world just yet.
(However, by the time you read this I'll already be on Cora World: TACZ w/Epic Fight as I craft the guns from TACZ and it's addon mods and the armors from a addon mod for TACZ.)

latest.log
https://gist.github.com/Coraline774477/b3d118fef442c308ca5f5c8e8f746a7f

P.S: I've copied this report from JEI's issue tracker and modified it to report about your mods after finding out that the issue may be coming from your mods, P3pp3rF1y...
Also I've since removed both mods to see if they're the ones causing items to no longer stack like how they should..
Even though I want to keep them installed since the Netherite Backpack has tons of storage space for items/loot as well as the upgrades such as the magnet and the pickup upgrades which are extremely helpful/useful and Sophisticated Backpacks is practically the spiritual successor to Iron Backpacks mod...

**Comment by P3pp3rF1y** [comment]
Sophisticated doesn't attach any NBT to anything but its own items. Are you able to recreate that issue with just sophisticated in the pack? Sounds like you are placing/breaking vanilla blocks so that should be easy to try.

**Comment by Coraline774477** [comment]
UPDATE: 

My last game session I did not have your mods installed and the issue was still happening.
So both of your mods are debunked as being the corporate of the issue.
So, during mod loading that after it reached "mod loading completed" that the game freezes up for a minute. Same happens when loading into the world.

I have took the time to figure out which mod was the corporate that's causing this whole mess and it's the main mod for the world I'm currently playing which is the gun mod TACZ (Timeless and Classics Guns: Zero)..

I think that why its happening in my MineColonies world is possibly coming from the main mod of that world MineColonies...

Before I conducted the tests to see which mod(s) was causing this issue that I had noticed a pattern when starting the game up during mod loading and during world loading which then leads to the main issue of items not stacking properly.

During the tests with just the performance mods installed on a test world that's fresh that I grabbed a stone axe and chopped two blocks of a spruce tree (since I spawned in a taiga biome in the test world) and I was right clicking with the two spruce logs in my hand and placing one back and breaking it again and it did stack.

However, when TACZ is installed I didn't even had to be in the test world because of the patterns at the start before ever entering the test world itself. The freeze during mod loading and world loading was a dead giveaway to the main issue at hand.

**Comment by Coraline774477** [comment]
I'm guessing that itll happen in my MineColonies world as well if I were to try to debunk MineColonies being the corporate to this issue as well...

**Comment by Coraline774477** [comment]
I'm starting to think that it has something to do with Forge itself...
Lex did his "magic" yet again with certain mods that he screws up when he's updating forge...

Since one forge update screwed up some mods such as Player Companions for an example with bad TPS lag, like really bad that's perpetual with or without the problematic mods installed which forces me to stop playing with those mods and delete my worlds due ti the bad TPS lag and now with mods like MineColonies and TACZ that what I've described above happens when they're installed!...

Now I can see why most of the mod authors such as the Twilight Forest devs decided to dump forge for NeoForged...
Since I'm getting sick and tired of Lex's bs and I'm not a mod creator for peet sakes!

**Comment by Coraline774477** [comment]
So, I was talkin on TACZ's discord server and someone was telling me to just forget about this whole thing and move on since forge is being forge as usual with it's millions of issues that Lex wouldn't fix and I'm afraid that this particular issue won't be fixed any time soon.

So what this means that I've lost 2 of my 6 modded minecraft worlds today to some random forge issue that Lex created and possibly wouldn't be fixing any time soon...

So practically I've done all of this for nothing and wasted your time as well as mine for no particular reason pretty much...

I'm sorry for causing this whole mess, conundrum, and commotion to begin with....

If you want too you can close this issue as whatever the label is or as "Won't Fix" since I believe that whatever I've encountered is a forge issue not particularly a mod issue. Since the problem is affecting MineColonies and TACZ but not Mine and Slash, Epic Fight and MCA Reborn😞
(those Mods are the main mods of my three remaining 1.20.1 worlds that I have while my fourth world is my 1.19.2 Immersive Engineering world)

P3pp3rf1y, I'm sorry for all of this as well as wasting your time dealing with this when you could've been using that time dealing with other issue reports that are affecting Sophisticated Backpacks and Core that you're fixing that deserves your attention more than this possibly false issue report😥

**Comment by P3pp3rF1y** [comment]
Well I am not a Lex fan by far, but do you actually have any clues that tell you it's definitely forge? It seems to me more like some mod took a shortcut and is using `getOrCreateTag` on all items unintentionally creating empty nbt tags which make those items different from nbt tags that are set to null. 

Anyway it sounds like this is not related to sophisicated so I am going to close

**Comment by Coraline774477** [comment]
Maybe both TACZ and MineColonies are doing that with "getOrCreateTag on all items unintentionally" which creates empty nbt tags which make those items different from nbt tags that are set to null?

**Comment by Coraline774477** [comment]
I still have TACZ issue tracker opened on a another chrome tab that I can copy that snd paste that as extra detail for the mod author to know about that?

**Comment by P3pp3rF1y** [comment]
It would be enough for them if you are able to recreate with just their mods and forge in the pack, they would know to be careful with these calls.

**Comment by Coraline774477** [comment]
I've finally found out what mods were causing the right click issue.
The mods are;
Mo' Enchantments and 
TACtical Movement mod

Both are MCreator mods btw

**Comment by P3pp3rF1y** [comment]
> I've finally found out what mods were causing the right click issue. The mods are; Mo' Enchantments and TACtical Movement mod
> 
> Both are MCreator mods btw

And both are closed source so I can't even take a look at their code, so yeah you would need to report it to them but it's very likely they may not even be able to fix it if it's actually mcreator itself doing the thing.

**Comment by Magamelin** [comment]
For those who have also encountered this issue, customNPC  forge 1.20.1 also causes this problem.

**Comment by GamingHQ** [comment]
Apologise for reopening a topic from a year ago, but this might be worth it for future search results if anyone experiences the same issues.

yesterday, we encountered the same issue, where random items like iron ingots or cobblestone stairs didn't properly stack, while the NBT data was intact and not corrupted. One thing is good to know, is that the backpacks and storage mods from here has nothing to do with it. 

As you ( coraline ) had TACz installed, look up if you also have some oddly levelling mod with it as well. This levelling TacZ stuff mod is excluded only for their server and on purposely has bugs for those trying to use it without its coremod. I had the same issue, after installing a structure mod for "lost cities mod", that came along with a load of nonsense that just doenst work at all without its coremod.

The mod we deleted that was making the problems on our end. 

https://www.curseforge.com/minecraft/mc-mods/tacz-weapon-leveling

**Comment by Coraline774477** [comment]
On Cora World: TACZ and Cora World: Zombie Apocalypse (that has TACZ in it) I dont have such mods like what you speak of, the only leveling system is TACZ's which is disabled/NYI currently.

**Comment by Coraline774477** [comment]
Btw, I still dont have this problem reoccurring since the removal of the mods I've said above from last year and have been avoiding them like the plague. I also dont play with the mods that Magamelin played with as well as the ones GamingHQ said. The only addons for TACZ that I have are:

TACZ Bullet Proof Enchant
[TaCZ] Endless Ammo
TaCZ Tweaks
[tacz] Maxstuff
TACZ: Durability
[TACZ] Enchanted Arsenal
And gunpacks that's in customization category on curseforge along with the addons channel on TACZ's discord server.
