### ISSUE TITLE
Crash when using Sophisticated Backpacks crafting upgrade

### ISSUE THREAD

**Issue by 420science** [P3pp3rF1y/SophisticatedBackpacks#1175]
**Describe the bug**

When pressing the + icon to get a recipe in the crafting grid the game crashes.
Will submit same issue with JEI Github:
https://github.com/mezz/JustEnoughItems/issues/3818

Crash log if it's a crash.

[crash-2024-10-13_19.35.50-client.txt](https://github.com/user-attachments/files/17356551/crash-2024-10-13_19.35.50-client.txt)

Info on what other mods you're using that may cause a conflict here if applicable.

250 Total mods.

**To Reproduce**
1. Open backpack
2. Click on 'Crafting' tab
3. Get some coal and sticks (Or logs ect...)
4. Use JEI to search recipe (torch/planks/pickaxe)
5. Press the + to add items to crafting grid 
6. Crash :)

**Expected behavior**

Not crashing? :)

**Versions**
Minecraft 1.19.2
Forge 43.4.0
sophisticatedbackpacks-1.19.2-3.20.2.1035
jei-1.19.2-forge-11.8.1.1033

**Comment by P3pp3rF1y** [comment]
you will need to donwgrade jei to version that is supported which should be 11.6.something. I haven't really supported 1.19.2 for a long time now and don't intend add compatibility for newest JEI given that players can play with newer versions of modded mc / mods.
