### ISSUE TITLE
Compacting / Compression does not work in Sophisticated Backpacks crafting

### ISSUE THREAD

**Issue by eSonOfAnder** [P3pp3rF1y/SophisticatedBackpacks#1177]
**Describe the bug**
Advanced Compacting Upgrade does not work; Crafting Tweaks hotkey for Compress Item/Stack/All also does not work with the Crafting Upgrade. I expect this is the same bug in different clothes.

Using this as part of the All the Mods 10 modpack: https://github.com/AllTheMods/ATM-10

**To Reproduce**
1. Open backpack
2. Install Advanced Compacting Upgrade
3. Add a stack of items that have a 3x3 compressed form (e.g. raw iron, iron ingots, etc.)
4. See that they are not auto crafted into their 3x3 compressed form

Alternate (with Crafting Tweaks):
1. Open backpack
2. Open crafting tab
3. Hover over a stack of items that have a 3x3 compressed form
4. Press one of the Compress Item/Stack/All hotkeys while hovering over said stack
5. See that they are not compressed into their 3x3 compressed form

**Expected behavior**
(Advanced Crafting upgrade) Items that are added to the backpack are auto-crafted into their compressed form
(Crafting Tweaks) Items are compressed into their compressed form when the appropriate hotkey is pressed

**Versions**
Sophisticated Backpacks: 1.21-3.20.17.1113
Sophisticated Core: 1.21-0.6.44.719

Have not tried updating Sophisticated Core, yet, to see if there is any difference in behavior.

**Comment by P3pp3rF1y** [comment]
Having the crafting upgrade work with compress key will require extra compatibility to be added I am pretty sure, I can take a note and potentially add depending on how complicated it's going to be.

As for compacting upgrade, how are you adding the items that you are compacting? Having them picked up by something like pickup upgrade / magnet upgrade or are you just clicking stacks in using gui? If the latter have you toggled the upgrade to actually compact stacks in gui?

**Comment by eSonOfAnder** [comment]
I will have to double check the setting on the upgrade when I can get back into game later today. I am not using any sort of pickup or magnet upgrade in it.

**Comment by eSonOfAnder** [comment]
It was on GUI mode, I flipped it to automation / upgrades mode and then back to GUI, and it seems to be working as expected now. I'm happy to chalk that one up to a weird glitch on my end. If you'd like me to create a feature request for the Crafting Tweaks compatibility, just let me know! (Since both things looked like they were failing from my POV, I assumed it was likely to be a single bug affecting both.)

**Comment by P3pp3rF1y** [comment]
> It was on GUI mode, I flipped it to automation / upgrades mode and then back to GUI, and it seems to be working as expected now. I'm happy to chalk that one up to a weird glitch on my end. If you'd like me to create a feature request for the Crafting Tweaks compatibility, just let me know! (Since both things looked like they were failing from my POV, I assumed it was likely to be a single bug affecting both.)

yes separate feature request for the crafting tweaks compression would be good, thanks

**Comment by P3pp3rF1y** [comment]
And I am closing this one given that the compacting upgrade works
