### ISSUE TITLE
problems with pickup upgrade [1.16.5]

### ISSUE THREAD

**Issue by MisterCat100** [P3pp3rF1y/SophisticatedBackpacks#1181]
Hello, when I mine blocks, let's say a cobblestone with a pickup upgrade, then they are added two at a time, but if I combine them, throw them out and pick them up, then they are already normally combined
**Version of game and mod**: 1.16.5-3.15.19.721
**Version of forge**: 36.2.39

**How it works:**
![image](https://github.com/user-attachments/assets/f11e5173-982b-46ef-8b76-724e3dd44bce)

**How it should**
![image](https://github.com/user-attachments/assets/4f74a6d1-7141-4d3d-b716-196d3da9e50c)

**Comment by P3pp3rF1y** [comment]
A mod in your modpack is causing the items to have different data when they are picked up. You will need to figure out which one and remove if you want to fix. I don't support 1.16.5 for at least 2 years now so can't grt you more help than that

**Comment by MisterCat100** [comment]
> A mod in your modpack is causing the items to have different data when they are picked up. You will need to figure out which one and remove if you want to fix. I don't support 1.16.5 for at least 2 years now so can't grt you more help than that

is it possible to sort the backpack automatically in survival, would that solve the problem?

**Comment by P3pp3rF1y** [comment]
There's no such functionality in the mod and I am not going to add it so no. You can of course go ahead and play with the mod in newer versions where this mod that was causing the issue doesn't seem to exist.

**Comment by MisterCat100** [comment]
> There's no such functionality in the mod and I am not going to add it so no. You can of course go ahead and play with the mod in newer versions where this mod that was causing the issue doesn't seem to exist.

Why won't you add it to the mod? it would be possible (on new versions) to make a type of next level (diamond, for example) for pickup upgrade

**Comment by P3pp3rF1y** [comment]
That functionality doesn't make sense because it's basically a functionality that "fixes" another mod's bug. An even if I was adding it it would be at the very least 1.20+

**Comment by MisterCat100** [comment]
> That functionality doesn't make sense because it's basically a functionality that "fixes" another mod's bug. An even if I was adding it it would be at the very least 1.20+

I suggest doing this on the latest versions, since I realized that you won't do it on the old ones.
and yet, why it can be convenient, not because it fixes a bug, but because, let's say, we have blocks, artifacts and tools in a mess and we need to take something and have to run our eyes all over the backpack, and when there is an auto-sorting, we won't have to do it, everything will be more clearly

**Comment by P3pp3rF1y** [comment]
Why wouldn't you just sort at that point. I mean it's one middle click.
I am definitely not implementing auto sort because of this even if it was on a toggle off by default because that could make players toggle it on more often than needed (which I still doubt when it would be needed) and server performance would tank just because of the constant comparisons of the stacks and figuring out if everything needs to move around.

**Comment by MisterCat100** [comment]
> Why wouldn't you just sort at that point. I mean it's one middle click. I am definitely not implementing auto sort because of this even if it was on a toggle off by default because that could make players toggle it on more often than needed (which I still doubt when it would be needed) and server performance would tank just because of the constant comparisons of the stacks and figuring out if everything needs to move around.

because after selecting each resource, you need to go in and sort, it would be a chore
to do the sorting once every 15 seconds or similar

**Comment by P3pp3rF1y** [comment]
> > Why wouldn't you just sort at that point. I mean it's one middle click. I am definitely not implementing auto sort because of this even if it was on a toggle off by default because that could make players toggle it on more often than needed (which I still doubt when it would be needed) and server performance would tank just because of the constant comparisons of the stacks and figuring out if everything needs to move around.
> 
> 
> 
> because after selecting each resource, you need to go in and sort, it would be a chore
> 
> to do the sorting once every 15 seconds or similar

Just to be clear I commented on your point that when you need to take something out of backpack it would be beneficial to have it already sorted. I don't think you need to do that every 15 seconds.

**Comment by MisterCat100** [comment]
> > > Why wouldn't you just sort at that point. I mean it's one middle click. I am definitely not implementing auto sort because of this even if it was on a toggle off by default because that could make players toggle it on more often than needed (which I still doubt when it would be needed) and server performance would tank just because of the constant comparisons of the stacks and figuring out if everything needs to move around.
> > 
> > 
> > because after selecting each resource, you need to go in and sort, it would be a chore
> > to do the sorting once every 15 seconds or similar
> 
> Just to be clear I commented on your point that when you need to take something out of backpack it would be beneficial to have it already sorted. I don't think you need to do that every 15 seconds.

of course a lot of time has passed, but the initial sorting does not help and initially I can not know what I will find
when the backpack picks up items that are the same, then it considers them as different and separates into different slots, taking up extra space
noticed that on new versions a similar problem but in other moments and mods

**Comment by P3pp3rF1y** [comment]
that is caused by some mod attaching data that it doesn't properly clear when the item is picked up making the item different from the ones that exist in the backpack. Origins is one of the examples of such mod. if you don't have that and can figure out which other mod is causing this I can take a look and potentially adjust my code if there's anything I can do (but very likely it will need to be fixed on that mod's side)

**Comment by MisterCat100** [comment]
I think autosorting would solve this problem
But I'm unlikely to know which mod is causing it
By the way, congratulations on being the author of the month!
