### ISSUE TITLE
Crash with smooth swapping - forge updated latest version on forge 1.20.1

### ISSUE THREAD

**Issue by Dodo19DBG** [P3pp3rF1y/SophisticatedBackpacks#1183]
**Describe the bug**
When swapping an item (shift+click) from the backpack to the inventory, the game crashes. Also, the swapping from inventory to
backpack isn't smooth.

**To Reproduce**
1.install SS - forge updated for 1.20.1 ( https://modrinth.com/mod/smooth-swapping-forge-updated )
2. Open backpack
3. Swapp an item that is in the backpack with shift + left click to put it in the inventory
4. Game crashes immediatly

**Expected behavior**
The item should simply come smoothly in the inventory and the items in the inventory should do the same
(not the case but doesn't makes the game crash)

**Versions**
Latest version of Smooth swapping AND SophisticatedBackpacks, on every version of forge, 1.20.1 .

**Comment by P3pp3rF1y** [comment]
That is a known issue in smooth swapping you need to report to them
