### ISSUE TITLE
Disappearing items

### ISSUE THREAD

**Issue by QueenDarkLady** [P3pp3rF1y/SophisticatedBackpacks#1185]
**Describe the bug**
Items can be shift-clicked into the inventory slot of the Match Tags option of the Advanced Upgrades, specifically Advanced Filter or Advanced Pickup (I don't know about others), resulting in more than one item in the spot. When the items are clicked on, they disappear. 
This is used with the Vault Hunters pack 3rd edition 3.15.1.4

**To Reproduce**
1. Access any backpack with an Advanced Pickup or Advanced Filter upgrade attached. 
2. Click on the tab to access the upgrade's settings
3. Change to the "Match Tags" option
4. "Place" an item with tags in the slot used to add tags (this will not actually remove the item from your inventory)
5. Shift-click on the item from your inventory (it will go into the slot used to add tags, resulting in the item showing more than one in that slot)
6. Click on the slot used to add tags. This will cause the item, including the one that had been in your inventory, to disappear. They will also disappear if you close the backpack inventory

**Expected behavior**
I would expect items not to be able to stack in the slot used to add tags to the filter.

**Screenshots**
Screenshots included showing the issue using a Small Backpack with the Advanced Filter upgrade with multiple eggs in the slot used to add tags.
![2024-10-23_19 31 13](https://github.com/user-attachments/assets/31ec4e45-59ba-4793-97a9-e13d2d530513)
![2024-10-23_19 31 20](https://github.com/user-attachments/assets/24525dce-11b4-4146-9a1c-cb3c9597d8a7)

**Versions**
Version in use: 3.18.46.821

**Comment by P3pp3rF1y** [comment]
Apparently I fixed this in of the later versions of SB so once that is updated in VH the issue will be fixed
