### ISSUE TITLE
Crafting upgrade slots can't hold items with 99 max stack size

### ISSUE THREAD

**Issue by Phoupraw** [P3pp3rF1y/SophisticatedBackpacks#1187]
**Describe the bug**
If you try putting a stack of item whose count is greater than 64 into crafting slots, only 64 items are placed, leftover remains in cursor.

**To Reproduce**
1. Run command `/give @p stone[minecraft:max_stack_size=99] 99`.
2. Hold the items in cursor and click slots in crafting upgrade.
3. Only 64 items are placed.

**Expected behavior**
The entire stack should be placed.

**Screenshots**
![image](https://github.com/user-attachments/assets/b11ee854-0b31-4c34-9c72-12dccb91e331)

**Versions**
- MC 1.21(.1)
- Neoforge 21.0.143
- Sophisticated Core 0.6.45
- Sophisticated Backpack 3.20.17

**Comment by P3pp3rF1y** [comment]
This is a non issue. There's no way of getting more than max stack size on cursor in regular game and there's way more stuff that would be broken if player was able to. Sounds to me more like that command is broken that it allows this. As such I am going to close unless you can provide me with steps I can get to this in survival without commands.

**Comment by Phoupraw** [comment]
I use command just for sample. In fact I installed a mod that boosts max stack size of all items to 99, so in a way this is a compability issue, though it can be reproduced without that mod.

**Comment by P3pp3rF1y** [comment]
Actually looking more into how this new data component works I am finding that I am wrong about vanilla capping at 64 in guis. Looks like I have to fix this one to allow max 99 or max stack size as defined for the stack if that's lower

**Comment by P3pp3rF1y** [comment]
This was fixed in the latest release
