### ISSUE TITLE
Stack Upgrades + Autofeeding Upgrades causes crash/disconnect on server

### ISSUE THREAD

**Issue by alfredggttv** [P3pp3rF1y/SophisticatedBackpacks#1193]
**Describe the bug**
Player could load into the server, but it wouldn't update his player.dat file. The world also refused to load for him. The server log showed that it was bugging due to "Value must be within range". He had a stack of carrots (175) and it was trying to autofeed him. I opened up his NBT file and edited out his auto-feed upgrade, and this allowed him to connect.

Server log for issue: 
[volt crash.txt](https://github.com/user-attachments/files/17611416/volt.crash.txt)

**To Reproduce**
1. Install a stack upgrade into backpack
2. Install a Feeding Upgrade into backpack
3. Place food items higher than the vanilla stack limit
4. When the upgrade tries to feed you, it throws the issue. On the server, this made it where the player couldn't see the world and the server couldn't update his player files.

**Expected behavior**
Feeding upgrade feeds the player, allows them to connect and keep playing.

**Versions**
Sophisticated Backpacks: 1.21-3.20.17.1113
Modpack version: FTB Evolution 1.0.3
NeoForge version: 21.1.72

**Comment by P3pp3rF1y** [comment]
I actually changed how feeding upgrade works just yesterday and it should only be putting stack of size 1 in player's hand and this crash should not be happening anymore. Could you retry with the newest version of SophisticatedCore?

**Comment by alfredggttv** [comment]
Will do in the next pack version, which should be tomorrow.

**Comment by P3pp3rF1y** [comment]
Closing this issue as the related issue in FTB pack was already closed
