### ISSUE TITLE
Game crashes when using JEI to craft in upgrade tab

### ISSUE THREAD

**Issue by helo-debug** [P3pp3rF1y/SophisticatedBackpacks#1200]
**Description**
When you use JEI to automatically place items in crafting upgrade tab, the game crashes.

I am using Create: Mekanized + Sophisticated Backpacks + ColossalChests + CyclopsCore + Sophisticated Core + JEI
[Crash Log](https://github.com/user-attachments/files/17756786/crash-2024-11-14_16.50.53-client.txt)

**To Reproduce**
1. Open backpack with crafting tab (the tab needs to be closed for JEI to fit).
2. Click on a recipe in JEI that you have the resources to craft.
3. Click the  "+" button

**Expected behavior**

I expected it to open the crafting upgrade tab and put in the resources needed.

**Screenshots**

![2024-11-10_13 53 27](https://github.com/user-attachments/assets/5a84f925-e56f-400f-a2d5-20dc5acd7228)

![2024-11-10_13 54 39](https://github.com/user-attachments/assets/4e1cff15-29db-4296-9173-b00eec075b60)

**Versions**

- Create: Mekanized  v1.6.2
- Sophisticated Backpacks1.19.2-3.20.2.1035
- Sophisticated Core 1.19.2-0.6.4.605
- ColossalChests 1.9.0
- Cyclops Core 1.19.5
- Just Enough Items 11.8.1.1033

**Comment by P3pp3rF1y** [comment]
I will need the crash log, please share it using github gist / pastebin or similar

**Comment by P3pp3rF1y** [comment]
are you able to share the crash log or should I just close?

**Comment by helo-debug** [comment]
> are you able to share the crash log or should I just close?

I've done that

**Comment by P3pp3rF1y** [comment]
right, just update sophisticated core to latest version and you're good this was fixed a bit back to be compatible with new versions of JEI again
