### ISSUE TITLE
Game crash when grab item from backpack via shift+click

### ISSUE THREAD

**Issue by ilu8ha** [P3pp3rF1y/SophisticatedBackpacks#1201]
**To Reproduce**
1. Open backpack
2. Shift+LMB on any items inside
3. Crash 

**Versions**
mc version 1.20.1
forge version 47.3.0
mod version 3.20.12.1126
[crash-2024-11-10_20.59.05-client.txt](https://github.com/user-attachments/files/17692757/crash-2024-11-10_20.59.05-client.txt)

**Comment by P3pp3rF1y** [comment]
Just drop smooth swapping from your modpack and issue is solved. They are causing this issue for more than a year now and don't seem to want to fix it.

**Comment by ilu8ha** [comment]
Thanks!
