### ISSUE TITLE
Client disconnects with error after trying to open my netherite backpack

### ISSUE THREAD

**Issue by jpeaglesandkatz** [P3pp3rF1y/SophisticatedBackpacks#1203]
After upgrading my server and client from All the Mods 10 from 1.17 to 1.19 (the latest) when I try to open my netherite backup it logs error messages and after 3 times trying to open it it disconnects from the server with the error shown in the attached screenshot. Both client and server log several errors.

I changed the max inventory slots in the .toml file on the server to max and the upgrade slots.

I have deleted the configs on the server and client.. restarted.. same errors...

Reproduce:
Try to open the backup...
Backback fails to open

**Versions**
Neoforge 21.1.77
sophisticatedbackpacks-1.21-3.20.19.1124.jar
sophisticatedcore-1.21-0.7.1.753.jar
sophisticatedstorage-1.21-0.10.53.946.jar

Mod version that you're using. Version of forge may also be helpful in some cases
![2024-11-14 09_31_32-Minecraft NeoForge_ 1 21 1](https://github.com/user-attachments/assets/00ce2197-9c3a-4467-997d-14821b6d366e)
[latest.log](https://github.com/user-attachments/files/17745703/latest.log)

**Comment by P3pp3rF1y** [comment]
Have you also changed number of filter slots in your compacting upgrade?

**Comment by jpeaglesandkatz** [comment]
> Have you also changed number of filter slots in your compacting upgrade?

Ouch..... I had before.... And since I upgraded the server/pack versions... It deleted those changes.. Thought I had copied them over... You are right... I did miss those edits to the additional upgrades... :(   Just made those edits again, and crash is gone.

Perhaps though there would be a more gentle way to protect the server/client from crashing if it detects when the NBT data on those upgrades does not reflect those in the config files?

But cheers for responding so quickly!! These mods have been one of my favorites since you made them..

The only big thing that really is missing is a way to search in your chests/ backpacks.. Things can get very hectic with so many different blocks in modpacks..

**Comment by P3pp3rF1y** [comment]
Agreed on this needing to be handled in a better way. I will take a look and if at all possible correct it so that it works with the previously higher number of slots or somehow logically reduces the number of filter slots on the upgrade

**Comment by P3pp3rF1y** [comment]
Just posted a new release of Sophisticated Core which fixes the number of filter slots to stay recorded on the upgrade itself and keeping showing that number even if the default in the config changes to a lower one - the config default affects only new upgrades similar to how it works for backpack slots. It's already available on Modrinth and will be available on curseforge shortly after it is approved.

**Comment by jpeaglesandkatz** [comment]
> Just posted a new release of Sophisticated Core which fixes the number of filter slots to stay recorded on the upgrade itself and keeping showing that number even if the default in the config changes to a lower one - the config default affects only new upgrades similar to how it works for backpack slots. It's already available on Modrinth and will be available on curseforge shortly after it is approved.

Cheers that was quick.. I see you also added a search option.. That is great..  One suggestion if possible, also make it searchable for enchants? 

But my current netherite chests now display as this when scrolling...

I just checked the settings in the .toml.... I updated a few advanced update modules and only the netherite backup/chests to max slots...

Slidiing down shows a broken UI.... 


[broken_storage_scrolling_sophisticatedstorage-1.21-0.10.54.949.webm](https://github.com/user-attachments/assets/cf1b53e3-279b-480c-ae6b-9166291a40e8)
[configs.zip](https://github.com/user-attachments/files/17796846/configs.zip)

**Comment by P3pp3rF1y** [comment]
I fixed that bug 2 days ago, you need to update core for sure, but I believe there was a minor thing in storage as well so worth updating that

**Comment by P3pp3rF1y** [comment]
And yes I will take a look at adding tooltip search as well so that it can be used to search for enchantment names

**Comment by jpeaglesandkatz** [comment]
Awesome job.. Thanks for  are the work you are putting into making this great mod even better and the fast replies!!! :)

**Comment by jpeaglesandkatz** [comment]
Hey there again... Question, were you by any chance planning to backport the latest changes, mainly the search funcion to maybe the 1.20.1 version (think still the most played version)? Would be awesome but haven't looked at the code yet so not sure how involved it would be

**Comment by jpeaglesandkatz** [comment]
Nvm.. my ignorance.. You work fast and already did that... Thanks..

I was trying to build the 1.20.1 and 1.21.1 versions of the mods but failed...  Apparently it needs a config file from a protected source.  Is there any way to build the mods without that? 

Purely for a learning purpose ofc... 

 Unable to load Maven meta-data from https://maven.pkg.github.com/p3pp3rf1y/sophisticatedcore/sophisticatedcore/sophisticatedcore/maven-metadata.xml.
            > Could not GET 'https://maven.pkg.github.com/p3pp3rf1y/sophisticatedcore/sophisticatedcore/sophisticatedcore/maven-metadata.xml'. Received status code 401 from server: Unauthorized

**Comment by P3pp3rF1y** [comment]
> Nvm.. my ignorance.. You work fast and already did that... Thanks..
> 
> I was trying to build the 1.20.1 and 1.21.1 versions of the mods but failed... Apparently it needs a config file from a protected source. Is there any way to build the mods without that?
> 
> Purely for a learning purpose ofc...
> 
> Unable to load Maven meta-data from https://maven.pkg.github.com/p3pp3rf1y/sophisticatedcore/sophisticatedcore/sophisticatedcore/maven-metadata.xml. > Could not GET 'https://maven.pkg.github.com/p3pp3rf1y/sophisticatedcore/sophisticatedcore/sophisticatedcore/maven-metadata.xml'. Received status code 401 from server: Unauthorized

You may be able to get access in there using personal tokens because I am pretty sure you can just go in the packages in sophisticatedcore and see the actual files in there.
