### ISSUE TITLE
Backpack doesn't take single items 

### ISSUE THREAD

**Issue by davidholcomb68** [P3pp3rF1y/SophisticatedBackpacks#1205]
Out of the blue, my iron backpack decided to not accept an item if it had a value of 1/1 on it (i.e. not stackable items). You could not drag and drop, however you could shift click it into the first available slot, however once hitting the 'sort inventory' button, the 1/1 items vanished. Not sure how to reproduce, but it is in game version 1.19.2 and the backpack had a crafting mod in it with designated spots for a couple tools and armours.

**Comment by P3pp3rF1y** [comment]
Does it happen with just SB in the modpack or you have other mods in there? if you have more mods could you try without them?

**Comment by davidholcomb68** [comment]
sb is the only backpack mod installed.

**Comment by P3pp3rF1y** [comment]
Is it the only mod in the modpack though - I am not asking about other backpack mods I am asking about any other mods at all

**Comment by davidholcomb68** [comment]
oh, sorry. the modpack has around ~365 mods, but that has been the case for about a month and it has worked perfectly fine up until yesterday.

**Comment by P3pp3rF1y** [comment]
Sure, but that means that something changed in that modpack that's causing this. It's the very first time I hear about issue like this in any version so it's something specific to your modpack. If you have any mod there that changes max stack size that would be the primary culprit.

**Comment by davidholcomb68** [comment]
yes, that did it. a mod called bigger stacks that came preinstalled with the mod pack (chocolate edition) must have auto updated and messed around with the files. thank you

**Comment by P3pp3rF1y** [comment]
yeah that mod messes up with sophisticated code so in general I would recommend using either sophisticated or bigger stacks

**Comment by davidholcomb68** [comment]
i have found that updating the mod was the issue, the mods are compatible with the most recent version of sophisticated and the second most recent version of bigger stacks.
