### ISSUE TITLE
The other slots is not showing.

### ISSUE THREAD

**Issue by Anonyiw** [P3pp3rF1y/SophisticatedBackpacks#1209]
**Describe the bug**
I'm having a problem/bug, when I open my backpack, whether it’s in my hand or on my back, when i scroll down, for see the other slots for items, i don't see any slots more, in the gold, diamond and netherite upgraded backpacks.
Note: But when I scroll up, the slots appear again.

**To Reproduce**

1. Open the gold, diamond or netherite backpack;
2. Slide the scroll bar for down, or just scroll down;
3. It doesn’t show any slots anymore.

**Expected behavior**
When I scroll down, I should see more item slots appearing, with the possibility of adding more items and viewing them.

**Versions**
Sophisticated Backpacks: 3.20.20.1129.
Sophisticated Core: 0.7.4.762.
NeoForge: 1.21.1-21.1.79.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest core release
