### ISSUE TITLE
Items not consumed by crafting recipes vanish until backpack is closed and reopened. 

### ISSUE THREAD

**Issue by telemenar** [P3pp3rF1y/SophisticatedBackpacks#121]
**Describe the bug**
sophisticatedbackpacks-1.16.4-2.2.9.243.jar

**To Reproduce**
1. Open backpack with crafting upgrade
2. Use it to craft a cake
3. Notice buckets vanish
4. Close backpack and re-open -- buckets are back!

**Expected behavior**
Buckets should not vanish.

**Versions**
sophisticatedbackpacks-1.16.4-2.2.9.243.jar

**Comment by P3pp3rF1y** [comment]
This was fixed in the last release
