### ISSUE TITLE
how to disable this search feature?

### ISSUE THREAD

**Issue by VaporeonScripts** [P3pp3rF1y/SophisticatedBackpacks#1211]
neoforge 1.21.1 .79 
![image](https://github.com/user-attachments/assets/d393d36a-9a4a-49e0-9987-06d5a068c328)

**Comment by P3pp3rF1y** [comment]
You can't. Why do you want it disabled? Also please use either discussion here or discord for questions like this and leave issues for issues.

**Comment by VaporeonScripts** [comment]
Alright ,wanted to disable it cuz I didn't want it

**Comment by P3pp3rF1y** [comment]
I mean I could potentially add that option, but would like to have a bit more of a justification than "I don't want it". there must be a reason that you don't want it, perhaps that reason will convince me why this needs to be added.

**Comment by VaporeonScripts** [comment]
its getting overridden by inventory profiles next, making it annoying

**Comment by VaporeonScripts** [comment]
so id prefer removing the search option :grin:

**Comment by P3pp3rF1y** [comment]
so using IPN in sophisticated gui could lead to item loss if you start using stack upgrades (at least last I heard from them they were looking into adding more compatibility, but decided to not do it after all) so I would recommend hiding those and using the functionality that comes with sophisticated

**Comment by VaporeonScripts** [comment]
They don't cause item loss lol,used sort from ipn for weeks and works fine

**Comment by P3pp3rF1y** [comment]
ok, tested it just now and it appears to ignore oversized stacks and kind of respect memorized slots, but sophisticated sorting is still better here for stuff like having stacks be put together when stack upgrade allows larger stacks than 64 or actually sort oversized stacks by whatever setting sorting is set to.
So definitely it doesn't seem destructive but sophisticated equivalent is clearly better at the very least when stack upgrades are used. Anyway you should be able to shift those ipn buttons to the left using their config.

**Comment by VaporeonScripts** [comment]
Their config is made like shit,nothing works correctly and search function doesn't work😭
