### ISSUE TITLE
Overlap Issue with Insert/Extract Buttons also shift lock working on normal inventory 

### ISSUE THREAD

**Issue by Ferm246** [P3pp3rF1y/SophisticatedBackpacks#1215]
ossible Fixes
Yes

Modpack Version
ATM9

What happened?
Bug Report
Title: Tooltip ![Uploading 2024-11-17_22.21.49.png…]()

Description:
When using the Sophisticated Backpacks mod, the tooltips for the Insert and Extract buttons overlap with other UI elements or text. This makes it difficult to read or understand the tooltips properly.

Steps to Reproduce:

Open the Sophisticated Backpacks inventory.
Hover over the Insert or Extract buttons.
Observe the tooltip's behavior and overlap with other UI components.
Expected Behavior:
The tooltips for the Insert and Extract buttons should display clearly without overlapping with other UI elements.

Observed Behavior:
The tooltips overlap with adjacent UI components, making them hard to read.

Environment Information:

Mod Version: 3.20.12
Minecraft Version:1.20.1

Additional Context:
This issue persists across different resolutions and UI scales. ALSO PERSIST WHILE ON A CLEAN INSTALL OF THE MODPACK

**Comment by Ferm246** [comment]
![Uploading 2024-11-17_22.21.49.png…]()

**Comment by P3pp3rF1y** [comment]
I can't see the screenshot, could you reupload? I am guessing that something else is adding elements into sophisticated gui that this is overlapping with, but better to actually see that

**Comment by P3pp3rF1y** [comment]
Found the issue you logged in ATM issues and commented there. Also please don't double log, best to let modpack authors look at this first and then they / you can follow up here.

**Comment by Ferm246** [comment]
Thanks, sorry for the double log.
