### ISSUE TITLE
Crash when entering zone, sophisticated backpacks and corpse mod

### ISSUE THREAD

**Issue by dvdvdvlol** [P3pp3rF1y/SophisticatedBackpacks#1218]
We updated the mods in our server and since then sophisticated backpacks make everyone crash when they are entering the zone near my dead body. Everything was working before the update and before crashing near I could just not open the inventory where we could see the back packs (curios API) or corpse mod or my one inventory or even once when it dropped on the ground.

HERE THE CRASH REPORT: https://mclo.gs/Lacv9g9 (every mods are at the end of it)

I have not been able to reproduce the error nor in solo world nor in the server I have inception upgrade, tank upgrade (with oil in the tank), stack upgrade, feeding upgrade and maybe some more. Its a netherite backpack 

I expect to be able to get my stuff back and my game not to crash

I have no screen shot but I could have taken one, depending on my render distance when I get near the corpse I crash. (and my friend to)

we can see everything at the end of the crash report just to be sure but: forge: 47.3.0 ; sophisticatedcore-1.20.1-0.7.5.773.jar ; sophisticatedbackpacks-1.20.1-3.20.13.1131.jar 
I switched forge version to the latest still crash.

**Comment by P3pp3rF1y** [comment]
Looks like as part of that update some fluid that was in your backpack got removed and now it's crashing because of that. I will add proper handling of that case so that this doesn't happen anymore

**Comment by P3pp3rF1y** [comment]
There are new releases of sophisticated backpacks and sophisticated core on Curseforge and Modrinth. Should fix this issue for you.

**Comment by dvdvdvlol** [comment]
Wow that was fast thank you it works
