### ISSUE TITLE
Hot bar swap moves oversized stacks

### ISSUE THREAD

**Issue by telemenar** [P3pp3rF1y/SophisticatedBackpacks#122]
**Describe the bug**
Hot bar swap moves oversized stacks. So you can end up with 1000 items in 1 slot on your hotbar. 

**To Reproduce**
1. Open backpack with 1000 cobble in 1 stack due to stack upgrades
2. Hover over stack and hit 1-9 to swap into hotbar. 
3. The whole stack moves -- panic and carefully swap it back in case it might crash things.

**Expected behavior**
1 stack of items should move or keybind should fail to work

**Screenshots**
![2021-04-22_22 07 59](https://user-images.githubusercontent.com/1326160/115821229-45c7d980-a3b7-11eb-88da-b6845a373f40.png)

**Versions**
sophisticatedbackpacks-1.16.4-2.2.9.243.jar

**Comment by P3pp3rF1y** [comment]
Fixed in the last release
