### ISSUE TITLE
Non Stackable Items get deleted after clicking the sort button

### ISSUE THREAD

**Issue by Chancho91** [P3pp3rF1y/SophisticatedBackpacks#1222]
When I put non-stackable items into my backpack and click the sort button, it deletes the items. I'm using the newest version of the mod for 1.18.2. 

What should I do? Is there another version of the mod I should use instead?

**Comment by P3pp3rF1y** [comment]
You are very likely using some other mod to sort your backpack. How are you triggering the sorting? A button or a keybind? Is sophisticated sorting bound to any key / button?

**Comment by Chancho91** [comment]
I'm using the Quark sorting feature. I was using a button to trigger the sorting (mostly), but I used a key-bind too. The sophisticated sorting is bound to the middle mouse button.

**Comment by P3pp3rF1y** [comment]
And there's your issue, just don't use quark to sort sophisticated storages, you should really only use sophisticated button / keybind to sort these.
