### ISSUE TITLE
Crash on startup with newer versions.

### ISSUE THREAD

**Issue by Marius-jj** [P3pp3rF1y/SophisticatedBackpacks#1224]
When updating to newer version of the mod, my game crashes on startup.

Mod version:3.1.59.909.

I have a lot of other mods installed, but all of them works fine with the old version of the Backpack mod.

Is it possible to see the problem through the crash log?
https://mclo.gs/0tQZuS8

**Comment by P3pp3rF1y** [comment]
There's nothing in that crash log that even remotely points to any issue in SB / SC but this tells me you should be able to see something in you log `One of more entry values did not copy to the correct id. Check log for details!` What are you seeing in there? (that is in `latest.log`)

**Comment by Marius-jj** [comment]
Sorry for the late reply, but here is the latest log

https://pastebin.com/8Dbb1X2s

**Comment by P3pp3rF1y** [comment]
you need to update your chipped version, the one you have there is very ancient (almost year and a half old) and they made a breaking change since which I adjusted my code for, but that obviously doesn't work with the old versions

**Comment by Marius-jj** [comment]
Yeah that worked, thanks a lot!

Could i ask where in the latest log you saw that that was the problem? So maybe i'l be able to see it myself if i have any crashes at a later time.

**Comment by P3pp3rF1y** [comment]
This part and then I checked the Chipped version. But even though it's obvious to me it probably won't be to anyone who doesn't have a bit more experience with SB / Chipped.
In general I would say double check versions of mods. If you have some that is a really old one and you can see multiple new versions of the mod that may be a clue to issues especially if some other mod has a compatibility with it.

```
[22Nov2024 13:47:47.942] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegisterEvent dispatch for modid sophisticatedbackpacks
java.lang.NoSuchFieldError: BOTANIST_WORKBENCH
	at net.p3pp3rf1y.sophisticatedbackpacks.compat.chipped.ChippedCompat.lambda$static$0(ChippedCompat.java:35) ~[sophisticatedbackpacks-1.20.1-3.20.17.1150.jar%23520!/:1.20.1-3.20.17.1150]
	```

**Comment by Marius-jj** [comment]
Thank you! Yeah the error didn't make much sense to me, but at least i can see the name of the mods involved, so now i know where to look when troubleshooting crashes in the future! Thanks for the help!
