### ISSUE TITLE
Backpack crashes my game

### ISSUE THREAD

**Issue by Noobsavior12** [P3pp3rF1y/SophisticatedBackpacks#1225]
When i open my backpack it crashes my game

1. Open Backpack 
2. Backpack crashes game

i have a backpack in a server with a crafting table upgrade but then when i open it it will crash sometimes

**Screenshots**
![image](https://github.com/user-attachments/assets/0f7b4b5d-16a0-4624-b734-ff4e56a3784a)

**Versions**
Forge 1.20.1
Forge version : 47.3.7
Mod version: 1.20.1-3.20.15.1143

**Comment by Noobsavior12** [comment]
[latest.log](https://github.com/user-attachments/files/17838322/latest.log)

**Comment by P3pp3rF1y** [comment]
There's no issue related to sophisticated in that log. Do you get a crash log when this happens? Sounds to me like some item is having some issues loading for some reason or some mod adds some kind of right click interaction that causes this, but I would need more info from logs or minimal set of mods and the flow with which you are able to recreate.

**Comment by P3pp3rF1y** [comment]
Anything you can share on this or should I just close?

**Comment by P3pp3rF1y** [comment]
closing given no response
