### ISSUE TITLE
Incompatible with EMI

### ISSUE THREAD

**Issue by IranMine123** [P3pp3rF1y/SophisticatedBackpacks#1226]
***DISCLAIMER: This is a duplicate of https://github.com/emilyploszaj/emi/issues/791 issue. as the developer request, the issue is reposted on here.***

**Describe the bug**
Hello. There is a bug when trying to Recipe fill by [EMI](https://github.com/emilyploszaj/emi) using Sophisticated Backpack Crafting Upgrade (`sophisticatedcore:emi_fill_recipe`).
also there is another bug reported on emi repository about Storage mod: https://github.com/emilyploszaj/emi/issues/778
log of error: https://mclo.gs/jnayaJX
video:

https://github.com/user-attachments/assets/617d1500-e0bd-41d5-b45b-0f754d73c375

**To Reproduce**
1. Open backpack
2. Open Crafting Upgrade Grid
3. Open Recipe of any item on EMI (Clicking any item on EMI menu)
4. Using "+" (Recipe Fill) button
5. World Crashes

**Expected behavior**
fill the recipe on crafting upgrade grid successfully.

**Versions**
Minecraft: 1.21.1
Sophisticated Core: 0.6.50.61
Sophisticated Backpacks: 3.20.19.51
EMI: 1.1.18

**Comment by P3pp3rF1y** [comment]
This issue is in the unofficial fabric version of the mod so you will need to log it on that tracker.
