### ISSUE TITLE
Lodestone' Screen Particles render twice in the backpack UI

### ISSUE THREAD

**Issue by SammySemicolon** [P3pp3rF1y/SophisticatedBackpacks#1229]
**Describe the bug**
As the title said, Lodestone's Item Bound' Screen Particles render twice in the backpack UI, but only in the player' inventory part of it
My best guess is that the items in the backpack's inventory portion are being rendered twice, and therefor rendering the particles twice.

**To Reproduce**
1. Open backpack
2. Observe Any item with Screen Particles associated with it, such as malum's spirits or ether
3. Notice that the items appear much brighter than usual

**Expected behavior**
The way they appear in the actual backpack is the expected behavior.

**Screenshots**
![image](https://github.com/user-attachments/assets/628aa8b9-bc66-47d8-bc62-6efb36ea514e)

**Versions**
Latest Forge 1.20

**Comment by P3pp3rF1y** [comment]
Found that I am actually unnecessarily rendering those slots twice. Just pushed a fix for that, already available on Modrinth, should be available on CF soon after approved.

**Comment by SammySemicolon** [comment]
👍 thriving
