### ISSUE TITLE
ATM9 advanced compact upgrade losing materials

### ISSUE THREAD

**Issue by JamieleeEllis2004** [P3pp3rF1y/SophisticatedBackpacks#1230]
whille playing ATM9, my netherite backpacks have repeatedly given me way less than what I should have. i was doing a quest to compact diamonds and emeralds, having 6561 of both, the correct amount, but after letting the backpack advanced compactor, i only had 700 odd returned, losing thousands of materials.

**To Reproduce**
1. Open backpack
2. have advanced compactor on and with the emerald, emerald block,emerald block x1, emerald block x2, emerald block x3 ready in allow mode
3. watch as your materials disappear

**Expected behavior**
i was expecting to see emerald block x4 in my hands, but instead i only got a single emerald block x3 (729)

**Versions**
ATM 9 - 0.3.5.  Minecraft 1.20.1
I'm also using ATLauncher

**Comment by P3pp3rF1y** [comment]
and you inserted 6561 emeralds right? That sounds correct because emerald block 3x compressed is 729 emerald **blocks** which equals 6561 emeralds

**Comment by P3pp3rF1y** [comment]
Any thoughts on this or should I just close?

**Comment by JamieleeEllis2004** [comment]
> Any thoughts on this or should I just close?

i added more than 8000 emeralds and even the autocrafters gave me less,

**Comment by P3pp3rF1y** [comment]
I don't understand what you mean with that. My question was if my math is somehow wrong? And based on that math for 8000 emeralds you would only get one 3x compressed emerald block

**Comment by JamieleeEllis2004** [comment]
> I don't understand what you mean with that. My question was if my math is somehow wrong? And based on that math for 8000 emeralds you would only get one 3x compressed emerald block

I'm an idiot sorry,
