### ISSUE TITLE
Experience pump upgrade duplicates EXP

### ISSUE THREAD

**Issue by PotatooSalad** [P3pp3rF1y/SophisticatedBackpacks#1233]
**Describe the bug**
When using experience pump upgrade options it won't take player's exp while storaging in tank upgrade.

**To Reproduce**
1. Open backpack with experience pump upgrade and tank upgrade while having some exp in player
2. Click on "Store X levels" or "Store All Experience"
3. Tank upgrade fills with EXP but EXP also stays with player

**Expected behavior**
EXP moves from player to tank upgrade and is no longer on player

**Screenshots**
Before pumping (level 21):
![2024-11-23_23 54 21](https://github.com/user-attachments/assets/2780293c-9b75-4456-9e55-324024d479ec)
After pumping (level 21 in tank and on player)
![2024-11-23_23 54 38](https://github.com/user-attachments/assets/63947e4e-e4d6-4ace-89f2-22b1a7e7ee74)

**Versions**
Tried with Sophisticated backpacks 1.21.3.20.18.1117 and 1.21.3.20.26.1151 with neoForge 21.1.73

**Comment by P3pp3rF1y** [comment]
I am unable to recreate so I guess you have another mod in the pack there that's messing with experience as well. If you can figure out the smallest modpack required to recreate I can check with that mod (those mods) if there's anything wrong that I should fix.

**Comment by PotatooSalad** [comment]
Sorry, my bad, I didn't test it with sophisticated backpacks only. 
I tested with all other mods in our pack and the problem shows up with Corail Deconstruction Table.
So, complete setup to replicate the problem:
- neoForge 21.1.73
- Corail Deconstruction Table 1.21.1-485
- Sophisticated backpacks 1.21.3.20.18.1117
- Sophisticated core 1.21-0.6.46.724

**Comment by P3pp3rF1y** [comment]
Yup, their vial item code overrides the xp I am taking from player with 0 so it ends up taking none. No idea why they're doing that and you will definitely want to report to them as I feel that code should do nothing when I am not even using that item.
