### ISSUE TITLE
Experience pump crashes the game

### ISSUE THREAD

**Issue by Alexseji** [P3pp3rF1y/SophisticatedBackpacks#1235]
A day ago, me and my friends ran into some issue with our server. I was hosting a mc world with ESSENTIALS mod. Suddendly the game of one of my friends crashed and he couldnt open his inventory anymore. I had to /kill him and because we were playing with another mod called ''corpse'' his inventory was saved in the corpse. None of us could open the corpse to get his stuff out without our games crashing. We then proceeded to make a new world to see what was wrong, and when one of my friends had the experience pump in his inventory it crashed again. 
This was the exit code: 
The game crashed whilst rendering item
Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'

Update: it only happens when you have the experience pump in your inventory or backpack and you come in contact with ex points. 

1. Have experience pump in your backpack with a experience tank
2. Come in contact with ex points
3. Open inventory or backpack
4. Then the game crashes

**Versions**
Mc version: 1.19.2
Forge version: 43.4.0
Mod version: 1.19.2-3.20.2.1035.jar

**Comment by P3pp3rF1y** [comment]
I will need a full crash log but this looks like you're using Optifine.

**Comment by Alexseji** [comment]
Nvm, the problem just solved itself. It was indeed Optifine. When I asked for his log he also went ahead and checked his mods, and he had Optifine in the folder. The other people strangely too even tho we never added this mod.

**Comment by P3pp3rF1y** [comment]
yeah in general whenever there are crashes in modded and optifine is present the first action is to remove optifine and check if the same crash still happens. They tend to break a lot of mods and don't seem to care about compatibility with modded minecraft.
