### ISSUE TITLE
JEI Send to crafting causes Crash

### ISSUE THREAD

**Issue by Mentaleak** [P3pp3rF1y/SophisticatedBackpacks#1236]
**Describe the bug**
When adding a recipe to the crafting grid via JEI the game Crashes.
The game crashed whilst mousereleased event handler
Error: java.lang.NoSuchMethodError: 'int mezz.jei.common.transfer.TransferOperation.craftingSlotId()'
[crash-2024-12-03_19.14.20-client.txt](https://github.com/user-attachments/files/18000866/crash-2024-12-03_19.14.20-client.txt)

**To Reproduce**
1. Open backpack
2. Click Crafting Grid Upgrade
3. Find a recipe to craft in JEI that you have the resources for
4. Click the "+" Icon to add recipe to grid
5. Game Crashes

**Expected behavior**
The recipe enters the crafting grid as it does in minecraft crafting table and other crafting grid mods.

**Screenshots**

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
Minecraft 1.19.2
Forge 43.3.13
sophisticatedbackpacks-1.19.2-3.20.2.1035
sophisticatedcore-1.19.2-06.4.730
JEI-1.19.2-forge-11.6.0.1019

**Comment by P3pp3rF1y** [comment]
You need to update JEI to one of the latest versions - 11.7.+
