### ISSUE TITLE
Crashing when opening a dropped backpack

### ISSUE THREAD

**Issue by cr4pshooter** [P3pp3rF1y/SophisticatedBackpacks#1238]
**Describe the bug**
The game crashes when I attempt to open the backpack dropped from a few different pillager @ my pillager spawner
[crash-2024-12-06_08.59.19-server.txt](https://github.com/user-attachments/files/18039822/crash-2024-12-06_08.59.19-server.txt)

**To Reproduce**
1. Kill Pillager
2. Pick up backpack
3. Open backpack
4. Game crash

**Expected behavior**
I expected to open the bag to some random loot and maybe the record that was playing

**Versions**
Forge 47.3.12 1.20.1

**Comment by P3pp3rF1y** [comment]
That happens because you have an ancient version of sophisticated backpacks in your modpack with almost the latest sophisticatedcore. Just update at least SB to the latest (but core also has 2 additional versions after the one you have there) and you're good.

**Comment by cr4pshooter** [comment]
Huh, I downloaded them the same day so I must have grabbed an old version.  Thanks
