### ISSUE TITLE
Anvil Upgrade can't use Formatting Codes

### ISSUE THREAD

**Issue by MoltonMontro** [P3pp3rF1y/SophisticatedBackpacks#1239]
**Describe the bug**
Unlike vanilla Anvils, the **Anvil Upgrade** can't accept certain Unicode characters, such as `§`, which is used for Minecraft's formatting codes (e.g., colored text).

**To Reproduce**
1. Open backpack
2. Add an Anvil Upgrade
3. Open the Anvil Upgrade's interface
4. Try to rename item with a formatting code included, such as `§dObsidian Furnace`.

**Expected behavior**
§ would be usable in the Anvil Upgrade interface, and display the formatting code's effect(s) on the text, just like a vanilla anvil.

**Screenshots**
What I'd expect to see:
![image](https://github.com/user-attachments/assets/dfdea2c9-d3e8-4daa-8248-049f59d3d5fc)

**Versions**
Mod version - 3.20.11.1115

**Comment by P3pp3rF1y** [comment]
How are you entering that character into Anvil? I can't use it there (tried copy pasting and it only pastes the "d" but not the formatting character) which makes me think it's some mod allowing that.

**Comment by MoltonMontro** [comment]
🤦 I'm silly – yeah. Anvils can do this on **_Bedrock_** without a mod. On JE, I'm able to do this because the modpack has Easy Anvils included. (Copy-pasting the text.)

Feel free to close if out-of-scope. :) I still believe it'd be nice to support, though at this point it's a feature request and not a bug report, ig!

**Comment by P3pp3rF1y** [comment]
I will take a quick look at this and may add if super easy

**Comment by P3pp3rF1y** [comment]
So I took a look at this and the implementation is actually very involved where I don't see a good reason to add it to the mod - this would be used pretty rarely and player's can use vanilla anvil with Easy Anvil mod in those cases.
