### ISSUE TITLE
Crash when opening backpack when Crafting Upgrade slot is open

### ISSUE THREAD

**Issue by pietro-lopes** [P3pp3rF1y/SophisticatedBackpacks#1242]
*IGNORE ALL THIS, READ OTHER POST HOW TO ACCURATELY REPRODUCE*
---
I have no idea what exactly triggers it (I know that you need, at least, that tab open), just have a video here until it bugs:

https://github.com/user-attachments/assets/4bffd1d8-2a59-42f4-a116-552b233ba11f

**To Reproduce**
ATM10 2.8 Modpack: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/6009022
World with bugged backpack: [Soph Backpacks.zip](https://github.com/user-attachments/files/18220592/Soph.Backpacks.zip)
1. Open backpack with right click
2. Crash

If you want to workaround this crash, before opening the bugged backpack, grab any empty backpack, open, now you can open the other.

**Versions**
Backpack: 3.20.27.1154
Core: 1.0.2.810

**Comment by pietro-lopes** [comment]
Updating, just managed to reproduce with only backpack mods and crafting tweaks, just do this:

grab a backpack
grab a crafting upgrade
add the upgrade to backpack
open the right side tab, left it open
leave world and:
**CLOSE MINECRAFT, YOU NEED TO CLOSE THE GAME**

Now join again and do the following steps:

https://github.com/user-attachments/assets/4346eeb1-ad71-4104-9c7d-497df673ea09

Open Inv
Shift to preview
Click to open
It will crash

**Comment by P3pp3rF1y** [comment]
Thanks for the detailed report. I have just released a new version of core that has the fix for this.
