### ISSUE TITLE
Feeding Upgrade

### ISSUE THREAD

**Issue by Blzd87** [P3pp3rF1y/SophisticatedBackpacks#1246]
Describe the bug
When the Feeding Upgrade in the Sophisticated Backpacks mod auto-feeds the player, if the player’s hotbar is highlighting a tool or weapon, the mod does not auto-feed. Instead, it duplicates the item currently in the player’s hand.

To Reproduce

Equip a backpack with the Feeding Upgrade installed.
Ensure there is food in the backpack.
Hold a tool or weapon in the hotbar and highlight it.
Let the Feeding Upgrade try to auto-feed the player (e.g., take damage or sprint until hunger drops).
Observe the duplication of the item instead of the auto-feeding.
Expected behavior
The Feeding Upgrade should auto-feed the player regardless of what is highlighted in the hotbar, without duplicating the item in hand.

Screenshots
If possible, add screenshots or a video showing the item duplication.

Versions

Mod version: 1.20.1-3.20.17.1.60
Forge version: (insert version here)
Minecraft version: 1.20.1
Additional context
No other mods seem to conflict with this feature, or list mods if applicable:

(list of installed mods)

**Comment by P3pp3rF1y** [comment]
Are you testing this with just SB in the modpack or you have other mods in there? Specifically have you got Inventorio mod as that is known to cause duplication issues.

**Comment by Blzd87** [comment]
https://img.blzd.dev/KVW5pf.png

Nope just these ones.

I also have Sophisticated Storage

**Comment by P3pp3rF1y** [comment]
At least 2 of those appear to be fabric mods. How are you playing with them when this is a forge mod?

**Comment by P3pp3rF1y** [comment]
Also just noticed that mod version. Are you sure that's the one you have? I have never released any version like that

**Comment by Blzd87** [comment]
https://img.blzd.dev/l9aVff.png

Im assuming its an issue with these being ports?

**Comment by P3pp3rF1y** [comment]
well in that case you need to report the issue to the unofficial fabric port issue tracker. This one is only for forge / neoforge

**Comment by P3pp3rF1y** [comment]
closing given that this is unofficial fabric version issue
