### ISSUE TITLE
restock upgrade not working with lootr

### ISSUE THREAD

**Issue by Dutchplayer** [P3pp3rF1y/SophisticatedBackpacks#1247]
**Describe the bug**
im currently playing allthemods 10 (V 2.13) and when i shift right click with the backpack in my hand or on my back (with advanced restock upgrade) it doesnt take the contents from lootr chests, i tried it with vanilla chests and sophistacted storage barrels and it works as intended there.

**To Reproduce**
1. shift right click on a lootr chest with a backpack with the restock upgrade
2. nothing happens

**Expected behavior**
the loot should go into the backpack

**Versions**
allthemods 10 V2.13
neoforge 21.1.91
sophisticated backpacks 1.21.1 - 3.20.29.1156

**Comment by P3pp3rF1y** [comment]
That is pretty intentional from Lootr side - you actually have to use the gui to transfer the items, there's no pipe or similar kind of support there hence restock won't work.
