### ISSUE TITLE
Crafting Tweaks Rotation Button doesn't update item to be crafted

### ISSUE THREAD

**Issue by telemenar** [P3pp3rF1y/SophisticatedBackpacks#125]
**Describe the bug**
Crafting Tweaks Rotation Button doesn't update item to be crafted

**To Reproduce**
1. Open backpack w/Crafting Upgrade
2. Click on Crafting Tab
3. Add two stacks of planks side by side -- see pressure plate recipe 
4. Click rotate button until they are vertical -- still see pressure plate recipe
5. Craft them -- receive sticks.

**Expected behavior**
Should see crafting result.

**Versions**
sophisticatedbackpacks-1.16.4-2.4.0.251.jar
CraftingTweaks_1.16.3-12.2.0.jar

**Comment by P3pp3rF1y** [comment]
I have this fixed in dev, it also fixes any other crafting tweaks action that can change the resulting recipe like spread grid, transfer into grid

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF
