### ISSUE TITLE
Placing lava buckets as acceptable fuel types into the Auto-smelting window crashes the game

### ISSUE THREAD

**Issue by StygianEmperor** [P3pp3rF1y/SophisticatedBackpacks#13]
**Version**
forge-1.16.4-35.1.13
sophisticatedbackpacks-1.16.4-0.11.1.88

**Steps to reproduce**
Place a bucket of lava into the bottom row of empty spaces in the auto-smelting window.

**Comment by P3pp3rF1y** [comment]
Just tried that and works without any issue. Can you share the crash log?

**Comment by StygianEmperor** [comment]
Sure:
[crash-2020-12-17_14.43.41-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/5718848/crash-2020-12-17_14.43.41-client.txt)
Looks like it may be some issue with Immersive Engineering.

**Comment by P3pp3rF1y** [comment]
Looks like IE may have been calling something that's not initialized clientside there. but they have completely removed that code 4 days ago so solution for you is use a new version of IE.
