### ISSUE TITLE
First tier backpack crashing when shift + right clicking with unstackabble items

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedBackpacks#136]
When shift + right clicking on the first tier backapack with some items the client crashes. The crash happens both on singleplayer and multiplayer. Not sure if other players would be affected, as the server continued running.

It's only happening on the first tier backpack. I tested on all other tiers with only an iron chestplate and acacia boat, acting normally. Manually dragging the item on the backpack inventory acts normally.

I have changed the config slots to the following settings:
1 tier: 18 slots
iron tier: 27 slots
gold tier: 36 slots;
diamond tier: 45 slots;
netherite tier: 54 slots.

1. Open first tier backpack with changed config (I didn't tested on with the default slot config);
2. Shift + right click with "acacia boat", "elytra" or "iron_chestplate" (pretty sure all unstackable items would crash);
3. The game crashes,

Expected behavior:
The item shold go to the backpack inventory or stay in players inventory if backpack has no empty slots.

Versions
Forge 36.1.0. The crash happened both on 2.4.0.259 and in 2.2.8.240. I didn't check on other versions.

Crash report:
[crash-2021-05-01_14.16.09-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6410017/crash-2021-05-01_14.16.09-client.txt)

**Comment by P3pp3rF1y** [comment]
this actually looks to be related to the fact that your first level backpack must have 0 upgrade slots, right? I can see it going through the part of code there which would cause this crash if there were 0 upgrade slots.

**Comment by ghost** [comment]
yes, I forgot to mention that I also changed the upgrade slots to be:

tier 1: 0 upgrade slots;
iron: 1 slot;
gold: 2 slots;
diamond: 3 slots;
netherite: 4 slots.

**Comment by someaddons** [comment]
think got the same issue, also have 0 upgrade slots on the lowest tier: https://gist.github.com/someaddons/ddd6976bdaaf2b14f4b2c880ec2b6f6d
