### ISSUE TITLE
Minecraft Crashes when you try to sleep while wearing the backpack.

### ISSUE THREAD

**Issue by Toximisity** [P3pp3rF1y/SophisticatedBackpacks#137]
Just as it says, i'm using a gold backpack and when i attempt to sleep, the game crashes.

**Comment by P3pp3rF1y** [comment]
well, there's nothing I can do about this without any crash log. Just tried sleeping with backpack on and it just works.

**Comment by P3pp3rF1y** [comment]
@Toximisity will you be able to provide crash log here?

**Comment by Toximisity** [comment]
Sorry for the late response, totally slipped my mind. So a little update, i recently lost my backpack for some random odd reason, not sure what it was so i never got around to testing it in my survival world again. Providing the crashlog from one of the times it crashed. Basically all that was happening is whenever i would attempt to sleep i would crash in the middle of the falling animation to the bed, and would appear MUCH higher above the bed when the crash happened. As an added side note, this was played in 1.16.5 on the modpack Modlife 4 through the curseforge launcher. [https://pastebin.com/vnE49dcz](url)

**Comment by Toximisity** [comment]
Also, if the tier of backpack changes at all it was the Gold tier backpack, that much was for sure.

**Comment by P3pp3rF1y** [comment]
This is a problem in modular powersuits mod - seems like a simple mistake where it by mistake treats whatever item handler is in chest slot as imodularitem and it looks just like missing brackets.

https://github.com/lehjr/MachineMusePowersuits/blob/1.16.5/src/main/java/com/github/lehjr/powersuits/client/event/RenderEventHandler.java#L109-L110

You will need to report this to them.
