### ISSUE TITLE
Pickup and Magnet upgrades & the Comforts mod's sleeping bags

### ISSUE THREAD

**Issue by StygianEmperor** [P3pp3rF1y/SophisticatedBackpacks#14]
Not a high priority, but the Comforts mod's sleeping bags are significantly less convenient when I can't tell my backpack not to suck them up automatically when they "break" themselves back into an item.

**Version**
forge-1.16.4-35.1.13
sophisticatedbackpacks-1.16.4-0.11.1.88
comforts-forge-1.16.4-4.0.0.2.jar

**Description**
The Comforts mod's sleeping bags are designed to "break" back into an item as soon as you're done sleeping on them, but the backpack's Pickup and Magnet upgrades' filters don't seem to care if you put a sleeping bag into their filter grid in block mode (in my case with match tags on).

**Steps to reproduce**
Equip Pickup or Magnet upgrade to backpack
Set its filter to block your sleeping bag and match tags
Use your sleeping bag to pass the night

**Comment by P3pp3rF1y** [comment]
Based on what I can see they don't have any tags so blocking no tags will block nothing here. You will need to filter by the item itself.

**Comment by StygianEmperor** [comment]
Oddly this bug seems to have fixed itself after I posted it, which is weird because it's happened for like a week now. So I concur that the issue should be closed, I guess!
