### ISSUE TITLE
Splitting Stacks splits as if 64

### ISSUE THREAD

**Issue by judicius** [P3pp3rF1y/SophisticatedBackpacks#141]
**Describe the bug**
When right clicking to split a stack of items from the backpack, the split amount is always 32 as opposed to half the stack.

**To Reproduce**
1. Add stack upgrade
2. Create a stack of items 128 or more
3. Right Click to split the stack
4. See error, stack that splits is always 32

**Expected behavior**
Stack splits in half.

**Versions**
MC 1.16.5
Forge 36.1.16
SoBags 2.4.0.259

**Comment by P3pp3rF1y** [comment]
that as far as I can see in other mods is the usual behavior and I like it as well. anyway if the stack size is over 128 you can't get more than a stack of 64 and at that point again the stack wouldn't be splitting in half. And then left and right click would do the exact same thing. So this is not going to change.
