### ISSUE TITLE
Crash when using mouse tweaks shift-drag

### ISSUE THREAD

**Issue by Talyda** [P3pp3rF1y/SophisticatedBackpacks#143]
Getting a crash when I use the shift-drag (and shift-click) feature of mouse tweaks to put stuff in leather sophisticated backpack

**To Reproduce**
Press "B" to open backpack and inventory
shift-drag mouse along inventory to get it all to just pop into backpack
Crash

**Expected behavior**
No crashy

**Versions**
Using 
sophisticatedbackpacks-1.16.4-2.4.0.259.jar 
MouseTweaks-2.14-mc1.16.2.jar  
forge 36.1.4

Crash log here:
https://gist.github.com/Talyda/a361b9880bcdc130731b8f8775c4da10

Latest.log here:
https://gist.github.com/Talyda/53f19aa822c08b01ce4a593741f9720f

Am also going to copy paste this to mousetweaks issues and put link to it here:
https://github.com/YaLTeR/MouseTweaks/issues/52

*edits* it's not happening with every item - I was able to put random things - string, wheat, paper, a lead, a slime sapling from tinkers - but then it crashed on a saddle, and iron armour

Tested again with the saddle, and normal picking it up and dragging the saddle to the backpack was fine - shift clicking it into there was fine

**Comment by Talyda** [comment]
Have only just realised this is probably the same issue as 
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/136
so feel free to close this - sorry!

**Comment by P3pp3rF1y** [comment]
yes this looks like the exact same issue. so I am closing
