### ISSUE TITLE
Infinity storage

### ISSUE THREAD

**Issue by IDEDARY** [P3pp3rF1y/SophisticatedBackpacks#144]
You can stack backpacks to infinity by placing storage in storage.
It is in-game that you cannot place a backpack in a backpack, but you can place a backpack in a shulker box and a shulker box in a backpack.

backpack < shulker < backpack < shulker  == Infinity storage.

**Comment by P3pp3rF1y** [comment]
yes you can but there are so many things that can potentially store backpacks that I can't just easily ban this. what I can provide however is a configurable list of names of items that are not supposed to go into backpack. I would still however not include shulkers as just putting shulkers with other items in a backpack sounds good to me. 

So I will keep this open and close once I have added configuration option to ban items from going into backpack

**Comment by Darkmega18** [comment]
_you can always just let them rage a bit when they try to go to infinite and then they end up overflowing the data of their recursive backpack and losing it all. :V_

**Comment by P3pp3rF1y** [comment]
a while ago I added a config option to ban specific items from going into backpack and later on also setting for whether container items can go into backpacks in general so this was solved back then
