### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Plix929** [P3pp3rF1y/SophisticatedBackpacks#150]
I created a modpack for me and my friends but we constantly crash after ~5 minutes of playing , 
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6522816/latest.log)
[VladPack5-1.16.5..zip](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6522818/VladPack5-1.16.5.zip)

**Comment by Phrankieboy** [comment]
Are you playing on a LAN game?

See #151 for some more detailed information.

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
