### ISSUE TITLE
Mobs spawning with backpacks crashes LAN game when trying to play music

### ISSUE THREAD

**Issue by Phrankieboy** [P3pp3rF1y/SophisticatedBackpacks#151]
Tested on 1.16.4-2.4.0.259:

Modpack is Stacia Expert v1.10.6  (manually updated the mod to v259, was crashing with the previous version as well)

Crash log:  https://pastebin.com/3pfLwCkn

When playing a LAN multiplayer game, the mod causes a crash when a mob spawned with a backpack tries to play music.

This crash does not happen in single player mode, but when someone else is connected to the LAN game, it crashes regularly.

To reproduce, use default config settings (chance of mob spawning with backpack) and the music playing TRUE.

Eventually the game will freeze and have to be closed manually, the crash report above is generated.

To test, I set the music playing option for mob backpacks to FALSE, and also set the chance of mobs spawning with backpacks to zero.

This looks like the same issue reported in #150

**Comment by P3pp3rF1y** [comment]
This looks like some mod changing how MC processes packets basically allowing them to be processed at the same time that other logic runs, I guess I will have to make the code there ready for it even though it's not really directly SBP issue.
