### ISSUE TITLE
[1.16.5] BUG: Advanced Tool Swapper Upgrade Don't swap weapon doesn't work

### ISSUE THREAD

**Issue by Zothen1973** [P3pp3rF1y/SophisticatedBackpacks#155]
Tested with a netherite backpack and an advanced tool swapper upgrade.

No matter if I enable or disable "Swap Weapon" in the "Tool Swap" tab, my diamond sword is swapped with a tool whenever I hit a block with it.

**To Reproduce**
1. Open netherite backpack
2. Insert an advanced tool swapper upgrade.
3. Put a pick, axe, hoe and shovel in the "Tool Swap" tab and then in the backpack.
4. Disable "Weapon Swap" in the "Tool Swap" window.
5. Put a diamond sword in your main hand.
6. Hit any block with your sword, while having a pick, axe, hoe and shovel in the backpack.

**Expected behavior**
I expect the option "Don't swap weapon" to keep the sword in the main hand without swapping with any tools I have in the backpack.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/77007295/119631795-82e91680-be10-11eb-9f5a-f0c40b0d03e7.png)

**Versions**
sophisticatedbackpacks-1.16.4-2.4.0.259
Forge 36.1.23

**Comment by P3pp3rF1y** [comment]
Don't swap weapon means that it won't try to swap the weapon when you're fighting with it. However it will still swap it for tool when you start to dig with it

**Comment by Zothen1973** [comment]
Hmm, then I don't get that toggle option. Of course no one wants a sword to be swapped with a tool when fighting. Another setting simply doesn't make sense. Apart from that, swapping still occured in a fight when I tried to hit the mob but missed.

Is there a setting to prevent a sword or spartan weapon to be swapped completely? 

An additional button for specifying a "swap slot" in the hotbar would be nice, so all other hotbar slots are unaffected by swapping.

**Comment by P3pp3rF1y** [comment]
I can also make it so that when you turn off weapon swapping it will not try to tool for anything that it considers a weapon, though how you figure out that something is a weapon is going to be a harder thing. regular swords are not an issue, but something like one of the weapons from tinkers may not that easily follow some general filter for weapons. But I agree that when you miss during fight it shouldn't swap the weapon for tool

**Comment by Zothen1973** [comment]
If I may suggest a solution: why not use the "weapon" slot in the "swap tab", so when "weapon swap" is disabled, the weapon put in that slot never is swapped for a tool.

**Comment by P3pp3rF1y** [comment]
yes that sounds reasonable, would just somehow need to be communicated to player that is the case, probably more info needed on don't swap weapon button tooltip

**Comment by P3pp3rF1y** [comment]
In the latest release there's a new option that allows setting tools to only swap for other tools and not weapons which should fix the issue described here
