### ISSUE TITLE
Inventories of Backpack deleted

### ISSUE THREAD

**Issue by CloWnicide** [P3pp3rF1y/SophisticatedBackpacks#156]
Running version 1.16.4-2.4.0.259 on Forge: 36.1.18 and I've run into this issue on multiple different versions of both the mod and Forge, but certain backpacks completely lose their inventories and upgrades randomly. It's happened in singleplayer and on my server, so not exactly sure why it does it.

Edit: This happens after restarting the client/disconnecting from the server

**Comment by P3pp3rF1y** [comment]
How were the backpacks created? Were all of them crafted? This sounds like the case of duplicate uuid. Can you check what uuid those backpacks have? (F3 + H to show in tooltip)

**Comment by CloWnicide** [comment]
I don't have the world on my server anymore after trimming un-needed mods from it. But all of the backpacks were crafted 1 at a time.. If it happens again I'll make note of it, as it seems to happen to me a lot.

**Comment by CloWnicide** [comment]
![2021-06-02_08 00 49](https://user-images.githubusercontent.com/27911500/120504132-bd0a6900-c378-11eb-82ab-d75f0ad9125a.png)

**Comment by CloWnicide** [comment]
Happened again. all my items from this backpack are now gone after a restart.

**Comment by P3pp3rF1y** [comment]
are you playing on a server or have you got another backpack? and actually can you check UUID of the backpack on your backpack against this one that you're looking at. This all seems to point to the fact there's another backpack with the same uuid and changes to it get propagated to yours because of that.

**Comment by CloWnicide** [comment]
Here's all the backpacks I have, and this has happened while playing singleplayer and on a server.

![2021-06-02_19 42 04](https://user-images.githubusercontent.com/27911500/120578451-af85cb00-c3da-11eb-8c8d-018ce67fd7d9.png)
![2021-06-02_19 42 10](https://user-images.githubusercontent.com/27911500/120578460-b280bb80-c3da-11eb-9e98-4fe50f2fe8b8.png)
![2021-06-02_19 42 12](https://user-images.githubusercontent.com/27911500/120578464-b44a7f00-c3da-11eb-98dc-c848a2820998.png)
![2021-06-02_19 42 14](https://user-images.githubusercontent.com/27911500/120578470-b6144280-c3da-11eb-8fc5-3d827805d6d6.png)

**Comment by CloWnicide** [comment]
And now the backpack marked as Tools has a different UUID

![2021-06-02_19 44 24](https://user-images.githubusercontent.com/27911500/120578606-f378d000-c3da-11eb-8ff2-64f90141316f.png)

**Comment by P3pp3rF1y** [comment]
the only way that new UUID could get assigned is if the backpack somehow lost its UUID assignment. And in SBP the only thing that can actually remove uuid is logic that removes it when mob wearing backpack dies or despawns and the backpack doesn't get dropped. And there's no way this logic could be run for player backpacks.
So that looks like some mod is deleting nbt data. At this point I don't see any way I can help you here. 
But I have just released new version which has fix for one issue where uuid was unnecessarily getting assigned clientside. I don't see how that could cause your issue, but it doesn't hurt to try to play with that version and see if this goes away.

I will leave this open for a bit, but if I don't see that this is happening with new version and steps to recreate I will close.

**Comment by CloWnicide** [comment]
Just got around to updating since Multicraft panels were down for the last 36 hours or so, will update with the results in a few hours, probably after 2 restarts.

**Comment by CloWnicide** [comment]
Waiting for my 2nd restart, which is in 2 hours of writing this, but the inventory of a backpack has deleted on the newest version of the mod. I'm not sure if this is related, but I know Random Patches tries to re-register UUIDs of things, maybe its causing this?

**Comment by P3pp3rF1y** [comment]
looked into random patches but those things that it does with UUID seem unrelated. btw one more thing that can happen is that during the saving of the world there's an issue like disk running out of space and then it's not able to save the backpack data. Are you sure that nothing like that happened for you?

**Comment by P3pp3rF1y** [comment]
Though thinking about that case that would only cause the backpacks to become empty but the uuid of the backpack would stay the same. 

Could you try one more thing? Try command `/sbp list` (you can also provide player name as parameter to limit to specific player). Can you see your tools backpack there with the previous UUID? and if so try giving it to yourself (click on its name to get the command) and check if it has its contents

**Comment by CloWnicide** [comment]
It has the exact same contents as the one I have in my bagpack
![2021-06-07_03 17 25](https://user-images.githubusercontent.com/27911500/121000296-e6dbdb00-c73e-11eb-91db-2f981ae1f3ac.png)
![2021-06-07_03 17 28](https://user-images.githubusercontent.com/27911500/121000309-e9d6cb80-c73e-11eb-90d4-04b8ef5df772.png)

**Comment by CloWnicide** [comment]
Also it seems every other bag I craft has this issue. My cyan colored one on the top there next to the green one is the one that bugged out, and I just crafted it the last restart, but if I were to make another bag, it'd be fine. That's what I did to the Tools bag, which is why 1 is named broken pack.

Edit: After updating the mod, the broken pack wasn't deleting my inventories.

**Comment by P3pp3rF1y** [comment]
So is the issue solved now for you? Honestly I am not sure how else to help you here and to be able to do anything I would need to get a minimal set of mods with which this issue happens and preferably reproduction steps as I myself don't know what could be causing this and you seem to be the only one having this issue despite thousands of people playing with the mod.

**Comment by CloWnicide** [comment]
This is the modpack I made and am currently using: https://www.curseforge.com/minecraft/modpacks/the-f-it-bucket

As far as the issue, I hadn't logged back onto my server since my post last night, although I believe it to still be there.

**Comment by P3pp3rF1y** [comment]
As I said I would need a minimal set of mods with which it happens. I can't go through 400+ mods trying to figure out which one is causing it and then trying to figure out what is causing it. That way I wouldn't be able to create / enhance this mod and would just spend my time debugging all kinds of modpacks.

**Comment by CloWnicide** [comment]
I mean I can try to see what I can do about the mod load, but this also happened on ATM6 modpack.

**Comment by P3pp3rF1y** [comment]
Well ATM6 doesn't have sophisticated backpacks so they must have been added. was the only mod added? and still that modpack is 250 or so mods which doesn't help as well as multiple people who reported some other stuff or suggested new things said that they play ATM6 with SBP and I haven't seen any complaint about deleted backpack contents. 
And again as far as I can see there's no code line in sbp that can actually do what's happening to you that is uuid being deleted and only gets generated if it's missing or possibly is malformed so we're definitely looking for some other mod that is not behaving properly.

**Comment by P3pp3rF1y** [comment]
Since I haven't got any additional info to help recreate and haven't heard from anyone else about similar issue I am going to close

**Comment by Exevan** [comment]
This issue still occurs on ATM 7, sorting my inventory has deleted about half of the contents of my backpack.
I encountered this bug shortly after upgrading from version 0.2.38 to 0.2.40b of the modpack, hopefully this helps narrow down the list of other mods that might cause this.

**Comment by P3pp3rF1y** [comment]
> This issue still occurs on ATM 7, sorting my inventory has deleted about half of the contents of my backpack.
> 
> I encountered this bug shortly after upgrading from version 0.2.38 to 0.2.40b of the modpack, hopefully this helps narrow down the list of other mods that might cause this. 

This is really old issue if there's something happening for you please log new one with exact steps on how to recreate or at least better description of the actual issue

**Comment by evsey9** [comment]
This just happened to me too. Pressed "sort inventory" twice in a rapid succession and half of the items just... poof, gone.

**Comment by evsey9** [comment]
It seems like for whatever reason, it just... doesn't touch the bottom part of the  backpack?
I tried it just now, and what happened was - it moved the items from the bottom half of the backpack into the top half, due to sorting... but it also just didn't move the bottom half. So, it duplicated some items.
At the same time it is an item loss bug, and a dupe bug. You could probably reproduce this by taking a large backpack, full of different items (think Diamond upgrade level or so) and trying to sort.

**Comment by P3pp3rF1y** [comment]
> 

there's no sense in commenting on an ancient closed issue and one that is very likely different than what you experience. So please create a new issue for yours and add related information like what version, how exactly you're sorting your inventory (clicking on the button vs using keybind) and potentially a screenshot of the backpack's gui

**Comment by evsey9** [comment]
> > 
> 
> there's no sense in commenting on an ancient closed issue and one that is very likely different than what you experience. So please create a new issue for yours and add related information like what version, how exactly you're sorting your inventory (clicking on the button vs using keybind) and potentially a screenshot of the backpack's gui

I'll make sure to create an issue when I can replicate it with a recording. (I tried to replicate it for a fat while yesterday while recording but couldn't :< )

**Comment by LimeShep** [comment]
> looked into random patches but those things that it does with UUID seem unrelated. btw one more thing that can happen is that during the saving of the world there's an issue like disk running out of space and then it's not able to save the backpack data. Are you sure that nothing like that happened for you?

i've had that kind of issue and everything is gone...
