### ISSUE TITLE
"Linked" Bags causing item duplication and item deletion

### ISSUE THREAD

**Issue by Neohedron512** [P3pp3rF1y/SophisticatedBackpacks#159]
**Describe the bug**
At least two backpacks became "linked," causing additions to one pack appearing in another, effectively duplicating the item. Occurs when adding items to one via the backpack item interaction, not placing the pack. However, if you add items to a backpack without placing it, then add or remove items from the other linked bag, then place down the first bag, the most recent additions (since you last placed down the bag) will be deleted.

**To Reproduce**
1. Create two backpacks without leaving the crafting gui
2. add items to one using it's item form, do not place down either pack
3. open the other bag, and the items you added to one have been duplicated. Every item you add appears in the other bag.

Possibly caused by duplicate UUID's? We destroyed the backpacks and got Traveler's Backpack after it deleted an entire dungeon of loot, so can't check to see if they did.

**Versions**
Forge-36.1.0
sophisticatedbackpacks-1.16.4-2.4.0.259

**Comment by P3pp3rF1y** [comment]
this is likely related to some mod propagating uuid from client to server in recipes. I have a fix for a bug that was creating uuid client side. I wasn't able to create the duplication of UUID even with that bug in two big packs I played recently (Enigmatica 6 and  Seaopolis) but the fact that it wasn't happening before this client side bug and is happening now tells me some mod out there is somehow propagating this UUID in custom packs. So once next release is out I am going to close this.

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
