### ISSUE TITLE
Creative Tab Missing Localization

### ISSUE THREAD

**Issue by WenXin20** [P3pp3rF1y/SophisticatedBackpacks#16]
`Minecraft v1.16.4`
`Sophisticated Backpacks v1.0.0.9`

![2020-12-18_22 15 09](https://user-images.githubusercontent.com/12000593/102680530-a8496880-417e-11eb-9665-4e8b0a2f687e.png)

**Comment by P3pp3rF1y** [comment]
just released version with fix
