### ISSUE TITLE
Game crashes when I open a backpack

### ISSUE THREAD

**Issue by Dragon-Fire813** [P3pp3rF1y/SophisticatedBackpacks#161]
Occasionally when I open a backpack in the curio slot or in the hotbar the game crashes. Something to do with a "Problematic frame," whatever that means. It's not consistent on when it happens, sometimes it happens after I just loaded in, other times I could be playing for hours before it happens. It has also crashed after just closing and then reopening it. I currently have four different backpacks (some dyed, some upgraded, some bigger,) and It's happened with all of them. It happens most often after placing or interacting with tech blocks like Mekinsim machines or Create's mechanical components.

It might have something to do with the most recent version of java. I updated it a few weeks ago. I tried to revert back, but I couldn't.

It's not a standard crash log, but it's the log I get when the game crashes.
[hs_err_pid10980.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6573011/hs_err_pid10980.log)

Currently playing a modified Egnimatica 6 mod pack (updated a few of the mods, added some of my own)

Currently using this version of the mod: sophisticatedbackpacks-1.16.4-2.2.4.192

**Comment by P3pp3rF1y** [comment]
and one of the added mods seems to be immersive railroading. they are doing some funky business with item rendering which crashes with one of the items in your backpack. so you will need to report this to them

**Comment by Dragon-Fire813** [comment]
It might be one of the rolling stock resource packs added or the fact that all of the rolling stock is fully rendered with their 3D models even in the inventory. I'll check the configs to see if the setting that makes them 2D images is still there to see if that helps.
