### ISSUE TITLE
Backpack not appearing or shows up on top of head (I'd appreciate the help)

### ISSUE THREAD

**Issue by DailyIntruder** [P3pp3rF1y/SophisticatedBackpacks#165]
I was crafting the Sophisticated Backpack and I noticed that it wasn't showing up and when I put it in another slot trying different things it would appear on my head which was odd, I've been using this mod for a long time back in the day before it looked this nice but its always been a good mod but, I deleted and restarted all my mods and now its not working. I have 1.16.5-forge-36.1.24 Minecraft version and as for the mod version I have the 1.16.5 2.5 version. 

here is a list of all the mods I have installed: 
Dannys Expansion -https://www.curseforge.com/minecraft/mc-mods/beta-dannys-expansion
AdHooks -https://www.curseforge.com/minecraft/mc-mods/advanced-hook-launchers
antiquestlas -https://www.curseforge.com/minecraft/mc-mods/antique-atlas
Areas -https://www.curseforge.com/minecraft/mc-mods/areas
BackTools -https://www.curseforge.com/minecraft/mc-mods/back-tools (Back Tools seems to not show up as well)
BetterCaves -https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves
Builders Dimension -https://www.curseforge.com/minecraft/mc-mods/builders-dimension
Cameraoverhaul -https://www.curseforge.com/minecraft/mc-mods/camera-overhaul-forge
Citadel -https://www.curseforge.com/minecraft/mc-mods/citadel
ColdsClaws -https://www.curseforge.com/minecraft/mc-mods/colds-claws-forge
Collective -https://www.curseforge.com/minecraft/mc-mods/collective
Comforts -https://www.curseforge.com/minecraft/mc-mods/comforts
Connectiblechains -https://www.curseforge.com/minecraft/mc-mods/connectible-chains-forge
Controllable -https://www.curseforge.com/minecraft/mc-mods/controllable
Corpse -https://www.curseforge.com/minecraft/mc-mods/corpse
CosmeticArmorReworked -https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked
Coyotelib -https://www.curseforge.com/minecraft/mc-mods/coyotelib
CreativeCore -https://www.curseforge.com/minecraft/mc-mods/creativecore
Curious API -https://www.curseforge.com/minecraft/mc-mods/curios
Customizableelytra -https://www.curseforge.com/minecraft/mc-mods/customizable-elytra
CyclopsCore -https://www.curseforge.com/minecraft/mc-mods/cyclops-core
DeadGuysUntitledDeepDark -https://www.curseforge.com/minecraft/mc-mods/dead-guys-untitled-deep-dark
Desolation -https://www.curseforge.com/minecraft/mc-mods/desolation-forge
DoggyTalents -https://www.curseforge.com/minecraft/mc-mods/doggy-talents
Dungeonsarise -https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise
Eidolon -https://www.curseforge.com/minecraft/mc-mods/eidolon
EnhancedVisuals -https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals
EpicFightMod -https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod
EverlastingAbilities -https://www.curseforge.com/minecraft/mc-mods/everlastingabilities
Fallingleaves -https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge
FallingTree -https://www.curseforge.com/minecraft/mc-mods/falling-tree
ForgeEndertech -https://www.curseforge.com/minecraft/mc-mods/forgeendertech
Geode -https://www.curseforge.com/minecraft/mc-mods/geode
Healingcampfire -https://www.curseforge.com/minecraft/mc-mods/healing-campfire
iceandfire -https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons
IChunUtil -https://www.curseforge.com/minecraft/mc-mods/ichunutil
immersiveportals -https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod
InventoryHud -https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge
ironchest -https://www.curseforge.com/minecraft/mc-mods/iron-chests
jei -https://www.curseforge.com/minecraft/mc-mods/jei
KimetsunoYaiba/Demon Slayer -https://www.curseforge.com/minecraft/mc-mods/demonslayer
minecolonies -https://www.curseforge.com/minecraft/mc-mods/minecolonies
MineMenu -https://www.curseforge.com/minecraft/mc-mods/minemenu
mowziesmobs -https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs
MutantBeasts -https://www.curseforge.com/minecraft/mc-mods/mutant-beasts
mysticalworld -https://www.curseforge.com/minecraft/mc-mods/mystical-world
Patchouli -https://www.curseforge.com/minecraft/mc-mods/patchouli
playerex -https://www.curseforge.com/minecraft/mc-mods/playerex
projectvibrantjourneys -https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys
SophisticatedBackpacks -https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
structurize -https://www.curseforge.com/minecraft/mc-mods/structurize
swingthroughgrass -https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass
TerraForged -https://www.curseforge.com/minecraft/mc-mods/terraforged
twilightforest -https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest
Undead -https://www.curseforge.com/minecraft/mc-mods/theundead/screenshots
Voidscape -https://www.curseforge.com/minecraft/mc-mods/voidscape
whisperwoods -https://www.curseforge.com/minecraft/mc-mods/whisperwoods
YungsApi  -https://www.curseforge.com/minecraft/mc-mods/yungs-api

Screenshots of 
bug/issue:

As you can see here I have my helmet equipped and the backpack is ontop of my head.
![1](https://user-images.githubusercontent.com/42361781/120942180-30073d00-c6f5-11eb-98a4-38f3cf9c9928.png)

 

As for here It'll show up when I have my inventory up but only for inventory and not outside of the inventory and I dont know why that is the case but its doing it.
![2](https://user-images.githubusercontent.com/42361781/120942210-66dd5300-c6f5-11eb-85d0-f389e8487590.png)

Here is some different screenshots of where I've tried different slots:
![3](https://user-images.githubusercontent.com/42361781/120942571-e835e500-c6f7-11eb-93aa-c1d8f494fe2a.png)
![4](https://user-images.githubusercontent.com/42361781/120942579-ec620280-c6f7-11eb-91a1-ab00d6360931.png)
![5](https://user-images.githubusercontent.com/42361781/120942581-ee2bc600-c6f7-11eb-82dc-747b2cfa25ae.png)

I've got it equipped on the back slot and as you can see its not there but it'll show up when I open my inventory
![2021-06-06_19 18 01](https://user-images.githubusercontent.com/42361781/120944338-ed982d00-c701-11eb-9d86-5adde14a5fd8.png)
![2021-06-06_19 18 20](https://user-images.githubusercontent.com/42361781/120944340-f0931d80-c701-11eb-9041-633d01f3136d.png)

Thanks for taking the time to read all this!

**Comment by P3pp3rF1y** [comment]
That thing with rendering at your head is a "feature" of Epic fight mod this is at least 3rd time someone has reported that, I feel like I may need to pin this or add to issue template. But basically you need to complain to them about this. 
Why the backpack doesn't render for you when in back slot and when you're outside of your inventory I have no idea as it renders well for me as well as for many other people in popular packs. So I will need you to figure out what mod interaction is causing it as your list is pretty long. Probably removing epic fight mod first would be best because of it's liberal approach to rendering.

**Comment by P3pp3rF1y** [comment]
Just checked quickly in epic fight mod and it appears to be another thing it causes https://github.com/Yesssssman/epicfightmod/issues/235

Closing this, feel free to reopen if you find out that it's not them.
