### ISSUE TITLE
Sort Buttons Overlap Quark Buttons

### ISSUE THREAD

**Issue by WenXin20** [P3pp3rF1y/SophisticatedBackpacks#17]
`Minecraft v1.16.4`
`Sophisticated Backpacks v1.0.0.9`
`Quark r2.4-279`

Quark also adds sort buttons to the inventory. Could a config be added to offset the buttons from this mod to a different location?

**Comment by StygianEmperor** [comment]
Oddly, for me the Quark sort buttons actually move over to the left to give room for the new SB buttons, so I wonder if there's already compatibility code in place that's just not triggering for you?

**Comment by WenXin20** [comment]
Hmm, I am using the mods on a server. Maybe that's why?

**Comment by P3pp3rF1y** [comment]
I can actually see that as well. it doesn't happen for diamond backpack as that uses wide inventory texture. but it does happen for all the other backpacks

**Comment by WenXin20** [comment]
I did only check one backpack size.

**Comment by StygianEmperor** [comment]
Ah, yep, I was using the diamond backpack.

**Comment by P3pp3rF1y** [comment]
In the latest version you now have client config to set where the buttons should appear - there are 4 different places so that should hopefully be plenty to avoid this conflict

**Comment by WenXin20** [comment]
Alright, thanks!
