### ISSUE TITLE
Stack upgrade not functioning

### ISSUE THREAD

**Issue by C3D307** [P3pp3rF1y/SophisticatedBackpacks#170]
I've been playing on a modded game (Enigmatica 6) for a while now, and this mod has been a game changer, especially with the stack upgrade. However, for whatever reason, I sorted the backpack, and all my items became unstacked, and the excess stuff was deleted! Has this happened to anyone else, and how would I fix this?

**Comment by P3pp3rF1y** [comment]
What way did you use to sort your backpack? the sorting button that's included in the backpack gui?

**Comment by P3pp3rF1y** [comment]
closing this as there was no additional info provided and I can't recreate
