### ISSUE TITLE
Inventory Crash

### ISSUE THREAD

**Issue by WenXin20** [P3pp3rF1y/SophisticatedBackpacks#171]
**Describe the bug**
Unfortunately, I was not paying attention to my screen when the crash occurred, so I'm not positive what caused it, but I might have accidentally pressed `B` to open the backpack while my inventory was already open.
[Crash Report](https://gist.github.com/WenXin20/41ce5d35fe69d55494b0fcfd057f4ae9)

**To Reproduce**
1. Open Inventory
2. Press `B` to open backpack
3. Crash?

**Expected behavior**
- No Crashes

**Versions**
`Minecraft v1.16.5`
`Forge v36.1.32`
`Sophisticated Backpacks v2.5.0.271`

**Comment by P3pp3rF1y** [comment]
So this is not possible to recreate with just SBP nor in pack that I play (Seaopolis). You have a mod in there that changes MC logic of checking whether keybind can be pressed in the given gui (KeyConflictContext). If you can figure out which mod it is I can take a look at what they are doing just to double check there really isn't an issue in sbp, but very likely you will then need to report this issue to that mod as something making MC ignore key conflict context would break many mods and may even break some vanilla keybind resolution especially if you use the same key for two different actions that can only every trigger in different contexts.

**Comment by P3pp3rF1y** [comment]
just looking at the mods list you may want to start with JEK as that seems to mess with keybinds and possibly has an issue there

**Comment by WenXin20** [comment]
It may have been JEK, I had removed that mod recently and did not get a crash when pressing `B` while in my inventory. Thanks for looking into it.

**Comment by P3pp3rF1y** [comment]
alright, thanks for confirming closing this
