### ISSUE TITLE
MohistMC , not working with Backpacks.

### ISSUE THREAD

**Issue by polios3** [P3pp3rF1y/SophisticatedBackpacks#174]
i tested on clean MohistMC. only your mod. and 0 datapacks.
and even i turned on "safe mode"

again: Failed to load datapacks, cant proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode

so yea. it might be your mod that have issue with MohistMC. Can you fix it somehow?
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6769751/latest.log)

EDIT: i tested it again. using older version(2.4.0.259 instead of 2.5.0.271) of your mod. and works fine with this version.

**Comment by P3pp3rF1y** [comment]
well, I am not sure what it is complaining about would need to get an actual error that tells me what's wrong, not just "failed to load datapacks" or the info that it's loading config.

Just to be sure I have checked what has changed in the last version and don't see anything related to data folder (which I would assume it puts under datapacks?) and just a minor thing in config where a setting was removed. 

And again the mod is include in multiple major modpacks that have many servers running and not one has complained so far about this and they definitely run SBP on server. 

So the most likely issue here is MohistMC doing something special. But as I said if you can get me more info on what it is complaining about I can take a look.

**Comment by P3pp3rF1y** [comment]
also could you get me `debug.log` ? Should have more info there if there isn't any crash log available

**Comment by Dunkmania101** [comment]
I had this too, only it happened on my own local server and in single-player.
It seems to have something to do with the Enable/Disable part of the configuration system:
`at net.p3pp3rf1y.sophisticatedbackpacks.Config$Common$EnabledItems.isItemEnabled(Config.java:344) ~[sophisticatedbackpacks:property(class java.lang.String, provider(?))]`
`at net.p3pp3rf1y.sophisticatedbackpacks.crafting.ItemEnabledCondition.test(ItemEnabledCondition.java:32) ~[sophisticatedbackpacks:property(class java.lang.String, provider(?))]`

[latest.log](https://gist.githubusercontent.com/Dunkmania101/50289c1ee7a09941666436eba31f77ee/raw/c438e538ee44bd4c34245a1a5302ae5674ef40c4/latest.log)

**Comment by P3pp3rF1y** [comment]
fixed in the latest version
