### ISSUE TITLE
Refilling items isn't the smartest.

### ISSUE THREAD

**Issue by ZeekDaGeek** [P3pp3rF1y/SophisticatedBackpacks#177]
**Describe the bug**
With the refill upgrade turned on for Torches for example you frequently run into issues where you pick up an item and all of a sudden you have 1 stack of 1 torch and a stack of 63 torches and never will they combine, which is annoying.

It would be nice if maybe you could specify that you want the stack to refill to 48 or less.

A check box for "Refill held item" without needing a filter would be a nice addition as well.

**To Reproduce**
1. Add the Refill Upgrade.
2. Place some torches around.
3. Break a torch that you misplaced while mining
4. Keep placing torches around as you mine
5. Be annoyed when you look into your inventory and realize you have 2 stacks of torches and you can't pick up the loot you want.

**Expected behavior**
Keep the items at the refill amount and suck up items that go over the limit.

**Versions**
Version 2.5.0.271

**Comment by P3pp3rF1y** [comment]
The issue with pickup is not really about refill functionality as where the torch goes that you pickup is a matter of default minecraft code and refill fills in first slot that it finds that matches the item. Potential functionality that would try combining items in different slots would then prevent you from splitting those items in your inventory as it would need to continuously scan for items in its filter and merge them if they were split in different stacks. So I don't see a way of fixing that. Maybe one where player would somehow have to say which exact slot the refill should be refilling.

Refilling held item option makes sense to me. So I will take an note of this and add in the future.

Not sure that I really see much use for setting how much you want to refill that one stack as in all examples that I can come up with I just want to continuously refill the item and in some situations it doesn't matter that it's always refilled to 64 (placing torches down there's no advantage of specifying lower number) and in others it's better (like builder wands that can't pull from backpack can place up to 64 blocks).

**Comment by P3pp3rF1y** [comment]
This actually was implemented a while ago, just closing now
