### ISSUE TITLE
Expanding the backpack with Tank Upgrade

### ISSUE THREAD

**Issue by Fr0stmatic** [P3pp3rF1y/SophisticatedBackpacks#185]
**Describe the bug**
The backpack with installed Tank Upgrade by SHIFT-click works incorrectly.
The tank interface does not appear (at first times), inventory slots do not disappear.
Removing Tank Upgrade adds new slots to backpack outside of GUI. 

**To Reproduce**
1. Open your backpack
2. Add Tank Upgrade by SHIFT-click
3. Remove Tank Upgrade
4. Repeat last 4 steps until new backpack's slots go right off-screen

**Versions**
Forge 36.2.0
Sophisticated Backpacks 3.0.0.287

**Comment by P3pp3rF1y** [comment]
ouch that doesn't sound good, I will take a look and probably fix pretty quickly, thanks for reporting it

**Comment by P3pp3rF1y** [comment]
fixed in the latest version on curseforge
