### ISSUE TITLE
Client crash when backpack placed in Tinker's Construct crafting station

### ISSUE THREAD

**Issue by jshydra** [P3pp3rF1y/SophisticatedBackpacks#195]
**Describe the bug**
When you place a sophisticated backpack into the crafting grid of a Tinker's Construct crafting station, the client will immediately crash.   It is reproducible.   From what I can gather, it looks like the table isn't rendering the backpack correctly.  Once it exists in the game world, the client will crash repeatedly trying to render the backpack.   This crash results in the World being unplayable, and it must be reverted to a backup.

**To Reproduce**
1. Place Sophisticated Backpack in Tinker's Construct crafting station crafting grid
2. Client freezes

**Expected behavior**
Expected that TCon crafting station would render a small version of the backpack I guess?

**Screenshots**
N/A
[crash-2021-07-29_09.01.47-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6900752/crash-2021-07-29_09.01.47-client.txt)

**Comment by lily-es** [comment]
This bug is fixed in the latest version of Sophisticated Backpacks

**Comment by P3pp3rF1y** [comment]
as said above, this was already fixed, please try to look for newer version next time before reporting an issue here
