### ISSUE TITLE
Mod does not load correctly in Enigmatica 6 server

### ISSUE THREAD

**Issue by Pactastic** [P3pp3rF1y/SophisticatedBackpacks#196]
**Describe the bug**
Server fails to load with error:
Sophisticated Backpacks (sophisticatedbackpacks) has failed to load correctly
		java.lang.IllegalStateException: Failed to resolve consumer event type: net.p3pp3rf1y.sophisticatedbackpacks.common.CommonProxy$$Lambda$9379/0x0000000000000000@adb810c0

**To Reproduce**
1. Start Server
2. See error

**Expected behavior**
Server to start

Crash Report:
[crash-2021-07-29_12.40.42-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6902325/crash-2021-07-29_12.40.42-fml.txt)

**Versions**
1.16.4-2.5.0.271

**Comment by P3pp3rF1y** [comment]
You're using OpenJ9 which is unsupported by forge because of the fact that it does things differently than other java implementations and what you're seeing here is caused by that. Switch to different Java JVM and this issue will be gone.
