### ISSUE TITLE
Wrong item in upgrade slot crashes the game

### ISSUE THREAD

**Issue by W0NSZ** [P3pp3rF1y/SophisticatedBackpacks#200]
**Describe the bug**
It is possible to put items other than upgrades in upgrade slots, by swapping an item with an upgrade in the slot. It causes the game to crash every time that backpack is opened.

[crash-2021-08-05_16.13.48-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6939322/crash-2021-08-05_16.13.48-client.txt)

None other mods were used.

**To Reproduce**
1. Open backpack
2. Put an upgrade in the upgrade slot
3. Take any other item, and swap the two
4. The game crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/71080786/128366677-f6a5b5ce-2469-4668-9a90-06adc8c386df.png)

**Versions**
sophisticatedbackpacks-1.16.4-2.2.7.222
1.16.5-forge-36.2.0

**Comment by P3pp3rF1y** [comment]
Please dont open issues for bugs that were fixed long time ago. Just update the mod to newer version

**Comment by W0NSZ** [comment]
> Please dont open issues for bugs that were fixed long time ago. Just update the mod to newer version

I am sorry, I didn't realize it actually is an old version.
