### ISSUE TITLE
Backpack Crashes Players on Server, but not Server itself

### ISSUE THREAD

**Issue by Ethan156** [P3pp3rF1y/SophisticatedBackpacks#201]
**Describe the bug**
I added the Sophisticated Backpacks mod to my modpack and created a server for my community. One player crafted a backpack. Once he wore it on his back, all players on the server had their games crash, but the server was still fine. It doesn't crash everytime someone wears one because when everyone loaded back in it was fine. But then we all disconnected and rejoined the next day, and everyone's game crashed once that player joined wearing the backpack. After looking at the crash report, seems it has something to do with rendering the backpack entity in the world.

**To Reproduce**
1. Craft Backpack
2. Wear Backpack on character's back
3. It might crash everyone's client, but not the server
4. See client crash report attached.

**Crash Report**
[crash-2021-08-06_21.44.44-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6948514/crash-2021-08-06_21.44.44-client.txt)

**Expected behavior**
The backpack is expected not to crash games when the user wears it on their back.

**Versions**
Minecraft 1.16.5
Sophisticated Backpacks 3.0.3.297
Forge 36.2.2

**Comment by P3pp3rF1y** [comment]
PowerSuits issue, one that was reported to me a few times already. they just assume that anything in chest slot that can handle items is modular item which backpack obviously isn't. So this needs to be fixed there

https://github.com/lehjr/MachineMusePowersuits/blob/1.16.5/src/main/java/com/github/lehjr/powersuits/client/event/RenderEventHandler.java#L109-L110
