### ISSUE TITLE
Crashing with java error Rendering Block Entity

### ISSUE THREAD

**Issue by ChewyBacon1** [P3pp3rF1y/SophisticatedBackpacks#202]
Mod was working fine until I tried to color my backpack purple. Now it crashes everytime I load into my server. 

[crash-2021-08-07_22.50.20-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6950157/crash-2021-08-07_22.50.20-client.txt)

**Comment by frOOps** [comment]
Same problem here but did not color it. It crashed when I tried to put it in a crafting table for upgrade. Had the same problem on other worlds before thou. 

[crash-2021-08-05_21.51.36-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6951197/crash-2021-08-05_21.51.36-client.txt)

[crash-2021-08-07_23.30.20-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6951194/crash-2021-08-07_23.30.20-client.txt)

**Comment by P3pp3rF1y** [comment]
Please update to the latest version it has been fixed in there for more than a week now
