### ISSUE TITLE
Backpack on Armor Stand crashes.

### ISSUE THREAD

**Issue by eliminat** [P3pp3rF1y/SophisticatedBackpacks#208]
Seems to be an issue similar to the previous Tinkers Crash.
Right clicked a backpack on an armor stand, instant client crash
Client can no longer back in, but people outside of view range can log in.

https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/195

Running Enigmatica 6  version 0.5.7
Running sophisticatedbackpacks-1.16.5-3.0.3.297

Pastebin of crash log: https://pastebin.com/UsFjT5Z6   |   https://pastebin.com/qsucwhhs

Edit: Workaround of /kill on the armor stand allowed me back in.

**Comment by P3pp3rF1y** [comment]
this is actually curious armor stands and an issue that I have fixed for curious itself in dev. So will be fixed with the next release.

**Comment by P3pp3rF1y** [comment]
fixed in latest version
