### ISSUE TITLE
Feeding Upgrade Eaten Food Doesn't Count as Eaten for Spice of Life Carrot Edition

### ISSUE THREAD

**Issue by NielsPilgaard** [P3pp3rF1y/SophisticatedBackpacks#21]
Not sure if this is caused by Sophisticated Backpacks, Spice of Life: Carrot Edition or both, but eaten foods via Feeding Upgrade don't count as eaten for the extra hp milestones from Spice of Life: Carrot Edition.

### Versions
- solcarrot-1.16.3-1.9.8
- sophisticatedbackpacks-1.16.4-1.1.2.105
- Forge-1.16.4-35.1.28

**Comment by P3pp3rF1y** [comment]
Looks like an event needs to be raised for SoL logic to fire. That hopefully should be a trivial change so I will add this in the next version.

**Comment by NielsPilgaard** [comment]
Awesome, thanks!

**Comment by P3pp3rF1y** [comment]
I have just uploaded new version to CF should be approved shortly and has this fix in.
