### ISSUE TITLE
Odd interaction between Farmer's Delight stackable soups and the auto-feeding backpack upgrade

### ISSUE THREAD

**Issue by Not-February** [P3pp3rF1y/SophisticatedBackpacks#210]
**Describe the bug**
I'm running Farmer's Delight alongside Sophisticated Backpacks. It by default allows its soups(and potentially others added in its config) to stack to 16. However, I've noticed that when allowing one of these soups to be used by the auto-feeding upgrade, it doesn't use up any of the stacked soup in the backpack but still lets you eat it/gives you a bowl back.

**To Reproduce**
1. Have autofeeding upgrade on a backpack
2. Set one of Farmer's Delight's soups to its filter
3. Have a stack of more than one such soup in your backpack
4. Get hungry to make the auto-feeding upgrade trigger
5. Watch as you get a bowl back and your hunger is restored but you still have just as much soup in your backpack as before

**Expected behavior**
I'd expect the soups to be actually consumed when you benefit from eating them, and to not get an extra free bowl every time you eat such a food

**Versions**
``Forge 36.2.0``
``Sophisticated Backpacks 3.0.3.297``
``Farmer's Delight 0.4.5``

**Comment by P3pp3rF1y** [comment]
I am sure this was working before as I have tested with this exact setup when testing stackable foods that return a container item. Will need to debug to see what's happening.

**Comment by P3pp3rF1y** [comment]
Just retested this and it's working properly for me with soups being consumed. The bowls are supposed to be returned and that's actually Farmer's Delight doing that so that's working properly as well. 
So I would need more pointers as to how to recreate what you're seeing as I am unable to.

**Comment by Not-February** [comment]
Strange. I'll see if I can take some time to test this and #211 sometime soon to figure out what's going on, I can also provide you with a full mod list soon

**Comment by Not-February** [comment]
Did a forced crash to generate a mod list for the setting of these issues. I apologize for not testing whether these problems happened in a standalone environment before reporting them and then not providing a full mod list.

https://gist.github.com/Febilian/08786322d49a1f6fe84c532d5e87f901

**Comment by Not-February** [comment]
As mentioned in the other issue I've subsequently been unable to reproduce the issue. It's possible it wasn't an issue in the first place. I'm not sure what happened.
