### ISSUE TITLE
NPE with version 316 of Sophisticated Backpacks.

### ISSUE THREAD

**Issue by darkphan** [P3pp3rF1y/SophisticatedBackpacks#214]
**Describe the bug**
Crashing if backpack is in inventory

Crashlog: https://gist.github.com/darkphan/d0dd077ad9ff6d43df2a3a39dcf6b8d4

1. Install version sophisticatedbackpacks-1.16.5-3.2.4.316
2. Have backpack in inventory/wearing
3. Crash

**Comment by RomoE** [comment]
Happening with me as well, crashlog provided 
[crash-2021-08-22_17.51.08-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7028477/crash-2021-08-22_17.51.08-client.txt)

**Comment by P3pp3rF1y** [comment]
a bit of a derp on my side - this happened when client only connected to dedicated server and backpack rendered there, a case I thought I have tested but apparently not. Anyway a fixed version is up on curseforge.

**Comment by NielsPilgaard** [comment]
I hope you don't mind me piggybacking on this issue, I had a very similar crash on version `sophisticatedbackpacks-1.16.5-3.2.7.326.jar` in singleplayer: https://gist.github.com/NillerMedDild/0911d8cfab3c2b12f6bc5340994fb2c2

I wasn't doing much really, and was in peaceful. 

Let me know if you'd prefer a new issue for this :)
