### ISSUE TITLE
[Mod interaction] [Unique Crops] Backpacks will auto-feed you gemstones and ingots under erraneous circumstances

### ISSUE THREAD

**Issue by Not-February** [P3pp3rF1y/SophisticatedBackpacks#216]
**Describe the bug**
There is a curio in the Unique Crops mod called the Cast Iron Stomach that allows the player to eat anything assigned to the tags ``forge:ingots`` or ``forge:gems`` if you have it equipped, but not at any other time.

Backpacks will automatically feed you these items with an auto-feeding upgrade regardless of whether you have the cast iron stomach equipped or even in your inventory.

I am uncertain of whether this is an issue more closely related to Sophisticated Backpacks or Unique Crops; I do know from a TellMe dump in another modpack setting that Unique Crops apparently designates anything found in ``forge:ingots`` and ``forge:gems`` as a food item regardless of whether you're using its curio, which is probably why Sophisticated Backpacks thinks it's okay to go ahead and eat it at any time.

I'm not actually sure how you'd go about fixing this without potentially trampling on any other mod that makes items only conditionally edible(like, for example, Origins with dietary restrictions enabled), though.

**To Reproduce**
1. Open backpack with Unique Crops installed
2. Apply auto-feeding upgrade and ensure it is enabled
3. Put nothing but iron ingots in the backpack
4. Lose enough hunger for the backpack to feed you

**Expected behavior**
I would not expect to be able to eat gems and metal ingots through the backpack when I can't actually eat them manually(i.e. when the curio is not equipped).

**Versions**
``Minecraft 1.16.5``
``Forge 36.2.2``
``Sophisticated Backpacks 3.2.4.316``
``Unique Crops 0.1.46``
``Curios 4.0.5.2``

**Comment by P3pp3rF1y** [comment]
I have added a bit of code in dev to call the method that is usually called when the player tries to eat so now this is working correctly in dev.

**Comment by P3pp3rF1y** [comment]
Fix released on curseforge
