### ISSUE TITLE
Feature Request - button to toggle magnet on/off

### ISSUE THREAD

**Issue by MatthiasMann** [P3pp3rF1y/SophisticatedBackpacks#22]
I'm using sophisticatedbackpacks-1.16.4-1.1.2.105 together with the mod Create.
It would be nice to have a hotkey to turn the magnet on/off (and have a small indication on the UI to show if it is on/off).

Alternative something like Botania's Solegnolia (I don't have Botania in my mod pack but could add it just to get this flower if supported by Sophisticated Backpacks) to disable magnets in a certain area.

**Comment by P3pp3rF1y** [comment]
a good idea, I will just make it into something more generic across upgrades so that you would be able to turn on and off any of them in backpack gui in general.

**Comment by P3pp3rF1y** [comment]
Latest release has switches next to upgrade slots to allow turning upgrades off. It also has keybinds that do the same for the first backpack found in player's inventory.

**Comment by MatthiasMann** [comment]
Works perfectly - thanks :D
