### ISSUE TITLE
Duplicate Fluids

### ISSUE THREAD

**Issue by GreninjaSan** [P3pp3rF1y/SophisticatedBackpacks#223]
**Describe the bug**
When using the tank upgrade for the backpacks, you can duplicate fluids by using tanks that can be stacked.

**To Reproduce**
1. Add a tank upgrade to a backpack.
2. Fill a column with the fluid of your choice (lava for example)
3. Then, use a stackable tank, with 64 of them stacked, to get the fluid back (Seared Fluid Tanks from Tinker's Construct for example)
4. The 64 tanks will be filled. Therefore you will have multiplied your fluids by 64.

**Expected behavior**
It should only fill one tank.

**Versions**
Last version sophisticatedbackpacks-1.16.5-3.2.4.321.jar

**Comment by P3pp3rF1y** [comment]
Fixed in the latest version on curseforge - only allows one tank to go in either output/input slot
