### ISSUE TITLE
Issue when hitting a zombie 

### ISSUE THREAD

**Issue by Wadwadmadlad** [P3pp3rF1y/SophisticatedBackpacks#233]
I immediately crash once I hit a zombie, when equipped with a backpack. I believe this mod is the issue since it's the only one I find in the crash report. Here it is attached
[crash-2021-08-29_14.46.42-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7072516/crash-2021-08-29_14.46.42-client.txt)

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
