### ISSUE TITLE
Duplication of items possible with shulkers

### ISSUE THREAD

**Issue by Shads404** [P3pp3rF1y/SophisticatedBackpacks#234]
Version:  1.16.5-3.27.326

This bug is only present when used in conjuction with quarks management 'right click shulker box' option which allows for quick placement of items into shulkers via right click.

Using this feature on a stack of shulker boxes in a backpack with stack upgrade will create a stack of shulkers with said item, allowing for duplication to occur.

**Comment by P3pp3rF1y** [comment]
to be honest I feel this one is more an issue on quark side - there are multiple mods that allow non stackable items to stack and Quark should be checking that it's adding items into a single item. Also I consider it a feature to allow stacking empty shulker boxes in backpacks as it should be possible to stack any non stackable item in there with stack upgrade. 

But given this issue I will take a look at adding a config to allow specifying list of items that should not stack in backpack.

**Comment by P3pp3rF1y** [comment]
The latest release has config that allows setting shulkers to not stack
