### ISSUE TITLE
Crash when opening player inventory in creative mode

### ISSUE THREAD

**Issue by MaxWasUnavailable** [P3pp3rF1y/SophisticatedBackpacks#236]
**Describe the bug**
Open player inventory in Creative (the actual inventory tab, not the creative tabs), the game crashes.

**To Reproduce**
1. Start new creative mode world
2. Open creative inventory
3. Click on player inventory tab
4. Crash

**Expected behavior**
That it doesn't crash.

**Versions**
1.16.5
Rest should be in the crash log
[crash-2021-09-05_02.03.08-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7110672/crash-2021-09-05_02.03.08-client.txt)

**Comment by MaxWasUnavailable** [comment]
I believe this might be an incompatibility with the Entity Culling mod? Disabled that one, restarted the game, and the crash didn't occur.

https://www.curseforge.com/minecraft/mc-mods/entity-culling

**Comment by NielsPilgaard** [comment]
I'm getting the same crash every once in a while, I also have the Entity Culling mod.

**Comment by MaxWasUnavailable** [comment]
Adding some more findings;

It seems it might be related to the "Snow! Real Magic!" mod. Having that in the pack together with the Sophisticated Backpacks mod resulted in fairly consistent crashes.

**Comment by NielsPilgaard** [comment]
That I do not have 😅

**Comment by P3pp3rF1y** [comment]
Actually this looks to be related to a bit of a threading issue where both client and server try to intialize two collections at almost the same time. Based on that I would guess you always got this issue only in single player, never on dedicated server. 
And I have just made a code change that should fix the threading issue here, should be able to release it in a few days

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
