### ISSUE TITLE
Inconsistent crash when breaking tile entities or killing entities

### ISSUE THREAD

**Issue by theboo** [P3pp3rF1y/SophisticatedBackpacks#238]
**Describe the bug**
I had a new superflat world and placed down the new apotheosis enchantment library block, when i broke it i client crashed to desktop. We also had someone playing using e6 dev branch report on our github tracker with the same error killing a mob in the nether. That issue and info is located here: https://github.com/NillerMedDild/Enigmatica6/issues/3186

I should mention that i was in a peaceful superflat world(no mobs with backpacks) and no backpack was ever used in that world

Crash log if it's a crash.
https://pastebin.com/7SMURX9D

**To Reproduce**
i have not been able to reproduce this, but it seems breaking a tile entity or killing a mob in a new world might cause it?

**Versions**
sophisticatedbackpacks-1.16.5-3.2.7.326.jar
forge 36.2.0

pack version:
enigmatica 6 latest dev branch

**Comment by P3pp3rF1y** [comment]
This is fixed as part of fix for #232

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
