### ISSUE TITLE
[Bug | 1.16.5 - 3.2.12.337] Filter Upgrades Not Working Together

### ISSUE THREAD

**Issue by Seikikai** [P3pp3rF1y/SophisticatedBackpacks#250]
I Have A Backpack In A Pipe Network That I Use As Storage For All The Items Of The Mod **Create** (Filter A: Allow/Match Mod) And Because Copper Ores From That Mod Ended In That Backpack Instead The Furnaces I Added To The Backpack Another Filter (Filter B: Block/Match Item) To Block The Copper Ore But Instead Blocking It The Baclpack Ends Receiving Any Items But The Copper Ore.

Filter A:
![BackpackA](https://user-images.githubusercontent.com/54079357/136102904-e1867c82-dd9b-4173-bdd7-de36a17db233.png)

Filter B:
![BackpackB](https://user-images.githubusercontent.com/54079357/136102923-4ef5cce3-4d25-4ea2-a013-33cd0e9f1223.png)

**Comment by P3pp3rF1y** [comment]
This is not really a bug, they are not supposed to work like one big filter. Complexity  of that implementation is way too high so I am not planning to implement this. If I change my mind in the future and have way too much time on my hands I may add it but for now I am going to close this
