### ISSUE TITLE
Certain Foods Duplication Bug

### ISSUE THREAD

**Issue by MindGames18** [P3pp3rF1y/SophisticatedBackpacks#251]
**Describe the bug**
Foods which return bowl (eg, rabbit stew) gets duplicated when fed to the payer via Advanced Feeder Upgrade

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Give it a Advanced Auto Feeder upgrade
3. Add few rabbit stew in the backpack's inventory
4. Get hungry.
5. When the bag feeds u the rabbit stew, youll haev a duplicated amount of rabbit stew in your main inventory

**Expected behavior**
Should not be duplicated

**Screenshots**
Sorry, none which can actually depict the bug

**Versions**
Minecraft version : 1.16.5
Modpack : Mineshafts and monsters 1.6.7_hf
mod version : 3.2.12.337
Forge Version : 36.2.2

**Comment by P3pp3rF1y** [comment]
this is likely that you have Charm and Farmer's delight mods in the modpack and both have their stackable bowls turned on which causes item duplication if not eaten out of player's hand. Can you check that? Solution is to just allow one of these mods to run their stackable bowls logic

**Comment by natelovesyou** [comment]
> 
> 
> this is likely that you have Charm and Farmer's delight mods in the modpack and both have their stackable bowls turned on which causes item duplication if not eaten out of player's hand. Can you check that? Solution is to just allow one of these mods to run their stackable bowls logic

The person who reported this is also in the Mineshaft & Monsters modpack discord. Yes, Charm and Farmer's Delight are both in the pack. I am not sure if there are other mods with similar stacking changes in the pack, however.

**Comment by P3pp3rF1y** [comment]
well, the least that can be done here is making sure that only one of these mods adds its stacking bowls functionality, it doesn't matter which one but the other needs the functionality turned off otherwise they are going to duplicate the foods like this

**Comment by natelovesyou** [comment]
> 
> 
> well, the least that can be done here is making sure that only one of these mods adds its stacking bowls functionality, it doesn't matter which one but the other needs the functionality turned off otherwise they are going to duplicate the foods like this

Ah, I see. I interpreted your earlier comment as saying you can control which mod's stackable bowls (or other items) logic runs in the backpack. I reached out the the modpack author regarding this to see if both are active.

However, since Charm and FD are very popular and are likely together in many modpacks with your mod, is there a way for you to control with stacking logic affects items within the backpacks? I don't mean to put this on you, but I'm sure many modpack authors are unaware that duplicate logic can cause this bug.

(Off-topic... It just clicked that you're the author of Reliquary. No wonder this mod is so awesome!)

**Comment by P3pp3rF1y** [comment]
Nope I can't do anything about that - one of these mods could be detecting the other and turning its logic off as an option. But probably the only realistic one is players / modpack makers having to turn that logic off in one of them.
