### ISSUE TITLE
Netherite tier completely resets backpack (Mineshafts & Monsters modpack)

### ISSUE THREAD

**Issue by natelovesyou** [P3pp3rF1y/SophisticatedBackpacks#254]
**Describe the bug**
Unlike previous tier upgrades, upgrading from Diamond to Netherite via the Smithing Table results in a brand new Netherite backpack. Everything is lost - items, upgrades, custom color, enchantments.

This does NOT occur in a test with just the mod and Forge (36.2.2 or 36.2.0 tested) in a fresh modpack profile. This was discovered to be present in the modpack Mineshafts & Monsters (MnM) as early as MnM 1.5.5_hf, and is still present in MnM 1.6.7. It's unknown why it's happening in the pack. I suspect that a mod in the pack is modifying a Smithing Table behavior.

**To Reproduce**

1. Download and launch Mineshafts & Monsters 
2. Get a Diamond Backpack with items, upgrades, a custom color, and potentially enchantments, namely Soulbound.
2. Place the Diamond Backpack in the Smithing Table and add a Netherite Ingot.
3. Note that the output is a completely reset/fresh Netherite Backpack.
4. If you're daring, craft the Netherite Backpack and observe that it has no items, upgrades, custom color, or enchantments.

**Expected behavior**
The output in the Smithing Table results in the same Diamond Backpack's data but upgraded to Netherite tier in the MnM modpack.

**Screenshots**
The example Diamond Backpack and its Netherite tier output:
![Netheritebackpack](https://user-images.githubusercontent.com/16608135/136311173-c0c4d24a-798c-4ce5-947e-d8c0701cc666.png)

**Versions**
Minecraft version 1.16.5. Bug confirmed with mod versions 3.2.7.326 (modpack version 1.5.5_hf) and 3.2.12.337 (modpack version 1.6.7); both use Forge 36.2.2.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate with just SBP, so I will need more info on what mod is causing this to happen. I suspect that some mod is overriding smithing table functionality and doesn't trigger the functionality that vanilla does causing this deletion. 
But I don't have time to narrow this down to a specific mod in a huge modpack like this.

**Comment by natelovesyou** [comment]
> 
> 
> I am unable to recreate with just SBP, so I will need more info on what mod is causing this to happen. I suspect that some mod is overriding smithing table functionality and doesn't trigger the functionality that vanilla does causing this deletion. But I don't have time to narrow this down to a specific mod in a huge modpack like this.

I also have a ticket open with the modpack creator in the pack's Discord. He's going to look into it himself as well. I realized that asking you to download the pack and look into it was asking a lot, so I made sure to tell the pack creator that the bug isn't happening when it's just your mod in MC.

**Comment by P3pp3rF1y** [comment]
any update on this? anything found that requires a fix in sbp? Otherwise I am going to close this

**Comment by natelovesyou** [comment]
> 
> 
> any update on this? anything found that requires a fix in sbp? Otherwise I am going to close this

Hey, thanks for checking in (and sorry for not following up). Looks like Mineshafts & Monsters' pack creator bstylia did address this at some point, as it appears to be fixed. He did not disclose what the core cause was, but it's likely a mod or option that changed the functionality of the Smithing Table. I'm not sure what you can do to help avoid this on your end, so we can close this.
