### ISSUE TITLE
Weapon swap replaces all stored swappable tools

### ISSUE THREAD

**Issue by homemmakako** [P3pp3rF1y/SophisticatedBackpacks#256]
When using a tool swapper upgrade, if you allow the replacing of weapons, whenever you attack a mob (and the backpack swaps the your sword for instance) all your tools will be transformed into the previously equipped tool. Apart from that sometimes it swaps to a random tool.

**To Reproduce**
1. Configure swappable tools and weapon
2. Allow weapon swapping
3. Hit a mob
4. Your tools should all have been replaced and stacked

**Screenshots**
### Before hitting an entity
![image](https://user-images.githubusercontent.com/7462905/136483500-b2a98bc7-e3b5-4d06-abe3-05a31979476e.png)
### After hitting an entity
![image](https://user-images.githubusercontent.com/7462905/136483551-26d99410-d4e0-44e2-a155-0b80bcd800ae.png)
As you can see, it gave me a shovel (?) and transformed all the configured tools into pickaxes (the one previously equipped) and even stacked them. 

**Versions**
SB: 1.17.1-3.2.12.346.jar
Forge: 37.0.83

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
