### ISSUE TITLE
Stack Upgrades deleting items

### ISSUE THREAD

**Issue by MerkFreeks** [P3pp3rF1y/SophisticatedBackpacks#260]
**Describe the bug**
Currently playing on my multiplayer server on the Better Minecraft Forge modpack 1.16.5. I have a netherite backpack with a tier 3 stack upgrade, and I had sorted my backpack and all of my stacked up items resetted back to 64 and then everything that was extra was deleted. I was unable to add items back into a multiple stack afterwards

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Click on sort tab
3. Multi-Stack items get set to 64 and items deleted
4. Items are deleted
5. Can no longer stack items despite having a stack upgrade

**Expected behavior**
Items not to be deleted and the stack upgrade to function properly

**Versions**
1,16,5 4-3.0.0.287
Forge version 36.2.6

**Comment by P3pp3rF1y** [comment]
what do you mean by "click on sort tab"? I am unaware there would be a tab in SBP that does the sorting, if you mean inventory tweaks button that it adds to the side then yeah this is exactly what will happen and there's no blocking it, I am already a lot to prevent inventory tweaks from sorting the backpack and this by default is the only thing that remains there

**Comment by P3pp3rF1y** [comment]
and inventory tweaks have config to prevent sorting from working in specific containers. Enigmatica 6 is already using that one for SBP container so that needs to be set and issue is prevented for the future

**Comment by P3pp3rF1y** [comment]
closing given no response to questions.
