### ISSUE TITLE
Crash while trying to close bucket GUI

### ISSUE THREAD

**Issue by ClaudiusMinimus** [P3pp3rF1y/SophisticatedBackpacks#261]
**Describe the bug**
Was trying to close the bucket GUI and the client crashed

Crash log if it's a crash.
[crash-2021-10-12_15.56.24-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7333375/crash-2021-10-12_15.56.24-client.txt)

**To Reproduce**
1. Open backpack
2. Click on the bucket tab
3. Crash

**Expected behavior**
Should be able to open and close bucket GUI without crash

**Versions**
Minecraft 1.17.1
Forge: 37.0.85
Sophisticated Backpacks-1.17.1-3.5.0.365

This is part of a pack I am updating to 1.17.1, which I am including since it is not on Curseforge yet.
[99 Mods 1.17.1-0.3.0.zip](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7333441/99.Mods.1.17.1-0.3.0.zip)

Thank you,
CM

BTW: Love your mod!

**Comment by P3pp3rF1y** [comment]
looks like a rewrite made in forge yesterday causes this, I have to update forge and then fix in the mod, but in the meantime downgrading to forge 37.0.84 will fix this for you

**Comment by ClaudiusMinimus** [comment]
Thanks. I downgraded and it works fine now.

**Comment by P3pp3rF1y** [comment]
This was fixed in the latest release.
