### ISSUE TITLE
Sound Crash when exploring End

### ISSUE THREAD

**Issue by brisingraerowing** [P3pp3rF1y/SophisticatedBackpacks#268]
**Describe the bug**
[Crash Log](https://gist.github.com/BrisingrAerowing/a63dba6438aebea7f61b25b67324d88c)

Happened while exploring the End. May happen in other dimensions as well. Haven't experienced such crashes yet.

**To Reproduce**
1. Explore End
2. Find music playing backpack mob
3. Crash?

**Expected behavior**
No crash

**Screenshots**
N/A

**Versions**
SB: 3.4.2.354

**Comment by P3pp3rF1y** [comment]
All I can say based on that crash log is that one of the many mods that you have there modifies vanilla soundhandler and introduces some code in there which makes it possible for that code to crash with the NullPointerException. (In vanilla code that exception is impossible to be thrown in there)
It's possible that when sbp checks whether a given sound is active it can potentially send something to that changed code that makes it crash, but without knowing what that other mod is and how it changes the code I can't fix this. 

So I will need you to narrow this down to the minimum number of mods with which this still crashes.

**Comment by brisingraerowing** [comment]
I'm presuming the mod at fault is Dynamic Surroundings, as it does some major changes to the sound engine.

**Comment by P3pp3rF1y** [comment]
I don't see in its code that it would be changing this part of vanilla code base so it is something else

**Comment by P3pp3rF1y** [comment]
closing as there was no additional info provided
