### ISSUE TITLE
Two backpacks acting like an Enderchest

### ISSUE THREAD

**Issue by ChibiTk** [P3pp3rF1y/SophisticatedBackpacks#271]
I will be honest I have no idea how to exactly describe this issue other than we have two backpacks on my server that are somehow linked together.  I recorded a video since screenshots do not exactly do it justice.

We are playing the Better Minecraft Mod 41.5 but now realize this has happened with the past 4 iterations since now we know where all the food kept going.  No other mods outside BMM installed.

https://photos.app.goo.gl/ZfSGZRB3tfKevw8LA

**Comment by P3pp3rF1y** [comment]
You will find that both of those backpacks have the same UUID (F3 + H to see it in the item tooltip). 
However what would be important to me is how did you get these backpacks
- did you perhaps switch to creative and placed the backpack on the ground?
- or did you use '/sbp' command to give yourself the backpack?
- or have you played the pack for some time, used inception upgrade and stacked two backpacks on top of each other at some point in the past?

These are ways I know of that duplicate the UUID (the last one is a bug that was fixed some time ago) and one more would be if backpack is a reward from a quest book and that reward was put in there by quest book author already with UUID, but I am guessing then a lot of players would complain.

So please let me know how you got these and then perhaps I will be able to recreate this issue and fix.

**Comment by ChibiTk** [comment]
Apologies, was not able to check on this until after work.  I checked the UUID and they are indeed the same.  I have not ever stacked them up (Didn't know you could, probably cuz my bags are always overflowing lol) with the inception upgrade and have never used the /sbp command (Don't know what that does tbqh)  These bags were all acquired for the most part in chests from dungeon called "The Forge" and then upgraded to diamond so not entirely sure how it ended up like that.  I know I did not go into creative and place them down at any point.  Maybe something went wrong during some random crashes we had.

Thinking on it, it is actually kind of cool that they can be linked like that.  Placing backpacks on the ground in creative causes it to have an identical UUID?  

Edit: Just tried the setting down backpacks in creative but was not able to duplicate the UUID :(

**Comment by P3pp3rF1y** [comment]
when you place the backpack in creative it will get placed but also stay in your hand and both the one on the ground and the one in your hand will have the same uuid. you just need to open it at least once since it was given / crafted.

**Comment by P3pp3rF1y** [comment]
this has been open for quite a while and no additional info provided on how a backpack with duplicate UUID could have been created and I haven't seen any other reports since either. So I am going to close but feel free to reopen / open new bug if you find how this could be done.
