### ISSUE TITLE
Crafting upgrade not working

### ISSUE THREAD

**Issue by Maximus3670** [P3pp3rF1y/SophisticatedBackpacks#273]
The cafting gid in the backpack doesn't show any output and cant craft anything

![image](https://user-images.githubusercontent.com/93289843/139144930-c3b0b930-d1bb-4a40-8262-a596b0ad9d89.png)

sophisticatedbackpacks-1.16.5-3.7.0.378 
Minecraft 1.16.5 
Forge 36.2.0

**Comment by P3pp3rF1y** [comment]
Works alright for me, I can see that this is in a modpack so I will need information on what minimal set of mods it doesn't work for you. And a confirmation that you can actually use this recipe in regular crafting table as modpacks can override any recipe.

**Comment by P3pp3rF1y** [comment]
any update on this? without additional info I can just close

**Comment by P3pp3rF1y** [comment]
closing
