### ISSUE TITLE
Cant select tags to filter

### ISSUE THREAD

**Issue by Coy-Allen** [P3pp3rF1y/SophisticatedBackpacks#275]
**Describe the bug**
I cant use the tag filters at all on the auto-smelting tab.

**To Reproduce**
1. Open backpack
2. Click on 'auto-smelting ' tab
3. Put something in the tag filter and try to scroll/click to add tag
4. Nothing happens

**Expected behavior**
I should be able to scroll and click on tags

**Screenshots**
![image](https://user-images.githubusercontent.com/22683505/139279545-f3305834-24d2-4017-9241-8f8083f9fa9e.png)

**Versions**
I am using a slightly outdated version of All The Mods 6 (i use multiMC so idk what version)
Mod version is 1.16.5-3.4.2.354
forge 36.2.6

**Comment by P3pp3rF1y** [comment]
I am aware that this is in the latest released version and in fact have merged in fix for this that I did in the 1.17 before.

**Comment by P3pp3rF1y** [comment]
fixed in latest release
