### ISSUE TITLE
Client crash when trying to use the stone cutter add on

### ISSUE THREAD

**Issue by Khallie** [P3pp3rF1y/SophisticatedBackpacks#276]
My minecraft client crashed when I tried to use the stone cutter add on feature for the backpack. 

[crash-2021-10-30_11.08.19-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7445554/crash-2021-10-30_11.08.19-client.txt)

**To Reproduce**
1. Open backpack
2. Click on 'stone cutter' tab, 
3. placed one cobblestone block in the processing section and clicked on the the slab icon
4. Client crashes

I tried to take a screen shot but my client crashed after the stone cutter tab had been open about 10 seconds

**Comment by P3pp3rF1y** [comment]
you need to update your forge version. that updated version of sophisticated backpacks has fix for new forge version specifically in that place where it crashes for you on the old one.
