### ISSUE TITLE
All items lost after placing backpack on ground

### ISSUE THREAD

**Issue by Tintow** [P3pp3rF1y/SophisticatedBackpacks#278]
**Describe the bug**
Have a back pack with multiple items inside and place on ground.  Pick up the backpack with 'attack'  (left mouse) rather than crouch-use (shift-right mouse) and all the contents of the backpack are lost - it's totally empty.

**To Reproduce**
1.  Place items in a backpack
2.  Place backpack on ground
3.  Pick up backpack using attack (left mouse button)

**Expected behavior**
I expected the contents of the backpack to remain.
Crouch-Use picks up the backpack and the contents remain as expected.

**Screenshots**
n/a

**Versions**
Sophisticated Backpacks 1.17.1-3.7.1.381
Minecraft 1.17.1
Forge 37.0.103
Journeymap 5.7.3rc5
JEI 8.1.0.31

These are the only mods I am running.

**Comment by Khallie** [comment]
I have had the same problem, and the backpack lost its colour. I took a screenshot of the backpack before I mined it with my pickaxe and the contents afterwards. This was a test backpack, previously I had picked up one full of wood and lost the lot,

![2021-11-01_11 53 38](https://user-images.githubusercontent.com/93413442/139611004-6d96f0e4-0304-40df-bcb2-9b38c4841dad.png)
![2021-11-01_11 54 10](https://user-images.githubusercontent.com/93413442/139611007-031c99d3-ae66-4767-a5b3-b377cde8fd2f.png)

**Comment by P3pp3rF1y** [comment]
yup, apparently a bug in forge caused loot tables for backpack blocks to lose a bit that makes them retain all their data once broken. 
I have this fixed in dev and for these cases where you lost the contents you can use `/sbp list [your ign]` to see backpacks that you opened and then clicking on those will get you a give command to get them back including contents.

**Comment by P3pp3rF1y** [comment]
fixed in latest release on curseforge
