### ISSUE TITLE
1.17.1 Compatability issue? not saying anything is wrong with your mod...

### ISSUE THREAD

**Issue by RepoDraghon** [P3pp3rF1y/SophisticatedBackpacks#284]
'JEK' (Just Enough Keybinds) is not compatible with 'Controlling', however, if both are installed so far the only mod I have experienced the loss of keybind is 'Sophisticated Backpacks' and this stays true with changing the keybind letter itself...

Using Modpack 'Better Minecraft' with said added (above) plus, 'Sophisticated Backpacks', 'Simple Backpack', and 'Traveler's Backpack' installed...

Works perfectly fine without 'JEK' installed though

Just a notice, you don't have to work on it... Please close the thread when you are finished reading...

**Comment by P3pp3rF1y** [comment]
Alright closing, but what was the fix for you? Sounds like something that may be coming up for others so I would like to understand how it can be fixed for them as well.

**Comment by RepoDraghon** [comment]
The simple fix of not using both JEK and Controlling at the same time since they conflict... However, the conflict shouldn't affect the function of the keybinding if I interpreted the description for JEK right...

**Comment by P3pp3rF1y** [comment]
just fyi, JEK breaks part of the functionality that SBP uses to check for whether keybind is pressed - specifically `consumeClick` method so this needs to be fixed on JEK side to work.

**Comment by RepoDraghon** [comment]
I don't know programming so I wouldn't know, I was just leaving this warning in case someone else brings up this issue about not being able to open the backpack via keybind so that the programmers of this mod will know to ask if these mods are in at the same time or not if that info was not provided.

**Comment by P3pp3rF1y** [comment]
sorry if my comment came over as harsh, definitely wasn't meant that way, I just wanted to let you know that in the meantime I have found why it didn't work for you and that JEK needs to fix this on their side as there's nothing wrong in this case about what SBP is doing in terms of keybind handling.
