### ISSUE TITLE
Bowls from stacked foods sometimes end up in the inventory

### ISSUE THREAD

**Issue by Quezler** [P3pp3rF1y/SophisticatedBackpacks#285]
**Describe the bug**
If you eat food that returns a bowl but happens to be stacked when eaten the bowl ends up in your main inventory.

**To Reproduce**
1. Have a backpack with a feeding upgrade
2. Grab 2 or more stackable edibles that return a bowl
3. Become ~~robot~~ hungry
4. Notice the bowl appearing in your inventory
5. If the last one from the stack is eaten, notice the bowl in the proper slot

**Expected behavior**
For the bowl to appear somewhere in the backpack (if there is room, and only if not to add it to the main inventory)

**Screenshots**
One can be found where the issue was relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3638

**Versions**
https://github.com/NillerMedDild/Enigmatica6/blob/cad2140eab2accf9751bd88eb70a73bf308d2174/MODLIST.md?plain=1#L278

**Comment by P3pp3rF1y** [comment]
This can't be fixed without adding support to forge for both the stack that's eaten from and container to be returned at the same time. 
At this point any item that can stack and has container needs to add the container to player's inventory if it's not eaten fully yet. The other potential option would be to hack this logic into the method that handles putting items in player's inventory and potentially breaking other mods or if broken breaking stuff like player picking up items. Honestly both of these are significant changes for something as small as a few container items ending up in player's inventory so I am not planning to "fix" that.
