### ISSUE TITLE
Pickup and Wonderful enchants

### ISSUE THREAD

**Issue by HeavyDeception** [P3pp3rF1y/SophisticatedBackpacks#286]
**Describe the bug**
The pick-up upgrade does not work if you have a tool enchanted with [Telekinesis](https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments).

**To Reproduce**
1. install [Wonderful enchants](https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments) add Telekinesis to a tool.
2. add pickup upgrade to backpack.
3. mine a block
4. dose not work

**Expected behavior**
Items should go into the backpack.

**Screenshots**
N/A

**Versions**
3.8.1.384

**Comment by P3pp3rF1y** [comment]
Not a sophisticated backpacks issue if it's actually an issue at all - telekinesis just add items directly into inventory so they are not picked up by player. 
If you feel this is actually an issue you will need to report that to Wonderful Enchants and to fix they will need to call `EntityItemPickupEvent` which sbp uses to run its logic when items are picked up by player.

**Comment by HeavyDeception** [comment]
@P3pp3rF1y I reported it because dank null handles it just find I should have said that.

**Comment by HeavyDeception** [comment]
It's only the backpack that seems to miss the event.

**Comment by P3pp3rF1y** [comment]
well, unless I am totally blind Wonderful Enchantments doesn't call the event so there's nothing to handle there. And SBP pickup works only through this event so if it didn't handle it the whole pickup logic wouldn't work at all.

And I am guessing that you mean dank storage, looking at their code they just handle the event the same way SBP does and have no special implementation where they would be handling addition of stacks in player's inventory. So no idea what kind of magic would make these items be picked up in that case.

**Comment by HeavyDeception** [comment]
Thank you for the info I was able to fix it a inventory sort mob was confliting with your backpacks so I apologize.
