### ISSUE TITLE
Backpack hotkey not compatable with other mod

### ISSUE THREAD

**Issue by n0proxy** [P3pp3rF1y/SophisticatedBackpacks#288]
**Describe the bug**
When 'Just Enough Keys' 0.3.2 is installed (https://www.curseforge.com/minecraft/mc-mods/just-enough-keys), the backpack hotkey does nothing.

**To Reproduce**
1. Install both this mod and 'Just Enough Keys'
2. Leave the backpack hotkey on default 'b'
3. Do not use Just Enough Keys to change any controls/hotkeys.
4. When backpack is in inventory (or Curios slot), press 'b'.
5. Nothing happens.

**Expected behavior**
When pressing the backpack hotkey, the backpack inv should open and be shown.

**Versions**
SB version: 3.8.1.386
JEK version: 0.3.2
Forge version: 37.0.65

**Comment by P3pp3rF1y** [comment]
as far as I can see from source code this is because JEK hijacks vanilla logic and breaks `consumeClick` which sbp uses to check if the keybind was clicked

**Comment by P3pp3rF1y** [comment]
And actually based on this it needs to be fixed on JEK side so I am going to close here.
