### ISSUE TITLE
Mobs not dropping backpacks

### ISSUE THREAD

**Issue by n0proxy** [P3pp3rF1y/SophisticatedBackpacks#289]
**Describe the bug**
Killing mobs that are visibly wearing backpacks does not drop any backpacks.

**To Reproduce**
1. Install both Sophisticated Backpacks and Curios
(Without Curios, backpacks don't visibly show up on mobs for me. I submitted a separate ticket for that issue.)
2. Find mobs visibly wearing backpacks
3. Kill those mobs
4. Receive only regular mob loot

**Expected behavior**
Killing a mob that are shown wearing a backpack should (at least sometimes) drop a backpack.

**Versions**
SB version: 3.8.1.386
Curios version: 5.0.1.0
Forge version: 37.0.65

**Comment by P3pp3rF1y** [comment]
Just retested and they are. it's just a 12.5% chance by default without looting so you can't expect that every single one of them will
