### ISSUE TITLE
Experience pump upgrade not working.

### ISSUE THREAD

**Issue by opticGT** [P3pp3rF1y/SophisticatedBackpacks#290]
**Describe the bug**
exp pump not working

**To Reproduce**
use the exp pump upgrade on backpack

**Expected behavior**
take exp from player to backpack and back

**Screenshots**
![image](https://user-images.githubusercontent.com/19476801/140421368-f8e6f7d8-0c36-4ef6-9632-a2b23265af62.png)

**Versions**
sophisticatedbackpacks-1.16.5-3.8.1.384

**Comment by opticGT** [comment]
![image_2021-11-04_162732](https://user-images.githubusercontent.com/19476801/140429064-e60764d4-c907-4d0a-8146-fde6d471036d.png)
![Screenshot 2021-11-04 162410](https://user-images.githubusercontent.com/19476801/140429099-ed310dc4-6124-4090-a682-25b991e2f390.png)
what tank upgrade????? is there a tank upgrade???

**Comment by P3pp3rF1y** [comment]
yes there's a tank upgrade, which you for some reason seem to be missing there, but I can definitely see many people playing with this so it must be your pack or your config settings. check sophisticatedbackpacks config to make sure tank isn't disabled. But yeah you need the tank upgrade to have somewhere to store the experience liquid.

**Comment by GEORGO-HTML100500** [comment]
Greetings, respectable developer! Why is the Tank Upgrade missing from chests, even though the XP Pump chest upgrade is there? Why was Sophisticated Warden so cruelly castrated? How put it back in mod?
