### ISSUE TITLE
Backpacks not sticking to filter upgrade.

### ISSUE THREAD

**Issue by HeavyDeception** [P3pp3rF1y/SophisticatedBackpacks#296]
**Describe the bug**
When you have more than one Backpack in a backpack with the Inception Upgrade. The bags in the Inception bag will just allow random stuff in them sometimes and not obey any filters they have on them.

**To Reproduce**
1. Make an Inception Backpack set setting to use inventory in subbackpacks first.
2. Make 2 subbackpacks with filters.
3. pick up random stuff and filtered stuff.
4. See the error

**Expected behavior**
All things should go into the correct backpacks.

**Screenshots**
An image doesn't really show what's going on.

**Versions**
Forge - 36.2.4
Soph. Backpack - 1.16.5-3.11.1.390

**Comment by P3pp3rF1y** [comment]
well to be able to figure this out best would be to see images of upgrades and their settings in those backpacks and what ended up in them. This way there's not much I can do as I don't even know how to recreate. 
I need questions answered like 
- where is the upgrade that picks up stuff pickup/magnet what are its settings
- by filters I assume you mean that you are using Filter Upgrades in those backpacks? what are they set to?

**Comment by HeavyDeception** [comment]
Right didn't think about that when I get home I will take some images but I have the adv pick up one installed.

**Comment by HeavyDeception** [comment]
[Main Backpack](https://puu.sh/InVyp/483ba82bed.png), [Inception Setting](https://puu.sh/InVAR/43cbf63dd3.png)
[Sub-Backpack Plant/Mob Drops](https://puu.sh/InVzJ/797fbb0844.png)
[Sub-Backpack Ore](https://puu.sh/InVAm/0f0b178566.png)

**Comment by HeavyDeception** [comment]
@P3pp3rF1y There ya go Plz let me know if there is anything else I can get you.

**Comment by P3pp3rF1y** [comment]
your issue is the pickup upgrade in main backpack - it basically uses all of the main backpack and all subpackacks inventories as one huge inventory so it matches everything against this huge inventory and then puts stuff in that huge inventory.

There's actually a way to prevent it from doing that to those individual backpacks by using Filter Upgrade to limit what can make it into them. Just at the moment filter upgrade doesn't have match by contents functionality (planned feature) so you would need to match by items / tags.

**Comment by HeavyDeception** [comment]
I tried matching by tag and item still doing it.

**Comment by P3pp3rF1y** [comment]
But are you matching by tag in filter upgrade (not pickup) in subbackpack?

**Comment by HeavyDeception** [comment]
Yes I changed it to that before I sent in the ticket.

**Comment by P3pp3rF1y** [comment]
could you show me screenshot of that filter settings together with backpack it's in

**Comment by HeavyDeception** [comment]
[Sub-Ore](https://puu.sh/Ioocl/b15b0b5a55.png), [Sub_Drops /Seeds](https://puu.sh/IooeQ/01a14eb15e.png) and, [The Main Bag](https://puu.sh/Ioofg/d57cce2363.png). Main bags [Inception settings](https://puu.sh/IoofE/baad17cc5d.png).

**Comment by P3pp3rF1y** [comment]
As I said before you need to use Filter upgrade and not pickup upgrade in subbackpacks if you want to filter what Pickup upgrade in the main backpack can put in there. The way you have it setup you basically have pickup upgrades in subbackpacks picking up correct things but the one in the main can still use any backpack to put anything in there.
