### ISSUE TITLE
Small cosmetic problem

### ISSUE THREAD

**Issue by zanecek** [P3pp3rF1y/SophisticatedBackpacks#298]
**Describe the bug**
Small display problem with Visiblearmorslots mod.
https://www.curseforge.com/minecraft/mc-mods/armor-slots-in-other-inventories

**Expected behavior**
Could you show the left tabs a few pixels upper, please?
Or client config?
Thx.

**Screenshots**
<img width="901" alt="2021-11-11_01 48 17" src="https://user-images.githubusercontent.com/62807156/141232479-7b519428-950b-44c7-96eb-684fbaa415f0.png">

**Comment by DJJolty257** [comment]
Dosen't VisibleArmorSlots have a config?
Maybe check using Create or the mod menu in Forge

**Comment by zanecek** [comment]
Only left or right slot side and left<->right fine move, see:
--------------------------
on_debug = false
debug_as_level_info = false
#Allowed Values: LEFT, RIGHT
slots_side = "LEFT"
#Range: 0 ~ 128
slots_margin = 2
swap_hands = true
blacklisted_screens = ["curios"]
----------------------

**Comment by P3pp3rF1y** [comment]
to be honest I considered this one a low priority and seeing that the mod in question isn't even getting updated to 1.18 I am going to just close
