### ISSUE TITLE
Smelting upgrades don't smelt

### ISSUE THREAD

**Issue by Wakatsu** [P3pp3rF1y/SophisticatedBackpacks#300]
Neither Smelting, nor Auto-Smelting upgrades work when loaded. Auto-Smelting upgrade picks up ores and fuels into slots, but then the items just sit there and nothing happens as if wrong type of items being loaded in (I tested it with all kinds of ore and fuel, including purely vanilla iron ore and coal)

1. Open backpack
2. Click on 'Smelting \ Auto-Smelting' tab
3. Load fuel and ore to smelt
4. See error of nothing happening

Expected behavior - ores would be smelt into ingots

Version 1.16.5-3.11.1.390

The game doesn't crash from this bug, so no crashlog, let me know if there is some other method of providing more info for you. Here's my regular mod loadout https://i.imgur.com/xHKd62D.png
I tried to locate potential mod conflicts by removing mods in halfs, but it seems no matter how much I remove the problem remains.

**Comment by Kalastra** [comment]
I am getting this as well in a custom modpack based on Enigmatica 6 (1.16.5 - 36.2.9). The conflict I have found is with [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph) (1.16.5-0.27 in the post above, and I have tested 0.29 and 0.30): smelting does not occur with only Sophisticated Backpacks and Polymorph installed even though the items enter the correct slots.

**Comment by P3pp3rF1y** [comment]
Looks like you will have to report this one to Polymorph - they have an integration with sophisticated backpacks (definitely for the smelting upgrades) that likely is causing this.

**Comment by TheIllusiveC4** [comment]
This should be fixed in the latest Polymorph (1.16.5-0.31).

**Comment by Wakatsu** [comment]
And it really is, just tested it. Thanx!

**Comment by P3pp3rF1y** [comment]
thanks @TheIllusiveC4 !

**Comment by Rykst3r** [comment]
I have this bug in 1.18.2. It will let me put in fuel, but it won't let me put in any smeltable items. Polymorph is not installed, so what could be the problem?
