### ISSUE TITLE
Auto-smelt

### ISSUE THREAD

**Issue by ChisleLP** [P3pp3rF1y/SophisticatedBackpacks#306]
**Describe the bug**
The Auto-smelt just doesn't work at all, it set to ON and i added filter example Gold ore and some raw food, it has coal, but it just doesn't burn at all. 
Im using the "All the Magic Spellbound" mods pack. And this mods has in it.

**To Reproduce**
1. Open backpack
2. Click on 'auto-smelt' tab
3. Add Gold Ore filter
4. Shift click gold ore from inventory to backpack and it will transfer automatic to Auto-Smelt
5. It doesn't burn at all, even it has coal.

**Expected behavior**
Burning and getting ingot of course. ^^

**Screenshots**
https://i.ibb.co/f4LQX7f/buuuurrrrnnn.png
**Versions**
Honestly, no clue. Its the "All the Magic Spellbound" modspack.

**Comment by P3pp3rF1y** [comment]
Check if you have Polymorph mod in the pack and update it to the latest version that should fix it.

**Comment by ChisleLP** [comment]
Seems it has include, but it doesn't tell which version is it.
https://www.modpackindex.com/modpack/38149/all-the-magic-spellbound-atms

**Comment by P3pp3rF1y** [comment]
well, just update to the latest and that should fix it
