### ISSUE TITLE
Auto Smelt Does not work (No Polymorph)

### ISSUE THREAD

**Issue by Anonimase** [P3pp3rF1y/SophisticatedBackpacks#309]
**Describe the bug**
I have items in both the fuel and the input slot of the auto smelt upgrade, nothing is happening. They are both allowed on the white list. The normal smelter works

**To Reproduce**
1. Open backpack
2. Put Fuel and Smeltable in auto smelter
3. Nothing Happens

**Expected behavior**
1. Open backpack
2. Put Fuel and Smeltable in auto smelter
3. Smeltable gets smelted

**Versions**
1.16.5-3.11.1.390.      I am on the Mythic Satus modpack on curse

**Comment by P3pp3rF1y** [comment]
That modpack includes Polymorph so just update that mod and you should be all set.

**Comment by Anonimase** [comment]
Ah, crap, sorry about that. I must have glossed over that because I expected it to be in alphabetical order. Sorry again, and cheers
