### ISSUE TITLE
Backpack Magnet & Pickup Upgrades Putting Items in Inventory, Not in Backpack/s

### ISSUE THREAD

**Issue by Morabert** [P3pp3rF1y/SophisticatedBackpacks#311]
**Describe the bug**
Since the last few updates _Sophisticated Backpacks_  _Magnet_ & _Pickup_ Upgrades (Basic & Advanced) no longer puts items in the backpack or the nested backpacks but instead puts them in the player inventory. 

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Have backpack equipped
2. Have Single or Nested Backpacks
3. Have _Magnet_ &/or _Pickup Upgrade_ Equipped
4. Items will will Hotbar & Player inventory
**Expected behavior**
This has been Consistent since the latest update, Early November/Later October the Upgrades were working as intended.

**Versions**
sophisticatedbackpacks-1.16.5-3.11.1.390
Forge 36.2.5
Java JDK 16.0.2

**Comment by P3pp3rF1y** [comment]
well, they don't put anything in player's inventory, I know that because the code hasn't changed and I am playing with that version myself and it definitely puts items in backpacks. 

So what's likely happening for you is that you have another magnet that does this

**Comment by Morabert** [comment]
I don't  have magnet rings or even curios installed. It's happening with stones & ores but not with player items such as tools

**Comment by Morabert** [comment]
> well, they don't put anything in player's inventory, I know that because the code hasn't changed and I am playing with that version myself and it definitely puts items in backpacks.
> 
> So what's likely happening for you is that you have another magnet that does this

It turned out to be a random enchantment from _Charm_, namely: **"Acquisition"**
