### ISSUE TITLE
[1.16.5] Pickup upgrade not working in Curios slot

### ISSUE THREAD

**Issue by vizthex123** [P3pp3rF1y/SophisticatedBackpacks#312]
**Describe the bug**
It's in the title, the upgrade doesn't work when in the Curious slot (back).

**To Reproduce**
1. Equip in Curios slot with a filtered pickup or magnet upgrade
2. Pick up the filtered items

**Expected behavior**
Picking up the item

**Screenshots**
N/A

**Versions**
Mod: 3.11.1.390
Forge: 36.2.4
Minecraft: 1.16.5

EDIT: Also not working when in inventory.

**Comment by vizthex123** [comment]
Nevermind, by default it's a blacklist. Should be a whitelist by default though, so I'll leave this issue open in case you plant to change it.

**Comment by P3pp3rF1y** [comment]
no plan to change it, it is that way so that by default it picks up everything.
