### ISSUE TITLE
[1.16.5] Very odd tooltip bug - it spams the screen with random info.

### ISSUE THREAD

**Issue by vizthex123** [P3pp3rF1y/SophisticatedBackpacks#313]
**Describe the bug**
It's in the title.

**To Reproduce**
1. View the tooltip, doesn't seem like equipped gear or anything changes the issue.

**Expected behavior**
A normal tooltip.

**Screenshots**
![image](https://user-images.githubusercontent.com/31721920/142976179-ba33a437-c2ec-49f7-b58a-6d177087195e.png)

**Versions**
Mod: 3.11.1.390
Forge: 36.2.4
Minecraft: 1.16.5

**Comment by P3pp3rF1y** [comment]
This is not happening with the mod by itself or in Enigmatica 6 modpack that I play so I will need information from you on what other mod needs to be in pack for this to happen.

**Comment by vizthex123** [comment]
It's in my Netherium modpack: https://www.curseforge.com/minecraft/modpacks/netherium

There's like 150 mods, but I guess it could be Curio? Maybe Create? This wasn't an issue until recently though.

**Comment by P3pp3rF1y** [comment]
it's neither of those mods but I can see Equipment Compare in the mod dependencies so similar to the other ticket linked here you will need to report this bug there as their code conflicts with Forge's one.
