### ISSUE TITLE
Backpack deleting my items when sorting out

### ISSUE THREAD

**Issue by Klouver-github** [P3pp3rF1y/SophisticatedBackpacks#330]
**Describe the bug**
anytime I assort my items in the backpack which I am using a Diamond tier, the items lower erases/deletes it.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Install latest quark with latest sophisticated backpacks
2. open the backpack
3. press sort items
4. items will be erased and not show even if re-open world
**Expected behavior**

**Screenshots**
I dont have a screenshot to show proof and not wanting to lose more of my items

**Versions**
Forge 1.16.5-36.2.19

**Comment by P3pp3rF1y** [comment]
Sort items is the Quark sort button right?

It doesn't work well with the new logic in backpacks and yet backpacks already have sort functionality which works without an issue. 

So you should disable these buttons in quark config using:

`"Ignored Screens" = ["net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen"]`

**Comment by Mi6kbuttface** [comment]
> 
Sort items is both Quark and Inv Tweaks features, I mainly use Inv Tweaks which does a better job sorting items by tags. And this also deletes items. I can provide a short video of the deleting bug if you want.

**Comment by Klouver-github** [comment]
> > 
> Sort items is both Quark and Inv Tweaks features, I mainly use Inv Tweaks which does a better job sorting items by tags. And this also deletes items. I can provide a short video of the deleting bug if you want. 

I say yes show a video, cause I am not wanting to lose my items i worked for and manage to get that's some are not craftable

**Comment by P3pp3rF1y** [comment]
@Mickbuttface I am using inventory tweaks all the time in dev and that one doesn't delete items for me - it uses a different way to interact with items than Quark. And as far as I can see I have been using the latest version of that mod for a very long time. So definitely need to see a video or get exact steps how to replicate inventory tweaks deleting items during sort.

**Comment by kyleminto97** [comment]
I had the same issue, turns out when you sort your player inventory, the glitch occurs with the backpack and it deletes loads of random items. I didn't notice at first and I've spent around an hour accidentally clearing all ores I collected

Anyway, here's a quick video - https://streamable.com/pmketu

**Comment by P3pp3rF1y** [comment]
@KyleMinto97 what button did you press there to sort? and isn't it bound to Quark sorting? And if so did you actually test it with one of the the two latest versions of SBP?

**Comment by kyleminto97** [comment]
@P3pp3rF1y I was clicking the middle mouse button, I believe that's the default binding for sorting inventories. I'm actually using a mod pack called Chroma Technology 2 which uses version **1.16.5-3.12.0.407**. I'll try with the newest version when I'm back and home and I'll update you 🤙

**Comment by P3pp3rF1y** [comment]
so that looks like what you have keybind tied to is Quark sorting and because you are using the version before sorting fix you're seeing stacks delete, nothing like that should happen with the latest version
