### ISSUE TITLE
[1.16.5] Quark Easy Transfering button strangeness/duplicate/not working

### ISSUE THREAD

**Issue by drakray** [P3pp3rF1y/SophisticatedBackpacks#332]
**Describe the bug**
Following update from 407 to 420, Easy Transfering duplicate item when pulling from SBP, and inserting just don't work

**To Reproduce**
1. Open backpack
2. Click on Quark Easy Transfering Button
3. Nothing happen

**Expected behavior**
To work as intended, it did before

**Versions**
MC 1.16.5
Forge 36.2.19
Quark 2.4.321
Buncha others

**Comment by drakray** [comment]
Duplicate occur for all items that are pullable: everything it can starting from the last on regular Click, only what is in player's inventory on Shift-Click

**Comment by P3pp3rF1y** [comment]
yup, looks like trying to prevent deletion of items in sorting makes the restock logic duplicate items because it doesn't check if it was able to extract items from the backpack's inventory

**Comment by P3pp3rF1y** [comment]
I am going to replace the Quark logic there with my own so that it would not only not duplicate and properly extract but that it would also work the other way around

**Comment by P3pp3rF1y** [comment]
Latest version on CF fixes this - the buttons now do what they are supposed, just keybinds won't work which is a limitation I cannot work around without having a change made in Quark.
