### ISSUE TITLE
Crash with using Advanced Compacting Upgrade with Pickup Upgrade

### ISSUE THREAD

**Issue by Kalavika** [P3pp3rF1y/SophisticatedBackpacks#336]
Crashed when I picked up the coal with stack.
When I reboot and check my inventory, it is properly compressed, but crashes every time.

**To Reproduce**
1. Open backpack
2. Set Pickup&Advance Compacting upgrade 
3. Set coal to both filter then pickup enough coal to make block

Forge version:
1.18-forge-38.0.15

Using mod:
sophisticatedbackpacks-1.18-3.12.1.427.jar
curios-forge-1.18-5.0.2.4.ja

[crash-2021-12-08_01.25.42-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7669984/crash-2021-12-08_01.25.42-server.txt)

**Comment by Kalavika** [comment]
This happened when I picked up a large amount of coal without any coal and coal blocks in my backpack, just set to filter.
I close here.

**Comment by P3pp3rF1y** [comment]
Reopening as this is issue I have fix for that is yet to be released

**Comment by P3pp3rF1y** [comment]
this is now fixed with the latest release
