### ISSUE TITLE
Crash when pickup item

### ISSUE THREAD

**Issue by DrSigma4164** [P3pp3rF1y/SophisticatedBackpacks#337]
**Describe the bug**
When my character picks up an item that is in the upgrade collection list and also when that item is in the compression list the game crashes.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Insert Advanced_Pickup_Upgrade and Advanced_Compacting_Upgrade.
3. Adjust upgrade to specific items
4. Try to pick up a customized item, and such a quantity that they can be compressed into a block, such as 9 bars of iron.
5. See error

I don't know for sure which item is crashing
Log:
[latest (2).log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7675637/latest.2.log)

 

**Versions**
Minecraft: 1.16.5
Forge: 36.2.8
Mod Version: 3.12.1.422

**Comment by P3pp3rF1y** [comment]
that log doesn't mention sophisticatedbackpacks not even once, but I am judging by your description that this is the same issue that was reported for 1.18 in #336 and I am just about to get a fix for that released

**Comment by P3pp3rF1y** [comment]
this is now fixed with the latest release
