### ISSUE TITLE
Game crash upon loading into world. Appears to be caused by the mod and I am unsure why.

### ISSUE THREAD

**Issue by DJJolty257** [P3pp3rF1y/SophisticatedBackpacks#340]
**The bug?**
Game crashes when entering a world.
[crash-2021-12-09_15.05.19-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7688480/crash-2021-12-09_15.05.19-server.txt)

- I am not sure why this occurs, but it has been occurring upon loading a world since I updated. I've tried downgrading but that is making it worse. Running the game without Sophisticated Backpacks seems to be working fine, but I want my backpacks.

**Versions**
Minecraft 1.16.5, Forge 36.2.19

**Comment by DJJolty257** [comment]
Edit: Seems to be the world I was using to test; it was broken. Just in case, it might be a decent idea to look into it. Please let me know what went wrong!

**Comment by P3pp3rF1y** [comment]
this is really odd - so a recipe tag doesn't seem to be properly loaded which should normally happen during game load even before world is started I have no idea why that would be but that is invalid state and would cause crashes even if just crafting in crafting table. So I am calling this a modpack issue, but if you can recreate with sophisticated backpacks and minimal set of mods and you will have exact steps how to recreate as well I will take a look. Anyway I am going to close this now given what I see in stack trace and what you said about broken world.
