### ISSUE TITLE
Liquids multiply if containers are stackable.

### ISSUE THREAD

**Issue by MechaJeb** [P3pp3rF1y/SophisticatedBackpacks#341]
**Describe the bug**
If you have a stack of empty containers, in this case Seared Tanks from Tinkers Construct, and you have, for example 4 buckets of lava in your backpacks liquid tank, and it's set to Output, all of the containers in the stack get filled with 4 buckets each, thus multiplying liquids. The opposite is true if the backpack is set to Input, and the stack of containers are full of liquid.

Info on what other mods you're using that may cause a conflict here if applicable.
Tinkers Construct.

**To Reproduce**
1. Have some liquid in the backpacks tank, set to output.
2. Have a stack of Tinkers Construct seared tanks in hotbar.
3. Watch them all get filled. 

**Expected behavior**
Not that.

**Versions**
MC 1.16.5, mod version 3.12.2.422

**Comment by P3pp3rF1y** [comment]
fixed in latest release
