### ISSUE TITLE
[1.18 Bug] Tool swapper upgrade is swapping tools to inexistence

### ISSUE THREAD

**Issue by grekdawid26** [P3pp3rF1y/SophisticatedBackpacks#347]
**Describe the bug**
Tools swapper upgrade fails to put the tool (the one it is replacing) into the backpack when first empty slot is set to "remember its content".

_(I experienced it with the "Advances tool swapper", and "Golden backpack", but I assume the code that replaces the tool is the same.)_

**To Reproduce**
1. Open backpack
2. Put some tools into first couple slots
3. Go to settings, remember those tools
4. Move (from backpack to inventory) or drop one of those remembered tools (to make an empty remebered slot)
5. Put some tool (that is not one of the remembred ones) into your hand
6. Try triggering the tool swap (ex. if you put a shovel into your hand, and try mining stone, assuming you have pickaxe in your backpack)

**Expected behavior**
Not this. Idk... maybe to see my diamond pickaxe in the backpack after the tool swap...

**Screenshots**
_(I think I described it pretty well)_

**Versions**
1.18-forge-38.0.17
sophisticatedbackpacks-1.18-3.12.1.433

**Comment by P3pp3rF1y** [comment]
fixed in latest release
