### ISSUE TITLE
1.17.1 players cannot access LAN game while having a backpack in Curios slot

### ISSUE THREAD

**Issue by itkminer** [P3pp3rF1y/SophisticatedBackpacks#348]
**Describe the bug**
We're using a single player world as a private family "server" at home via OPEN to LAN option. Sophisticated Backpacks seem to work just fine on its own even with the Curios mod running, but once there is interaction between Curios and Sophisticated Backpacks it gets complicated. The single player world works fine and the owner can use Sophisticated Backpacks with Curios as intended. The back slot works. However for all other members that join via LAN the following problem arises :
Once a backpack is in the Curios Back Slot the player can never again connect to the world while the two mods are running (actually the owner can see the player connect only to get kicked out immediately) - there are different error messages, the most common one is "java.net.socketexception : connection reset". The only way to get the player back into the world is to load the world without Curios (which means losing all equipped backpacks and their contents of course). 

By the way, as long as the backpacks are in the inventory of the players and not in the curios back slot the game seems to work as intended, everyone can log out and back in without issues.

Info on what other mods you're using that may cause a conflict here if applicable.

This happens in a fresh test world where the only mods running are Sophisticated Backpacks and Curios.

**To Reproduce**
1. Open a single player world to LAN with Curios and Sophisticated Backpacks installed. It will work just fine for the owner, you need to join with a second player to see the bug.
2. Join the world with a second character, create a backpack and equip it to his back slot from Curios.
3. Leave the world. Don't log out your first player, keep the world running.
4. Try to reenter the world.

**Expected behavior**

Well, you should be able to log back in with a backback in your Curios back slot ....

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases

Playing on Forge 37.1.1 (also tested on 37.1.0) with Sophisticated Backpacks 3.12.1.418 and Curios 5.0.2.2 (or .3 or .4, same thing happens for all three versions).

**Comment by P3pp3rF1y** [comment]
I tried quickly debugging this and it seems to happen when curios sends one of its packets and I also found that someone else had similar issue in a pack that has curios, but doesn't have Sophisticated Backpacks https://www.reddit.com/r/MinecraftHelp/comments/pwcqio/i_am_at_a_complete_loss_with_this_1171_modded_lan/ 

Could you try the same without sophisticated backpacks but one of the mods that use curios slots and see if you get the same issue?

**Comment by itkminer** [comment]
Yeah, good call. Same thing happens when isolating Curios with Statues in a fresh test world. So it‘s a Curios issue, but consequences for Sophisticated Backpacks are potentially really huge, you might lose an awful lot of stuff. There should be a temporary warning somewhere I guess.

**Comment by P3pp3rF1y** [comment]
Well, this seems to happen only with LAN game not for a dedicated server and should really be fixed by curios fairly quickly I would hope. Anyway I can see that you have logged this issue over there so I am going to close here.

**Comment by itkminer** [comment]
Sure, thanks for having looked into this!
