### ISSUE TITLE
Crashes Server when dispensing it using a downward facing dispenser

### ISSUE THREAD

**Issue by Testingmofo** [P3pp3rF1y/SophisticatedBackpacks#349]
**Describe the bug**
Title Says it all

[Crash file paste.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/7718324/Crash.file.paste.txt)

**To Reproduce**
1. Place a dispenser facing downwards
2. Put bag inside
3. Power the dispenser with any redstone
4. See error Exception ticking world

**Expected behavior**
Server Crash with Exception ticking world

**Screenshots**
N/a

**Versions**
1.18

**Comment by P3pp3rF1y** [comment]
fixed in latest release
