### ISSUE TITLE
No Sort Slot/Slot Memory issue

### ISSUE THREAD

**Issue by Modeeves** [P3pp3rF1y/SophisticatedBackpacks#350]
**Description**
The pickup/magnet upgrade isn't working when No Sort Slot/Slot Memory is empty.
Not sure if this is normal.

**Reproduce Steps**
1. Open backpack
2. Choose an item to be "not sorted" and/or be a "Slot Memory" in the backpack.
3. Equip the "Magnet Upgrade"
4. Remove an item from "No Sort Slot/Slot Memory" or leave it blank.
5. Magnet nor Pickup Upgrade will not pick up anything as long as the "No Sort Slot/Slot Memory" is empty or blank.

**Expected behavior**
Shouldn't it still pick up items while avoiding the "No Sort Slot/Slot Memory" to be filled by something else?

**Screenshots**
Not applicable

**Versions**
Sophisticatedbackpacks-1.16.5-3.12.2.432
Forge version: 1.16.5 - 36.2.22

**Comment by P3pp3rF1y** [comment]
Just tested this exact flow and works as expected - items just get picked up / put into backpack. So I will need more information on how to recreate exactly and screenshot of the settings of pickup / magnet and the backpack contents may be helpful here

**Comment by P3pp3rF1y** [comment]
actually found a bug in insert logic so I know how to recreate this and will be fixed in the next release

**Comment by P3pp3rF1y** [comment]
fixed in latest release
