### ISSUE TITLE
Unkillable witch in 1.18

### ISSUE THREAD

**Issue by aAndrew3030** [P3pp3rF1y/SophisticatedBackpacks#352]
**Describe the bug**

A witch ended up in my base, wearing the backpack and playing music. Unfortunately it had infinite potions and 78 health with no way to kill it as it just healed back to full health instantly 

**Expected behavior**
Mob that is killable

**Versions**
1.18-3.12.1.433

**Comment by P3pp3rF1y** [comment]
I am sure the potions were not infinite as SBP "only" applies 30 mins of potions. Would you be able to tell what potion effects it had (perhaps you're using The One probe)? Also what weapon have you used to kill it? Netherite enchanted with highest level enchants?

**Comment by aAndrew3030** [comment]
Okay, I obviously didn't wait long enough then. It is unable to be killed during those 30 minutes though. Not sure if that is intended. I used spawn eggs to spawn another, and the effects it had were Regeneration 4, Absorption 3, Fire Resistance 3, Resistance 4, and Strength 3. I used the Create mod saw, lava fan, Cyclic spikes, and a netherrite sword with attack damage of 12 (sharpness 7 and sweeping edge 3) all at once. 
![2021-12-17_08 53 46](https://user-images.githubusercontent.com/84727133/146594886-82a76149-c9f4-4f37-88d4-639dd549f3b2.png)

**Comment by aAndrew3030** [comment]
![2021-12-17_14 04 17](https://user-images.githubusercontent.com/84727133/146595257-2d8a107b-9bd7-4b97-8dbf-eb933f965760.png)

**Comment by P3pp3rF1y** [comment]
wow, that's quite a bit of damage given that it actually should be hard to kill, but still killable with top tier equipment in vanilla. 
It shouldn't be getting level 4 of regen. I will check that part of the code but level 3 should be max. And I am suspecting that on top of this regen the witch does its own regen so in this case it may really be unkillable

**Comment by P3pp3rF1y** [comment]
just released a modified version that shouldn't allow this high resistance and regeneration
