### ISSUE TITLE
Left shift not showing any items 

### ISSUE THREAD

**Issue by lalamas97** [P3pp3rF1y/SophisticatedBackpacks#356]
Hello , I have had this problem for a quite a while . I have downloaded Better Minecraft modpack for 1.16.5. I have started playing it and everything was perfectly fine with Sophisticated backpack . When I clicked left shift I could see all of my items in my backpack. Then out of nowhere one day I stopped seeing any items . The whole frame , where I could see my items shifted out of the screen . The only thing I can see right now is : contentsUuid and some number . I can not see any items . Right now I am playing on the version 1.16.5-3.7.0.378 . 
Can somebody please help me Fix this problem ? 
![Uploading 27D7087D-C9B7-491B-AE18-BA3247718C7C.jpeg…]()

**Comment by lalamas97** [comment]
![2461929A-5A5A-41FB-B78F-8CEDF6128B5D](https://user-images.githubusercontent.com/96323655/146626409-a27e2b32-d9e1-4469-bd96-157c56f2ef28.jpeg)

**Comment by P3pp3rF1y** [comment]
that looks like you have full nbt being displayed and perhaps even more than that - sounds like a mod adds this functionality and maybe it adds it to just advanced tooltips. try F3 + h and see if it goes away

**Comment by lalamas97** [comment]
Oh my Yes ,it worked . Thank you so much

**Comment by P3pp3rF1y** [comment]
You're welcome and closing this ticket...
