### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by Congraz8961** [P3pp3rF1y/SophisticatedBackpacks#359]
Hallo there.

I do not detect errors on the console when I am in the game and using a backpack. But when I start the server or restart the server, this error occurs on the console. I have no idea why.

I don't use any other mods other than:
Goblins and Dungeons Mod
Bountiful Mod

Screenshot:
![image](https://user-images.githubusercontent.com/56209437/147154061-531a6132-4a42-48d4-b364-7ce8dc20f1dd.png)

SophisticatedBackpacks version: 1.16.5-3.12.0.407
Forge version: 1.16.5-36.2.20

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
