### ISSUE TITLE
Issue with tank upgrade bricking backpack

### ISSUE THREAD

**Issue by Xtraite71** [P3pp3rF1y/SophisticatedBackpacks#366]
I have encountered a problem where a backpack that has the tank upgrade and any amount of fluid will become useless. 

I tried water and creosote oil (I.E.) and while i can add, view, and remove the fluid, If i shift click the backpack with an open slot, my character is holding "air" and I cannot open the backpack. I can replace it on the ground, and right click and it performs like normal. Removing the fluid doesn't work, and removing the upgrade also doesn't work. (gold backpack if that matters)

I was able to fix the issue by breaking the backpack with an iron pick. It then works correctly until I place it on the ground again. 

I am using the follow versions

S.B. - 1.18.1-3.14.3.485
Forge - 39.08
Minecraft - 1.18.1

![Uploading 2021-12-26_00.11.27.png…

![2021-12-26_00 11 15](https://user-images.githubusercontent.com/96675181/147399775-e77905e4-73f8-46d8-b157-35fcbebd80ab.png)
![2021-12-26_00 11 20](https://user-images.githubusercontent.com/96675181/147399777-3fc44198-cacf-4677-b27d-0409f3f94633.png)

**Comment by Xtraite71** [comment]
![2021-12-26_00 11 27](https://user-images.githubusercontent.com/96675181/147399893-4cb4960c-648d-4287-8dd7-13ab3c681c94.png)


My screen shots got messed up. Sorry!

**Comment by P3pp3rF1y** [comment]
I am unable to recreate this so I assume that you use this in a modpack (judging by that tank in the view very likely). Could you narrow this down to minimal set of mods that are still causing this issue?

**Comment by Xtraite71** [comment]
Ah, yep, idk why I didn't think to do that. It is the "carry-on" mod. I had the keybind for Carry-On set to left shift as with the backpack and that was causing the issue. Changed the bind and now its working perfectly!

Thanks for a great mod!
