### ISSUE TITLE
Crash from conflict between 3.15.0.494 and Polymorph

### ISSUE THREAD

**Issue by Syampuuh** [P3pp3rF1y/SophisticatedBackpacks#374]
**Describe the bug**
When loading a world with the most recent version of Sophisticated Backpacks and [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph), the game hangs and crashes. It would appear this is related to the new blasting/smoker upgrades.
https://pastebin.com/raw/TWgY6gD4

**To Reproduce**
1. Install [Polymorph ](https://www.curseforge.com/minecraft/mc-mods/polymorph)alongside Sophisticated Backpacks 3.15.0.494
2. Create or load into any world
3. Freeze and crash

**Versions**
 - Forge 39.0.9
 - Sophisticated Backpacks 3.15.0.494
 - [Polymorph 0.33](https://www.curseforge.com/minecraft/mc-mods/polymorph/files/3578522)

**Comment by ModernGamingWorld** [comment]
Just ran into this same issues

**Comment by P3pp3rF1y** [comment]
You will need to report this issue to Polymorph there needs to be a change made on their side to support new internals of SBP. I have already pinged C4 about this but better to have a ticket in their tracker for this as well. Anyway closing as this is not an issue that can be fixed on SBP side.
