### ISSUE TITLE
Crash on 1.16.5

### ISSUE THREAD

**Issue by SheReyy** [P3pp3rF1y/SophisticatedBackpacks#377]
**Describe the bug**
Got a crash.
[Here](https://gist.github.com/IamRyan30/cc66f6f69607af74c8232f211f403556)'s the latest log.
[Here](https://gist.github.com/IamRyan30/63b683359acadd565ac15d91f1108e6c)'s the mod list.

**Versions**
Mod Version: sophisticatedbackpacks-1.16.5-3.15.0.493.jar
Forge Version: 36.2.4
Curios version: curios-forge-1.16.5-4.0.6.8.jar

**Comment by P3pp3rF1y** [comment]
just update polymorph to the latest version and your issue is resolved
