### ISSUE TITLE
Make it impossible to switch off stacking upgrade

### ISSUE THREAD

**Issue by Ko0oin** [P3pp3rF1y/SophisticatedBackpacks#387]
I had a problem with the mod, a part of my inventory in a backpack disapeared and i found out the problem; 
i had a lot of stacks of wood (with a stacking upgrade tier 2) and i didn't know there were a keybind to switch off upgrades, so i inadvertently pressed it and it turned off the stacking upgrade. Next i opened my backpacks, didn't understand what the fuck was going on with all the wood blocks not being stacked and pressed sort, which made a part of the inventory vanish because of the lack of space .

So yeah, please make it impossible to switch off stacking upgrade T_T

**Comment by P3pp3rF1y** [comment]
Already fixed in the latest version of the mod
