### ISSUE TITLE
Issue with bundles mod

### ISSUE THREAD

**Issue by Dreea11** [P3pp3rF1y/SophisticatedBackpacks#4]
Hello! I don't know if the issue is on your side but i encountered a compatibility problem between your mod and the Bundles! mod https://www.curseforge.com/minecraft/mc-mods/bundles-mod
The bundles should be showing the items they contain on hover, however this doesn't work when the backpack interface is opened. It still works as intended when i open the normal inventory.
I am playing on 1.16.3 with both backpacks (v 0.9.2.70) and the Bundles! mod (v 1.3). Curios API is version 4.0.3.0

Thank you! (really enjoying this mod!!)

**Comment by P3pp3rF1y** [comment]
So I have looked into this. It looks like bundles mod is relying on an event to be triggered, which as far as I have tested sophisticated backpacks doesn't block and it still gets triggered allowing other mods to react to it. So I don't really see anything wrong on my side. And I don't have time to debug someone else's mod to figure out what may be going wrong there. So I am going to close this one and please report it to them if they find something wrong with SB please let me know and feel free to reopen this issue.
