### ISSUE TITLE
Everlasting

### ISSUE THREAD

**Issue by BishopBone** [P3pp3rF1y/SophisticatedBackpacks#401]
Hey, I had a gold uncolored backpack with everlasting on it. I put it down on the ground, added the everlasting, but when I broke it to pick it up it just had some green sparkles and disappeared. I have xaero's minimap and it shows a red dot indicating there's something on the ground at that spot, but whenever I walk over it the dot disappears and I don't pick anything up. I'm not sure how I'm suppose to get this back. I have the 1.18.1 version.

**Comment by P3pp3rF1y** [comment]
this looks like a conflict with another mod - I just tested in game with the latest version and the backpack is properly dropped, shows both the backpack itself and the particles and can be picked back up. So I will need you to narrow this down to what mod is causing this and then I can look into whether there's some issue on my side.

**Comment by BishopBone** [comment]
Thanks for checking. I'll check which mod is causing the problems later this week.

**Comment by BishopBone** [comment]
Hey, sorry for the false flag. I tried to recreate it in a new world and couldn't make it work. It somehow popped up about 20 blocks above me in my original world.

**Comment by P3pp3rF1y** [comment]
ohh right, that would be the bug that's related to the new world depth in 1.18 which I need to fix - basically the code that saves your backpack from falling into void still uses the old world depth and tries to bring the backpack to y level 1 instead of only triggering this logic at level -64 and below

**Comment by P3pp3rF1y** [comment]
This is now released
