### ISSUE TITLE
Unable to open backpacks within backpacks after setting a new keybind to a mouse button [Minecraft 1.18.1 - Version 3.15.1.505]

### ISSUE THREAD

**Issue by VolcanicMG** [P3pp3rF1y/SophisticatedBackpacks#407]
With the default button to open backpacks set to "b", when opening backpacks, I am able to open up backpacks within backpacks, but when I want to change the button to let's say "button4" (Mouse button) It won't let me open up backpacks from the backpack anymore (It will still let me open the main backpack though)

**Comment by P3pp3rF1y** [comment]
I can see what's going on here - it's not any keybind but specifically mouse buttons that don't work in this case. I will take a look at that.
