### ISSUE TITLE
Experience pump and tank bugging

### ISSUE THREAD

**Issue by antoine-courant** [P3pp3rF1y/SophisticatedBackpacks#408]
I'm using the mod among Better Minecraft (v10) before it got replaced by another backpack mod
When having a pump expertience with a tank upgrade, if you have for example 10B in it when putting the bag on the ground (shift right click), it doubles the experience in the tank (here 20B)
I don't really get why, to me it's a bug
Each time you break the bag and put it on the ground again, it doubles the xp in the tank
Link to the video I made to show
https://youtu.be/F-R2NrXr41o

**Comment by P3pp3rF1y** [comment]
What version is that? I just tried the same thing in 1.18 pack I play and am not able to recreate

**Comment by antoine-courant** [comment]
![image](https://user-images.githubusercontent.com/11462348/151542576-d5434f1a-d698-4487-a603-ecd312b598ff.png)

**Comment by P3pp3rF1y** [comment]
This appears to be a mod interaction issue with some mod that I don't have in my modpack. Could you get me list of mods in your modpack? 
And do you by any chance have Global XP mod in the pack?

**Comment by antoine-courant** [comment]
Well I have a lot of mods, the ones that are in Better Minecraft V10 haha, I didn't install anything more, high chance of interaction yeah
I don't have Global XP it seems
Here's the list :
![image](https://user-images.githubusercontent.com/11462348/151550896-d22fd2b7-9304-404c-9ec6-154c7fdc7a63.png)

**Comment by antoine-courant** [comment]
Do you need some more infos ? Or maybe there's too much mods ? (which I would understand of course) :)

**Comment by P3pp3rF1y** [comment]
well I don't have that much time for this so if you can limit it to minimum set of mods that still cause the issue that would help.

The other thought I have is that perhaps you have special item / enchantment which get you extra xp or something else that also messes with xp so when I get to replicating this I may not be able to recreate the exact issue.

**Comment by antoine-courant** [comment]
Okay no problem, I'll try with just your mod and see if it fixes the problem, thanks for your time ;)

**Comment by P3pp3rF1y** [comment]
any follow up info on this?

**Comment by antoine-courant** [comment]
For now no, I just avoid to put my experience backpack on the ground as much as possible
I'll tell you if I do test one day

**Comment by P3pp3rF1y** [comment]
closing given there has been no additional info and potentially it's related to a bug that caused fluid duplication when placing backpacks which is now fixed as well

**Comment by antoine-courant** [comment]
Hello, just wanting to tell ya the problem dissapeared when I took an upgraded version ;) so all is fine

**Comment by P3pp3rF1y** [comment]
Ohh, I remember fixing that bug so I am confused why I closed it with this message. Probably found a way to recreate it after this was closed for a bit already

**Comment by antoine-courant** [comment]
Oh okay, great then ;) happy to know you were able to fix it anyway (meaning you found the reason)
