### ISSUE TITLE
Sorting backpack with inventorysorter deletes items.

### ISSUE THREAD

**Issue by Feliixtc** [P3pp3rF1y/SophisticatedBackpacks#409]
**Describe the bug**
When sorting a backpack equipped with a stack upgrade with the sorting option from the inventorysorter mod it unstacks items into default 64 stacks. Any overflow from this unstacking procedure is deleted.

**To Reproduce**
1. Open backpack with stack upgrade equipped
2. Fill backpack at least halfway to keep it simple 
3. Press inventorysorter mod key to sort
4. See everything unstacked from modified quantities into vanilla stack quantities voiding any excess items in the process.

**Expected behavior**
Inventory sorting with inventorysorter mod to obey mod stack quantities.

**Versions**
forge 39.0.40
sophisticatedbackpacks-1.18.1-3.15.1.505
inventorysorter-1.18-19.0.0

**Comment by P3pp3rF1y** [comment]
Yes it does you need to ban sorting backpack in inventorysorter. I have added compatibility on my side to ban it automatically but unfortunately this is broken in inventorysorter and gets overriden with its config settings which by default allow it to sort everything.

**Comment by Feliixtc** [comment]
“ ban sorting backpack in inventorysorter”

Ok, that’s fine. I’ve tried to ban it on the sorter side, but I’m not sure what exactly to put in the black list. When I put in what I thought it wanted, it changes the entries to “false” and Minecraft no longer launches until the entry is removed. Do you know what should go there? Or would I be better off asking over on their mod page?

**Comment by P3pp3rF1y** [comment]
I believe that is full screen class name so in sbp case `net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen`. if that doesn't work you will probably have better luck over there.

**Comment by P3pp3rF1y** [comment]
actually just checking the curseforge page I was wrong they are looking for container name. and they have these instructions for commands you can use

```
/inventorysorter <arg>

It interacts with the last container you middle click sorted (or attempted to), to allow you to manipulate the container blacklist. These are containers that don't respect middleclick sorting for one reason or another (typically where a special slot containing a special item is not properly marked read only, allowing for it to be duped instead).

 

* bladd: adds the last container to the blacklist

* blremove: removes the last container from the blacklist

* show: shows the last container sorted

* list: shows the list of blacklisted containers
```
