### ISSUE TITLE
Purge command of Mob Bags Suggestion

### ISSUE THREAD

**Issue by Speiger** [P3pp3rF1y/SophisticatedBackpacks#414]
Please just don't lock without me being able to provide another solution.

Continuation of #413

I am running the latest curseforge version on 1.16.5.
And this is not a rant but a problem i found and i would like to share.
And it might not "right now" be an issue but lets say it like this.
On ChunkPregenerator is this exact bug mentioned as a memory leak and that you should look at it for the "Mineshaft" structure in 1.12 or older because this was the exact same implementation.
Just that they were stored 2x in ram.

And people were able to save 5 GB of ram because of it (the file was 5MB big at worst)

So I come with real world experience of that issue and want to make sure you don't run  into this issue because resolving it after it happend is going to be a grind.

What my suggestion would be to simplify something is.
Maybe provide a command to purge "mob" bags from the NBT.
This would at least remove the requirement to open the NBT file with edit it with NBTExplorer having to read through thousands of entries.

This would at least make this from a problem to a "server maintance" tasks.

You can just use the access cache to find which are player and which are mob bags.
So it should be a fairly simple task.

**Comment by P3pp3rF1y** [comment]
As mentioned in the other issue the command is already there. `/sbp removeNonPlayer false` (the boolean just decides if backpacks with anything in their inventory - not upgrade slot like jukebox is - should be kept so setting it to false deletes all backpack contents of backpacks that were never open by player

**Comment by Speiger** [comment]
Ok yeah used the command (deleted 8k backpacks) and it worked fine.

Thanks for telling me this command.
