### ISSUE TITLE
Inception Backpack Not Respecting Filter

### ISSUE THREAD

**Issue by rwagner00** [P3pp3rF1y/SophisticatedBackpacks#415]
**Describe the bug**
I have a Netherite backpack with an Inception upgrade, upgrade is set to use sub-bags first. Top level bag has a magnet set to gather all but certain items. Sub bag has a filter mod set to only allow existing contents, but all items are being passed into the sub bag.

**To Reproduce**
1. Have sub-bag with only a block of stone in it. 
2. Cause item to spawn in world which is not on the top bag magnet black list, and which is not stone. Throw item from inventory, kill mob to cause drop, etc.
3. Approach within magnet range of item. 

**Expected behavior**
Stone will appear in top level backpack.

**Actual Behavior**
Stone will appear in sub-bag.

**Screenshots**
Screenshots of bag settings here: https://photos.app.goo.gl/qwiyRdgYoZAKj98Q7

**Versions**
Forge Launcher: 36.2.20
Mod Version: 1.16.5-3.15.0.493

**Comment by rwagner00** [comment]
Unrelated: Do the maintainers have a tip jar somewhere? This small bug aside, Sophisticated Backpacks has done absolute wonders for my enjoyment of the game and I would absolutely love to be able to tip those responsible.

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this. It was pretty quick thing to fix so it's going to be included in the next release.

As for the tip jar I don't really have one as I am not doing this for money, but I guess I could use a bit of cache for a coffee or such. You have any recommendation for a donation service?

**Comment by rwagner00** [comment]
A pretty popular one is https://ko-fi.com/. It originated, appropriately enough, as a "Buy a creator a cup of coffee" service. :)

Just because I'm absolutely trash at remembering to check updates and would like to set a reminder for myself, do you have a rough idea of when the next release will be? If not, no worries.

**Comment by P3pp3rF1y** [comment]
I am guessing in the next few days, in the worst case till the end of next week

**Comment by P3pp3rF1y** [comment]
and thanks for the tip! (I mean tip for the tip jar :D )

**Comment by rwagner00** [comment]
Quite welcome, thanks for the super quick responses and fix!

**Comment by P3pp3rF1y** [comment]
I have set the ko-fi up so there's now donate button on sophisticated backpacks page that leads there.
