### ISSUE TITLE
A Polymorph crash with latest 1.18 beta 

### ISSUE THREAD

**Issue by A5TC** [P3pp3rF1y/SophisticatedBackpacks#419]
I recently updated to the most recent beta version of the sophisticated backpacks. And this is what I got. I have no idea what is causing the crash. I honestly have way too many mods to know exactly what even happened.

[crash-2022-02-07_13.38.28-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8018667/crash-2022-02-07_13.38.28-fml.txt)
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8018668/latest.log)

**Comment by P3pp3rF1y** [comment]
Right, Polymorph issue. That actually needs to be fixed on their side, but let me notify C4 of that.

**Comment by P3pp3rF1y** [comment]
Related issue that C4 is looking into already https://github.com/TheIllusiveC4/Polymorph/issues/146

**Comment by P3pp3rF1y** [comment]
Polymorph released a new version so this is now fixed
