### ISSUE TITLE
Unable to disable items

### ISSUE THREAD

**Issue by SynfulChaot** [P3pp3rF1y/SophisticatedBackpacks#42]
Version: 1.16.4-2.1.1.153

Attempting to disable items by removing them from the `enabledItems` section in the config does not actually disable the items.  They retain their recipes and remain able to be crafted.

**Comment by P3pp3rF1y** [comment]
Removing from the list does nothing (or rather they will get automatically readded to the list on start). You have to change `true` to `false` for the items that you want to disable. That disables the crafting recipe for the item.
