### ISSUE TITLE
Diamond tier with only 1 chest worth of storage

### ISSUE THREAD

**Issue by Palaek** [P3pp3rF1y/SophisticatedBackpacks#424]
I'm using sophisticated backpack in 1.18.1 server and after looting a dungeon from "when dungeon arise" the diamond backpack inventory turn into decrease and only have 27 slots on it.

**Comment by P3pp3rF1y** [comment]
If you craft a new diamond backpack does it have 27 slots as well? and are you saying that you have found diamond backpack in the loot there? I am not even sure that I am including diamond backpack anywhere apart from maybe end loot.

**Comment by P3pp3rF1y** [comment]
Any answer to my questions? Or should I just close?

**Comment by P3pp3rF1y** [comment]
closing given no additional feedback provided
