### ISSUE TITLE
Dupe bug on Tank upgrade

### ISSUE THREAD

**Issue by ZEROX7** [P3pp3rF1y/SophisticatedBackpacks#426]
**Describe the bug**
wehn using stack tanks such as tinkers tanks or other mods ones, i used ones from lightmans currency, you can click on the tank ui with the stacked tanks and it fills the stacked ones but only takes one tank amount like i take out 1bucket but both tanks reacive 1bucket each so that i have 2 buckets worth

**To Reproduce**
1. Open backpack
2. install tank upgrade
3. use a stack of tanks from mods like tinkers on the liquid bar itself

**Expected behavior**
it would extract at all like wehn you try with stacked buckets

**Versions**
mc 1.18.1 
forge 39.0.79
backpack 3.15.9.533

**Comment by Speiger** [comment]
Duplicated #422

**Comment by P3pp3rF1y** [comment]
actually this one is something I can fix on my side - I am just going to not allow clicking on the bar with stack size larger than 1

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
