### ISSUE TITLE
Match NBT but ignore durability on void upgrade

### ISSUE THREAD

**Issue by Everbane37** [P3pp3rF1y/SophisticatedBackpacks#430]
So I was playing with this mod in a modpack that also included Apotheosis and i was trying to create a backpack that would automatically magnet armor/weapons/tools into it using the advanced magnet upgrade (via match backpack contents setting). 

I then wanted to use the void upgrade specifically in the configuration of ignore durability but respect NBT with unenchanted items as the filter on the void upgrade. My goal was to have the vacuum suck up all those items and delete any extra (more than one stack) of the items that were unenchanted so i could store the enchanted items for later processing without flooding my or the backpack's inventory with multiple semi-broken items.  

however i noticed through testing that the void upgrade does not have this behavior. 

when the upgrade is set to ignore durability and respect NBT it will not delete any excess (more than one stack) items if they are damaged with different durabilities. 

Truly, I dont know whether this is an actual bug, or if each level of durability is being counted as a unique NBT tag by the upgrade's logic.

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
