### ISSUE TITLE
Sophisticated Core (sophisticatedcore) has failed to load correctly 1.18.2

### ISSUE THREAD

**Issue by manzipan** [P3pp3rF1y/SophisticatedBackpacks#432]
**Describe the bug**
Game crash on 1.18.2 would be nice to get it to work on this version 

**Versions**
Tryed official release on curseforge aswell and had the same issue thats why took this version
i am Using Forge 40.0.12 for mc 1.18.2

**Comment by P3pp3rF1y** [comment]
well that's to be expected as 1.18.2 changes some things and mod wasn't released for that version yet. So you will need to wait a bit for 1.18.2 version which I should be releasing the next few days

**Comment by manzipan** [comment]
Thank you very much, this is the greatest mod and belongs on first place of all mods in my opinion

**Comment by manzipan** [comment]
I use this mod for the community. so i was wondering if i shuld downgrade the comunity server to 1.18.1 for the time being or are you just about to realease something for 1,18,2

**Comment by P3pp3rF1y** [comment]
1.18.2 version is out
