### ISSUE TITLE
[1.16.5-1.18] Mass Removal of items of a backpack

### ISSUE THREAD

**Issue by Speiger** [P3pp3rF1y/SophisticatedBackpacks#433]
When you shift click on a Item in minecrafts inventory it transfers all of the same items into the inventory you are looking at right now.

But when you try that with a backpack it does not work.
So this is a bugreport but also feature request.

Add a button combo where you can move multiple stacks of the same item into your player inventory or drop it on to the floor with less button clicks because for 2k items i kinda have to mash so fast the combo that i am scared of hurting my keyboard.

It makes life easier for everyone and also allows mass transportation of resources from bases a lot easier.

Also optional a key combo that tells the backpack crafting upgrades to refill from the backpack if the items are removed from it,
dunno if a upgrade already does it but this is like really good quality of life stuff that would be nice.

**Comment by P3pp3rF1y** [comment]
Hold on just shift click? that should transfer just one stack, right?
Are you perhaps referring to slots that have more than usual stack size because of stack upgrade used? you can use Ctrl + Shift + Click to transfer as much as possible from those.

**Comment by Speiger** [comment]
Yes that exactly.
Thank you. Would be nice if that would be done like mcs default behavior too.
(Shift Clicking on a Item + Having a Item in the mouse slot does what your Ctrl + Shift does)

**Comment by P3pp3rF1y** [comment]
You must have some mod that does that - when I have item in hand (same or different) and shift click on a stack in vanilla chest it moves just the stack I clicked on and leaves others in place. But it's true that this works with double click and perhaps you meant that and you're right that stack over maxstacksize when double clicked with item in hand doesn't move as many as possible I will take a look at that one

**Comment by Speiger** [comment]
Try fastclicking right click because this is a vanilla behavior. I think its double click based.

**Comment by P3pp3rF1y** [comment]
well, I am getting even more confused by this to be honest, shift right clicking on a stack with another in hand will just move a single whether I single click or double click on a stack in the chest inventory.
And based on this info there's no such thing as shift right click to move more than one stack https://minecraft.fandom.com/wiki/Controls#Non-configurable_controls

**Comment by Speiger** [comment]
https://user-images.githubusercontent.com/2556269/158057818-c2f8ce36-60bd-48d2-921c-5b19a77c95b6.mp4

Installed mods: 
JEI, Unique Enchantments mods, First Aid, Enchantment Descriptions.
(Its my UE dev space)

But yeah all i did was take a item into the hand and double leftclicked on to the item i wanted to move in mass.

It would be nice if that behavior would be supported too since its a vanilla feature and it would at least not confuse people to have lookup custom made keybindings that do that for you. Makes it easier to remember too.

**Comment by P3pp3rF1y** [comment]
alright so as I said above that's something I will look into and add, I was just confused when you said "fastclicking right click"

**Comment by Speiger** [comment]
Yeah I had to try it to visualize it properly. Sry

**Comment by P3pp3rF1y** [comment]
shift double clicking is implemented in the latest version and I have put the idea with refilling the crafting upgrade on my list of potential future enhancements

**Comment by Speiger** [comment]
thank you.
