### ISSUE TITLE
Making identical Backpacks When open game to Lan world

### ISSUE THREAD

**Issue by Daihok41** [P3pp3rF1y/SophisticatedBackpacks#434]
In version 1.18.1-3.15.9.533.jar For some reason When you open Gme to Lan World and if you try and make 2 Backpacks one right after the other You get 2 backpacks with Duplicate ID. Meaning you could put a crafting table in 1 backpack and then open the other backup and access almost like they are enderbags are something. This is with the base backpacks no upgrades. Then if you exit game and start back up without going into Lan World the backpacks will revert to having 2 diff IDs. It only seems to happen sometimes though. I keep trying to reproduce and sometimes it does it and sometimes it dont.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate that - tried crafting one, opened it, crafted second and opened it as well and they both have different id. So I have then tried to craft both of them before opening and they still have different ids even from the ones crafted previously. And yes I tried all of this in game open to lan

So I will need exact steps on how to recreate the issue

**Comment by spyhermit** [comment]
I was temporarily able to duplicate this. I created a backpack, put a crafting and a smelting upgrade in it, then created 2 more backpacks in this backpack. I had cheats enabled for that world. they all had the same uuid. After a reload, new backpacks create with unique uuids.  This was during the first load of a new world in a new instance with cheats enabled, but I cannot duplicate this even with a new instance in multimc.

**Comment by P3pp3rF1y** [comment]
I have just released a kind of fix which makes sure that uuid is removed from recipe result when the backpack is crafted so this should no longer be possible even in those cases where it somehow happened in the past
