### ISSUE TITLE
1.18 "Failed to load the mod" Sophisticated Backpack

### ISSUE THREAD

**Issue by SolidusSloth** [P3pp3rF1y/SophisticatedBackpacks#435]
The mod pack fails to load on launch. I receive this crash report. https://pastebin.com/Q7ZUM0xB
This is the only mod I am running. 

I am using forge 1.18.2 and I am using the mod version of  1.18. 1-3.15. 1.505
However, I have tried every mod version of 1.18 with the same results.

**Comment by P3pp3rF1y** [comment]
that's because there isn't a version for 1.18.2 yet should be out there in a few days. anyway I am going to close as there's already another ticket for the same thing
