### ISSUE TITLE
Graphical bug when a backpack has no upgrade slots

### ISSUE THREAD

**Issue by SynfulChaot** [P3pp3rF1y/SophisticatedBackpacks#44]
Version: 1.16.4-2.1.1.153

If you reduce the number of upgrade slots in a bag to zero (0) it will show a small nub out of the side of the interface where the upgrades used to be.  This does not seem like desired or intended behaviour.

![](https://i.imgur.com/0jAJbTA.png)

**Comment by P3pp3rF1y** [comment]
yeah it's true that I have never thought of any backpack tier being used without any upgrade slot. But shouldn't be that hard to fix so I will likely add this in the next release.
