### ISSUE TITLE
Recent version introduces dupe bug when using FastWorkbench

### ISSUE THREAD

**Issue by maxhenkes** [P3pp3rF1y/SophisticatedBackpacks#445]
**Describe the bug**

The current version: 1.16.5-3.15.13.560 dupes items while crafting inside the backpack in combination with FastWorkbench Minus Replacement mod. (1.1-1.16.3). When you craft any item (shift or normal), it also throws the same item out (eg. craft planks from logs). This bug was introduced in one of the last commits downgrading to the February version removes this bug. I assume it's the one with the bugfix for dropping items when full.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate with fastworkbench in the pack. I have tried simple clicking to craft, shift clicking to craft, filling inventory to see if dropping happens and all of these work correctly. So I will need exact steps or more info on what other mod needs to be in the pack to be able to recreate

**Comment by maxhenkes** [comment]
That's odd, it happens right away for me with only FastBenchMinusReplacement-1.4 and the latest version of your mod
![dupeBug](https://user-images.githubusercontent.com/817708/159608977-8c084352-1cba-4532-87a9-c79c2d2c4dea.gif)
.

We're currently running the older version mentioned in the report on our server and it works fine. No dupe bugs so far. Only happens with the most recent version. As you can see from the gif it crafts it and at the same time also drops it.

**Comment by P3pp3rF1y** [comment]
that mod isn't official fastworkbench and it seems to change crafting slot in a way where after removing the item it still stays there at the very least server side and that's why drop logic drops it because it sees it as something that remained in the slot after crafting. My suggestion - don't use that mod, it doesn't seem to be maintained anyway and there's an official fastworkbench

**Comment by maxhenkes** [comment]
Alright, we were initially using it because it was using Mixins instead, while the "official" Fastworkbench mod was not and had some compat issues so I've been using the other ever since, but it seems like it has also changed over at some point so I will happily switch over to fix this dupe bug. Should probably note incompatibility somewhere tho because your last update breaks with the mod installed! Thanks for the help!
