### ISSUE TITLE
Items in filter slot crashed the game

### ISSUE THREAD

**Issue by manzipan** [P3pp3rF1y/SophisticatedBackpacks#446]
**Describe the bug**
After Killing an enderman he droped a backpack with a diamond backpack inside and inside the diamond backpack there was diamond blocks in the filter upgrade slot upon klicking it it crashed the game

**To Reproduce**
not been able to reproduce

**Crashlog**
https://pastebin.com/5Uax6Pqb

**Comment by P3pp3rF1y** [comment]
In the latest version of sophisticated backpacks loot that gets generated in backpack will automatically exclude backpacks as that breaks a bit of balance given that they are put in backpack without inception upgrade and it also causes some of these super hard to fix issues. So this issue with latest version isn't possible
