### ISSUE TITLE
Backpacks cleared own inventory

### ISSUE THREAD

**Issue by Slothematic** [P3pp3rF1y/SophisticatedBackpacks#449]
I am playing on a player-pack created (Through Curseforge) mod server (I host locally) with sophisticated backpacks installed. My computer has had troubles staying on (separate issue) but crashed when the server was still up. After a reload of the server, all items in every players backpacks are gone but, in creative mode, i can see the inventory of everything that was in there. When a new items is added into the backpack, everything that was in it is deleted.

![2022-03-24_18 51 37](https://user-images.githubusercontent.com/102337047/160038940-dda1753e-f972-40e2-a63d-5c321a33fe7d.png)

Same backpack:

![2022-03-24_18 52 17](https://user-images.githubusercontent.com/102337047/160039854-377e2c7c-450c-410c-88af-444c655bde63.png)

I realized the files are corrupt, but I am trying to figure out where in the files it is to try and fix it. When I go back to a backup, the same thing occurs so I don't think it is a player data issue. Please help if possible.

**Comment by qyl27** [comment]
Same problem in my server.
Players said when unload from the curios inventory, the items in backpack are all missing.
