### ISSUE TITLE
[Feature Request] Command to get back a backpack with a specific UUID

### ISSUE THREAD

**Issue by FreeFull** [P3pp3rF1y/SophisticatedBackpacks#45]
The command would be useful in the case the backpack gets somehow deleted, especially if the command can do some sort of tab completion too.

**Comment by P3pp3rF1y** [comment]
The problem I see with that is players won't know UUID of their backpack most probably not even first few characters until they would need it for this command and I am not sure where they could dig it up. Also you could then pretty easily use vanilla command to give yourself backpack with the uuid passed in nbt part.

I was actually thinking of starting to track who crafted what backpack and then add command that would allow players to see all backpacks they crafted, but I still feel that would have very limited use. So I will leave this issue request open for now and decide whether I want to go ahead and add that command.

**Comment by P3pp3rF1y** [comment]
Released commands in the latest release on CF
