### ISSUE TITLE
Can't open any backpacks Ver. 1.18.1-3.15.9.533

### ISSUE THREAD

**Issue by bluediamond24** [P3pp3rF1y/SophisticatedBackpacks#450]
I have bound and rebound the backpack key to both keyboard and mouse buttons but neither will work. There are no conflicting keys and the mouse button is functional. Yesterday the backpack was working just fine, but I logged in today and can't open it. I'm currently playing in the modpack "All The Mods 7".

**Comment by P3pp3rF1y** [comment]
I am not sure that I will be able to help because I do quite a bit of testing and haven't seen this myself and also no one else reported anything similar despite the pack being very popular. Could you check if there's anything in log when you try to open the backpack?

**Comment by P3pp3rF1y** [comment]
Any update on this or should I just close?

**Comment by P3pp3rF1y** [comment]
closing
