### ISSUE TITLE
Advanced Compacting Upgrade not working on Quartz

### ISSUE THREAD

**Issue by StarBanger69** [P3pp3rF1y/SophisticatedBackpacks#451]
I'm playing Not Too Complicated 2, and I was trying to use the backpack to compress quartz into blocks for another automation, but I can't get it to compress the blocks. I am on the latest version (1.16.5-3.15.13.560) and I have it set to Compress anything. 

**To Reproduce**
1. Open backpack
2. Install Advanced Compacting Upgrade
3. Put Nether Quartz in the Filter (set to allow)
4. Set to allow it to compact anything.

**Expected behavior**
It would Compact the Nether Quartz into Blocks

**Screensho
![2022-03-27_14 55 47](https://user-images.githubusercontent.com/39132142/160296368-696ed56c-848a-4d94-be8b-171826dbadd4.png)
ts**

**Versions**
1.16.5-3.15.13.560

**Comment by P3pp3rF1y** [comment]
I don't play that modpack so can you check if there's in fact a 2x2 or 3x3 recipe that makes quartz block?

**Comment by StarBanger69** [comment]
The recipe for quartz is a 2x2, with no 3x3 option for quartz to blocks

**Comment by P3pp3rF1y** [comment]
actually are you expecting the quartz that already exists in the backpack to be compacted? that's not how it works - it will compact it when it's input using pipes or clicked in. At that point it may use some additional quartz from what already exists in the backpack, but it won't just start compacting everything that's in the backpack when you add the compacting upgrade

**Comment by StarBanger69** [comment]
I put the upgrade in before the quartz was put into the bag. This pack has a recipe for compact quartz blocks and I wanted to use the backpack to automate it, but the first step (turning quartz into quartz blocks) isn't working for some reason.

**Comment by P3pp3rF1y** [comment]
So are these your steps?
1) put compacting upgrade in backpack
2a) pipe quartz into backpack or have pickup / magnet upgrade put quartz into backpack
2b) enable "works in gui" on compacting upgrade and put quartz into backpack by clicking / shift-clicking it into backpack?

These definitely work for me with that version so if it doesn't for you in your pack I will need specifics on what mod is causing a conflict here

**Comment by P3pp3rF1y** [comment]
and actually perhaps you can show the screenshot of the recipe in JEI that shows how quartz block is crafted from 4 quartz crystals as this seems odd and maybe it's some kind of special recipe that needs some other condition fulfilled for it to work?

**Comment by P3pp3rF1y** [comment]
I am guessing there were custom recipes which blocked this from working so closing the issue.
