### ISSUE TITLE
[1.18.2] Crafting Tweaks buttons not showing up in crafting upgrade gui.

### ISSUE THREAD

**Issue by Baggytrousers27** [P3pp3rF1y/SophisticatedBackpacks#452]
Forge 1.18.2 40.0.41
balm-3.0.2+0
craftingtweaks-forge-1.18.1-14.0.2 (Listed on curseforge for 1.18.2)
sophisticatedbackpacks-1.18.2-3.15.17.559
![2022-04-07_13 37 05](https://user-images.githubusercontent.com/15883796/162116180-d27dadc0-2b92-4232-b8b2-da498e2b3f6b.png)

For comparison 1.18.1 39.0.75
balm-2.4.3+0
craftingtweaks-forge-1.18.1-14.0.2
sophisticatedbackpacks-1.18.1-3.15.9.533
![2022-04-07_13 29 18](https://user-images.githubusercontent.com/15883796/162116551-406411ce-1fba-458a-9bcf-0501eebe909c.png)

[Standard Crashlog](https://pastebin.com/Wtgd4FWT)/[Debug Crashlog](https://pastebin.com/6ED4Jj77).

**Comment by P3pp3rF1y** [comment]
well yeah, when I was updating crafting tweaks were not ready for 1.18.2 so I had to remove that compat. I will include it again in the next release if they're in fact ready.

**Comment by Baggytrousers27** [comment]
Ahh. Groovy.
