### ISSUE TITLE
Crash upon Dedicated server start with modpack.

### ISSUE THREAD

**Issue by Darkmega18** [P3pp3rF1y/SophisticatedBackpacks#453]
**Describe the bug**
This comes from a friend who tried to run the modpack as a server.

Upon starting the server, crash during loading. I asked for the logs and saw:
Sophisticated Backpacks (sophisticatedbackpacks) has failed to load correctly
		java.lang.IllegalStateException: Failed to resolve consumer event type: net.p3pp3rf1y.sophisticatedbackpacks.common.CommonProxy$$Lambda$8731/0x0000000000000000@c2de2bfd

**To Reproduce**
Download "Order of All Creation: Relic hunters" modpack for exact installation set up.

Copy required files etc from installation (config, defaultconfigs, openloader, mods, scripts) to forge server install to run.

run.bat it.

kaboom.

**Expected behavior**
The game loads and my friend can play the video game? :V

**Versions**
From crash report: 
sophisticatedbackpacks-1.16.5-3.15.13.560.jar
forge-1.16.5-36.2.28.jar

Here is the report I got given. It seems to also have issues with reliquary, which is where I'll be going next...
[crash-2022-04-07_16.23.12-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8441092/crash-2022-04-07_16.23.12-fml.txt)

latest.log of the running when it crashed also:
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8441095/latest.log)

**Comment by P3pp3rF1y** [comment]
forge is incompatible with OpenJ9 JVM so you need a different jvm to run forge modpacks.
