### ISSUE TITLE
BUG/Feature? Void upgrade to not pickup automatically.

### ISSUE THREAD

**Issue by ALainxD** [P3pp3rF1y/SophisticatedBackpacks#454]
When I equip a Void upgrade to the backpack it also pickups items automatically without having the option to disable auto pickup.

My issue is I want to make a backpack with a Pickup upgrade that only pickup matching backpack content and a Void upgrade that only voids more than a stack items in backpack.

The combination of these items would allow to make basically a filtered trashcan with lots of filter slots. Because many modpacks have now so many different seeds, saplings and stonetypes that would be a great way of void anything you put in the backpack.

A solution to this would be give the void or maybe just the advanced void upgrade the option to enable/disable autopickup when in block mode. Or even give it a option that it only pickups matching inventory items.

Sophisticated Backpacks 1.16.5-3.15.13.560
Modpack: Enigmatica 6 Expert

**Comment by Targren** [comment]
Came to report this same issue, same version, same pack. 

A few ways I think this could go without breaking too much: 

* When both a void upgrade and pickup upgrade are installed, transparently disable the void upgrade pickup logic and defer to the pickup upgrade, then apply the voiding rules to the items collected through the pickup upgrade. This is how I (and I think how most players) expected these two upgrades would interact. 

* Manually disable pick up on void upgrade as the other poster suggested. 

* Give the Void Upgrade filter logic an option to "Match Backpack Contents" like the Pickup upgrade has. This is probably the easiest to implement (would probably need a bit of logic massaging to make it work with the "overflow only" void setting, but should be pretty straightforward), but would remove the need for the pickup upgrade entirely for this use case, which some may consider "overpowered"

**Comment by gregoriousbig** [comment]
Same issue in 1.18.2, a simple match backpack content would be oerfect for the void upgrade

**Comment by P3pp3rF1y** [comment]
I am going to remove pickup from void upgrade as it's unintuitive and even though the original intention was to be able to void stuff that player picks up like cobble with just void upgrade alone the pickup upgrade on top of it doesn't seem that expensive.

**Comment by Targren** [comment]
> I am going to remove pickup from void upgrade as it's unintuitive and even though the original intention was to be able to void stuff that player picks up like cobble with just void upgrade alone the pickup upgrade on top of it doesn't seem that expensive.

That actually sounds perfect.  The Void Upgrade alone still has use in automation/storage setups, too.

**Comment by P3pp3rF1y** [comment]
in the latest release pickup is removed from void upgrade

**Comment by bcrotty** [comment]
@P3pp3rF1y Is there a way to add this as a button to enable/disable it? I have my pickup upgrade set to match backpack contents, so now the void upgrade doesn't really work until I manually move items into the backpack for it to delete them.

**Comment by P3pp3rF1y** [comment]
You can still go for overflow with the void upgrade though

**Comment by bcrotty** [comment]
@P3pp3rF1y Yah, I just don't want it to void anything else that overflows. That's okay. I'll make do. Thanks for your great mods!

**Comment by P3pp3rF1y** [comment]
if you have void filtered it will only void overflow of the items in the filter so you don't have to worry that anything not in it wouldn't start filling additional slots
