### ISSUE TITLE
Backpack content copied/overwrites to other backpack... losing previous contents...

### ISSUE THREAD

**Issue by AefRal** [P3pp3rF1y/SophisticatedBackpacks#455]
**Describe the bug**
Playing single player, the contents of one bag gets overwritten with that of the other and vice versa, depending which one I open first after switching back to survival from creative.

Crash log if it's a crash.
No crash.
Playing All The Mods 7 - ATM7 - 1.18.2

**To Reproduce**
1. Make two backpacks (tiers didn't matter)
2. Put stuff in one
3. Switch to creative and back (not sure if I opened the bag while in creative).
4. Check bag
5. See your nearly filled bag's contents replaced with a copy of that of your practically empty one.
6. Cry.
Extra info,  I even made one bag gold tier while leaving the other iron tier. It still occurred as it did when they were both iron tier.

**Expected behavior**
Backpacks to retain individuality.

Losing a ton of valuables from freshly looted pirate ships and sunken ships/ruins is reason enough to not use this mod. As much as I love it, until it's fixed I can't trust my loot to these backpacks.

**Screenshots**

**Versions**

sophisticatedbackpacks-1.18.2-3.15.17.559.jar
Forge - 40.0.44

Modpack 
All The Mods 7-0.3.4.zip

**Comment by P3pp3rF1y** [comment]
can you check UUID of those backpacks? - F3 + H to see it in tooltip
Is it the same?

if so it was very likely copied in creative in some way. If you are actually able to recreate that in survival let me know and I can take a look.

**Comment by AefRal** [comment]
I loaded up into the world again, and hit F3+H, Yes, the affected backpacks
have the same UUID.
I even tried to redo this glitch.
I made two more backpacks, put an item in one and checked the other. Still
empty. Good.
Went into creative and back, checked backpacks, one with the item one
empty...
Tried going creative and opening one backpack, then back to survival. Still
separate.
Tried opening both in creative, and going back. Still not overwriting...
Not sure what I did to have that happen the first time.
Wish I could have been of more help.

**Comment by P3pp3rF1y** [comment]
I am guessing you may have used the dupe stack key in creative which woudl do exactly this. Anyway I am going to close, but if you find that you are able to recreate in survival feel free to reopen/create new issue with the exact steps

**Comment by hyodocraft** [comment]
I'm also playing ATM7 modpack v0.3.11 (mc1.18.2) (soph backpack v3.15.17.559)
And I have a similar problem, so I'll put a video and a ss here. but survival and no cheats.
In my case, the newly crafted backpack already has the same UUID as the existing backpack (the first backpack made in this save). 
Sadly the cause and reproducibility are unknown, and after re-entering the world, it will return to the expected normal behavior.
https://streamable.com/v1mfe0
https://i.imgur.com/VwuVgRO.png

**Comment by Miner94** [comment]
i may have figured it out on how to cause it
save and quit, then rejoin the world 
i have only tested single player

**Comment by GreenForzeGaming** [comment]
ive made this happen in version sophisticatedbackpacks-1.16.5-3.15.13.560. i will link a youtube video of me doing it very soon.

**Comment by GreenForzeGaming** [comment]
https://www.youtube.com/watch?v=GL-VyVzyBEY
