### ISSUE TITLE
Crashes upon loading world while using Polymorph mod 1.16.5

### ISSUE THREAD

**Issue by ggmg42** [P3pp3rF1y/SophisticatedBackpacks#466]
So at first I thought the mod was conflicting with Travelers Backpack, but after looking through the crash log it mentioned Polymorph and that seemed to the issue. I took out Polymorph and it loaded fine. I'm attaching the crash report in case it helps to fix the compatibility with Polymorph.
[crash-2022-05-08_15.16.31-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8647651/crash-2022-05-08_15.16.31-server.txt)

**Comment by P3pp3rF1y** [comment]
Just update polymorph to one of the later versions - don't know in which one exactly it was fixed but you should really be looking for a new version when you get a crash like this.
