### ISSUE TITLE
Open Backpack key doesn't work in Curio slot anymore

### ISSUE THREAD

**Issue by Draskh** [P3pp3rF1y/SophisticatedBackpacks#474]
**Describe the bug**
Since the latest update to 3.16.3.582 my backpacks only open when I have them in inventory.

**To Reproduce**
1. Change  key
2. put backpack in Curio slot
3. Press custom button
4. nothing happens

**Expected behavior**
Backpack inventory should open

**Versions**
3.16.3.582 with 40.1.20

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
