### ISSUE TITLE
Sophisticated Backpacks crashes without proper explanation when not using latest version of Sophisticated Core

### ISSUE THREAD

**Issue by mothnox** [P3pp3rF1y/SophisticatedBackpacks#476]
Version: 3.16.4.584

When using the latest version of Sophisticated Backpacks with a version of Sophisticated Core other than the latest (tested with 0.0.7.16), Minecraft crashes without reporting to the user that the need the latest version of Sophisticated Core. 

To fix: 
Add latest version of sophisticatedcore as a dependency in mods.toml

**Comment by P3pp3rF1y** [comment]
That is already the case so I am confused why it would crash. Can you share the crash log that you get?

**Comment by krumbld** [comment]
I had the same problem, here is the crash log. Recreated same issue after restarting without the core update. After updating to latest sophisticated core, issue resolved. 

[crash-2022-05-30_14.27.40-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8800258/crash-2022-05-30_14.27.40-server.txt)

**Comment by P3pp3rF1y** [comment]
I found an issue with the version I had in dependencies so in the next release this will be fixed

**Comment by P3pp3rF1y** [comment]
the latest version on curseforge has proper dependency version so this should no longer happen going forward
