### ISSUE TITLE
Cannot install upgrades

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedBackpacks#478]
**Describe the bug**
Crash log if it's a crash.
Info on what other mods you're using that may cause a conflict here if applicable.

I am using the latest Direwolf20 v1.2.0 pack for minecraft 1.18. It has a LOT of new mods so I expect there is some sort of conflict happening.

In any case, I cannot add any upgrades to the upgrade slots of the backpacks. The upgrade slots highlight when I mouse over them, but I cannot drop in an upgrade. It simply refuses to take the item.

**To Reproduce**
1. Open backpack
2. Try to drop an upgrade into an upgrade slot

**Expected behavior**
I expect the upgrade to drop into the slot and start working. Instead, its not accepted.

**Versions**
Mod version is sophisticatedbackpacks-1.18.2-3.16.1579 and forge appears to be version 1802.3.6 but some libraries are 1802.1.7

**Comment by P3pp3rF1y** [comment]
Are you sure that you are not using storage upgrades from sophisticated storage for backpacks? There are backpack upgrades which are separate and the reason for that is difference in price of those - backpack ones are more expensive.

**Comment by ghost** [comment]
D'Oh! That was, indeed, the issue. The two sets of upgrades look identical and have almost identical recipes, so I never noticed it was two sets and not one. Thanks!

**Comment by P3pp3rF1y** [comment]
Yeah I will actually take this as a note and likely add something in the tooltip that shows where they can be used.
