### ISSUE TITLE
Rendering entity in world crash

### ISSUE THREAD

**Issue by MaxWasUnavailable** [P3pp3rF1y/SophisticatedBackpacks#479]
**Describe the bug**
Teleported to user and crashed.

**To Reproduce**
1. Log into server.
2. Teleport to user with Backpack.
3. Crash?

**Expected behavior**
No crash.

**Versions**
Forge: 40.1.22
Sophisticated Backpacks: 1.18.2-3.16.4.584
Sophisticated Core: 1.18.2-0.1.0.19

Crash log:

[crash-2022-05-22_21.49.53-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8750174/crash-2022-05-22_21.49.53-client.txt)

**Comment by P3pp3rF1y** [comment]
Looks like a crash when backpack on corpse is being rendered. I will need to take a look at what that is doing there to cause this but it should be handled more gracefully anyway even if it messes with rendering data

**Comment by gabgat** [comment]
Same problem, using forge 40.1.0

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
