### ISSUE TITLE
Advanced tool swap Tetra tool

### ISSUE THREAD

**Issue by Jax1366** [P3pp3rF1y/SophisticatedBackpacks#481]
When filtering a tetra tool in advanced tool swap the tool only swaps in a small portion of the time, and using the keybind will not switch to the specified tool.

**To Reproduce**
1. Open backpack
2. Equip advanced tool swapper
3. Filter tetra tool

**Expected behavior**
Tool switching.

**Screenshots**

**Versions**
Version 3.15.7.531
Forge version 36.2.31

**Comment by P3pp3rF1y** [comment]
fix in the latest release on curseforge
