### ISSUE TITLE
Crashing when trying to open the backpack by pressing B

### ISSUE THREAD

**Issue by MrJustusGames** [P3pp3rF1y/SophisticatedBackpacks#485]
I just made a tier 1 backpack, equipped it, pressed B and it crashed my game. I tried it again and it crashed a second time. I have 3 other mods installed, Create, Immersive Engineering and JEI. I dont know what is causing this as there is not any conflicting Key Binds for it.

EDIT: Fixed issue by downloading and installing the previous version for sophisticated core as the one that was updated on 5/27/22 was the issue.

[crash-2022-05-27_17.43.04-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8790425/crash-2022-05-27_17.43.04-fml.txt)

**Comment by MrJustusGames** [comment]
Fixed issue by downloading and installing the previous version for sophisticated core as the one that was updated on 5/27/22 was the issue.

**Comment by P3pp3rF1y** [comment]
could you get me the actual crash log from when that issue happened for you? (the one you have provided is from when you were missing correct sophisticated core version). 
Downgrading to previous version of core really isn't a solution unless a breaking change was made in it and you're still using older version of backpacks that the new core version isn't compatible with. But that doesn't seem to be the case here so I would like to understand what happened there to see if I can fix

**Comment by P3pp3rF1y** [comment]
This is likely caused by incorrect backpacks version another report said that curseforge for some reason doesn't show the newest one in their app. So I am going to close
