### ISSUE TITLE
The order of the item column is wrong when opening the backpack

### ISSUE THREAD

**Issue by xuwuwudi** [P3pp3rF1y/SophisticatedBackpacks#486]
**Describe the bug**
as title says

**To Reproduce**
1. Open backpack

**Screenshots**
![image](https://user-images.githubusercontent.com/84704462/170816241-331cada9-bd67-47e3-9ebe-b3a312c57efd.png)
but in backpack gui
![image](https://user-images.githubusercontent.com/84704462/170816269-20f96a86-e61b-4e76-8280-ae2f0dd5c4cc.png)
![image](https://user-images.githubusercontent.com/84704462/170816272-02453587-f9b7-4114-aa00-8b4252aea60d.png)
Obviously the rows are in the wrong order

**Versions**
latest

**Comment by Mattsingen** [comment]
I came here to also report this. I've tested with only Sopisticated Backpacks and Core. So it's not an interaction with anything else that is causing this.

**Comment by P3pp3rF1y** [comment]
Found the bug in the new code in core related to displaying scrollable inventory. I will have the fix up very soon

**Comment by P3pp3rF1y** [comment]
Thanks fore reporting this the bug is now fixed in the latest version of sophisticatedcore
