### ISSUE TITLE
Crash when opening a backpack after updating Sophisticated Core

### ISSUE THREAD

**Issue by fuzzl3** [P3pp3rF1y/SophisticatedBackpacks#487]
Anytime I use either the hotkey or right-click from the hotbar to open a backpack, the server (but not the client) crashes.

[crash-2022-05-28_14.23.44-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8791659/crash-2022-05-28_14.23.44-server.txt)

Crashlog should contain the full modlist.

1. Open backpack
2. Server crashes

**Expected behavior**
1. Open backpack
2. See inventory

**Versions**
Forge: Forge - 40.1.23
Sophisticated Backpacks: sophisticatedbackpacks-1.18.2-3.17.2.588.jar
Sophisticated Core: sophisticatedcore-1.18.2-0.2.2.23.jar AND sophisticatedcore-1.18.2-0.2.4.26.jar

I have been able to fix this error by downgrading Sophisticated Core to: sophisticatedcore-1.18.2-0.1.0.19.jar

**Comment by P3pp3rF1y** [comment]
Well the version of backpacks I can see in crashlog is previous one which is incompatible with those two versions of core. Try to update to version of backpacks you mentioned above and that should fix it

**Comment by fuzzl3** [comment]
Interesting. Curseforge isn't detecting a newer version of Sophisticated Backpacks, but it is there and labeled release when I look at the versions list. Will update and let you know if there's still any issue.

**Comment by fuzzl3** [comment]
Yep, works now. Just a case of Curseforge being Curseforge I guess.
