### ISSUE TITLE
Bug when Shift+Right-Click to pickup a backpack in the world when another backpack already equipped...

### ISSUE THREAD

**Issue by Howsyomamanem** [P3pp3rF1y/SophisticatedBackpacks#488]
I'm playing on a Server...  I didn't capture any error info.  Sorry about that.  

When I shift+right-click an "in world" backpack and having had another backpack already equipped (in curio slot), I was unable to access my inventory in any way after that. 

Nothing worked:  'e' to open inventory,  'b' to open backpack, I couldn't even use the number keys or the mouse wheel to move between items on my hot bar.

The game wasn't frozen or anything, I could still move around.

Anyway, it should be easy enough to reproduce.  Good luck.

I ended up having to do a world restore from backup to resolve the issue.

**Comment by P3pp3rF1y** [comment]
I don't what version this is for, but this is something I do a lot in the pack that I am playing (ATM7) and I haven't seen any issue like that so I will need specifics as to how to recreate / what mods it fails with / which version / ,,,

**Comment by P3pp3rF1y** [comment]
And one more thing is also you would usually see something in logs when something like this happens. not guaranteed but good to take a look there and share.

**Comment by Howsyomamanem** [comment]
the jar is:  sophisticatedbackpacks-1.18.2-3.16.4.584.jar
in DW20 1.18 pack
It could be some issue with something the 1st backpack contained.  the one I picked up was empty tho.
it was really weird the effect it had.  but if you can't reproduce it, i wouldn't worry about it.  :-)

**Comment by amrodir** [comment]
I'm pretty sure it conflicts with the [Carry On](https://www.curseforge.com/minecraft/mc-mods/carry-on) mod, that allows you to move around block entities by shift+right-clicking.

It happens if you're too close to your backpack, and "Carry On" thinks it's turn to pick up the block.
You can simply right-click on the ground and your backpack will be back.

**Comment by P3pp3rF1y** [comment]
In that case that's very likely on carry on - perhaps it doesn't cancel the interaction event properly which could cause weird things to happen. I just double checked that picking up on my side doesn't seem to have any obvious issue in it.
