### ISSUE TITLE
Sophisticated Backpacks and Chests don't display tooltips or respond to JEI Use/Recipes keys...

### ISSUE THREAD

**Issue by Gantros** [P3pp3rF1y/SophisticatedBackpacks#490]
**Describe the bug**
When viewing the contents of the backpack, no tooltip information is displayed nor does JEI display uses or recipes when the appropriate key is pressed (R/U by default). Transferring the item/stack from the Sophisticated storage (Backpack or Chest) to regular inventory restores the tooltip within the regular inventory and JEI R/U functions. Barrels do not appear affected by this issue.

**To Reproduce**
1. Open backpack/chest
2. Hover mouse over any item/stack and/or click R/U on any item/stack (if JEI is installed)
3.) Observe issue

**Expected behavior**
I expected tooltip information and JEI Use/Recipe info when requested.

**Screenshots**
![2022-06-01_11 57 37](https://user-images.githubusercontent.com/63207219/171481574-708a3c72-a0d6-4bce-8412-f44e19d67a08.png)
![2022-06-01_11 57 39](https://user-images.githubusercontent.com/63207219/171481579-16c95f39-5b1a-4302-8365-9df31cdc11e0.png)
![2022-06-01_11 58 01](https://user-images.githubusercontent.com/63207219/171481581-7171825e-c17f-438b-960f-314f3cee04af.png)
![2022-06-01_11 58 04](https://user-images.githubusercontent.com/63207219/171481586-0726b0b7-5bd4-4216-afdf-6e4b75f57e64.png)

**Versions**
Minecraft version 1.18.2
Forge version 40.1.22
Sophisticated Core 1.18.2-0.2.5.28
Sophisticated Backpacks 1.18.2-3.17.2.588
Sophisticated Storage 1.18.2-1.0.6

**Comment by P3pp3rF1y** [comment]
Fixed in the latest sophisticated core on curseforge
