### ISSUE TITLE
Tool swapper is switching to Tinker's Mattock when hitting dirt, but not switching back to any other tool. Axe and Pickaxe work fine.

### ISSUE THREAD

**Issue by AryuSyrius** [P3pp3rF1y/SophisticatedBackpacks#492]
**Describe the bug**
I have installed the Advanced Tool Swapper Upgrade. I am also using Tinker's Construct. I added a Slimesteel Pickaxe, Slimesteel Mattock, and Slimesteel Hand Axe to the Tool Swap filter. The swapper work great for the Pickaxe and the Axe. The Mattock when left clicking on dirt, will switch to the mattock, but clicking on anything else will not switch to the other tool.

**To Reproduce**
1. Open Backpack
2. Install Advanced Tool Swapper.
3. Make Tinker's Tools
4. Notice that it will not swap to a pickaxe or axe from mattock.
Note: I think this was working with bronze head pieces, but I don't remember. So this specifically applies to tools in which Slimesteel make up the head/s.

**Expected behavior**
When I click on a shovel-able material, I expect the upgrade to swap to my shovel tool equivalent. 

**Screenshots**
Here is a video I uploaded to youtube, showing this issue.
https://youtu.be/reGhO45c5Vs

**Versions**
Forge: 40.1.25
Minecraft: 1.18.1
Sophisticated Core: 1.18.1-0.2.5.28
Sophisticated Backpacks: 1.18.2-3.17.2.588

**Mod List**
Corail Tombstone
Corail_31
tombstone-7.4.6-1.18.2.jar

Dynamic View[Forge]
someaddon
dynview-1.18.2-2.7.jar

Sophisticated Core
P3pp3rF1y
sophisticatedcore-1.18.2-0.2.5.28.jar

Additional Structures
XxRexRaptorxX
Rex's-AdditionalStructures-1.18.2-(v.3.0.3).jar

Akashic Tome
Vazkii
AkashicTome-1.5-20.jar

Apotheosis
Shadows_of_Fire
Apotheosis-1.18.2-5.3.5.jar

AppleSkin
squeek502
appleskin-forge-mc1.18-2.4.0.jar

Aquaculture 2
Shadowclaimer
Aquaculture-1.18.2-2.3.6.jar

Architectury API (Fabric/Forge)
shedaniel
architectury-4.4.68.jar

ATO - All the Ores
ATMTeam
alltheores-1.9.9a-1.18.2-40.1.0.jar

Auto Ore Dictionary Converter
MattDahEpic
autooredictconv-1.18.2-18.0.2.jar

AutoFish for Forge
NorthWestWindNWW
forgeautofish-4.1.0-1.18.2.jar

AutoRegLib
Vazkii
AutoRegLib-1.7-53.jar

Balm (Forge Edition)
BlayTheNinth
balm-3.0.3+0.jar

Bamboo Everything (Forge)
Gaz_
bambooeverything-1.2.7-build.14+mc1.18.2.jar

Better Advancements
way2muchnoise
BetterAdvancements-1.18.2-0.2.0.129.jar

BetterF3
cominixo
BetterF3-1.2.5-Forge-1.18.2.jar

BlockUI
H3lay
blockui-1.18.2-0.0.47-ALPHA.jar

Bonsai Trees 3
davenonymous
bonsaitrees3-3.1.0.jar

Bookshelf
DarkhaxDev
Bookshelf-Forge-1.18.2-13.0.13.jar

Botania
Vazkii
Botania-1.18.2-432.jar

Carry On
Tschipp
carryon-1.18.2-1.17.0.8.jar

Champions
TheIllusiveC4
champions-forge-1.18.2-2.1.5.4.jar

Cloth Config API (Fabric/Forge)
shedaniel
cloth-config-6.2.62-forge.jar

CoFH Core
TeamCoFH
cofh_core-1.18.2-1.6.3.19.jar

Comforts (Forge)
TheIllusiveC4
comforts-forge-1.18.2-5.0.0.4.jar

Configured
MrCrayfish
configured-1.5.3-1.18.2.jar

Controlling
Jaredlll08
Controlling-forge-1.18.2-9.0+19.jar

Create
simibubi
create-mc1.18.2_v0.4.1.jar

Cucumber Library
BlakeBr0
Cucumber-1.18.2-5.1.1.jar

Curios API (Forge)
TheIllusiveC4
curios-forge-1.18.2-5.0.7.0.jar

Domum Ornamentum
OrionOnline
domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar

Enchantment Descriptions
DarkhaxDev
EnchantmentDescriptions-Forge-1.18.2-10.0.3.jar

Farmer's Delight
vectorwing
FarmersDelight-1.18.2-1.1.1.jar

Farsight [Forge]
someaddon
farsight-1.18.2-1.9.jar

Fast Leaf Decay
olafskiii
FastLeafDecay-28.jar

FastFurnace
Shadows_of_Fire
FastFurnace-1.18.2-6.0.3.jar

FastWorkbench
Shadows_of_Fire
FastWorkbench-1.18.2-6.0.2.jar

FerriteCore (Forge)
malte0811
ferritecore-4.2.1-forge.jar

Flywheel
jozufozu
flywheel-forge-1.18-0.6.2.jar

FTB Backups 2
FTB
ftbbackups2-forge-1.18.2-1.0.10.jar

FTB Library (Forge)
FTB
ftb-library-forge-1802.3.6-build.119.jar

FTB Ultimine (Forge)
FTB
ftb-ultimine-forge-1802.3.3-build.55.jar

Goblin Traders
MrCrayfish
goblintraders-1.7.2-1.18.2.jar

Immersive Engineering
BluSunrize
ImmersiveEngineering-1.18.2-8.0.1-147.jar

Just Enough Items (JEI)
mezz
jei-1.18.2-9.7.0.195.jar

Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.18.2-0.14.1.170.jar

Libnonymous
davenonymous
libnonymous-2.1.0.jar

Mantle
mDiyo
Mantle-1.18.2-1.9.20.jar

MattDahEpic Core (MDECore)
MattDahEpic
mdecore-1.18.2-18.0.1.jar

Mekanism
bradyaidanc
Mekanism-1.18.2-10.2.2.462.jar

Mekanism Additions
bradyaidanc
MekanismAdditions-1.18.2-10.2.2.462.jar

Mekanism Generators
bradyaidanc
MekanismGenerators-1.18.2-10.2.2.462.jar

Mekanism Tools
bradyaidanc
MekanismTools-1.18.2-10.2.2.462.jar

MineColonies
H3lay
minecolonies-1.18.2-1.0.737-RELEASE.jar

Mod Name Tooltip
mezz
modnametooltip-1.18.1-1.18.0.jar

Mouse Tweaks
YaLTeR
MouseTweaks-forge-mc1.18-2.21.jar

Multi-Piston
H3lay
multi-piston-1.18.2-1.2.7-ALPHA.jar

Mystical Agradditions
BlakeBr0
MysticalAgradditions-1.18.2-5.1.1.jar

Mystical Agriculture
BlakeBr0
MysticalAgriculture-1.18.2-5.1.0.jar

Nether's Delight
lumpazl
NethersDelight-1.18.2-2.2.0.jar

NetherPortalFix
BlayTheNinth
netherportalfix-forge-1.18-9.0.0.jar

Patchouli
Vazkii
Patchouli-1.18.2-69.jar

Placebo
Shadows_of_Fire
Placebo-1.18.2-6.4.0.jar

PneumaticCraft: Repressurized
desht_08
pneumaticcraft-repressurized-1.18.2-3.2.3-84.jar

Quark
Vazkii
Quark-3.2-357.jar

ReAuth
TechnicianLP
ReAuth-1.18-Forge-4.0.0.jar

Serene Seasons
TheAdubbz
Serene Seasons-1.18.2-7.0.0.13.jar

Sophisticated Backpacks
P3pp3rF1y
sophisticatedbackpacks-1.18.2-3.17.2.588.jar

Sophisticated Storage
P3pp3rF1y
sophisticatedstorage-1.18.2-0.1.1.35.jar

Structurize
H3lay
structurize-1.18.2-1.0.399-RELEASE.jar

The One Probe
McJty
theoneprobe-1.18-5.1.0.jar

Thermal Cultivation
TeamCoFH
thermal_cultivation-1.18.2-1.6.1.9.jar

Thermal Expansion
TeamCoFH
thermal_expansion-1.18.2-1.6.1.11.jar

Thermal Foundation
TeamCoFH
thermal_foundation-1.18.2-1.6.2.27.jar

Thermal Innovation
TeamCoFH
thermal_innovation-1.18.2-1.6.1.10.jar

Thermal Integration
TeamCoFH
thermal_integration-1.18.2-1.6.0.6.jar

Thermal Locomotion
TeamCoFH
thermal_locomotion-1.18.2-1.6.0.6.jar

Tinkers Construct
mDiyo
TConstruct-1.18.2-3.5.0.17.jar

TrashSlot
BlayTheNinth
trashslot-forge-1.18.1-11.0.2.jar

Waystones
BlayTheNinth
waystones-forge-1.18.2-10.0.0.jar

Xaero's Minimap
xaero96
Xaeros_Minimap_22.8.2_Forge_1.18.2.jar

Xaero's World Map
xaero96
XaerosWorldMap_1.22.0_Forge_1.18.2.jar

**Comment by P3pp3rF1y** [comment]
fix in the latest release on curseforge
