### ISSUE TITLE
JEI add to crafting table missing

### ISSUE THREAD

**Issue by prof-ion** [P3pp3rF1y/SophisticatedBackpacks#494]
Since updating to 1.18.2 version of SophisticatedBackpacks I can no longer quick add items to the crafting table in a backpack. The button isn't even there. 
However the button still exists in all other crafting tables I have checked. 
Double checked and have the latest of sophisticated backpacks and core, as well as JEI. 

Minecraft version 1.18.2
Forge 40.1.31
Sophisticated Core 0.2.6.30
Sophisticated Backpacks 3.17.2.588
JEI 9.5.5.174

**Comment by P3pp3rF1y** [comment]
that's because you have version of JEI that's more than 2 months old. just update to JEI version 9.7.0+ (first such release was 2 months ago)
