### ISSUE TITLE
Backpack showing inventory/hotbar incorrectly

### ISSUE THREAD

**Issue by Cormac777** [P3pp3rF1y/SophisticatedBackpacks#496]
**Describe the bug**
When opening the backpack, my inventory rows are displayed in the wrong order. Every row of my inventory, including my hot bar, has been shifted up by 1. 

![image](https://user-images.githubusercontent.com/107157838/172737661-219872e2-cb33-482f-9d32-f39b50b57278.png)

![image](https://user-images.githubusercontent.com/107157838/172737721-d965b0d9-404b-4048-92e0-9188bd0abee0.png)

**To Reproduce**
1. Open backpack - inventory is different in backpack from how it looks when opening inventory 

**Expected behavior**
It should look the same

**Screenshots**

**Versions**

sophisticatedbackpacks-1.18.2-3.17.2.588.jar as part of Better Minecraft Plus 1.18.2

**Comment by P3pp3rF1y** [comment]
just update to the latest version of sophisticatedcore. this issue is solved for a few weeks now
