### ISSUE TITLE
Adv. Compacting Upgrade not working

### ISSUE THREAD

**Issue by Merthew** [P3pp3rF1y/SophisticatedBackpacks#5]
I have the advanced compacting upgrade in by backpack and when I put a coal piece in the filter area and a stack of coal in the backpack, nothing happens. I have tried changing the allow/block option, the filter matching type, and i've left it alone for a while and it still isn't working.
![image](https://user-images.githubusercontent.com/23420800/100946479-6b6c4900-34d1-11eb-9ef4-228e5854fc53.png)
![image](https://user-images.githubusercontent.com/23420800/100946485-7030fd00-34d1-11eb-8383-d8e81bef8fa9.png)

**Comment by P3pp3rF1y** [comment]
It only compacts stuff when it's inserted using other means than gui - pickup / magnet upgrades or piped in when in block form.

The intention is that you can still keep uncompacted stacks in your backpack if needed - like in this case you may want to have a stack of coal handy to craft torches so you can put it in the backpack using gui and keep it there like that. I may change this in the future, but at the moment I feel this is the way it should work.
