### ISSUE TITLE
 Compatibbility with coloured tooltips

### ISSUE THREAD

**Issue by AlleCraft-alterego** [P3pp3rF1y/SophisticatedBackpacks#50]
can add compatibbility with any mod change tooltips ? when press shift button for view iten in backpack change tooltips from modded tooltips in vanilla tooltips 

https://www.curseforge.com/minecraft/mc-mods/coloured-tooltips

**Comment by P3pp3rF1y** [comment]
This is definitely bigger change and not super high priority so I will leave it open and take care of it later when I have time.

**Comment by P3pp3rF1y** [comment]
Just released new version which should support this.
