### ISSUE TITLE
[Bug]: Sophisticated Backpack shift-click tool to hotbar behaves in opposite manner than expected 

### ISSUE THREAD

**Issue by TheonlyTazz** [P3pp3rF1y/SophisticatedBackpacks#500]
**Describe the bug**

Weird thing with Sophisticated Backpacks.

In normal inventory, if I shift click an item from my inventory into my hotbar, it goes into the leftmost open slot on the hotbar.

However, (and annoyingly so), when shift clicking a tool from the backpack into my hotbar it goes into the rightmost empty slot in the hotbar.

Crash log if it's a crash.
Info on what other mods you're using that may cause a conflict here if applicable.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. empty the middle four slots of your hotbar, and put the cursor on slot 4 in anticpation of using the tool
2. test shift-clicking some tools from your inventory into the hotbar and you see they wind up in slot 4 if it's empty, ready to use
3. now press B to open your backpack
4. now test shift-clicking some tools into your inventory and you will see they wind up in slot 7 not slot 4 and now you have to either undo and use a number key to move the tool to the chosen slot, or mousewheel over to it to use it

**Expected behavior**
exactly as it works when doing it from personal inventory

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3908847/173345292-a020ee4e-4110-4d04-b09f-2cb2d691d208.png)
![grafik](https://user-images.githubusercontent.com/3908847/173345308-8a76d2b3-ca81-4ffb-b1da-bbd32348eabb.png)
![grafik](https://user-images.githubusercontent.com/3908847/173345326-19cbba44-6342-47ac-ad6d-bad9c38e916c.png)
![grafik](https://user-images.githubusercontent.com/3908847/173345343-29557aaa-a29b-4ef5-a6e1-57d7c4de5d05.png)

**Versions**
sophisticatedbackpacks-1.18.2-3.17.2.588.jar

**Additional Information**
This Issue has been submitted on the FTB Issue tracker for FTB Direwolf20 1.18
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/899

**Comment by P3pp3rF1y** [comment]
this is the exact same behavior as when shift clicking from any vanilla container (chest/barrel) so you would need to complain to Mojang if you want to have this changed, from my point of view I would much rather have backpacks consistent with any other container than have it consistent with just player's inventory handling.
