### ISSUE TITLE
Upgrade slots bar is too tall

### ISSUE THREAD

**Issue by NebelFox** [P3pp3rF1y/SophisticatedBackpacks#501]
**Describe the bug**
I decreased the size of each backpack to be a multiple of 9 (from 1 to 5 respectively), but left the upgrade slot counts the same. And now in the backpack UI the upgrade slots bar is higher than the actual backpack inventory. Moreover, on large UI scale it may go beyond the top of the screen.

**To Reproduce**
Steps to reproduce the first issue:
1. Set the size of a backpack in the config (e.g. 27)
2. Set the slots count of this backpack in the config to n, where the n satisfies `9 * n > backpack size` (e.g. 4)
3. Open this backpack in game
4. See the upgrade slots bar being taller than the backpack inventory.

Steps to reproduce the second issue:
1. Set the slots count of a backpack in the config to 9 or greater
2. Set the UI scale to 4 in game
3. Open this backpack in game
4. See the upgrade slots bar going beyond the top of the screen.

**Expected behavior**
Would like the slots to kinda wrap or form a grid, so their area doesn't exceed the height of the backpack main inventory

**Screenshots**
First Issue:
![](https://i.ibb.co/zfVtDnR/2022-06-15-20-53-55.png)

Second Issue
![](https://i.ibb.co/VCpS6Fb/2022-06-15-20-54-26.png)

**Versions**
Minecraft version used: `16.5`
Mod version used: `3.15.13.560`

**Comment by P3pp3rF1y** [comment]
Upgrades slots were redesigned a while ago in 1.18+ and can fit more slots and not break like this so closing
