### ISSUE TITLE
Items go into backpack without the pickup upgrade

### ISSUE THREAD

**Issue by CindersOfGreed** [P3pp3rF1y/SophisticatedBackpacks#503]
Items will go into the bag instead of the inventory without the pickup upgrade and it is only for one bag in the server unluckily its a diamond bag we've tried using a pickup upgrade to cancel it and it still goes straight into the bag, put down then picked up the bag same thing, rejoined the game and same thing not sure what to do.

**Comment by P3pp3rF1y** [comment]
if you put down this backpack and have a different one in your inventory does it still happen? Sounds to me like you have another modded item that just puts items directly into any item handler it finds

**Comment by CindersOfGreed** [comment]
> if you put down this backpack and have a different one in your inventory does it still happen? Sounds to me like you have another modded item that just puts items directly into any item handler it finds

Sorry for the late response but its on a server with my two friends and his diamond backpack alone automatically picks up things directly into his backpack no other backpack on the server does this we each have multiple bags because we gawk at the mod each time we play but its only his bag that does this we haven't added any major mods we only have about 14 if you have any idea of some way to fix this we'd be thankful.

**Comment by CindersOfGreed** [comment]
didnt mean to close it soryy

**Comment by CindersOfGreed** [comment]
update: he believes it was caused by the void upgrade but we still haven't found a way to fix it

**Comment by P3pp3rF1y** [comment]
void upgrade if set to overflow will try to fill one slot with the item. Is that what's happening for you?

**Comment by P3pp3rF1y** [comment]
anyway I will need exact steps on how to recreate or at the very least screen of the said backpack

**Comment by CindersOfGreed** [comment]
He made a new diamond bag and now threatens everyone who jokes about giving him a void upgrade like rabid dog in a corner. Problem solved he cant use void upgrade.
