### ISSUE TITLE
dupe or loss from backbacks

### ISSUE THREAD

**Issue by Divineaspect** [P3pp3rF1y/SophisticatedBackpacks#507]
**Describe the bug**
Backpack contents are resetting in a way which sometimes deletes items or dupes them.
My suspicion is that this is tied to backpack use on server when FTB backups 2 is running. 

**Versions**
Sophisticated Backpacks 1.18.2-3.17.2.588
Forge 40.1.30

**Comment by P3pp3rF1y** [comment]
Well that could potentially just affect it exactly during the backup which runs for several seconds usually so are you telling me you can recreate it only then? 
In my experience this usually happened when two backpacks got the same UUID by being duplicated or something similar. Does it happen to just one specific backpack or all of them and can you verify that UUID isn't the same as another one of your backpacks / backpack of another player? (F3 + h to view advanced tooltip)

**Comment by Divineaspect** [comment]
I'm saying that of the evidence we have, that at least three of the known cases happened when it was saving. Backup takes (tested for this) 160 seconds.
It's happening on non-dupe backpacks, which I know is true of mine at least.
I've poked the server members to check their glitchy backpacks and compare their own backpack uuids.

**Comment by P3pp3rF1y** [comment]
I didn't have too much time for this, but took a look at the code both in SB and in forge/vanilla/ftbbackups and can't see any place where it could cause this kind of duplication through something like throwing away current state and reloading old one or similar. Before I go ahead and start modifying FTB backups to be able to debug this can you by any chance try to recreate with just SB and FTB backups? Feels to me like there's another mod at play here which "optimizes" something on server that causes this.

**Comment by DiggityMan420** [comment]
i have a dupe in if u have the backpack inside a backpack addon and make a few backpacks the the tag ends up being the same as another one (they will stack inside the backpack) whatever u put in that backpack will end up in both and if u pull them out and open them up u can take both items out and place them back in your backpack to do it agian

**Comment by DiggityMan420** [comment]
when i get a few mins ill try and make a exact on how i did it no commands just plain old crafting and logging in an out on getting the tags the same

**Comment by P3pp3rF1y** [comment]
a while ago I made it impossible to stack backpacks by default and if this config is turned off the stack backpacks can't be open or items right clicked into them so that also takes care of the issue so I am closing this.
