### ISSUE TITLE
Strange crash after updating inventory count. 

### ISSUE THREAD

**Issue by Nesetalis** [P3pp3rF1y/SophisticatedBackpacks#514]
I attempted to set netherite backpack to 144 slots, but in world it shows only 12x10 backpack grid, upgrade slot count I set to 9, but shows only 6. 

```
	#Netherite Backpack Settings
	[common.netheriteBackpack]
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 144
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 9
```
Results: 
![backpack](https://user-images.githubusercontent.com/3489557/175862076-fcd45416-c62f-4d05-9801-7f729546be77.png)

Using version 1.18.2-3.17.5.602 with forge version 1.18.2-40.1.52

Edit: actually, it's showing 7 upgrade slots. But the backpack is nested in the first slot... if you try to take it out, game crashes. This was after I opened my backpack, then opened a new one I spawned in. I also noticed in the picture my inventory was empty, except it was not. 
When I opened it a second time, it showed 144 slots, but 2 backpacks in the top left. That was when I tried to grab one of those backpacks, and the game crashed. 
[crash-2022-06-26_23.51.38-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/8988763/crash-2022-06-26_23.51.38-client.txt)

I also relogged in to my server, and... everything was working as intended, 144 slots, 9 upgrades, and no odd backpack dumped in the corner. So... odd.

**Comment by P3pp3rF1y** [comment]
have you opened that backpack at least once before you updated the slot counts?

**Comment by Nesetalis** [comment]
that backpack was spawned in via JEI/NEI/REI whatever, after the config was updated.

**Comment by P3pp3rF1y** [comment]
closing old issues, this one likely was something related to curios desync I remember fighting with back in the day. anyway it doesn't seem to be happening anymore (haven't heard anything on that for at the very least 1 year)
