### ISSUE TITLE
Lost all my backpacks after update

### ISSUE THREAD

**Issue by MainComDX** [P3pp3rF1y/SophisticatedBackpacks#518]
Hi 

I updated from 1.18 to 1.19 and all my backpacks dissepeard, is there somthing that can be done to get them back?

**Comment by brisingraerowing** [comment]
Probably not. Upgrading modded worlds between major versions is generally unsupported, for reasons such as what you experienced.

**Comment by P3pp3rF1y** [comment]
I haven't really changed storage format, but I can't vouch for things like forge or anything else not changing how this works. If you can consistently recreate that a pack that consists only of backpacks which gets upgraded to 1.19 will get contents cleared I may take a look but it definitely is a low priority as many mod devs use major updates to change underlying stuff making upgrades between versions impossible so just having backpacks like wouldn't be enough anyway.

**Comment by P3pp3rF1y** [comment]
closing as I can't guarantee stability between major versions so if this works it's a plus but if it doesn't it just means a need to restart on a new version and that's it
