### ISSUE TITLE
Backpacks not scaling correctly

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedBackpacks#519]
**Describe the bug**
Without any other mods installed, the bigger backpacks' GUIs are bigger than what can fit in the screen (especially with the netherite backpack)

The only workaround is reducing your GUI scale.

**To Reproduce**
1. Open the bigger backpacks
2. Check that part of the menu can't fit in the screen

**Expected behavior**
A backpack menu with the correct scaling according to the one defined in the Minecraft's settings

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/108262327/177711015-c3d06f8c-2887-4656-b02c-bc42847096fd.png)

**Versions**
sophisticatedbackpacks-1.16.5-3.15.15.607
forge-1.16.5-36.2.35

**Comment by P3pp3rF1y** [comment]
This is solved in 1.18+ with scrollable inventory and I am not going to port that back to 1.16. You will need to use different scaling there.
