### ISSUE TITLE
Add Netherite backpack with more upgrade slots

### ISSUE THREAD

**Issue by Lystraeus** [P3pp3rF1y/SophisticatedBackpacks#52]
Thank you for your mod. Best backpack mod for 1.16, imho.

I'm finding the diamond backpack slot limit very restrictive. I suggest this mod adds a netherite upgrade, which doesn't add inventory space (diamond is ample), but another 1 or 2 upgrade slots.

**Comment by P3pp3rF1y** [comment]
just released new version with this.
