### ISSUE TITLE
Crashes before the game even opens, Java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by SuperSly12** [P3pp3rF1y/SophisticatedBackpacks#522]
**Describe the bug**
[crash-2022-07-09_Im_Gonna_Kms.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9077909/crash-2022-07-09_Im_Gonna_Kms.txt)

**To Reproduce**
1. Place mod in mod folder
2. Launch game 

**Expected behavior**
The game to open

**Screenshots**
![Screenshot 2022-07-09 165714](https://user-images.githubusercontent.com/109001023/178122449-03ecdc25-9976-448d-8970-4e070e6a53f0.png)

**Versions**
Forge 1.19

**Comment by P3pp3rF1y** [comment]
Please make sure that you update the mod before reporting something like this - you're using a very early 1.19 version of SB that doesn't work with newer versions of forge hence why there are updated versions of mod on curseforge
