### ISSUE TITLE
can't even play over 1.19.41.0.64

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/SophisticatedBackpacks#527]
java.lang.reflect.InvocationTargetException: null keeps popping up on every version higher than 1.19.41.0.64 even when i change versions and there's no way i can play over 1.19.41.0.61. please fix this if you can.

**Comment by P3pp3rF1y** [comment]
there is a version of backpacks for version .84+ and I have just added another one for .96+ so it's just a matter of updating the mod
