### ISSUE TITLE
Dropping Backpack Crashes Game

### ISSUE THREAD

**Issue by IchBinTimothy** [P3pp3rF1y/SophisticatedBackpacks#529]
**Describe the bug**
Dropping the backpack as an item to float in the world crashes the game.
No other mods added; only SophisticatedBackpacks and its relevant Core Mod.

**To Reproduce**
1. Obtain Backpack
2. Drop Backpack or Die
3. Not Stonks

**Expected behavior**
I expect the item to be droppable in the world as is.

**Versions**
sophisticatedbackpacks-1.19-3.17.12.626.jar
sophisticatedcore-1.19-0.3.9.63.jar

Forge Versions: 41.0.96 and 41.0.98

**Comment by IchBinTimothy** [comment]
Going into third person also seems to crash the game.

**Comment by Badger-c** [comment]
Adding to this, with https://pastebin.com/m8KcS1JR crash report from a completely clean install, with only core and backpacks installed. Was in creative, put an empty back pack in my tool bar then dropped it.

**Comment by IchBinTimothy** [comment]
Adding onto this again, going into third-person with the backpack in the main hand or the offhand causes a crash.

**Comment by P3pp3rF1y** [comment]
this is fixed in the latest version on curseforge
