### ISSUE TITLE
Experience Pump not taking any experience from player 

### ISSUE THREAD

**Issue by JackMidnightVR** [P3pp3rF1y/SophisticatedBackpacks#533]
**Describe the bug**
When having the Xp pump and tank upgrade it rarely takes xp from my player leaving the tank empty or i have to manually per buttom pump in any xp even if take from player is selected
**To Reproduce**
1.start any world
2.get backpack with tank and xp pump upgrade
3.give yourself some xp
4.it wont take them from your player

**Expected behavior**
Would take xp to fill the tank and repair stuff with mending

**Screenshots**

![2022-07-15_02 41 21](https://user-images.githubusercontent.com/33065711/179124078-a61aafc4-20cd-4bab-8b34-a4c80aea545e.png)

![2022-07-15_02 41 27](https://user-images.githubusercontent.com/33065711/179124089-f8105a29-60e7-4a3b-b7f2-00e644afb368.png)

**Comment by P3pp3rF1y** [comment]
How exactly are you getting your experience? This sounds like a bug where some mods don't properly update player's experience points and only update player levels which creates inconsistency and to xp upgrade it looks like player doesn't have enough experience in your case for those 50 levels that you want to keep on the player.

**Comment by P3pp3rF1y** [comment]
any additional info you can provide or should I just close?

**Comment by JackMidnightVR** [comment]
> any additional info you can provide or should I just close?

well got this problem fixed, found a new one with servers tho got my own server running with config changed of the mod but it wont change like i gave the entherite backpack 144 slots but its not in the server when i open the config its changed in it tho im confused

**Comment by P3pp3rF1y** [comment]
That issue with change of number of slots is likely that you opened backpack that was crafted / spawned in before the slot change. The changed numbers only apply to new ones.
