### ISSUE TITLE
Experience Tank Cap Limited

### ISSUE THREAD

**Issue by TopPercentageRattata** [P3pp3rF1y/SophisticatedBackpacks#536]
Netherite backpacks with a tank upgrade and experience pump upgrade reach some sort of hidden maximum level capacity with 1 T4 stack upgrade and the rest only T3 with the cap being around 4900.
This makes having more than 1 T4 upgrade in the backpack useless due to it having no benefit.

1. Place tank upgrade, xp pump upgrade, and 1 T4 sack upgrade into a netherite backpack.
2. Put T3 stack upgrades into rest of the upgrade slots.
3. Check level max capacity by hovering over tank on right.
4. Replace T3 stack upgrades with T4 stack upgrades
5. See tank capacity having 0 increase

Expected behavior:
T4 stack upgrades having a benefit besides the first

**Versions**
MC version: 1.18.2
Mod version: 3.17.10.621
Forge version: 40.1.60

**Comment by P3pp3rF1y** [comment]
yes there is a cap and that one is based on number of mB that can be stored in the tank and based on those the cap for xp levels is calculated which stands just above 4900
I don't really see a need to allow more levels, you can still add another tank in your backpack or have multiple backpacks with tanks if 4900 levels is something you can fill, but I have never seen anyone to be able to fill that and the most I have seen was about 2000 levels and that's still a very long way away from 4900

So this is not going to get changed
