### ISSUE TITLE
Crafting tab glitch when Shift-mousing over/away from other backpacks in normal inventory.

### ISSUE THREAD

**Issue by PaterFrog** [P3pp3rF1y/SophisticatedBackpacks#541]
**Describe the bug**
Holding Shift and moving the mouse onto or away from a backpack in your normal inventory causes the crafting tab to visually close, but not functionally.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Set tabs to remember open on reopen tabs
3. get Crafting upgrade for backpack (tested in Curio back slot)
4. have at least one more backpack in your normal inventory
5. Crafting tab open!
6. Hold SHIFT and mouse over and away from any of the backpacks in your normal inventory.
7. Alternatively, keep mouse over another backpack, and just click SHIFT
8. Crafting tab closes, and is now glitched:
9. Shift click items into CLOSED crafting tab,
10. Try to open and close crafting tab multiple times, watch it be stuck.

**Screenshots**
![BackpackInventoryCraftingShiftGlitch](https://user-images.githubusercontent.com/46433636/180002346-b5a2e646-b23b-4d11-b3aa-69a8734f8c13.gif)

**Versions**
Forge 40.1.54
JEI 9.7.0.226 (as the crafting tab affects the right side screen where the JEI item list is, this _may_ have something to do with it, though I find it unlikely)
Sophisticated Backpack 3.17.9.621 (I did just noticed an update only hours old, which I will be getting. The changelog does not mention any fix regarding this behavior though.)

**Comment by P3pp3rF1y** [comment]
The steps are pretty clear above but upon trying to recreate I am unable to. So it's very likely interaction with another mod that's causing this. Could you figure out which one it is and let me know?
Thinking about this it seems to me that the crafting table was borked even before you started shifting over the backpacks as it looks like they try to go in on client, but are not allowed on server and that's why the tab closes for you.

**Comment by P3pp3rF1y** [comment]
I am not able to recreate this one and have no additional info on how or reports from other players either so I am going to close. Feel free to reopen if you happen to recreate, but I will need steps on how I can recreate it myself.
