### ISSUE TITLE
Compressing upgrade mod conflict between Prefab and Compressium

### ISSUE THREAD

**Issue by Satork** [P3pp3rF1y/SophisticatedBackpacks#544]
**Describe the bug**
When inserting the compressing upgrade in the backup, if there are several mod recipies in conflict (which can be solved using other mods such as Polymorph), the compressing upgrade won't compress those blocks which recipies are in conflict.

Context:
- Prefab mod: includes a compress format of stone, which can be obtained by setting 9 blocks of either granite, andesite or stone. The compressed block is not reversable, so you can't get back the 9 blocks used to create the compressed block.
- Compressium mod: has reversable compress blocks for each block type.

Theoretically, if the Advanced compressing upgrade is used and the "only uncraftable" feature is selected, it should use the Compressium recipie. It does not do it. Stone will stack up in the backpack without compressing.

**To Reproduce**
1. Have installed Prefab mod and Compressium mod
2. Open backpack
3. Add Advanced Compressing Upgrade
4. Open the Advanced Compressing Upgrade tab
5. Select "Only Uncraftables" option
6. Add a stack of stone / granite / andesite
7. See how the stack won't be compressed to the Compressium recipie

**Expected behavior**
It is expected to get the stack of stone/granite/andesite being compressed to its compressed block format automatically.

**Versions**
Sophisticated Backpacks: v 3.15.15.607 - 1.16.5
Prefab: v 1.6.5.15 - 1.16.5
Compressium: v 1.2.3 - 1.16.5

**Comment by P3pp3rF1y** [comment]
The issue here is that the compacting logic only expects one result of the compacting and based on the result it gets it will then judge whether item is uncompactable. So this will require fairly significant refactoring to support multiple recipes and try to get best compacting result when multiple are present. I will take a look at it but probably not as one of the next things.

**Comment by P3pp3rF1y** [comment]
I made a change in newer versions of the mod to try different crafting results and figure out which one can actually be compacted uncompacted so marking this one as solved even though it's not for 1.16.5
