### ISSUE TITLE
CTD upon world load

### ISSUE THREAD

**Issue by CloWnicide** [P3pp3rF1y/SophisticatedBackpacks#547]
CTD upon world load after CTD of playing game.

**To Reproduce**
Step 1, Load world
Step 2. Crash

**Expected behavior**
No CTD

**Versions**
Forge: 40.1.68
Backpacks: 3.18.4.646

**Crash Report**
[crash-2022-07-25_20.41.50-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9186352/crash-2022-07-25_20.41.50-server.txt)

**Comment by P3pp3rF1y** [comment]
I will be totally honest that I don't understand how that issue can even happen for you - I have reviewed my code and even java internals and that should be impossible to happen. Which leads me to suspect some performance mod which may be doing stuff like adding multithreading in some place which can cause this or modifying java classes which can cause the issue as well. 

Anyway I am going to make a small change on my side which will stop the crash in this place for you, but I don't know what that other thing is changing there so even though you may not have crashes there may easily be an odd behavior happening - upgrades not working, items duplicating, disappearing, ...

**Comment by P3pp3rF1y** [comment]
There's new version on CF which has a code change which is probably going to help you here, but as said above not sure what other things you can expect if something like this is happening there.
