### ISSUE TITLE
[Suggestion 1.16.5] Please add support for demagnetizing mods

### ISSUE THREAD

**Issue by theboo** [P3pp3rF1y/SophisticatedBackpacks#55]
It would be very nice for SB to have support for both the demagnetize mod and botania's solegnolia.
Instructions for demagnetize mod compat can be found here: https://www.curseforge.com/minecraft/mc-mods/demagnetize , it is pretty simple..

And cyclic was able to add support for botania solegnolia flower in 1.16.x here: https://github.com/Lothrazar/Cyclic/pull/1614

**Comment by theboo** [comment]
apparently this is implemented already xD sorry about that

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this anyway, based on this issue I have added  support for Botania's Solegnolia

**Comment by theboo** [comment]
awesome, thanks!

**Comment by P3pp3rF1y** [comment]
just released a version that has the solegnolia support
