### ISSUE TITLE
[1.18.2] Crashing after opening backpack

### ISSUE THREAD

**Issue by INooBTooMuch** [P3pp3rF1y/SophisticatedBackpacks#550]
**Describe the bug**
When ever I press "b" to open backpack the game crashes.

**To Reproduce**
1. Open backpack
2. Crash

**Expected behavior**
Not crash

**Versions**
Forge : 40.1.68
Sophisticated backpack : 1.18.2-3.18.4.646
Core : 1.18.2-0.4.10.85

(I updated the core mod today too, I don't know if I played right after and crashed but it does crash now. Also downgrading to Core : 1.18.2-0.4.5.76 fixes the problem)

Log : 
https://gist.github.com/INooBTooMuch/ee146740f757d5b5dfa70afe43bd110b#file-gistfile1-txt

**Comment by MagisterXero** [comment]
Can confirm, direct crash log:
https://pastebin.com/m1z4FYVj

**Comment by P3pp3rF1y** [comment]
missed upload of the new SB version, just uploaded that to CF should be approved shortly

**Comment by P3pp3rF1y** [comment]
released on CF
