### ISSUE TITLE
Feeder upgrade reads baked potato as poisonous potato

### ISSUE THREAD

**Issue by BowBoy1** [P3pp3rF1y/SophisticatedBackpacks#554]
**Describe the bug**
The backpack's feeder upgrade reads a baked potato as a poisonous potato and can inflict poison upon potato consumption

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Insert a feeder upgrade and baked potatoes
3. The backpack will occasionally give you poison when the baked potato is eaten

**Versions**
Forge 40.1.60 on 1.18.2, mod version 3.17.10.621, sophisticated core version 0.3.7.59

**Comment by P3pp3rF1y** [comment]
It's the actual food that's giving you these effects - all that feeding upgrad does is tell the food to apply its hunger / saturation / effects to the player. So you either have poison potatos in the backpack as well (or some other poisonous food) or you are playing a modpack in which baked potatos have this additional effect. 
if you are able to recreate this with just baked potatos in backpack and SB as the only mod in the pack let me know

**Comment by P3pp3rF1y** [comment]
closing as there was no additional info provided
