### ISSUE TITLE
[1.16.5]The hotkey does not work together with the Essential mod

### ISSUE THREAD

**Issue by DrSigma4164** [P3pp3rF1y/SophisticatedBackpacks#555]
**Describe the bug**
When the Essential mod is installed, it recently got support for version 1.16, the backpack inventory open key doesn't work, meaning I can't open the inventory when it's in the inventory or curio slot with the hotkey.

**To Reproduce**
1) Install the Essential, Sophisticated Backpacks mods
2) Configure a hotkey for opening the backpack
3) Try to open the backpack. 

**Versions**
Minecraft: 1.16.5
Forge: 36.2.39
Sophisticated Backpacks: 3.15.15.607
Essential mod: They haven't uploaded the version for 1.16 on Curseforge yet, but here is the link to their official site: https://essential.gg/download

**Comment by DrSigma4164** [comment]
I would like to clarify that the backpack does not open specifically in the curio slots. In the breastplate slot or in the inventory, it opens.

**Comment by P3pp3rF1y** [comment]
Alright in that case please report to them as they are the cause of this issue.
