### ISSUE TITLE
[1.19-3.18.9.661] Flagged as non-client / server-only in CurseForge

### ISSUE THREAD

**Issue by TigerWalts** [P3pp3rF1y/SophisticatedBackpacks#558]
**Describe the bug**
When installing version `1.19-3.18.9.661` in CurseForge, or installing a modpack containing this version it will be disabled by default.

If installing a modpack, the mod will still be disabled even if it is enabled in the profile.

The `isCompatibleWithClient` flag is set to `false` for the file in the CurseForge database.

Previous versions have the correct setting.

**To Reproduce**
1. Create a custom 1.19 modpack in CurseForge
2. Add Sophisticated Backpacks `1.19-3.18.9.661`
3. Note that the mod is installed but disabled

**Expected behavior**
Mod to not be disabled when installed.

**Screenshots**
N/A

**Versions**
- Sophisticated Backpacks 1.19-3.18.9.661

**Comment by P3pp3rF1y** [comment]
I am not even sure where to find this `isCompatibleWithClient` flag, but just tried creating custom profile, added sophisticated backpacks and they are enabled by default so I will need more info on how I can recreate this?

**Comment by P3pp3rF1y** [comment]
closing as there was no additional info provided
