### ISSUE TITLE
[3.18.11] Client Crash when spawning Creeper with backpack

### ISSUE THREAD

**Issue by kipieslim** [P3pp3rF1y/SophisticatedBackpacks#559]
**Describe the bug**
Creepers with backpacks cause a client render crash

**To Reproduce**
1: Spawn a creeper with a backpack

**Expected behavior**
No crash

**Versions**
minecraft version: 1.18.2
forge version: 40.1.60
Sophisticated backpacks version: 3.18.11.664

**Stacktrace**
[crash-2022-07-31_12.11.01-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9228741/crash-2022-07-31_12.11.01-client.txt)

**Comment by rrusciguy** [comment]
Seeing exact same issue and stacktrace

**Comment by rrusciguy** [comment]
Issue persists, crashing each time you try to load the world.
rolling back to backpack version 3.18.9.659 allows the world to load.

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
