### ISSUE TITLE
JEI '+' button is only shown while items are missing

### ISSUE THREAD

**Issue by MatthiasMann** [P3pp3rF1y/SophisticatedBackpacks#56]
Using
sophisticatedbackpacks-1.16.4-2.2.0.171
jei-1.16.4-7.6.1.71
forge-1.16.5-36.0.40

With an iron backup and pickup upgrade in the top slot, and a crafting upgrade in the bottom slot.
The crafting grid is open (right side) with the arrow pointed down (player inventory).

When I open a recipe in JEI for a 3x3 craft (haven't tried 2x2 or shapeless) - the '+' button is shown when I'm missing items for the shown recipe. But once I have all items the '+' button is just gone from the JEI recipe page.

**Comment by Jeisecke** [comment]
Using
sophisticatedbackpacks-1.16.4-2.2.0.171
jei-1.16.4-7.6.1.71
forge-1.16.5-36.0.40

With an iron backup and pickup upgrade in the top slot, and a crafting upgrade in the bottom slot.
The crafting grid is open (right side) with the arrow pointed down (player inventory).

When I open a recipe in JEI for a 3x3 craft (haven't tried 2x2 or shapeless) - the '+' button is shown when I'm missing items for the shown recipe. But once I have all items the '+' button is just gone from the JEI recipe page.

Had another one written names [MatthiasMann](https://github.com/MatthiasMann)


I have a similar problem, only that I have no + at all when I select justenoughitems recipes and have the crafting field open in the backpack
I use the justenoughitems version
jei-1.19.2-forge-11.4.0.285.jar
and the version from sophisticatd backpacks

sophisticatedcore-1.19.2-0.5.15.142.jar

sophisticatedbackpacks-1.19.2-3.18.29.719.jar
