### ISSUE TITLE
[1.18.2] (3.18.11.664) Opening others' backpacks is still possible, even when disabled.

### ISSUE THREAD

**Issue by aethaerya** [P3pp3rF1y/SophisticatedBackpacks#560]
**Describe the bug**
Even with `allowOpeningOtherPlayerBackpacks = false`, players that do not have it set to false in their common config can still open other players' backpacks. This was tested with only Sophisticated Core and Sophisticated Backpacks.

**To Reproduce**
Simply try to open another player's backpack when on a server that has set `allowOpeningOtherPlayerBackpacks = false`.

**Expected behavior**
The config should sync to clients, removing any related settings, as well as opening functionality.

**Screenshots**
Not really required, I think.

**Versions**
* Forge Version 40.1.68
* Core Version 0.4.11.89
* Backpacks Version 3.18.11.664

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
