### ISSUE TITLE
Crafting Upgrade Grid Item Duplication

### ISSUE THREAD

**Issue by Alzarath** [P3pp3rF1y/SophisticatedBackpacks#562]
**Describe the bug**
Shift-clicking an item from the crafting grid to a partially filled slot in your inventory with a stack count that exceeds the target stack drops the difference in stacked items while keeping it in the Crafting Grid slot.

**To Reproduce**
1. Fill backpack and inventory with any items
2. Place 32 of the items you want to duplicate in a slot in your inventory
3. Place 64 of the items you want to duplicate in any of the backpack's Crafting Grid slots
4. Shift-click the stack of items from the Crafting Grid slot
5. 32 of the items are transferred to the inventory, 32 items remain in the Crafting Grid Slot, and 32 items are dropped from the player.

**Expected behavior**
Only up to the stack count of items are placed into the inventory, the rest remain in the grid.

**Screenshots**
[Screenshot Album](https://imgur.com/a/peVMAHR)

**Versions**
Minecraft 1.16.5
Forge 36.2.35
Sophisticated Backpacks 1.16.5-3.15.15.607
No other mods installed.

**Comment by P3pp3rF1y** [comment]
Is sophisticated backpacks the only mod in your modpack? If not have you got fastworkbench without replacement in the pack? That is cause of your issue in that case

**Comment by Alzarath** [comment]
As I mentioned I have no other mods installed. I noticed the issue in a larger pack, so I created a new setup where that was the only mod and got the most recent version to confirm it wasn't some conflict.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release on curseforge
