### ISSUE TITLE
[1.16.5] Backpack inventory is synced over all backpacks given with the starterkit mod.

### ISSUE THREAD

**Issue by ProsperCraft** [P3pp3rF1y/SophisticatedBackpacks#566]
**Describe the bug**
When using https://www.curseforge.com/minecraft/mc-mods/starter-kit to give players a blue backpack on start players can see items other players put in their backpacks, and take it, but the original player still has it as well.  
I don't see this behavior in 1.18.2 and I don't know if this is on the starterkit side or this one.

**To Reproduce**
1. Player gets a backpack on a dedicated server from the starterkit mod and puts things in it and puts it on their back and opens it with the hotkey.
2. Second player logs in and gets a backpack from the starterkit mod, and does the same thing and sees a copy of player 1's items.

**Versions**
starterkit_1.16.5-3.1.jar
sophisticatedbackpacks-1.16.5-3.15.15.607.jar

**Comment by P3pp3rF1y** [comment]
that backpack has UUID already assigned - if you don't open you shouldn't see backpack getting the id assigned, however there are some mods it appears that try to get into backpack inventory which forces it to get UUID so if that's your case best way is to edit it out from its nbt.
