### ISSUE TITLE
Bug when open backpack with curios mod

### ISSUE THREAD

**Issue by javierbentez** [P3pp3rF1y/SophisticatedBackpacks#568]
![image](https://user-images.githubusercontent.com/78614041/181646718-33f37202-07f7-4b64-bd1d-710fce0eb82b.png)
![image](https://user-images.githubusercontent.com/78614041/181646729-4961c9bf-21b5-41c1-becc-077efef954f7.png)

The bug is coming with that mods:
- Minecraft 1.16.5 Forge 36.2.39 (Mohist version)
- curios-forge-1.16.5-4.0.8.2.jar
- sophisticatedbackpacks-1.16.5-3.15.15.607.jar

_Originally posted by @SuperBabaFR in https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/384#issuecomment-1198685641_

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
