### ISSUE TITLE
Cannot open Backpack with V in Enigmatica 8

### ISSUE THREAD

**Issue by balloonhead** [P3pp3rF1y/SophisticatedBackpacks#569]
**Describe the bug**
Cannot open backpack with V had to switch it to MouseButton 5 which works.

**To Reproduce**
1. Open backpack with V

**Expected behavior**
backpack opens

**Screenshots**

**Versions**
Modversion: 1.18.2-3.17.10.621
Enigmatica 8 Version: 2.1.0

**Comment by P3pp3rF1y** [comment]
that would be because there's a conflict with something that you have bound to V so you will need to unbind that in controls
