### ISSUE TITLE
dupe bug

### ISSUE THREAD

**Issue by Knightnight123** [P3pp3rF1y/SophisticatedBackpacks#570]
**Describe the bug**
Apon adding Sophisticated Backpacks to my modpack one of my members noted that you can dupe using the bundle from another mod called "Corail Tombstone"  attached is a video demonstrating how it is done

**To Reproduce**
1. Open backpack with stack upgrade
2. stack Empty Enchanted bundles from mod Corail Tombstone
3. place item that you want to dup into the stack of bundles
4. then remove the bags individually and remove the duped items

**Screenshots**
how about a viedo?
https://youtu.be/Uk6ehhf_29k

**Versions**
Minecraft 1.18.2,  mod ver's 3.18.13.666

**Comment by P3pp3rF1y** [comment]
that bundle just needs to be added to `nonStackableItemsList` in the config
