### ISSUE TITLE
Jukebox upgrade playing music globally instead of around the player.

### ISSUE THREAD

**Issue by rpop0** [P3pp3rF1y/SophisticatedBackpacks#571]
**Describe the bug**
The jukebox upgrade plays the music globally to everyone and doesn't play it in the proximity of the player wearing the backpack/the backpack itself.

All mods present on the server:
- Vanilla Tools
- The One Probe
- JEI
- AE2
- Mekanism
- JAOPCA
- XAERO's Minimap
- Gravestone mod
- Croptopia
- Cooking for blockheads
- Citadel
- Alex's mobs
- SecurityCraft
- CC Tweaked
- Balm
- TrashCans
- CarryOn
- FallingTree

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Click on 'Jukebox' tab
3. Put disk in
4. Play the disk
5. Music plays globally instead of in the proximity of the backpack

**Expected behavior**
The music should only play around the player/backpack itself.

**Screenshots**
N/A

**Versions**
Forge 40.0.2
Sophisticated Backpacks 1.19-3.18.9.661
Sophisticated Core 1.19-0.4.10.87
Minecraft 1.19.1

**Comment by P3pp3rF1y** [comment]
Are you getting this with any disc playing there or just specific ones? And is it different from playing those in vanilla jukebox?

This very much looks like a disc having stereo sound which then is played globally by mc even when played in vanilla jukebox. I know that Alex's mobs had one like that.

**Comment by P3pp3rF1y** [comment]
Closing as this is very likely a modded disc that has music in stereo, an issue that needs to be fixed by them.
