### ISSUE TITLE
Etched Mod Compatability

### ISSUE THREAD

**Issue by HockeyZman2000** [P3pp3rF1y/SophisticatedBackpacks#572]
The custom music discs created using the Etched mod on 1.18.2 cannot be placed in the jukebox upgrade slot in the backpack. If this would be a possible thing to implement I would be eternally grateful!

**Comment by Pockett-Dev** [comment]
This is still an issue on 1.19.2

Hopefully support is added in the future :)

**Comment by P3pp3rF1y** [comment]
Given that we now have sounds stored in components in 1.21 if Etched ports it should use those and custom disks should just work in jukebox upgrade so I am closing this.
