### ISSUE TITLE
Smelting upgrade filter doesnt work

### ISSUE THREAD

**Issue by nikapaka00** [P3pp3rF1y/SophisticatedBackpacks#574]
Smelter upgrade filter doesnt work. I cant place the items that i dont want burn as fuel as bow. So when i turn on the addon it automaticly use bows as fuel and when it try place bows to filter i cant place to it. So i dont wanna lost my enchanted bows and i dont wanna have them in my normal inventory either.

game version : 1.16.5
mod version sophisticatedbackpacks-1.16.5-3.15.16.669.jar

**Comment by P3pp3rF1y** [comment]
top filter is only for items that are supposed to be smelted or not smelted and as bow can't be smelted into anything you can't filter it. The bottom filter is there for items that **can** be used as fuel so the only way for you to prevent using bows as fuel is to put in there what you actually want to use as fuel.
