### ISSUE TITLE
items gone from backpacks after a server crash

### ISSUE THREAD

**Issue by SpaceGazen** [P3pp3rF1y/SophisticatedBackpacks#575]
i have a server hosted locally and after we added a few mods the game crashed (like it does usually) but when it came back up all the items in everyone's backpacks were gone. ive looked around here for a solution but couldnt find one with the same problems as me (sorry if there is one and i missed it). 

im not very fluent with server stuff other then the basics so im gonna need easy to understand answers :)

i cant see the item contents in creative and the uuid attached to the backpacks are all different but none of them are an actual player uuid. 
![Base Profile Screenshot 2022 08 10 - 18 23 41 29](https://user-images.githubusercontent.com/111030414/184051803-ccc2ddfd-a827-4032-9d1f-6e525913d6c3.png)

also another problem which complicates things is that i cant make myself op on the server for some reason, it just kicks me. it just gives random errors every time that look like this
![Base Profile Screenshot 2022 08 10 - 18 52 27 84](https://user-images.githubusercontent.com/111030414/184051950-af26174f-21ce-4555-925d-e8bd04d35ff7.png)

these are the mods that were added and their dependencies (mods that were already in the files before the update but were still a dependency of a new mod are marked with "not new")

create additions
   - create (not new)
   -flywheel (not new)

create big cannons
   -create (not new)
   -flywheel (not new)

experience obelisk
   -GeckoLib

Music maker mod (xercamusic)
   -none

JustEnoughDrugz
   -none

TouHou Little Maid
   -JEI (not new)
   -Patchouli (not new)

Etched
   -Pollen

**Comment by P3pp3rF1y** [comment]
Sophisticated backpacks contents are saved in file called `sophisticatedbackpacks.dat` and what likely happened there was that the server crashed before it was able to successfully save into that file. You will need to restore the file from backup if you have any.
