### ISSUE TITLE
[Suggestion] Deposit items from backpack into an inventory whilst wearing the backpack

### ISSUE THREAD

**Issue by Nevrai** [P3pp3rF1y/SophisticatedBackpacks#577]
Whoops, hit enter too soon. Anyway, the deposit upgrade only works if you’re holding the backpack in your hand. I thought that it would let you sneak-right-click on an inventory to deposit items with the backpack on. Is this something that could be implemented? Would be fantastic and super convenient!

**Edit:** Found out there’s a key bind. Leaving this open because I still think it’d be nice if you could use sneak-right-click for this functionality as well, as that’s not possible with the key bind.

**Comment by P3pp3rF1y** [comment]
I don't see a difference between sneak right click vs using a keybind and sneak right clicking with empty hand will very likely conflict with other mods logic that they have for empty hand so I am not going to add this.
