### ISSUE TITLE
Compat with Ender Tanks (fluid multiplication issue)

### ISSUE THREAD

**Issue by Raidobw2** [P3pp3rF1y/SophisticatedBackpacks#582]
**Describe the bug**
If you use (right click) an Ender Bucket from EnderTanks https://www.curseforge.com/minecraft/mc-mods/endertanks on the tank bar, it multiplies the fluid quickly and can overflow
![image](https://user-images.githubusercontent.com/17010632/185242010-b4031749-d1ab-4d0e-8938-5d84d00e1739.png)
![image](https://user-images.githubusercontent.com/17010632/185242149-92bc1d49-e86a-4143-b365-0e9ba519daa7.png)

**To Reproduce**
1. Fill an Ender Bucket with at least 2 buckets' worth of a fluid
2. Open a backpack and put the Tank Upgrade into an upgrade slot
3. Grab the Ender Bucket in the inventory GUI and hover over the tank in the backpack
4. Right-click on the tank. It should now have 1,000mB worth of fluid in it
5. Right-click on the tank again. It should now have an amount close to the amount in the Ender Bucket when you started minus 1,000mB.
6. Keep right-clicking the tank. It will keep filling up with the amount in the previous step and will go beyond the tank limit

**Expected behavior**
No fluid dupe, or not having the possibility to right click with that Ender Bucket on the tank bar

**Screenshots**
Right click the Ender Tank against the tank bar to multiply fluids

https://user-images.githubusercontent.com/17010632/185245633-e0c2f027-43fd-4406-b4ad-a0c1b76d7e0d.mp4

**Versions**
MC 1.18.2
Forge 40.1.73
Sophisticated Backpacks `sophisticatedbackpacks-1.18.2-3.18.17.680.jar`
Sophisticated Core `sophisticatedcore-1.18.2-0.5.1.98.jar`
Ender Tanks `endertanks-1.18-1.11.7.jar` ( + requires lib dependency)

Relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1154

Thanks in advance for checking it out!

**Comment by P3pp3rF1y** [comment]
I made a minor modification on my side, but this is really an issue in ender tanks because when their fill method is called (yes in this case tank upgrade is actually trying to fill the ender bucket) they return negative value of the total amount of fluid in ender bucket. So my modification is to just ignore filled negative values, but this could be causing issues with other mods as well.

**Comment by Raidobw2** [comment]
Thank you! I'll properly report this to Ender Tanks then, thank you for the information as well
