### ISSUE TITLE
[1.18.1] Version question

### ISSUE THREAD

**Issue by Ullimunate** [P3pp3rF1y/SophisticatedBackpacks#585]
Is it possible to integrate your mod into version 1.18.1 of the Forge version soon?

Since I downloaded your mod for version 1.18.1 from a third-party site (not from CurseForge), an error occurs (example below), which is called even if this mod is the only one in the client.
![image](https://user-images.githubusercontent.com/112324101/187073308-f09692fc-75c7-484b-ac31-36091ce71b93.png)

**Comment by P3pp3rF1y** [comment]
1st thing - NEVER download any mods from any other site than curseforge or Modrinth unless mod developer specifically indicated that their mod should be downloaded from somewhere else.  You can even get malware installed on your machine that way. More info here - https://stopmodreposts.org/

And there are 1.18.1 versions on curseforge as well look in files where you can also filter by that specific version.
