### ISSUE TITLE
"rendering item"  crash

### ISSUE THREAD

**Issue by Farcry210** [P3pp3rF1y/SophisticatedBackpacks#588]
**Describe the bug**
Crash log if it's a crash.
Info on what other mods you're using that may cause a conflict here if applicable.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open creative inventory or trys to craft backpack
2. Game freezes and goes back to launcher
3. Gets exitcode -1 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/112445634/187320862-65bb8a00-aa8b-4720-ba84-dba0c49d0bbf.PNG)

**Crash report**
[crash-2022-06-12_02.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9448555/crash-2022-06-12_02.txt)

**Versions**
CurseForge: 43.1.3
Sophisticated Backpacks: 1.19.2
Sophisticated Core: 1.19.2

**Comment by P3pp3rF1y** [comment]
you need to report this to twilight forest as their code is crashing and I see no relation to sophisticated backpacks other than that they are also in your modpack with many other mods.

**Comment by Farcry210** [comment]
sophisticated backpacks is the only mod I am using at the moment

**Comment by Farcry210** [comment]
mod*
