### ISSUE TITLE
dupe glitch

### ISSUE THREAD

**Issue by Adapron** [P3pp3rF1y/SophisticatedBackpacks#589]
so the game crashed and i think that i got two backpack with the same id or something

https://drive.google.com/file/d/1MSPbPLeg-m8Sef9md2-dOH7mhHsSt9v3/view?usp=sharing

i think the video explains it all perfectly. i can send you the mc world and you can try it yourself.

**Comment by P3pp3rF1y** [comment]
I can't solve issues related to crashes as that's then dependent on what is actually saved, what other mods are doing etc. The only way would be if you have a repeatable way of crashing the world and getting duplicate backpack with just SB. And the other thing is that in the latest release this would be automatically taken care of once you open one of those backpacks - second backpack gets its UUID removed and thus will be empty when you open it.

**Comment by Twisted-Code** [comment]
what version adds the check for cloned backpacks? Think I might be running an old version since I ended up with a clone from restoring an inventory backup (and was about to report it as a bug, since it was allowing for duping the contents)

**Comment by P3pp3rF1y** [comment]
I don't recall which one that was. But 1.18 and 1.19 have it for sure for those past 5 months

**Comment by Twisted-Code** [comment]
... Nevermind, I guess. Assuming the fix is part of Backpacks, not Core, I'm on build 671, released almost a month before this issue was even opened... I'll open an issue with FTB since it's their pack; hopefully they are still maintaining it, as I don't really feel like dealing with dependency hell myself.
