### ISSUE TITLE
Curse of Vanishing deletes entire backpack, not just cursed item

### ISSUE THREAD

**Issue by ignis444** [P3pp3rF1y/SophisticatedBackpacks#594]
If you place an item with the curse of vanishing into a backpack, upon death, entire backpack and all items in it get deleted, not just the cursed item.

1. Open backpack
2. Place cursed item with curse of vanishing in backpack
3. Die

Instead of just the cursed item being deleted like would normally happen in your inventory, entire backpack is deleted. 

Version 1.19.2
Forge 43.1.3

**Comment by P3pp3rF1y** [comment]
cursed of vanishing can't do that. Have you got curios in your pack? have you checked if your backpack is in your back slot in curios?
