### ISSUE TITLE
Setting Item Display breaks inventory UI

### ISSUE THREAD

**Issue by Strana** [P3pp3rF1y/SophisticatedBackpacks#597]
1.18.2, Mod version 3.18.24.704, Core version 0.5.9.115

When using large sized backpacks (Backpacks that have a scrollbar), its inventory acts as though it's over top the player inventory, causing unintentional selection of items that aren't in view.

This is demonstrated in this video:
https://user-images.githubusercontent.com/34879226/189096999-4ba20f16-906d-4955-ab61-957d0cdb4779.mp4

In the video I also try to shift+click items in my inventory to move to the backpack, yet nothing happens, likely because it's acting as though I'm clicking the empty spaces in the backpack inventory.

Reproduction:
Have items in both your inventory, and in the lower part of a backpack inventory (must be a large backpack that has a scrollbar), these items in the backpack should be hidden when you scroll back up in the backpack inventory, make sure to have a different item in your inventory compared to the item in the backpack so you can tell the difference.

Try clicking around the top of your inventory where the hidden items of the backpack inventory should be hidden behind.
![1](https://user-images.githubusercontent.com/34879226/189098059-e18d2c7b-e0e6-4d37-a430-f433a72ee316.PNG)
You may notice you are selecting the items in the backpack, not your inventory.

If you scroll the backpack inventory a bit and try selecting the items in your inventory again, the issue may stop happening, but only temporarily, as it will happen again once you open the backpack again.

**Comment by P3pp3rF1y** [comment]
I will need more information on how to recreate this - I am unable to and when I double check the code there's certainly a code part in there that moves any slots that are not displayed away from the screen so that they cannot be clicked on like in your case. 

So I am guessing that some mod interaction is doing this? Can you recreate without any other mods? If so what steps can I take to recreate? And if you find that a mod interaction does it feel free to let me know as well I can take a look and see if there's anything I need to change or they would need to

**Comment by Strana** [comment]
I have moved all my mods to a stand-by folder, and have tested with only the mod and its core installed, this issue does not occur during this test.

I will test this in combo with other mods to find the cause of the issue.

Update- This gets strange, after testing it, adding my mods back one-by-one, I haven't ran into the issue, not even using shaders is causing it, this is on a freshly made superflat test world.

**Comment by Strana** [comment]
@P3pp3rF1y 
Okay so this gets even _more_ stranger...
I try to reproduce this with all my mods + shaders again, in the test world which I mentioned: This issue does _not_ occur

BUT, if I open my survival world and then try moving things, this issue _does_ occur suddenly.

https://user-images.githubusercontent.com/34879226/189541362-fcd6db54-71d7-49b0-bf98-cf2edf15deb7.mp4

**QUICK UPDATE: I think I have found a lead, in my test world, I decided to set an item display slot (the thing to display an item on the physical model), and I have successfully reproduced the issue, so this may be the cause.**

Except if I disable the item display slot, the issue still persists, even if I close and re-open a world, so it seems as though setting an item display slot will completely break the UI for that particular world permanently, by the looks of it.

**Comment by Strana** [comment]
>QUICK UPDATE: I think I have found a lead, in my test world, I decided to set an item display slot (the thing to display an item on the physical model), and I have successfully reproduced the issue, so this may be the cause.
>
>Except if I disable the item display slot, the issue still persists, even if I close and re-open a world, so it seems as though setting an item display slot will completely break the UI for that particular world permanently, by the looks of it.

I have made a new test world, and replicated the issue by doing exactly as described, but this time I recorded it, and I'll search the log for the session to see if there's anything in there.

https://user-images.githubusercontent.com/34879226/189542217-aff85c50-1a3b-46f7-8501-ea78b15fc52e.mp4


>I have made a new test world, and replicated the issue by doing exactly as described, but this time I recorded it, and I'll search the log for the session to see if there's anything in there.

I couldn't find anything related in the logs.

**Comment by P3pp3rF1y** [comment]
You're right, I am able to recreate in dev now as well. I will get this one fixed soon

**Comment by Strana** [comment]
@P3pp3rF1y
This has been marked as fixed but this issue is still present in the latest version of the mod available on the CurseForge page (3.18.29.718 - Published one day ago as of writing this).

Is this fixed in a version that isn't yet available?

EDIT - Nevermind, the fix is in the core, which is just confusing. You should clarify that, mate.

**Comment by P3pp3rF1y** [comment]
yup it is in core as this is shared functionality between backpacks and storage. I got a little lazy on closing tickets this time so I haven't included this comment here and this time it would actually help a lot🤦‍♂️
