### ISSUE TITLE
backpack doesn't stay with me after I die

### ISSUE THREAD

**Issue by SlimJordi** [P3pp3rF1y/SophisticatedBackpacks#599]
when I die the backpack no longer stays in my inventory and is left behind with all of my loot, please help fix this since all of my users in my server are having the same problem, if you go back to your death spot the backpack is still there, but the whole point of it was to save your loot when you die so you don't lose it

**Comment by P3pp3rF1y** [comment]
you have curios in your pack? have you checked the back slot in there? graveyard mods try to put any curios items in there first so even if you didn't have backpack in that slot you will find it there after death

**Comment by P3pp3rF1y** [comment]
as discussed on Discord backpack isn't supposed to stay on after you die so what you experienced in the past is likely a bug connected to some other mod
