### ISSUE TITLE
Crash con nuevas versiones de Core

### ISSUE THREAD

**Issue by kaiza19** [P3pp3rF1y/SophisticatedBackpacks#600]
**Describe the bug**
Buenas no hablo ingles por lo que necesitaran traducirlo, El bug y crasheo ocurre cuando actualizo el Sophisticatedcore a la última version, al tratar de abrir o ver el inventario de la mochila el juego crashea y se cierra

**To Reproduce**
1. actualiza el mod sophisticatedcore-1.19.2-0.5.1.97 a una version más reciente como la sophisticatedcore-1.19.2-0.5.9.117 para poder utilizar Sophisticated Storage
2. el juego carga normalmente y el servidor sin errores
3. al precionar la tecla asignada para abrir el inventario del mod o abrir algun almacenamiento donde contenga las mochilas del mod el juego crashea

**Expected behavior**
Creo que al actualizar el core se les debio olvidar probar la compatibilidad del mod de mochilas con el nuevo core ya que con la version vieja que tenia si lo abre perfecto pero el storage pide una version mas nueva del core por lo que no puedo instalarlo

**Comment by P3pp3rF1y** [comment]
I don't speak Spanish but what I can understand here is that you have only updated sophisticated core, you need to update sophisticated storage as well, just updated them both to the latest and you're good. if you're having more issues I will need steps in English and actual crash log.

**Comment by kaiza19** [comment]
Tenias razon, me falto actualizar el mod de Backpacks, gracias y disculpa la molestia, buen trabajo
