### ISSUE TITLE
Backpacks with Magnet Upgrade Pick up Items after Death

### ISSUE THREAD

**Issue by PraseodymiumSpike** [P3pp3rF1y/SophisticatedBackpacks#604]
**Describe the bug**
I am using the Do I am cake? modpack by Tamaized. In it, there is a Mod called Twilight Forest that adds Items that are kept after Death. These include the Tower Key, the Phantom Chestplate, and the Phantom Helmet. When one of these is in the Inventory or Hotbar, the Backpack is kept on Death if it is in the Curios Back slot. If it has a Magnet Upgrade in it and turned on, the Magnet Upgrade continues pulling Items into the Backpack while the Player is Dead.

**To Reproduce**
1. Open Backpack
2. Place Magnet Upgrade in Backpack
3. Obtain a Tower Key, Phantom Helmet. or Phantom Chestplate from Twilight Forest Mod
4. Place another Item such as Dirt somewhere in Inventory
5. Die
6. The other Item such as Dirt pops out of Player's Body upon Death and is immediately sucked up by the Backpack
7. Respawn
8. Tower Key is still in Inventory (intended), Backpack is on Back (unintended), Dirt is in Backpack (very unintended)

**Expected behavior**
It is very difficult to state what is supposed to happen as there are 3 different Mods interacting in this case. However, I think a simple fix would be to have Dead Players' Backpack upgrades no longer function.

**Versions**
[Do I am cake?](https://www.curseforge.com/minecraft/modpacks/do-i-am-cake/files/3954737)

**Comment by P3pp3rF1y** [comment]
So as for backpack staying on the player there's nothing in SB that could do that so you will need to look for a different mod in that case. However I can take a look at not running magnet logic once player is dead which it seems that in this case after player dies there's one more tick run when that happens.
