### ISSUE TITLE
[Feature/Bug] Autofeeder config blacklist for food / minimum nutrition

### ISSUE THREAD

**Issue by jeremiahwinsley** [P3pp3rF1y/SophisticatedBackpacks#607]
Originally reported here: https://github.com/AllTheMods/ATM-7/issues/1499

There is an issue with the autofeeder upgrade and Botania mana in a bottle, where it will continuously consume them and dump bottles everywhere. I think this requires stack upgrades + a full backpack but I haven't done much testing. 

I would like to request configs for either or both of:
- blacklist for individual food items
- minimum nutrition for autofeeder (since mana in a bottle is edible but has no nutrition)

**Comment by P3pp3rF1y** [comment]
I went for an additional check that makes sure that item has at least some nutrition for it to be considered a food that can be fed. This is now fixed in sophisticated core dev version and I will hopefully release very soon.
