### ISSUE TITLE
Backpacks not opening only in server not in single player worlds

### ISSUE THREAD

**Issue by NachoLibre998** [P3pp3rF1y/SophisticatedBackpacks#613]
Using a mod pack mod and not opening at all unless I place and open on the server, but confirmed it does work in single-player.

Made sure no key bind conflicts.

**Comment by P3pp3rF1y** [comment]
What version of the mod have you got? 
In what slot are you trying to open it with keybind? Have you tried putting it in any other slot and opening it in there?
Does right clicking on the backpack in your hotbar open it?

**Comment by P3pp3rF1y** [comment]
there was no follow up and i am sure this is workign with so many players playing so closing
