### ISSUE TITLE
Fluid tank makes world unplayable

### ISSUE THREAD

**Issue by ItzLucaGER** [P3pp3rF1y/SophisticatedBackpacks#615]
**Describe the bug**
Filled fluid upgrade of a netherite backpack with water. (When replicating 3 was enough). After picking it up the game crashed instantly, same when re-entering the world

**To Reproduce**
1. Fill backpack with water (3 buckets at least for me)
2. Pick it up

**Versions**
I used version [1.19.2-3.18.29.719]

I also attached 2 of the crash reports. 

[crash-2022-10-01_17.22.25-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9691046/crash-2022-10-01_17.22.25-client.txt)
[crash-2022-10-01_17.23.35-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9691047/crash-2022-10-01_17.23.35-client.txt)

(Edit: Uploaded wrong file, also ignore what happened in the comments, first time using Github)

**Comment by ItzLucaGER** [comment]
I noticed one of the crash reports was wrong

**Comment by ItzLucaGER** [comment]
I found out that it was (apparently) optifine's fault. Removing it made the world playable again. At least I think it was optifine's doing, not sure if any other factors counted in towards the crashes.

**Comment by P3pp3rF1y** [comment]
ahh, right. Optifine is messing with vanilla code here and needs to adjust to the latest forge changes not to break this, that's definitely on them.
