### ISSUE TITLE
Error while starting up the server

### ISSUE THREAD

**Issue by Keruj47** [P3pp3rF1y/SophisticatedBackpacks#617]
After restarting server this error poped off
![unknown](https://user-images.githubusercontent.com/58606900/193467596-b440b9a0-58a0-495e-a33a-c173c7b7c310.png)
Which apparently caused whole server to be broken
![](https://cdn.discordapp.com/attachments/916726304475328542/1026179684863578222/unknown.png)
This is all the screenshots I've got and friend (who is hosting) had to reinstall everything

**Comment by P3pp3rF1y** [comment]
looks like your config got corrupted just delete it and start again
