### ISSUE TITLE
Incorrect localization for feeding upgrades

### ISSUE THREAD

**Issue by Nevrai** [P3pp3rF1y/SophisticatedBackpacks#618]
The feeding upgrade and advanced feeding upgrades have incorrect localizations (lower case “u”s).

![y76QbRc](https://user-images.githubusercontent.com/59761487/193832526-c1d504fc-174f-4718-982c-efa3e26acdbc.png)

### Versions
* **Minecraft:** 1.18.2
* **Sophisticated Backpacks:** 3.18.29.718

**Comment by P3pp3rF1y** [comment]
closing, the fix was released back in December
