### ISSUE TITLE
Game crash when trying to use upgrade

### ISSUE THREAD

**Issue by juliesomething0** [P3pp3rF1y/SophisticatedBackpacks#620]
**Describe the bug**

i try to put coal into the HUD and it freezes and then crash 

When i put fuel in it crashes

[help.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9717353/help.txt)

**Versions**
1.16.5

**Modpack**

Modlist:

- Appleskin
- Better Nether Reforged
- Better End
- Botania
- Comforts
- Corpse
- Curios API
- Divine RPG (Official)
- Disenchanting(FORGE)
- Easy Villagers
- Fertilization
- Hwyla
- Inventory Sorter
- Inventory HUD+
- Journeymap
- JEI
- JER
- Mahou Tsukai
- Mekanism
- Mekanism: Generators
- Mouse Tweaks
- Oh The Biomes You'll Go
- Openblocks Elevator
- Ore Excavation
- Patchouli
- Refined Storage
- Refined Storage Addons
- RSinfinitybooster
- Sophisticated Backpacks
- SwingThroughGrass
- Visual Workbench
- Xp Tome
- Waystones

**Comment by P3pp3rF1y** [comment]
Please update your forge version, the one you're using is ancient and it's very likely that one doesn't have the method SB is expecting.

**Comment by juliesomething0** [comment]
i have that version for it to function with optifine 

![image](https://user-images.githubusercontent.com/115100855/194549636-3218e627-a289-4d10-a505-8720f2a6227d.png)
