### ISSUE TITLE
Game Crashes when Sophisticated Backpack picks up a Shift Broken Lootr Shulker

### ISSUE THREAD

**Issue by Subi-alt** [P3pp3rF1y/SophisticatedBackpacks#623]
**Describe the bug**
Singleplayer Game Crashes when Sophisticated Backpack picks up a Shift Broken Lootr Shulker
Crash log if it's a crash.
https://pastebin.com/Nr7DNG2V

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
Have a Sophisticated Backpack on with a pickup upgrade. (For reference, I had a netherite backpack with no other upgrades other than pickup).
Go to the end where there are Lootr shulker boxes.
Shift break one with a shulker dropping.
Have it picked up with the backpack.
See that you have crashed.

**Expected behavior**
The game should not crash

**Screenshots**

**Versions**
Forge: 40.1.80
Sophisticated Core: 0.5.13.132
Sophisticated Backpacks: 3.18.29.718
Lootr: 2.21.58

Modpack: TNP Limitless 5 version 2.24.0

**Comment by P3pp3rF1y** [comment]
Going to leave a dev note here - looks like Lootr uses caps to store its data rather than regular nbt and ItemStackKey doesn't consider this in hashcode calculation.

**Comment by P3pp3rF1y** [comment]
should be fixed in the latest version of sophisticatedcore on curseforge
