### ISSUE TITLE
Dupe Bug with Crafting Upgrade [edit: conflict with FastWorkbench Minus Replacement]

### ISSUE THREAD

**Issue by fahlur** [P3pp3rF1y/SophisticatedBackpacks#624]
**Describe the bug**
Crafting Grid upgrade appears to dupe items.

Was able to recreate for myself in..
- Single Player on Survival Mode with cheats disabled
- Multiplayer on Survival Mode without OP

**Reproduce Steps**
- Place item in backpacks crafting grid.
- Click result (Do not shift click, that works)
- Items should be in hand and a copy should of fell to the floor.

**Versions**
sophisticatedbackpacks 1.16.5 
3.15.18.698

**Comment by fahlur** [comment]
It appears it was caused due to a conflict with the mod [FastWorkbench Minus Replacement](https://www.curseforge.com/minecraft/mc-mods/fastworkbench-minus-replacement).

**Comment by P3pp3rF1y** [comment]
yeah that mod is bugged, just use a regular fastworkbench and you're good.
