### ISSUE TITLE
[1.19.2] Crash when configuring backpack locked slots

### ISSUE THREAD

**Issue by EvergreenSystems** [P3pp3rF1y/SophisticatedBackpacks#625]
**Describe the bug**
Crash when configuring locked and/or display slots in a backpack.
https://gist.github.com/Shedao-Shai/013b363e1de396ae25d00ea5cdb4fa93 

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Place backpack
2. Open, and lock a slot into a specific item (in my case it was stone)

**Expected behavior**
The backpack should have just accepted the configuration and been all fine and dandy

**Versions**
Sophisticated Backpacks: 1.19.2-3.18.29.719
Sophisticated Core: 1.19.2-0.5.12.130

Forge: 43.1.32

**Comment by EvergreenSystems** [comment]
I will note that this does not happen every time, its very intermittent

**Comment by P3pp3rF1y** [comment]
@Shedao-Shai could you share more info on the backpack where you're trying to set this up? An idea that I have is that it could be related to frequent server>client updates that some upgrade may do for some reason and knowing more on what upgrades you have in there or how you're using them would help.

**Comment by EvergreenSystems** [comment]
The only upgrade present is a tier 4 stack upgrade (base backpack with 1
chests worth of slots), otherwise there is no upgrade present (crash
happens in both) and the backpack is placed in the world. What I am doing
is opening the backpack, placing an item in, locking the slot, then setting
that same slot as a display. It typically hangs when I try to lock the
slot, then crash moments later.

**Comment by P3pp3rF1y** [comment]
I am still not able to recreate and haven't got any other reports for this issue so I am guessing this is some odd mod interaction and I am closing the ticket. In case you can recreate with specific steps with just sophisticated mods or are able to get me info on what exact mod needs to be in the pack for this to break feel free to create new ticket with that info.
