### ISSUE TITLE
[1.16.5] Ticking player with magnet upgrade

### ISSUE THREAD

**Issue by khaos99X** [P3pp3rF1y/SophisticatedBackpacks#627]
**Describe the bug**
Having a problem with backpack when it has magnet upgrade and I can not narrow down what might be causing it besides the crash log mentioning the backpack magnet as it would work any other time without it. However when have it upgraded would immediately lock up and crash if I go to kill mobs rapidly.
Playing on a modpack called Age of Fate through curse

https://pastebin.com/SjVSXGXw 

**To Reproduce**
1. Install magnet upgrade
2. kill mobs
3. See error

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
1.16.5 MC
36.2.39 Forge 
1.16.5-3.15.18.698 Sophisticated Backpack

**Comment by P3pp3rF1y** [comment]
Fixed in the latest version of SB on curseforge
