### ISSUE TITLE
[1.19.2]Game Crashing 

### ISSUE THREAD

**Issue by Striker183** [P3pp3rF1y/SophisticatedBackpacks#629]
Good morning,
Unfortunately I get a crash every time I start the game with the mod. I have already tried to reinstall the mod and delete the configs. Everything was unsuccessful. I am also attaching a crash report.

Exit Code:
`The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "itemNames" is null`

Versions: 
Minecraft 1.19.2
Forge 43.1.47
SophisticatedBackpacks 3.18.29.719

Greetings,
Alex

[crash-2022-10-24_06.40.10-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9848853/crash-2022-10-24_06.40.10-client.txt)

**Comment by P3pp3rF1y** [comment]
this is fixed in the latest release of sophisticated core on curseforge
