### ISSUE TITLE
Editing CompoundTag while it is written to by packet

### ISSUE THREAD

**Issue by nullspeaker** [P3pp3rF1y/SophisticatedBackpacks#63]
See [this issue](https://github.com/NillerMedDild/Enigmatica6/issues/1409#issuecomment-786338463) from Enigmatica6.

We're also seeing it in a personal pack right after adding SophisticatedBackpacks, so I think this is correct.
(Personal pack version of SophisticatedBackpacks is latest release: `sophisticatedbackpacks-1.16.4-2.2.1.183.jar` from curseforge as of Feb 25.)

**Comment by MaxNeedsSnacks** [comment]
This should actually have been solved by https://github.com/P3pp3rF1y/SophisticatedBackpacks/commit/3893201b5a1fad6cfe6513410f0b63f864fa19b0 as the offending lines (https://github.com/P3pp3rF1y/SophisticatedBackpacks/blob/aa8323b62540a4557e40e7cfb5dbe2e78d0291f9/src/main/java/net/p3pp3rf1y/sophisticatedbackpacks/backpack/wrapper/BackpackWrapper.java#L140-L141) no longer exist after this commit.

**Comment by P3pp3rF1y** [comment]
yes it is solved in the latest version on CF.
