### ISSUE TITLE
Mekanism Canteen should be feeding upgrade usable!

### ISSUE THREAD

**Issue by UnhappyCodings** [P3pp3rF1y/SophisticatedBackpacks#630]
title tells the whole story. 
Mekanism has a item called "Canteen" where you put nutrition paste, made from food inside a machine, inside and it fills your whole food bar by one slurp.
would be cool to have!

**Comment by P3pp3rF1y** [comment]
Looking at canteen code base it's not marked as or behaving as food code-wise so that would need to be custom integration added for it. I will leave this here for some time, but don't see it as a very likely thing to be added.

**Comment by P3pp3rF1y** [comment]
closing as there are not other foods for which I need to have custom implementation and havent' heard of canteen since this issue was logged
