### ISSUE TITLE
multi backpack slowness nerf option only works in overworld

### ISSUE THREAD

**Issue by MCKyralina** [P3pp3rF1y/SophisticatedBackpacks#632]
**Describe the bug**
The config option to enable a nerf for carrying multiple backpacks only correctly applies the slowness effect to players in the overworld. Upon entering other dimensions the slowness will fade after a few seconds.

**To Reproduce**
1. Set the nerf as enabled in the config ( For reference I personally set it so than carrying more than 1 backpack would apply the slowness).
2. Go in-game and obtain multiple backpacks (In the overworld, you will have the correct slowness effect applied).
3. Go to any other dimension besides the overworld, the slowness effect will dissipate after a short few seconds.

**Expected behavior**
For the slowness debuff to be applied equally regardless of current dimension (Potentially including custom dimensions if possible).

**Screenshots**
N/A

**Versions**
sophisticatedbackpacks-1.18.2-3.18.29.718
sophisticatedcore-1.18.2-0.5.15.141

**Comment by P3pp3rF1y** [comment]
fixed in the latest release
