### ISSUE TITLE
Item locking not working

### ISSUE THREAD

**Issue by MajorGhosty** [P3pp3rF1y/SophisticatedBackpacks#634]
The item locking is not working at all. I clicked all the slots I want saved, moved them from the backpack to my inventory then back to the backpack and the slots were not saved

I added this mod to stoneblock 3

1. Open backpack
2. Click on settings tab
3. Click slot memory settings
4. Select slots to save
5. No slots are saved

Backpack slots are supposed to be saved

sophisticatedbackpacks-1.18.2-3.18.29.718

**Comment by P3pp3rF1y** [comment]
Just did exactly the same thing - added latest SB to latest stoneblock 3 and when I use and mark memory slots they memorize their stacks and then shift clicking puts the stacks into correct slots. So I will need more info on how exactly to recreate your issue.
When you mark the slots do you then see the ghost of the item in the slot if you remove the item from there?
Are you actually opening the memory settings tab before you start marking slots to be memorized? (marking them only works with that tab open)

**Comment by MajorGhosty** [comment]
I just updated to the latest version of Stoneblock and it's working. I don't know why but yesterday it was not working. I'm so sorry to have wasted your time. Thank you for your help.

**Comment by vinterdo** [comment]
Hi, just encountered the same bug: clicking on slots in memory settings didn't do anything. Vault Hunters 3 modpack. It fixed itself by leaving to the menu and reloading the world - after that, it worked fine.

**Comment by P3pp3rF1y** [comment]
actually in VH I found out how to recreate this issue - it only occurred to backpacks that were never moved from player's slot where they were open for the first time. This is fixed in the two latest releases of SB.
