### ISSUE TITLE
1.19.2 Server Crash

### ISSUE THREAD

**Issue by TobiDoes** [P3pp3rF1y/SophisticatedBackpacks#636]
**Describe the bug**
It's a crash. There are 6 other mods crashing along side yours 
Crash Report: https://pastebin.com/1mCicg0h
-Quark
-Create
-Ars Nouveau
-Occultism
-Immsersive Engineering
it is giving a "Registry Object not present: sophisticatedbackpacks:backpack" error but everything runs fine outside of a server Environment

**To Reproduce**
Start a Server using my mod pack Mystic Horizons

**Expected behavior**
A server to Launch

**Screenshots**

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
1.19.2-3.18.29.719

**Comment by P3pp3rF1y** [comment]
From what I can see there are multiple mods that have the same issue and at the same time all these mods including mine are used without issues on many servers. So you will need to figure out what's wrong with your modpack / server . 
I don't have time to debug someone else's modpacks and in this case I don't even see how my mod would be causing this issue. However if you find out some issue with my mod specifically feel free to report here.
