### ISSUE TITLE
1.18.2 Cobblestone appears in backpacks overwriting items??

### ISSUE THREAD

**Issue by xFirefalconx** [P3pp3rF1y/SophisticatedBackpacks#638]
**Describe the bug**
I am not sure if this is from Sophisticated backpacks alone, but during my time playing, I knew I had about no cobblestone in my inventory anymore. I happened to suddenly have TONS of cobblestone then. In my chest and in the backpacks. I first thought huh okay I had more than I thought but then I couldn't find my zombie flesh anymore? It was gone. I picked my items and put them from the "problematic chest" into my backpack. I had none in my backpack, zero cobblestone. Then I went back to building my monster farm, when I came back, I had over 800 cobblestones in one stack of my not upgraded backpack. I am scared to continue playing now. Losing progress is not cool... I though have no idea if it's from any of the other mods or caused by this mod, somehow overwriting my chests as well? If it's not this mod, please let me know if the latest log tells anything about a possible other cause so I can ask the devs there instead. 

There appears lots of cobblestone in chests and backpacks, even MORE than the backpacks can hold! Crazy high numbers. 
I don't know the trigger, if it's a certain game event or just... random ticks? Time? 

**To Reproduce**

I don't know, really... Play the game, have chests, put items in them like zombie flesh? See if it turns to cobble all of a sudden, maybe walk out of range of those chests, let them be loaded again and maybe kill monsters, build cobblestone walls or drop cobblestone? Place birch signs on cobblestone? Or place dirt? Cut down birch trees? Plant birch trees? Let them grow? A monster spawn? Maybe a monster dying of fall damage? Maybe a weird thing like exoticbirds tick or my croptopia plants growing? Maybe the chunk by chunk blocks? Or the cobblestone generator mod I am using? I have no blocks of that mod in my game world right now. 

I'm... clueless... but this is my scenario. Maybe I can upload my world somewhere? (Idk how or where)
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/9976789/latest.log)

**Mod list:**

[Forge/Fabric] BeehiveTooltips
EDToaster
beehive-tooltips-forge-1.4.2.jar

[SBM] Jukebox
StrikerRocker
SBM-Jukebox-1.18-1.0.4.jar

Akashic Tome
Vazkii
AkashicTome-1.5-20.jar

Anvil Tooltip
nero_surfing
anviltooltipmod-MC1.18.2-1.0.0.jar

AppleSkin
squeek502
appleskin-forge-mc1.18.2-2.4.1.jar

Architectury API (Fabric/Forge)
shedaniel
architectury-4.10.86-forge.jar

Auto Planting Forests
Lothrazar
autoplant-1.18.2-1.0.0.jar

AutoRegLib
Vazkii
AutoRegLib-1.7-53.jar

Bad Mobs
DarkhaxDev
BadMobs-1.18.2-13.01.jar

Balm (Forge Edition)
BlayTheNinth
balm-3.2.0+0.jar

Bamboo 2: Modded Boogaloo
callmeschmille
bamboo2-1.18.1_0.4.jar

Bamboo Everything (Forge/Fabric)
Gaz_
BambooEverything-forge-1.3.4-build.35+mc1.18.2.jar

Bee Fix
MacTso
BeeFix-1.18-1.0.6.jar

Beekeeper
MacTso
Beekeeper-1.18.2-1.0.0.4.jar

Benched
SuperMartijn642
benched-1.2.1-mc1.18.jar

Better Compatibility Checker
Gaz_
BetterCompatibilityChecker-1.1.16-build.39+mc1.18.2.jar

Better Fishing Rods
TrueRealCursed_Warrior
Better Fishing Rods 1.0.0 - 1.18.2.jar

Better Foliage Renewed
EERussianguy
betterfoliage-3.1.4.jar

Better Loading Screen
shedaniel
better-loading-screen-1.4.0.jar

Better Mending - Quilt/Fabric
Final_Production
bettermending-forge-1.2.1+1.18.2.jar

Better Safe Bed
frankv_
bettersafebed-1.18-forge-a.jar

Better Spawner Control (Forge)
Serilum
betterspawnercontrol_1.18.2-3.0.jar

Better Third Person
Socolio
BetterThirdPerson-Forge-1.18.2-1.8.1.jar

Bewitchment Plus
MrSterner_
bewitchmentplus-1.18.2-14.jar

Biome Spawn Point (Forge)
Serilum
biomespawnpoint_1.18.2-1.5.jar

Biomes O' Plenty
Forstride
BiomesOPlenty-1.18.2-16.0.0.109-universal.jar

Blueprint
TeamAbnormals
blueprint-1.18.2-5.5.0.jar

Book Fishing
TrueRealCursed_Warrior
Book Fishing 1.0.0 - 1.18.2.jar

Bookshelf
DarkhaxDev
Bookshelf-Forge-1.18.2-13.2.50.jar

Borderless Window
SgtSalocin
BorderlessWindow-1.18-1.4.0.jar

Carry On
Tschipp
carryon-1.18.2-1.17.0.8.jar

Chimes
BlewberryPie
Chimes-1.1.2-1.18.2.jar

ChinjufuMod +JapaneseBlock
鮎滝渉
ChinjufuMod[1.18.2]6.2.4.jar

Chunk By Chunk
dividesBy0
ChunkByChunk-forge-1.18.2-1.9.1.jar

City Decor
TzarAnthony
citydecor-1.1.1.jar (CURRENTLY DISABLED DUE TO BUG)

Cloth Config API (Fabric/Forge)
shedaniel
cloth-config-6.4.90-forge.jar

Clumps
Jaredlll08
Clumps-forge-1.18.2-8.0.0+15.jar

Collective (Forge)
Serilum
collective-1.18.2-5.15.jar

Configured
MrCrayfish
configured-2.0.0-1.18.2.jar

Controlling
Jaredlll08
Controlling-forge-1.18.2-9.0+22.jar

Cooking for Blockheads
BlayTheNinth
cookingforblockheads-forge-1.18.2-12.2.0.jar

Crated Vanilla Foods - Farmers Delight
thevillain_inc
Crated_Vanilla_Foods_1.1-1.18.2.jar

Creeper Confetti
SR2610
creeperconfetti-3.11.jar

Croptopia
thethonk
Croptopia-1.18.2-FORGE-2.1.0.jar

Croptopia's Chocolaterie [Forge]
slomax907
croptopia-chocolaterie-1.1.jar

deepslate dubble
TheluckyguyNL
deepslate_dubble003.jar

DisenchantingForge
chirptheboy
Disenchanting-forge-1.18.2-2.1.0.jar

Dungeon Crawl
xiroc_
DungeonCrawl-1.18.2-2.3.10.jar

Dynamic Surroundings Resurrected
theNyfaria
DynamicSurroundings-5.0.0.4.jar

Dynamic Trees
ferreusveritas
DynamicTrees-1.18.2-0.11.0-Beta3.jar

Dynamic Trees - Biomes O' Plenty
cadaverous_queen
DynamicTreesBOP-1.18.2-3.0.0-Beta1.jar

Dynamic Trees +
supermassimo0310
DynamicTreesPlus-1.18.2-0.1.0-Beta1.jar

Dynamic Trees Croptopia
thethonk
dtcroptopia-1.0.0.jar (CURRENTLY DISABLED DUE TO BUG)

Enchantment Descriptions
DarkhaxDev
EnchantmentDescriptions-Forge-1.18.2-10.0.9.jar

Ex Nihilo: Sequentia
NovaMachina
ExNihiloSequentia-1.18.2-20221109-230920.jar

Exline's Wool to String
exlinegames
wooltostring-forge-1.18.2-1.0.1.jar

Exotic Birds
ThePavoReality
exoticbirds-1.18.2-1.8.0.jar

Extended Item Information
Alexiy_Orlov
ExtendedItemInformation-4.0.2-1.18.2.jar

Farmer's Delight
vectorwing
FarmersDelight-1.18.2-1.2.0.jar

Farmer's Respite
lumpazl
FarmersRespite-1.18.2-1.3.0.jar

Farming for Blockheads
BlayTheNinth
farmingforblockheads-forge-1.18.2-10.0.2.jar

Fast Leaf Decay
olafskiii
FastLeafDecay-28.jar

Forgiving Void
BlayTheNinth
forgivingvoid-forge-1.18.1-6.0.1.jar

Game Menu Mod Option [Forge]
morimori0317
GameMenuModOption-1.18-Forge-1.14.2.jar

GeckoLib
ThanosGecko
geckolib-forge-1.18-3.0.54.jar

Guard Villagers
almightytallestred
guardvillagers-1.18.2.1.4.3.jar

Hedgehogs
orcinus73
hedgehog-1.18.2-1.1.0.jar

Honey Expansion (Add-on for Farmer's Delight)
Spiteful_raccoon
honeyexpansion-1.1.1.jar

Ignition: EnderBags
Shadows_of_Fire
EnderBags-1.18.1-8.0.0.jar

Info Datapack
GoryMoon
InfoDataPack-1.18.1-2.0.2.8.jar

ItemLocks
Kirdow
ItemLocks-Forge-1.18.2-1.3.jar

Jade 🔍
Snownee_
Jade-1.18.2-forge-5.2.5.jar

JEI Enchantment Info
Phylogeny
JEIEnchantmentInfo-1.17.1-2.0.0.jar

JourneyMap
techbrew
journeymap-1.18.2-5.8.5-forge.jar

Just Enough Items (JEI)
mezz
jei-1.18.2-9.7.1.255.jar

Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.18.2-0.14.1.171.jar

Keep My Soil Tilled (Forge)
Serilum
keepmysoiltilled_1.18.2-1.6.jar

Kiwi 🥝 (Forge)
Snownee_
Kiwi-1.18.2-forge-6.1.3.jar

Kotlin for Forge
thedarkcolour
kotlinforforge-3.7.1-obf.jar

Large Meals (An Add-on for Farmer's Delight)
LostWiz08
largemeals-1.18.2-2.0.jar

Level One
WatermelonFrogy
Level-One-MC1.18.2-v1.5.0.jar

Macaw's Bridges
sketch_macaw
mcw-bridges-2.0.5-mc1.18.2forge.jar

Macaw's Roofs
sketch_macaw
mcw-roofs-2.2.1-mc1.18.2-forge.jar

Macaw's Windows
sketch_macaw
mcw-windows-2.0.3-mc1.18.2.jar

Merge Enchantments [Fabric/Quilt & Forge]
Dplayend
merenc-forge-1.18.x-v1.9.jar

Mob Catcher [FABRIC/FORGE]
kwpugh
MobCatcher-Forge-1.18.2-1.1.6.jar

Mod Name Tooltip
mezz
modnametooltip-1.18.1-1.18.0.jar

Moonlight Lib
MehVahdJukaar
selene-1.18.2-1.17.9.jar

More MobGriefing Options
GeheimagentNr1
MoreMobGriefingOptions-1.18.2-2.0.1.jar

More Overlays Updated
RiDGo8
moreoverlays-1.20.9-mc1.18.2.jar

More_Advancements
ph5r0
advancement(r).jar

Mouse Tweaks
YaLTeR
MouseTweaks-forge-mc1.18-2.21.jar

Nature's Compass
Chaosyr
NaturesCompass-1.18.2-1.9.7-forge.jar

Oh The Biomes You'll Go
AOCAWOL
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7.jar

Overweight Farming
agentmhkskg
overweightfarming-1.18.2-1.6.0-forge.jar

Passive Endermen (Forge)
Serilum
passiveendermen_1.18.2-3.0.jar

Patchouli
Vazkii
Patchouli-1.18.2-71.1.jar

Pehkui
Virtuoel
Pehkui-3.6.0+1.18.2-forge.jar

Placebo
Shadows_of_Fire
Placebo-1.18.2-6.6.6.jar

playerAnimator
KosmX
player-animation-lib-forge-0.3.5.jar

Polymorph (Forge)
TheIllusiveC4
polymorph-forge-1.18.2-0.45.jar

Quark
Vazkii
Quark-3.2-358.jar

Regrowth
MacTso
Regrowth-1.18.2-1.40.0.31.jar

Simple Cobblestone Generator [FORGE]
Block_Legend001
simplecobblestonegenerator-1.18.2.jar

Skin Layers 3D (Fabric/Forge)
tr9zw
3dskinlayers-forge-1.5.2-mc1.18.2.jar

Skylight Lanterns
ferreusveritas
skylightlanterns-1.18.2-1.0.0.jar

Smooth Boot (Reloaded)
AbdElAziz333
smoothboot(reloaded)-mc1.18.2-0.0.1.jar

Snow! Real Magic! ⛄ (Forge)
Snownee_
SnowRealMagic-1.18.2-forge-4.2.3.jar

Snowy Spirit
MehVahdJukaar
snowyspirit-1.18.2-1.3.2.jar

So Many Enchants
yeetmanlord
so_many_enchants-1.7.0 (1.18).jar

Sophisticated Backpacks
P3pp3rF1y
sophisticatedbackpacks-1.18.2-3.18.29.718.jar

Sophisticated Core
P3pp3rF1y
sophisticatedcore-1.18.2-0.5.15.141.jar

Spells & Shields
CAS_ual_TY
spells_and_shields-1.18.2-1.9.1.jar

Spice of Life: Carrot Edition
lordcazsius
SoL-Carrot-1.18.1-1.12.0.jar

SuperMartijn642's Config Lib
SuperMartijn642
supermartijn642configlib-1.1.6-forge-mc1.18.jar

SuperMartijn642's Core Lib
SuperMartijn642
supermartijn642corelib-1.0.19-forge-mc1.18.jar

Supplementaries
MehVahdJukaar
supplementaries-1.18.2-1.5.13.jar

SwingThroughGrass
exidex
swingthroughgrass-1.18.2-1.9.1.jar

TerraBlender (Forge)
TheAdubbz
TerraBlender-forge-1.18.2-1.2.0.126.jar

Torchmaster
xalcon
torchmaster-18.1.0.jar

Tumbleweed
bconv
tumbleweed-1.18-0.4.12.jar

Vending Machine
MacTso
VendingMachine-1.18.2-1.0.0.7.jar

Village Bell Recipe (Forge)
Serilum
villagebellrecipe_1.18.2-1.4.jar

Village Employment
EnderPreston
village-employment-1.18.2-1.5.1.jar

Village Spawn Point (Forge)
Serilum
villagespawnpoint_1.18.2-2.9.jar

Villagers Respawn (Now with FORGE and FABRIC versions)
MacTso
VillagersRespawn-1.18.1-1.39.0.5.jar

Villagers Sell Animals
nocubeyt
Villagers_Sell_Animals_1.1.3_Forge_1.18.2.jar

Waystones
BlayTheNinth
waystones-forge-1.18.2-10.1.0.jar

Weapon Leveling
GeradesoLukas
weaponleveling-1.18.2-1.4.2.jar

XP From Harvest
ReaIGecko
XPFromHarvest-1.18.2-1.2.2.jar

XP Tome
bl4ckscor3
xptome-1.18.2-2.1.7.jar

**Expected behavior**
No cobblestone that suddenly shows up... My items stay where they belong and how many there are. 

**Screenshots**
This is... impossible, correct? I didn't put them there. The chest itself displays them as 64-stacks when I look at the chest with Jade Mod. 
![Unbenannt](https://user-images.githubusercontent.com/106652912/200983571-4d395332-617c-4bf5-9b90-fd4bae094767.PNG)

**Versions**
Mod 3.18.29.718
Forge 40.1.74

**Comment by xFirefalconx** [comment]
Edit: Cobblestone Generator mod seems to be the culprit here. Might still be a small incompatibility that those huge stacks appear.

**Comment by P3pp3rF1y** [comment]
Have you got that backpack set on top of cobblegen? Or you're telling me that it pushes into that remotely?

**Comment by xFirefalconx** [comment]
I had no cobblestone generator in my world, so no. It remotely filled anything that had an inventory. At random, that is. I have this video to check: [https://www.youtube.com/watch?v=cXAhz4Ru_EY](url)

**Comment by P3pp3rF1y** [comment]
Closing as this is a bug in another mod causing the issue.
