### ISSUE TITLE
(1.16.5) Coloring the backpack makes items vanish

### ISSUE THREAD

**Issue by WolWolffz** [P3pp3rF1y/SophisticatedBackpacks#64]
I was playing with a friend on local online and he decided to recolor his backpack. He forgot to take the items out of the bp before coloring it and the items vanished. I tried replicating the issue in singleplayer and, as you can see [here](https://youtu.be/FDq2lJ3ecMs), it is not related with the fact that we were playing online. What made me think is that items are still in the backpack until the moment you take it out of the crafting table slot, that's weird. RIP loot from a dungeon we explored.

**Comment by P3pp3rF1y** [comment]
What version of the mod have you got this issue with? the latest? sophisticatedbackpacks-1.16.4-2.2.1.183.jar I have made changes in that one that simplifies crafting recipes and that as a side effect solves some kind of incompatibility with some mod that affects crafting. Also there was an issue previously with coloring basic backpacks which was solved in the version before this one.

**Comment by WolWolffz** [comment]
Im using 1.16.4-2.2.0.171, i will update it and try to replicate the bug again, wait a sec.

**Comment by WolWolffz** [comment]
Ok it's fixed in the 2.2.1.183 version, thanks hah

**Comment by P3pp3rF1y** [comment]
alright closing this one then.
