### ISSUE TITLE
[1.19.2] Contents of nested backpacks sometimes getting erased

### ISSUE THREAD

**Issue by MojiRS** [P3pp3rF1y/SophisticatedBackpacks#642]
On a server during a normal playthrough, I had a backpack with the inception upgrade containing about a dozen other backpacks, most of which were filled with items. Upon relogging, several backpacks (including their items and upgrades) were empty - specifically all the backpacks placed past a certain slot/index in the main backpack inventory.

I attempted to recreate a very similar situation in a test world (12 backpacks within a main backpack, the nested backpacks filled with random items), and, when reloading the world, one of the backpacks did empty. I filled it with items again, reloaded the world, and it emptied again, so the bug seems somewhat reliable. However, it was the third of the twelve backpacks (instead of all backpacks past a certain index), and upon shuffling the main backpack inventory around a little bit, the bug stopped occurring. All the backpacks have unique UUIDs, and there are no other backpacks in the world.

This bug seems very similar and potentially related to [this issue](https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/410) that was reported a while ago.

Sophisticated Backpacks v3.18.29.719
Forge v43.1.38
[Modlist](https://i.imgur.com/F5wa44K.png)

**Comment by P3pp3rF1y** [comment]
closing old bugs, especially given I haven't heard about anything like this happening since then
