### ISSUE TITLE
Backpack Tanks Corrupt World

### ISSUE THREAD

**Issue by 2iqPlayss** [P3pp3rF1y/SophisticatedBackpacks#644]
Bug:
When using the tank upgrade for the backpacks picking up the backpack with liquid in the tank causes the game to crash and world can not be reopened without crashing.

Crash Report (hopefully this works I'm not 100% sure how to add files.)
[---- Minecraft Crash Report ----.pdf](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10079914/----.Minecraft.Crash.Report.----.pdf)

To Reproduce:
1. Place backpack in world.
2. Place Tank Upgrade in backpack.
3. Fill backpack with any liquid. (I used water)
4. Attempt to pick up backpack using shift (sneak key) + right click (use item button)

Expected Behavior:
I would expect that the backpack would just be picked up and put into the player's hand as it is without liquid in the tank. It works without liquid, just not with.

Mod Versions:
sophisticatedbackpacks-1.19.2-3.18.29.719
forge-1.19.2-43.1.43

[---- Minecraft Crash Report ----.pdf](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10079914/----.Minecraft.Crash.Report.----.pdf)

**Comment by P3pp3rF1y** [comment]
Drop Optifine and you're good.

**Comment by P3pp3rF1y** [comment]
And just to add a bit more explanation - Optifine doesn't care about mods and simply removes functionality that mods depend on causing them to crash. And I am getting a bit fed up with that happening especially given that there's nothing I can do on my side other than to start dropping functionality from my mod.
