### ISSUE TITLE
"Sort by Name" should respect renamed items

### ISSUE THREAD

**Issue by Naxum** [P3pp3rF1y/SophisticatedBackpacks#645]
Hello! I love Sophisticated Backpacks!

I was hoping to have a backpack that holds many toolboxes from Create, which I've individually dyed and named to represent their contents. But it seems when I "sort by name" in the backpack it sorts them based on their original item name. e.g. "Brown Toolbox" comes before "Purple Toolbox" even though I've renamed them to "1 Conveyors" and "2 Basic Machines."

My use case: I have a general order I want these toolboxes to be sorted, in which I can easily take them in and out of the backpack and leave ordering up to the sort button. Right now that doesn't seem possible.

It would be great if sorting by name respected rename item's names instead of their original names.

**Comment by P3pp3rF1y** [comment]
in the past sort by name used item registry name, but I changed this a while back to use the translation / custom name shown to the player so this was in fact fixed with that change.
