### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null - Sophisticated Backpacks

### ISSUE THREAD

**Issue by DeathTouch314** [P3pp3rF1y/SophisticatedBackpacks#649]
Updated to Forge 43.1.58 and new launcher, no issues yesterday at all. Updated Sophisticated Backpacks this morning and insta-crash. Tried to troubleshoot by deleting the MC install and reinstalled, same isue. Tried to roll back the version and I am still getting the same error. Tried to delete the JSON files and still crash. Disabling the mod allows me to get back into MC without issues.

As a side note, disabling the Core lib does not disable Sophisticated Backpacks, and enabling Sophisticated Backpacks does not enable the Core lib in CurseForge.

[crash-2022-11-29_11.19.11-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10116784/crash-2022-11-29_11.19.11-fml.txt)

**Comment by P3pp3rF1y** [comment]
As discussed in Discord this is BiggerStacks mod issue, please follow up with them
