### ISSUE TITLE
Client hard-crash when opening backpack with memory slot for specific items

### ISSUE THREAD

**Issue by hazardoushazik** [P3pp3rF1y/SophisticatedBackpacks#653]
**Describe the bug**
When using Tetra to create armor, tools, or weapons, if the item is placed in a sophisticated backpack and the respective slot is told to memorize the location of that item, this causes a hard crash in sophisticated core causing the client to exit.

**To Reproduce**
1. Open backpack
2. Place item from Tetra inside bag
3. Open memory tab and memorize slot with Tetra item

**Expected behavior**
Sophisticated backpacks should be able to memorize items from other mods.

**Screenshots**
N/A

**Versions**
sophisticatedbackpacks-1.19.2-3.18.33.742
sophisticatedcore-1.19.2-0.5.26.166

tetra-1.19.2-5.0.0-pre.7
tetrawear-1.19.2-0.0.0-pre.7

[tetra-1.19.2-5.0.0-pre.7.jar.zip](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10149142/tetra-1.19.2-5.0.0-pre.7.jar.zip)
[tetrawear-1.19.2-0.0.0-pre.7.jar.zip](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10149143/tetrawear-1.19.2-0.0.0-pre.7.jar.zip)

**Comment by P3pp3rF1y** [comment]
could you provide the crash that you're getting?

**Comment by hazardoushazik** [comment]
Its attached now, I totally forgot to include it in the ticket

[crash-2022-12-04_13.30.35-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10149483/crash-2022-12-04_13.30.35-client.txt)

**Comment by P3pp3rF1y** [comment]
I never responded to this but was some kind of issue where Tetra wasn't able to render item without nbt. Closing and if anyone runs into this in newer version they can report here or in Tetra tracker which actually has similar issue logged for the same crash with optifine shaders.
