### ISSUE TITLE
1.19.2 Mod conflict with BiggerStacks | Results in Sophisticated Backpacks not loading correctly & game crash

### ISSUE THREAD

**Issue by TheLifeSpice** [P3pp3rF1y/SophisticatedBackpacks#654]
**Describe the bug**
Cannot use mods Sophisticated Backpacks and [Bigger Stacks](https://www.curseforge.com/minecraft/mc-mods/bigger-stacks) at the same time.

**To Reproduce**
1. Fresh 1.19.2 Minecraft Instance
2. Install Forge version 43.1.7
3. Install Sophisticated Backpacks 3.18.33.742, Sophisticated Core 0.5.26.166, Curios API 1.19.2-5.1.1.0
4. Install Bigger Stacks 1.19.2-2.0
5. Launch game
6. See error

**Expected behavior**
The game to launch as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/78243562/205548133-4e7a43a9-308a-43b0-beba-c53cf5a3895f.png)

**Versions**
- sophisticatedbackpacs 1.19.2-3.18.33.742 
- sophisticatedcore 1.19.2-0.5.26.166 
- Curios API 1.19.2-5.1.1.0 
- biggerstacks-1.19.2-2.0
- Forge 1.19.2-43.1.7
[crash-2022-12-04_20.10.06-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10150585/crash-2022-12-04_20.10.06-fml.txt)

**Comment by P3pp3rF1y** [comment]
That's a bigger stacks issue, they change internal code in sophisticated and when I change naming in that internal code ro move some stuff around this happens so you need to complain to them. 
Also just from looking at their implementation quickly they just plain replace stack size limit with their limit which means stack upgrades do nothing.

**Comment by TheLifeSpice** [comment]
Sounds good, I'll let them know.

Thank you for your crazy fast response 👍
