### ISSUE TITLE
Existing items dont update with config changes

### ISSUE THREAD

**Issue by mihlek1** [P3pp3rF1y/SophisticatedBackpacks#657]
When you update anything on the sophisticatedbackpacks-common.toml the already created filters, backpacks, upgrades etc will NOT update.
It's even worse when on forge servers, cause you actually can see the slots, but they are unusable, in other words, ghost slots.

**To Reproduce**
Open game and get any backpack and magnets
Change magnet "filterSlots" (this was tested only making it bigger than before)
Change said backpack "upgradeSlotCount" (this was tested only making it bigger than before)

**Expected behavior**
All backpacks and upgrades should update with the config, so it doesn't cause desyncs (mainly online)

**Versions**
1.16.5-forge-36.2.34

The inventory slots "inventorySlotCount" problably would bug aswell, but I didn't tested it

**Comment by P3pp3rF1y** [comment]
Is this on multiplayer server and have you update the server? there are multiple modpacks that change the values for backpack inventory slots and upgrade counts that work without any issue so I would find it surprising if it didn't work suddenly without any change.

**Comment by P3pp3rF1y** [comment]
And have you actually changed the values and only then started the game? Forge configs sometimes can automatically change these values when the game is loaded but there's an issue where it many times doesn't seem to work and load of the game is required after changing the values.

**Comment by P3pp3rF1y** [comment]
Though I can certainly see an issue with magnet upgrade not respecting the number of slots if the client has different configs so I will fix that part, but most probably not for 1.16 as that I only support with super critical fixes and this is not one of them.

**Comment by mihlek1** [comment]
Im pretty sure the change went through, cause you could actually see the slots for the backpack, they just didn't worked. By example, if you added more upgrade slots, and put the workbench upgrade, it wasn't possible to craft using it, the items would simply bug, and once you changed the slot to one which already existed all the items would be inside it. Pretty confusing.
Yes it is in multiplayer, forge, everyone has the mod installed in the clientside

**Comment by villainous-j** [comment]
This thread is very old but I came here while looking for any report of the server configs not applying to clients.

I've changed the capacity and slot count for the Netherite backpack, and unfortunately the new values only seem to apply to newly created backpacks. Any pre-existing backpacks still use the old values. Is there a way to 'update' existing backpacks with the server's current config?

**Comment by P3pp3rF1y** [comment]
in 1.18+ there are now server configs that get properly synced to client so difference of number of slots is no longer an issue

And old backpacks not being updated with new slot settings is on purpose to prevent config related item lost even though I have a note to allow higher values to updated current backpacks. Anyway that's not what this issue was about and I am closing it.
