### ISSUE TITLE
Backpacks don't respect config

### ISSUE THREAD

**Issue by SpokenWig620933** [P3pp3rF1y/SophisticatedBackpacks#658]
**Describe the bug**
I try to change backpack size and upon opening a new backpack it glitch renders my new size once, then open again to find it hasn't changed the size. The config file doesn't load with the right sizes either, it loaded 27 & 1 as default on all the backpacks.

**To Reproduce**
1. Change config file backpack sizes
2. Open a new backpack
3. See it Glitches
4. Open again, see it hasn't changed

**Expected behavior**
The backpack size to change

**Versions**
*Dedicated Server*

forge-1.18.2-40.1.86

sophisticatedbackpacks-1.18.2-3.18.35.752
sophisticatedbackpacks-1.18.2-3.18.33.741
(I did not test on this version) sophisticatedbackpacks-1.18.2-3.18.32.736
(Works on this version) sophisticatedbackpacks-1.18.2-3.18.29.718

sophisticatedcore-1.18.2-0.5.32.179
sophisticatedcore-1.18.2-0.5.26.165
(Works on this version) sophisticatedcore-1.18.2-0.5.15.141

**Comment by mihlek1** [comment]
Created backpacks do not update their size, it's problably related to my issue [https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/657]

**Comment by SpokenWig620933** [comment]
I had specifically stated "new backpack" because of that reason. 

I know that current backpacks don't, and a good reason for that is so items in current backpacks dont get deleted.

So no, it is not related

**Comment by P3pp3rF1y** [comment]
Just tested this and it just works. Have you actually updated the configs on server in this case given that it's dedicated server? The symptoms that you mention definitely sound like only client has the updated configs.

**Comment by SpokenWig620933** [comment]
I did make sure the configs are updated.
I am currently using another version of the mod and it's working just fine, didnt touch the configs between version changes

**Comment by P3pp3rF1y** [comment]
well, that is even stranger then as it both works for me in dev and I haven't changed this part of the mod in a very long time and for sure no change was anywhere close to this in the last few updates.

**Comment by SpokenWig620933** [comment]
Ill Go at it again when I get home, see if it was some random thing that broke it.

I wouldn't be suprised if something broke when you did that memory saving change.

**Comment by SpokenWig620933** [comment]
When I had loaded the mod for the first time on the new version all the backpack configs said 27 & 1 unlike the version I said worked in my other modpack aswell

**Comment by SpokenWig620933** [comment]
I just upgraded versions and it seems to be working.
I have no clue why this happened as I did make sure the server had the configs, and I tried restarting the server after /reload didn't work.

**Comment by P3pp3rF1y** [comment]
> Ill Go at it again when I get home, see if it was some random thing that broke it.
> 
> I wouldn't be suprised if something broke when you did that memory saving change.

Plain making a change in unrelated part of the mod can't break the mod that easily. And as I said I can't recreate so I would rather think it's some kind of interaction with some other mod unless you can recreate with just sophisticated mods and in that case I will need to understand steps to recreate as the ones above just work.
