### ISSUE TITLE
[Bug]: Tabs don't stay rendered

### ISSUE THREAD

**Issue by SpokenWig620933** [P3pp3rF1y/SophisticatedBackpacks#663]
**Describe the bug**
https://github.com/P3pp3rF1y/SophisticatedCore/issues/67#issue-1497810501

**To Reproduce**
1.

**Comment by SpokenWig620933** [comment]
https://github.com/P3pp3rF1y/SophisticatedCore/issues/67#issuecomment-1370455392

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version of core on curseforge
