### ISSUE TITLE
JEI doesn't respect memory settings

### ISSUE THREAD

**Issue by SpokenWig620933** [P3pp3rF1y/SophisticatedBackpacks#664]
**Describe the bug**
When using JEI to input a recipe into the crafting table upgrade, it will move any items currently in the table to your backpack, including memory set slots, where only a certain saved item should go.

**To Reproduce**
1. Set your first slot to a axe or something in memory mode
2. Place some other random item in your crafting upgrade
3. use JEI to input a different recipe
4. See that the item is in that memorized slot

**Expected behavior**
For the item to pass over the memorized slot, and onto another one

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases

MC: 1.18.2
Forge: 40.1.86
JEI 9
Sophisticated-Backpacks: 752
Sophisticated-Core: 179

**Comment by P3pp3rF1y** [comment]
I must have fixed this a while ago and not update this issue because it works correctly now and doesn't override memorized slot so closing.
