### ISSUE TITLE
[1.18.2][BUG]The crafting and stonecutter GUIs close on their own

### ISSUE THREAD

**Issue by karikusa** [P3pp3rF1y/SophisticatedBackpacks#665]
Forge : forge-1.18.2-40.1.86
MOD : sophisticatedbackpacks-1.18.2-3.18.37.763
The GUI placed on the right side of the craft and stonecutter in the backpack of this MOD,
If you do crafting several times, the GUI will close without permission.
If you put an item inside the crafting grid, it will close as well.

**Comment by lilhappymuchsad** [comment]
I have the same problem and it's driving me nuts, it does only happen in my own mudpack tho mudpacks like create live 3 are totally fine maybe something with mouse tweaks ?

**Comment by karikusa** [comment]
I am also playing with MODPACKs that I have collected myself.
I tried to eliminate mouse tweaks just in case,
It doesn't change that the GUI closes on its own.

**Comment by karikusa** [comment]
It seems that the bug I reported was fixed when I installed the latest version! thank you! !

**Comment by karikusa** [comment]
It seems that the bug I reported was fixed when I installed the latest version! thank you! !
