### ISSUE TITLE
The arboreal extractor from thermal series stops extracting (Mc Ver.:1.19.2)

### ISSUE THREAD

**Issue by Z3bzonic** [P3pp3rF1y/SophisticatedBackpacks#672]
When installing sophisticatedbackpacks-1.19.2-3.18.40.775
The thermal series machine "Arboreal extractor" stops working.

**To Reproduce**
install sophisticatedbackpacks-1.19.2-3.18.40.775
since I am not aware what exact expansion the arboreal extractor is from I will list all:
install thermal_foundation-1.19.2-10.0.0.38
install thermal_expansion-1.19.2-10.0.0.19
install thermal_innovation-1.19.2-10.0.0.16
thermal_cultivation-1.19.2-10.0.0.15
thermal_locomotion-1.19.2-10.0.0.12

**Expected behavior**
I expected to have my existing machines to remain in working order.
Uninstalled SB(this.mod) and everything worked again.

**Screenshots**
no specific proof that is adequate for a screenshot

**Versions**
Forge version 1.19.2-43.1.1

**Comment by P3pp3rF1y** [comment]
Just tested this with just thermal stuff in modpack first and then sophisticated backpacks added and I can't recreate so I will need more info on that or it appears this may have been fixed on thermal side.

**Comment by Z3bzonic** [comment]
I have updated all mods and it seems to be ok now. So I assume it was something else going on indeed.
