### ISSUE TITLE
Backpack stops working after adding two mods

### ISSUE THREAD

**Issue by banana-boye** [P3pp3rF1y/SophisticatedBackpacks#674]
Although I have no screenshots due to the issue being resolved, I had added the nyf's beasts and vampirism mods to my server and then my friend was unable to store/remove items from his backpack, it would simply return to his cursor/backpack whenever he tried, after resetting the server it continued working like normal, the issue hasn't appeared again (happened two days ago, I didn't put up the issue due to wanting to see if it appears again or not).

**Comment by P3pp3rF1y** [comment]
I am going to close and please feel free to reopen when / if you are able to recreate and able to provide steps on how to recreate as this very likely was some other mod misbehaving and causing backpacks to not be openable and because of that I wouldn't be able to do anything with this issue.
