### ISSUE TITLE
Unsorting a full backpack with stack upgrades deletes items

### ISSUE THREAD

**Issue by pafflu** [P3pp3rF1y/SophisticatedBackpacks#675]
>         > Seems fixed. If the bug pops up again, I will reopen the issue.
> 
> I am having this problem as well 
> it is not the sort button it is the unsort button. 
> When I have a stacking upgrade in a backpack and accidentally hit shift and the center button (sort) it unstacks the stacks,  and half to 3/4 of my items disappear from the world permenantly.  This happened to me,  my husband and to both of us since all our storage is in backpacks placed in our home
> We would love to completely disable this feature until fixed if that is possible I came here looking for a way to remove the unstack feature 
> when one tries to remove a stacking upgrade with stacked items, it simply won't let you,   so this should simply not let you do it if there isn't room in the back pack but it does and it's bad enough that we will either have to not use stack upgrades or not use backpacks at all.
> 
> _Originally posted by @anastasia590 in https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/631#issuecomment-1374674955_

Steps to reproduce:

1. Put Stack Upgrades in Backpack
2. Fill backpack with various things
3. Hit "Sort Inventory" from "Inventory Sorter" (Shift + Middle Mouse Button in my case)
4. Bigger slots get split into many x64 slots. Overflowing items don't drop, they simply get deleted.

Workaround:

Unbind Sort inventory from the "Inventory Sorter" Mod, and you won't accidentally void half your things.

**Comment by P3pp3rF1y** [comment]
there's no way I can fix inventory sorter mod from backpacks so you have to work with that mod - remove it / unbind / try if the disabling specific screens is fixed there.
