### ISSUE TITLE
Backpack Crafting Table Closes When Interacted With

### ISSUE THREAD

**Issue by Darmandir** [P3pp3rF1y/SophisticatedBackpacks#676]
**Describe the bug**
While using the crafting upgrade, any insertion/removal of an item into the crafting GUI will cause the tab to close, except for removing items from the result box. This makes the crafting upgrade very difficult to use. The only mod I am using which also adds a crafting GUI is MineColonies, which it adds inside a separate workstation GUI screen.

**To Reproduce**
1. Open backpack
2. Click on Crafting tab
3. Place any item in the crafting table GUI slots
4. Tab closes

**Expected behavior**
Crafting table upgrade works as a normal crafting table would without closing upon interaction.

**Screenshots**

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
SB 1.18.2-3.18.40.773, forge 40.1.92

**Comment by MKingPP** [comment]
When you use a backpack to manually synthesize an item, click the item and the composition bar will automatically close. This problem exists in 773&777 versions.

**Comment by P3pp3rF1y** [comment]
Just released version with fix on curseforge
