### ISSUE TITLE
compacting upgrades interfere with pickup upgrade's "match Backpack contents" mode

### ISSUE THREAD

**Issue by Twisted-Code** [P3pp3rF1y/SophisticatedBackpacks#677]
**Describe the bug**
I noticed that, a little over a year ago, you fixed [a crash involving the pickup upgrade and compacting upgrade](https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/336). However, it seems these 2 upgrades still don't QUITE harmonize with one another. If you have the pickup upgrade set to "match bag contents", but end up picking up a number of one of the contained items such that the total is a multiple of 9 (or 4 in the case of 2 x 2 compacting), the pickup upgrade will stop picking up that item because the items it was matching got compacted.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Install the pickup upgrade (advanced pickup and the magnetic version might also work. However, from here on, I will only address the upgrade as "pickup upgrade" regardless of which one you actually use)
3. configure the pickup upgrade to "Match Backpack Contents"
4. Add at least 1 Redstone
5. Go mining or simulate it with random amounts of Redstone
6. pickup upgrade functions as normal, until you...
7. install advanced compacting upgrade. (note: this malfunction also occurs with the basic compacting upgrade, but this way you don't have to disable Compact Only Uncraftable[*] or get nether ores involved)
8. The moment you get 9/18/27/etc. Redstone, the pickup upgrade will stop working on Redstone

**Expected behavior**
One way or another, the pickup upgrade should continue picking up Redstone in this situation. I have two ideas how you could do this:
1. the easier option is to just have the compacting upgrade wait for one more item before compacting, so that it goes from 10 Redstone to 1 and you always have at least 1 Redstone in the backpack
2. the more SOPHISTICATED *rimshot* solution would be to somehow allow the pickup upgrades to remember items that were recently compacted even if there are 0 of them currently in the backpack. I suppose you could technically use the memory tab of the core backpack settings for this, but I would rather it "just work" without the player having to reconfigure the backpack each time they add an item that might be subject to compacting.

**Screenshots**
notice that I have 4 amethyst dust (from http://github.com/gamma-delta/HexMod) here:
![image](https://user-images.githubusercontent.com/7110033/211432259-a5f24ad1-f08a-4ce9-8b98-2513005f8095.png)
now, because of the compacting upgrade, I have 0 and the pickup upgrade will not pick up any more amethyst dust:
![image](https://user-images.githubusercontent.com/7110033/211432558-e2381753-75cb-4dc4-b887-557d389cf0fb.png)

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
Sophisticated Backpacks: 3.18.16.671
Forge: 40.1.84

**Comment by P3pp3rF1y** [comment]
This is actually working exactly as expected so there's nothing to fix. 
And there are ways you can get the behavior you want
- use allow filter in pickup upgrade
- set memorized slots for the items (pickup uses memorized slots item as filter even if these are empty)

**Comment by Twisted-Code** [comment]
@P3pp3rF1y Fair enough I guess, though it can be a little tedious to still have to configure the backpack each time I add something new. That's part of the reason I chose to use Match Backpack Contents. 
come to think of it, I have a feature request regarding the GUI tabs: can you try to make it possible to move them elsewhere in the backpack GUI (to reduce the tedium mentioned above)? I have a spinal cord injury, and they happen to be on the same side of the backpack as my on-screen keyboard. It's also kind of irritating that when a tab is open, it covers the button(s) for the tab(s) below it.....
