### ISSUE TITLE
Lava in Tank Upgrade crashes game

### ISSUE THREAD

**Issue by PurplePlight** [P3pp3rF1y/SophisticatedBackpacks#678]
**Describe the bug**
While putting lava inside a backpack with a Tank Upgrade the game will crash. After the crash, opening the game will cause the game to crash again after a few seconds. 

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'

**To Reproduce**
1. Open backpack
2. Place Tank Upgrade in upgrade slot
3. Place lava bucket in tank bar
4. Game Crashes

**Expected behavior**
Backpack should hold lava inside backpack without crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/122404456/211661124-4fdfb405-3df9-4ef4-a08d-34f1f73da645.png)

**Versions**
1.19.2
Sophisticatedbackpacks-1.19.2-3.18.40.775
Sophisticatedcore-1.19.2-05.37.198

**Comment by PurplePlight** [comment]
Upon further messing around it seems like one of my other mods caused the lava in the tank to crash the game. Not sure which one causes it to crash, but it's no fault with Sophisticated Backpacks, lol.
![image](https://user-images.githubusercontent.com/122404456/211665475-b8f656e5-f32c-41fb-9eba-dfe1df636842.png)

**Comment by P3pp3rF1y** [comment]
it's for sure optifine based on that error
