### ISSUE TITLE
Minecraft 1.19.2 realease is incompatible with my other mods

### ISSUE THREAD

**Issue by yeahboy234** [P3pp3rF1y/SophisticatedBackpacks#680]
So when i load up minecraft and check my resource packs floder on 1.19.2 it says it is incompatible with the current version of 1.19.2

**Comment by P3pp3rF1y** [comment]
I would need much more info than that - actual message / log / crash log. 1.19.2 version is used by tens if not hundreds of thousands of players so there's something special happening here for you.

**Comment by P3pp3rF1y** [comment]
closing as no additional info was provided
