### ISSUE TITLE
Backpack fills up by only two items per slot

### ISSUE THREAD

**Issue by totte1015** [P3pp3rF1y/SophisticatedBackpacks#684]
Really weird issue, look at my picture
![Namnlös](https://user-images.githubusercontent.com/32680625/212403555-5e8b2b13-886a-4ea2-b2d0-b84f67c9bd1a.png)

It only fills TWO items PER slot, and it does NOT keep filling, it stops working more or less

How to fix this?

**Comment by P3pp3rF1y** [comment]
what version is that? I am guessing 1.16.5, is that the latest version? if so I am afraid I can't help because there's some mod in your modpack that adds hidden data to items which makes them stack like this.

**Comment by totte1015** [comment]
> what version is that? I am guessing 1.16.5, is that the latest version? if so I am afraid I can't help because there's some mod in your modpack that adds hidden data to items which makes them stack like this.

Oh!! Yeah I have Enigmatica 6, and apparently it was just the second newest version, I updated now and hopefully it works
