### ISSUE TITLE
Crash Report, Force Shuts Down Minecraft 

### ISSUE THREAD

**Issue by WiZeXC** [P3pp3rF1y/SophisticatedBackpacks#687]
Hi, found a recent issue when filling up water within the tank upgrade. As im putting the bucket of water within the tank upgrade, minecraft will crash and say its "having trouble rendering an item entity". I have to remove the mod packs from forge and reinstall them in order to launch up the world again, otherwise, When i  load up the world and whenever i try accessing my inventory or backpack, it will crash again. 
I have a crash report if that helps

**To Reproduce**
1. Open backpack
2. Click on the Upgrade Tank Tab
3. Add a water bucket to fill up the tank
4. If the crash hasn't happened yet.... Close inventory and open up the backpack again.
Sometimes the crash wont happen right away, itll happen maybe 2 min later on.

**Expected behavior**
Was just hoping to fill up the tank on the backpack.

**Screenshots**
![image](https://user-images.githubusercontent.com/122758796/212575975-04e04343-3438-41c8-ad0d-d86debf6129f.png)

**Versions**
Mod Version: 1.19.2
Forge Verson: 1.19.2

**Comment by P3pp3rF1y** [comment]
Just remove optifine and you will get not crashes anymore, they are the ones who cause this crash
