### ISSUE TITLE
Crash: Compacting meets Twilight Forest boss trophy

### ISSUE THREAD

**Issue by enigmaquip** [P3pp3rF1y/SophisticatedBackpacks#688]
**Describe the bug**
A Twilight Boss trophy added to a backpack (manually or by magnet) that has a compacting upgrade in it will cause a client crash

https://mclo.gs/xaIQMTM

IE Plays a role in this. (Removing IE does remove the crash) Let me know if I should kick the ball over into their court or twilight's

**To Reproduce**
1. Open backpack
2. Backpack has compacting upgrade
3. Add Trophy

**Versions**
Forge 43.2.3
Soph Core 5.37.198
Soph Back 3.18.40.775
Twilight 4.2.1468

**Comment by P3pp3rF1y** [comment]
this is caused by bug in immersive engineering recipe where it doesn't expect custom item rarities. I am going to add a bit of code to prevent crashes from broken recipes in the future and this is tracked in #679
