### ISSUE TITLE
[Feature Request] Option to set refill upgrade to only refill partial stacks

### ISSUE THREAD

**Issue by TheDeviantCrafter** [P3pp3rF1y/SophisticatedBackpacks#69]
I'd like to see a checkbox added to the Refill upgrade. The tooltip will say "Only refill partial stacks"

When enabled: The upgrade will only refill items if at least one of that item exists in your inventory. If there are 1-63 of that item, it will top off the stack. If there are none of that item it won't start a new stack.

When disabled: Current behavior. If no items are in the inventory, it will transfer a stack from the backpack to the inventory.

**Comment by P3pp3rF1y** [comment]
I have actually implemented this to work by default - it will always find a partial stack and only if unable the logic puts a new stack in the first empty slot it finds

This is included in the latest release on curseforge
