### ISSUE TITLE
Backpack upgrades stop working

### ISSUE THREAD

**Issue by XGhostReaper6X** [P3pp3rF1y/SophisticatedBackpacks#692]
**Describe the bug**
all smelting and blasting and smoking and feeding upgrades except craftingtable upgrade stop working and stop accepting input except for adding fuel and it stops feeding you with the feeding upgrade and wont accept filter inputs 
**Versions**
mod--3.18.40.779
core---0.5.38.203

**Comment by P3pp3rF1y** [comment]
Would you have any additional info on how this happens. As far as I can see upgrades work for me and I don't have any other reports like this.

**Comment by P3pp3rF1y** [comment]
closing this as no additional info was provided
