### ISSUE TITLE
Botania Bottle of Mana constantly consumed with auto-feeding upgrade

### ISSUE THREAD

**Issue by Pretender8** [P3pp3rF1y/SophisticatedBackpacks#693]
**Describe the bug**
When a bottle of mana is placed in a backpack with an auto-feeding upgrade, it constantly returns an infinite amount of empty bottles. It also spawns a bunch of water in the player's position.  

**To Reproduce**
1. Open backpack
2. Place a bottle of mana in the backpack and an auto-feeding upgrade
3. Watch as water blocks are placed around you, and bottles fill up.

**Expected behavior**
The bottle of mana is used once, doing the effect, then is deleted and replaced with an empty bottle. 

**Versions**

sophisticatedbackpacks-1.19.2-3.18.40.779.jar
Botania-1.19.2-436-FORGE.jar
43.2.3

**Comment by jeremiahwinsley** [comment]
Previously reported in #607 but that fix does not account for "Should feed immediately when hurt" being enabled:
https://github.com/P3pp3rF1y/SophisticatedCore/blob/9196c9ac89b6fc4904080744147f4e1f13d8ce53/src/main/java/net/p3pp3rf1y/sophisticatedcore/upgrades/feeding/FeedingUpgradeWrapper.java#L77

I can reproduce this when damaged and hungry on 1.18.

**Comment by P3pp3rF1y** [comment]
Just released version with fix on curseforge
