### ISSUE TITLE
Lava/Water Tank Upgrade Causes Crash Upon Rendering Backpack

### ISSUE THREAD

**Issue by Lymni** [P3pp3rF1y/SophisticatedBackpacks#695]
**Describe the bug**
Upon loading into the world, depending on if the backpack with the Lava/Water tank is inside player inventory it will crash upon opening inventory. Else; player crashes immediately after loading the world. Dropping Backpack upon death will also crash game immediately

**To Reproduce**
1. Open backpack
2. Place upgrade into slot
3. Place Water/Lava into fluid meter

**Expected behavior**
I expected to be able to move after the game crashes if the item is in my inventory but if the item is in my hotbar, it will crash immediately upon loading into the world. 

**Screenshots**
![Base Profile Screenshot 2023 01 27 - 16 58 55 87](https://user-images.githubusercontent.com/123780744/215221992-b009f9ff-3df3-4f52-83ed-df415af415d0.png)
![Base Profile Screenshot 2023 01 27 - 16 59 18 07](https://user-images.githubusercontent.com/123780744/215221994-ea18b7dd-8341-4819-b782-b4ea43963c67.png)
![Base Profile Screenshot 2023 01 27 - 16 59 24 27](https://user-images.githubusercontent.com/123780744/215222003-a59a8ef0-87a7-41dc-b7da-0fc2edf1d927.png)
**Versions**
Sophisticated Backpacks Mod: 1.19.2-3.18.40.775
Sophisticated Core Mod: 1.19.2-0.5.38.203

**Comment by P3pp3rF1y** [comment]
are you using optifine? if so remove that to fix

**Comment by P3pp3rF1y** [comment]
I am pretty sure this was optifine and there was no additional info provided so closing
