### ISSUE TITLE
Backpack items and upgrades lost after server crash

### ISSUE THREAD

**Issue by abdallah-mahmoud** [P3pp3rF1y/SophisticatedBackpacks#696]
Last night after ATM 8 server crash and we relog in all the backpacks lost its contents along w upgrades etc
I saw an old issue here w close case so i checked backpacks uuid n they aren't the same is there away to fix this or prevent it from happening in future?

Mod ver 1.19.2-3.18.40.779
Atm 8-1.0.9

**Comment by P3pp3rF1y** [comment]
this likely caused by server not being able to save backpack contents back to the disk. Only fix for that is to have backup mod running that regularly backs this up.
