### ISSUE TITLE
[1.16.5/1.19.2] Inception and stack Upgrades allows backpacks to stack

### ISSUE THREAD

**Issue by DoctorMage** [P3pp3rF1y/SophisticatedBackpacks#697]
**Describe the bug**
1.16.5 / 1.19.2
Player obtaining backpacks without ever holding them can be stored inside inception backpack and stacked on top of eachother with stack upgrade

Afterwards any thing thats magnetted into backpack from magnet upgrade will be put in both.
The backpacks will gain eachothers contents even when seperated as long as the player did not hold them.

Both bags have same uuid as well

**To Reproduce**

1.16.5
1. create backpack give it inception upgrade, stack upgrade and magnet
2. create 2 more backpacks without ever holding them in your hand
3. insert them inside inception backpack and they will stack
4. gather a bunch of items without ever holding backpacks and they will duplicate contents

1.19.2
1. create backpack give it inception upgrade, stack upgrade and magnet
2. craft 2 more backpacks but indivually never making the base backpack by  inserting more than 1 item into the crafting grid
3.Insert them inside inception backpack and they will stack
4. gather a bunch of items without ever holding backpacks and they will duplicate contents

**Expected behavior**
Backpacks do not stack while using inception upgrade even with stack upgrade

**Screenshots**
1.16.5
https://streamable.com/j4c5jg

https://streamable.com/n30o6n

![image](https://user-images.githubusercontent.com/85318453/215921889-dfd64073-a139-4af2-9d29-835d29cebb30.png)
![image](https://user-images.githubusercontent.com/85318453/215921904-1bcc2ce5-e536-4e27-99ec-d27b72814020.png)

1.19.2
https://streamable.com/8i874l

**Versions**

1.16.5
sophisticatedbackpacks-1.16.5-3.15.20.755.jar
Forge 36.2.39

1.19.2
sophisticatedbackpacks-1.19.2-3.18.40.779.jar
sophisticatedcore-1.19.2-0.5.38.203.jar
Forge 43.2.0

**Comment by DoctorMage** [comment]
appears similiar to #271 but found another way of creating backpacks with duplicate uuid

may also be possible in 1.18.2 never tested 1.19.2 method there

**Comment by P3pp3rF1y** [comment]
I have a fix for this issue in 1.18+

**Comment by P3pp3rF1y** [comment]
Just released version with fix on curseforge
