### ISSUE TITLE
Shift right click issue

### ISSUE THREAD

**Issue by zanecek** [P3pp3rF1y/SophisticatedBackpacks#70]
Shift right clicking the backpack on the ground picks it up, but immediately places it again, if the ground is reachable.

**Comment by P3pp3rF1y** [comment]
That definitely isn't the case with just SBP in the pack or in Enigmatica 6 pack that I play. Sounds like some kind of mod interaction issue. 
Can you actually recreate with just SBP?

**Comment by zanecek** [comment]
Collision is with mod PreciseBlockPlacing.

Is possilble to disable pick up the backpack by shift right click?
I can always pick it up by breaking it.
Btw, netherite backpack drops nothing!

**Comment by zanecek** [comment]
I thought, to disable it only as an option, in config...

**Comment by P3pp3rF1y** [comment]
5 tick cooldown on pickup is included in the latest release that should take care of this issue.
