### ISSUE TITLE
Backpack power stacking and MEK cycle lead to infinite power

### ISSUE THREAD

**Issue by McAZero** [P3pp3rF1y/SophisticatedBackpacks#700]
**Describe the bug**
Backpack power stacking and MEK cycle lead to infinite power

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Put one BatteryUpgrade and five StackUpgradeTier4 in NetheriteBackpack
![image](https://user-images.githubusercontent.com/52328924/217447817-0642d58a-0e8e-45e6-bb8e-c98749a2fc97.png)
2. Place MEK cable on the top of NetheriteBackpack and change MEK cable to pull
![image](https://user-images.githubusercontent.com/52328924/217441037-087d1bf5-9cfd-4056-b86d-aea10848beb0.png)
3. Store a little energy in the energy cube
4. Then change the side of MEK energy cube to output
![image](https://user-images.githubusercontent.com/52328924/217441521-09de912c-bf7e-44e6-b3f1-52ecee5c952e.png)
5. Finally, put StackUpgradeTier4 into the last module, and then the backpack energy bar will fluctuate up and down incorrectly.
![image](https://user-images.githubusercontent.com/52328924/217441893-1e47b75d-c53a-4755-ba93-838dcdc83780.png)

**Expected behavior**
Hope to repair

**Screenshots**
null

**Versions**
sophisticatedbackpacks-1.18.2-3.18.40.777
sophisticatedbackpacks-1.16.5-3.15.20.755

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
