### ISSUE TITLE
Quark shift locking prevents backpack from opening

### ISSUE THREAD

**Issue by INooBTooMuch** [P3pp3rF1y/SophisticatedBackpacks#701]
**Describe the bug**
I think that clicking on shift lock from quark (the little lock in the inventory) will behave as if shift is being pressed, meaning you can't open the backpack with the key bind.

**To Reproduce**
1. Have sift lock from Quark enabled
2. Press the key bind to open the backpack
3. It won't open

**Expected behavior**
I think a solution would be to change the key bind to work with and without shift pressed to open the backpack, unless this is an intentional feature. Then, disabling the shift lock feature while in the inventory of the backpack (its above the player inventory) could be another one maybe...

**Versions**
Minecraft : 1.18.2
Forge : 40.2.0
Sophisticated Backpacks : 3.18.40.777

**Comment by P3pp3rF1y** [comment]
That appears to be a functionality of Quark where it will basically hold shift for you for anything - so if I change the backpack keybind to shift + b and then in game with shift locked only press b (without holding shift myself) it will open the backpack correctly. So if you don't like that either turn it off or you need to complain to Quark about this
