### ISSUE TITLE
Having an issue loading the mod.

### ISSUE THREAD

**Issue by KingCaleb97** [P3pp3rF1y/SophisticatedBackpacks#703]
I'm not much into these things, just started this serveR but ill remove the mods until I get an answer. ill attach my crash report, I can't make much of anything in it other than it just won't load properly, soph backpacks and soph core. please help.

[crash-2022-09-02_01.57.00-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10727669/crash-2022-09-02_01.57.00-client.txt)
 update, I think its cause its 1.19.2 and I'm running 1.19.3,

**Comment by P3pp3rF1y** [comment]
I don't have a version for 1.19.3 and haven't tested the mod with that version, but this looks to me more like a case of curseforge launcher. I would suggest trying with different launcher first
