### ISSUE TITLE
mod not loading on start

### ISSUE THREAD

**Issue by eMortifed** [P3pp3rF1y/SophisticatedBackpacks#704]
Minecraft is crashing on start up tried to load with only the back pack mod into 1.19.3
looks like maybe an update issue

[crash-2023-02-14_18.26.25-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10738043/crash-2023-02-14_18.26.25-fml.txt)

**Comment by P3pp3rF1y** [comment]
This would be because you're trying to add it to 1.19.3. There's no version for that version yet and I will see if there is even going to be one as 1.19.3+ versions are pretty much snapshots of 1.20 and most mods stay on 1.19.2
