### ISSUE TITLE
Stacking bug in backpack - may just be a setting I can't find to undo

### ISSUE THREAD

**Issue by Skunkpuncher** [P3pp3rF1y/SophisticatedBackpacks#705]
I am playing on a RAD2 server and have a backpack upgraded to gold. I added an advance magnet upgrade to the backpack. It is picking up basic items and placing them in stacks of 2 in my backpack - such as dirt, cobblestone, gravel, etc and even torches. It will pick up ores and stack them normally. I have tried removing and reinstalling the upgrade as well as turning it off and then back on. It is still repeating.

RAD2-1.16.5-1.0a

**Comment by P3pp3rF1y** [comment]
This is an issue of some mod in 1.16 adding custom capability nbt data to stacks so when they are picked up they are different than the ones in backpack and so they can't be stacked. Not much I can do about that as stacks with different data shouldn't stack.

**Comment by Skunkpuncher** [comment]
Dirt is different than dirt? Cobblestone is different than Cobblestone? Do they have nbt data if they do not have durability loss? Also, when I click the button to organize the backpack, they stack normally. When I hold my mouse button after picking one up and dragging it over the others, it stacks normally. When I middle mouse click on the opened backpack, it shifts the contents and stacks normally. It is only when it automatically picks those items up that it limits it to stacks of 2.
