### ISSUE TITLE
Stacks into stacks of 2 and deposit upgrade not working.

### ISSUE THREAD

**Issue by hacim** [P3pp3rF1y/SophisticatedBackpacks#706]
**Describe the bug**

1. When the backpack auto pickups it puts stuff in weird stack quantities (usually 2).
2. With the deposit upgrade when I shift (sneak) click a chest or another inventory it opens it instead of depositing the items there. (fixed, only works when im holding the backpack in my hand)

**To Reproduce**

It happens when just mining collecting resources and when you shift click inventories.

**Expected behavior**
1. To fully stack to the 64 limit (without stack upgrade)
2. To deposit the items in the corresponding inventory.

**Versions**
sophisticatedbackpacks-1.16.5-3.15.20.755.jar

**Comment by JordiCool** [comment]
ive had the item stacking issue as well, notably my pickup ubgrade is set to "match backpack contents" if i:
set the pickup upgrade to "match NBT"
AND
set the void upgrade i also have installed to have something in its filter (it being set to block with nothing in it does not work)

then things stack properly.

**Comment by P3pp3rF1y** [comment]
There is some mod in 1.16 that adds some capability nbt data to stacks which also seem to be deleted once stacks are picked up by player, but not soon enough for pickup upgrade to see stacks without them. So if you can figure out what mod that is I may make a fix for this. The same issue doesn't happen in 1.18+ which uses the same code to compare stacks so I wouldn't count on this being fixed as 1.16 is no longer supported in my book and the fix isn't needed for other versions.

**Comment by P3pp3rF1y** [comment]
closing as there was no response for a while
