### ISSUE TITLE
Backpack inventory is gone after game crashed

### ISSUE THREAD

**Issue by Julianna91** [P3pp3rF1y/SophisticatedBackpacks#707]
Hello!

My single game word crashed, and after launching the game all the inventory in the backpack was gone :(
I am not a dev, or know about mods, but I would like some help to fix this and get the inventory inside the backpack back. 

I am playing in version 1.19.2.

Other info:
- sophisticatedbackpacks-1.19.2-3.18.40.779
- sophisticatedcore-1.19.2-0.5.38.203

I hope someone can help me.
Thank you!

![minecraft - 1 19 2 -issue](https://user-images.githubusercontent.com/120489274/220715538-a50006ba-26a7-4739-9e09-f23b370937a2.png)

**Comment by P3pp3rF1y** [comment]
That unfortunately means your data is gone. Most of the modpacks use backup mod for this reason to prevent data loss - SB isn't the only mod that uses this way of storing its data and there is also other data that can be lost partially or fully due to crashes.
