### ISSUE TITLE
Crashes while loading my mod loadout 1.19.2

### ISSUE THREAD

**Issue by PatTheWizard** [P3pp3rF1y/SophisticatedBackpacks#708]
I am using the latest version of the mod on 1.19.2 forge I'm getting a null crash. Below is crash log:
[crash-2023-02-23_21.20.06-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10820083/crash-2023-02-23_21.20.06-client.txt)

**Comment by P3pp3rF1y** [comment]
you have newer version of core than of the backpacks. just update backpacks to the latest and issue is solved
