### ISSUE TITLE
Mod don't load on server

### ISSUE THREAD

**Issue by clement5188** [P3pp3rF1y/SophisticatedBackpacks#717]
Hello everybody !
I try to implement sophisticatebackpack in gradle to use it as dependency.
in build.gradle I added : implementation fg.deobf("curse.maven:sophisticatedbackpacks-422301:4167327")
Now When I lauch client no problem but when I launch on server I get this crash (in attachement)
can you help me ?
thank's for reading
**Versions**
I use mod version 1.16.5-3.15.20.755, the version 1.16.5-3.15.19.721 doesn't work to.

[crash-2023-03-16_21.14.49-fml.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/10995893/crash-2023-03-16_21.14.49-fml.txt)

**Comment by P3pp3rF1y** [comment]
this is not really a mod bug and I don't support 1.16 anyway either, but from the quick look it seems like you have something in your dev environment that causes client proxy to be loaded on server side in DistExecutor on that line where it crashes. So you will likely need to mess with removing dependencies / jdk or something like that.

**Comment by clement5188** [comment]
Ok thank you for answering me!
I will check that.
