### ISSUE TITLE
Crashes when shift click dragging with mouse tweaks mod

### ISSUE THREAD

**Issue by RichPrune** [P3pp3rF1y/SophisticatedBackpacks#719]
**Describe the bug**
Crash log if it's a crash: https://pastebin.com/5eBCPPAV 
Info on what other mods you're using that may cause a conflict here if applicable.

Mouse Tweaks shift click dragging items feature crashes the game in a backpack. Ive had this consistently happen since I installed your mod, ive had to avoid but it happens too often this way without exception.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2.Shift click drag any item.
3. Crash to launcher

**Expected behavior**
no crash

**Screenshots**
crash report is enough.
**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
1.19.2 forge 43.2.0
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11094186/latest.log)

**Comment by sirucus** [comment]
I've got the same issue, although its only when trying to drag in the lower half. I have a gold backpack and I can shift drag the top layers just fine.

**Comment by RichPrune** [comment]
actually scratch that, even without the mod it crashes, shift clicking smelted furnace upgrade items crashes as well

**Comment by P3pp3rF1y** [comment]
smoothswapping is your issue so you will need them to fix their code
