### ISSUE TITLE
Indestructible enderman wearing a backpack

### ISSUE THREAD

**Issue by TheDeviantCrafter** [P3pp3rF1y/SophisticatedBackpacks#72]
In my creative world, I found a totally indestructible enderman wearing a backpack. Resistance V gives monsters 100% damage immunity (20% per level). That should be capped at level 4.

Latest.log file (includes the mob's NBT string gathered with /data): https://gist.github.com/TheDeviantCrafter/4a76b3e27239452eadbe996bbb463607

Screenshots:
![2021-03-07_21 15 00](https://user-images.githubusercontent.com/18755309/110270199-ee96b280-7f8a-11eb-89fb-d74f80716efc.png)
![2021-03-07_21 15 09](https://user-images.githubusercontent.com/18755309/110270205-f0f90c80-7f8a-11eb-9936-8ffcd718a7d8.png)

**Comment by P3pp3rF1y** [comment]
fixed in latest release
