### ISSUE TITLE
1.19.2: crash during world loading: java.lang.NoSuchFieldError: PACKET_HANDLER (Certainly due to the Sophisticated Core update today)

### ISSUE THREAD

**Issue by Daltaxy** [P3pp3rF1y/SophisticatedBackpacks#721]
**Describe the bug**
Yesterday, everything was fine. Today, Sophisticated Core was updated, and I crash while loading my world, at the Terrain generation step (latest)
[crash-2023-03-30_16.48.45-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11113116/crash-2023-03-30_16.48.45-server.txt)
debug.log: https://gist.github.com/Daltaxy/1cc2c8a35dd6b60df2c597b0308c4515

**To Reproduce**
Load my world after updating Sophisticated Core to sophisticatedcore-1.19.2-0.5.46.230, released today

**Expected behavior**
no crash

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
sophisticatedcore-1.19.2-0.5.46.230
sophisticatedbackpacks-1.19.2-3.18.40.779
latest Forge: 43.2.8

**Comment by P3pp3rF1y** [comment]
you need to update to latest version of backpacks

**Comment by Daltaxy** [comment]
oh.. there was a few hours of delay before the update came for this one. Thank you
