### ISSUE TITLE
Items Void When using Advanced Deposit Upgrade

### ISSUE THREAD

**Issue by QuantumRainz** [P3pp3rF1y/SophisticatedBackpacks#725]
**Describe the bug**
Right Clicking with "Allowed" Filter Removes and Voids All the items Inside.
I only have a Magnet Upgrade, Stack Upgrade Tier 2 And Advanced Deposit Upgrade
(was testing more and found the other way with "Block" also Deletes Items)

**To Reproduce**
1. Have backpack with many items
2. Set The Filter to Allow
3. Right Click a Chest
4. Have items Disappear into Air

**Expected behavior**
Items in Filtered or Unfiltered ONLY being Moved Not Removed or Deleted
Example: Cobblestone only

**Screenshots**
I have only notices The NBT Tag changing Not the ID not sure if that's helpful
For example: 6 to 7

**Versions**
1.19.2 
Forge - 43.2.6

**Comment by P3pp3rF1y** [comment]
Just fixed this bug in the latest update for sophisticatedcore, it's uploaded on curseforge but currently going through approval so once approved this bug is fixed.

**Comment by P3pp3rF1y** [comment]
and closing as now the new release is out
