### ISSUE TITLE
1.19.2 - Dedicated Server Refuses to Start ``Mod Loading Error``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [P3pp3rF1y/SophisticatedBackpacks#728]
**Describe the bug**
The server crashes. I tried to reset configs and even make a new world and the latest Sophisticated Backpacks simply crashes.

**To Reproduce**
Update to ``sophisticatedbackpacks-1.19.2-3.18.43.801.jar``

**Expected behavior**
No crash.

**Versions**
Forge 43.2.8

**Crash Log**
https://gist.github.com/P3rf3ctXZer0/796346cd394ee48388fd7304e04f8087

**Comment by P3pp3rF1y** [comment]
that's a fault of biggerstacks trying to mixin some code into sophisticated you will need to report that to them.
