### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by Ellow-Ellow** [P3pp3rF1y/SophisticatedBackpacks#731]
While opening the game, (1.16.5) before it loads it crashes and I get Exit Code 1. I've opened the game without mods and it works like normal when I remove the mod from my folder, it also works fine. I know it's not one of the mods in the folder because it used to work with them. 

here is the Exit Code text

 The game crashed whilst rendering overlay
Error: 
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException:
 Failed loading config file sophisticatedbackpacks-common.toml 
of type COMMON for modid sophisticatedbackpacks

**Comment by P3pp3rF1y** [comment]
you will need to include more of that exception this only says that it crashed during config load but doesn't say what actually happened there which it should. Also 1.16.5 hasn't been changed in quite a while and is played by many players with no one reporting any issues with config load so without seeing the actual crash log I would think there's some issue with the mods you have in the pack or loader or something similar.

**Comment by P3pp3rF1y** [comment]
there was no additional info provided for a while and there's nothing I can work with here so I am closing this now
