### ISSUE TITLE
Removing of upgrades via configs seems to not be working.

### ISSUE THREAD

**Issue by ItsBootsy** [P3pp3rF1y/SophisticatedBackpacks#736]
**Describe the bug**
When trying to remove a recipe for an upgrade for the backpacks it appears the config is being ignored.

Prior to 1.19.2 from what iv'e been told the format was to edit the 'sophisticatedcore-server.toml' and insert the items you want disabled like so:

```
#Server Settings
[server]
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["sophisticatedbackpacks:restock_upgrade|false"]
```
However, this appears to not function in the current version (sophisticatedbackpacks-1.19.2-3.18.43.801)

**To Reproduce**
1. Modify the sophisticatedcore-server.toml file to remove a recipe from being used.
2. Start server
3. Join and search for recipe via JEI and or try to create the item
4. You'll still see and be able to create/use the item even though you have 'disabled' it via the config.

**Expected behavior**
Would expect the upgrade or backpack to no longer display in JEI and be unable to craft/use the upgrade or backpack.

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
sophisticatedbackpacks-1.19.2-3.18.43.801
sophisticatedcore-1.19.2-0.5.47.234
forge-1.19.2-43.2.0

**Comment by P3pp3rF1y** [comment]
this was solved a while ago - I moved this config back to common which actually is available at the stage when item recipes get registered.
