### ISSUE TITLE
tool swapper not swapping on certain items

### ISSUE THREAD

**Issue by theelusianmysteries** [P3pp3rF1y/SophisticatedBackpacks#738]
hi! i got the tool swapper upgrade and it only swaps on raw versions of the item (i.e, only stone and not cobble, only logs and not planks.) and the weapon swapper doesn't work on all entities.
1.18..2 
ty in advance!

**Comment by P3pp3rF1y** [comment]
Just retested and it just works for me so I will need more details on how exactly I can recreate this. Are you using modded tools? are you using this in a bigger modpack and are you able to recreate without other mods in the modpack?

**Comment by theelusianmysteries** [comment]
no modded tools, and removed all unneeded mods and still doesnt work ): (re-install didnt work either)

**Comment by theelusianmysteries** [comment]
alr i see what i was doing wrong, i was using the swap tool keybind instead of just left-clicking.
