### ISSUE TITLE
[1.18.2] - Startup Crash - Possible Incompat with Bigger Stacks?

### ISSUE THREAD

**Issue by PhweeDev** [P3pp3rF1y/SophisticatedBackpacks#742]
When using both the latest and version prior to the latest, I get this crash.  Whilst reading the crash report, I suspect it might be an issue with Bigger Stacks, or maybe it's just something in the mod itself that causes a conflict? 

Important to note: This does not happen with Soph Backpacks version 1.18.2-3.18.40.77. and only versions 1.18.2-3.18.43.802 and latest, 1.18.2-3.18.44.814

Crash Report: https://paste.gg/p/anonymous/983853d7348e4b62b294dd82a2c5c798
Log: https://paste.gg/p/anonymous/14f838edcda149ca9163c0511f2fe9d3

**Comment by P3pp3rF1y** [comment]
yeah just report that to bigger stacks who are breaking my mod.
