### ISSUE TITLE
Backpack Stashing

### ISSUE THREAD

**Issue by SpokenWig620933** [P3pp3rF1y/SophisticatedBackpacks#743]
Prior to 3.18.44.814 you had to right-click an item to stash it in the backpack, now though on 3.18.44.814 you can regularly click it and it'll stash it, but that's inconvenient when you go to move the backpack around the inventory and attempt to swap it with an item and instead stash it, so you have to open the backpack, drop an item, move the backpack, then pick up the item to get it into the right spot when your inv is full.

**Comment by P3pp3rF1y** [comment]
this is fixed in the latest release on CF
