### ISSUE TITLE
Not able to manually insert/extract charged/uncharged mekasuit helmet into any backpack slot with battery upgrade

### ISSUE THREAD

**Issue by liopyu** [P3pp3rF1y/SophisticatedBackpacks#748]
**Describe the bug**
To recreate this open up the backpack with a battery upgrade in it and try to manually insert a charged/uncharged mekasuit helmet into any slot in the backpack. Additionally it wont let me put it back into my own inventory after i take it out. I can shift click it back and forth just fine. The odd thing is that it works perfectly fine if i try to insert any other mekasuit piece/energy cube/meka-tool ect. Its just the helmet that wont re-insert into the inventory. I'll provide a screenshot with the tags it has along with some other mekanism energy-capable items, its newly generated from the creative window. Let me know if i can assist with anything more. Thanks :)

**Versions**
sophisticatedbackpacks-1.19.2-3.18.44.815
Mekanism-1.19.2-10.3.8.477
forge version:43.2.4

Screenshots:
Helmet tags:
https://user-images.githubusercontent.com/130418550/232884827-325eb19b-12f6-4df4-aa1b-e716f6c59c96.png

Helmet issue analysis
https://user-images.githubusercontent.com/130418550/232884821-e3d0d9a4-efe8-44f8-823c-c376525a32ba.png

Tags for related Items unaffected by this:
Meka-Tool
https://user-images.githubusercontent.com/130418550/232884815-0ab01afb-9b5c-4adb-ae05-70b29245f2a0.png

Mekasuit Body Armor
https://user-images.githubusercontent.com/130418550/232884833-a6f6154e-9d33-4e21-9592-7fb10bb338ac.png

Mod List:
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Biome Makeover (Forge) (by Lemonszz)](https://www.curseforge.com/minecraft/mc-mods/biome-makeover-forge)
[Dense Ores - Abundant! (by NewJumperr)](https://www.curseforge.com/minecraft/mc-mods/dense-ores-abundant)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Simple Backups (by MelanX)](https://www.curseforge.com/minecraft/mc-mods/simple-backups)
[Game Stages (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/game-stages)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[MineColonies (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/minecolonies)
[Structures Plus II (by Qra5)](https://www.curseforge.com/minecraft/mc-mods/structures-plus-ii)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
[Daily Dad - Server (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/daily-dad-server)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Flux Networks (by sonar_sonic)](https://www.curseforge.com/minecraft/mc-mods/flux-networks)
[XP Tome (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/xp-tome)
[Biome Particle Weather (by shadowmaster404)](https://www.curseforge.com/minecraft/mc-mods/biome-particle-weather)
[Falling Leaves (Forge) (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)
[Presence Footsteps [Forge] (by Paint_Ninja)](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge)
[Neat (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/neat)
[Fireplace Lib (Forge) (by The_Fireplace)](https://www.curseforge.com/minecraft/mc-mods/fireplace-lib-forge)
[Tool Stats (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/tool-stats)
[KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Ars Nouveau (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau)
[Server Utilities (by ArrowsendGaming)](https://www.curseforge.com/minecraft/mc-mods/server-utilities)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Healing Flasks (by mumihp)](https://www.curseforge.com/minecraft/mc-mods/healing-flasks)
[Geophilic – Biome Overhauls (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/geophilic)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Villager Brute [FORGE] (by TeamTechnicMC)](https://www.curseforge.com/minecraft/mc-mods/villager-brute)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[FancyMenu [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/fancymenu-forge)
[MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/mmm
mmmmmmmmm)
[Crafting Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks)
[Better Compatibility Checker (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Unforgiving Void (by The_Fireplace)](https://www.curseforge.com/minecraft/mc-mods/unforgiving-void)
[First Aid (by ichttt)](https://www.curseforge.com/minecraft/mc-mods/first-aid)
[Tan's Huge Trees (by TannyJung)](https://www.curseforge.com/minecraft/mc-mods/tan-huge-trees)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[YDM's MobHealthBar (by YourDailyModderx)](https://www.curseforge.com/minecraft/mc-mods/ydms-mobhealthbar-mod)
[Reap Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/reap-mod)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[ImmediatelyFast Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast-reforged)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Ensorcellation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/ensorcellation)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Rapid Leaf Decay (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/rapid-leaf-decay)
[Keebsz's Battle Towers (by keebsz_)](https://www.curseforge.com/minecraft/mc-mods/keebszs-battletowers-fabric)
[Dimensional Threading Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/dimensional-threading-reforged)
[Projectile Damage Attribute [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/projectile-damage-attribute)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[YDM's Weapon Master (by YourDailyModderx)](https://www.curseforge.com/minecraft/mc-mods/ydms-weapon-master)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Ponder for KubeJS (by Lytho)](https://www.curseforge.com/minecraft/mc-mods/ponder)
[InvMove (by PieKing1215)](https://www.curseforge.com/minecraft/mc-mods/invmove)
[Origins Extra Keybinds [Forge / Fabric] (by fireheart3911_)](https://www.curseforge.com/minecraft/mc-mods/origins-extra-keybinds-forge)
[Mekanism Additions (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions)
[Awesome Dungeon Nether edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-nether-forge)
[Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)
[Ageing Spawners (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/ageing-spawners)
[Elenai Dodge 2 (by ElenaiDev)](https://www.curseforge.com/minecraft/mc-mods/elenai-dodge-2)
[Jade Addons (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Bygone Nether (by izofar)](https://www.curseforge.com/minecraft/mc-mods/bygone-nether)
[Effective (Forge) (by BottomTextDanny)](https://www.curseforge.com/minecraft/mc-mods/effective-forge)
[Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Integrated API (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/integrated-api)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[MrCrayfish's Gun Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod)
[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[Ars Armiger (by VykladeLapiet)](https://www.curseforge.com/minecraft/mc-mods/ars-armiger)
[Snow Under Trees (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/snow-under-trees)
[Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)
[CodeChicken Lib 1.8.+ (by covers1624)](https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8)
[Dungeons Libraries (by Patrigan)](https://www.curseforge.com/minecraft/mc-mods/dungeons-libraries)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[RpgSkillable (by dragoni_7)](https://www.curseforge.com/minecraft/mc-mods/rpgskillable)
[Ender Storage 1.8.+ (by covers1624)](https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8)
[Cyclops Core (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/cyclops-core)
[Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Akashic Tome (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/akashic-tome)
[Scaling Health (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/scaling-health)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[More Babies (Forge & Fabric) (by mammut53m)](https://www.curseforge.com/minecraft/mc-mods/more-babies)
[Lootr (Forge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[Simple Discord RPC [Forge/Fabric/Quilt] (by hypherionsa)](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc)
[FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Easy NPC (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/easy-npc)
[Silent Lib (silentlib) (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-lib)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Underground Villages (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/underground-villages)
[Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
[Unlit Campfire (by thecech12)](https://www.curseforge.com/minecraft/mc-mods/unlit-campfire)
[Human Companions (by jus10wontons)](https://www.curseforge.com/minecraft/mc-mods/human-companions)
[Applied Energistics 2 Wireless Terminals (by Mari_023)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals)
[Basic Nether Ores [Forge/Fabric] (by cScotPlay)](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores)
[Multi-Piston (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/multi-piston)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Not Enough Animations (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Dungeons Mobs (by the_infamous_1)](https://www.curseforge.com/minecraft/mc-mods/dungeons-mobs)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[Xtra Arrows (by Jackbusters1)](https://www.curseforge.com/minecraft/mc-mods/xtra-arrows)
[Magnesium/Rubidium Extras (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[ConnectedTexturesMod (by tterrag1098)](https://www.curseforge.com/minecraft/mc-mods/ctm)
[Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Feathers (by ElenaiDev)](https://www.curseforge.com/minecraft/mc-mods/feathers)
[Shutup Experimental Settings! (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings)
[Adaptive Performance Tweaks: Core (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-core)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Tips (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/tips)
[ReAuth (by TechnicianLP)](https://www.curseforge.com/minecraft/mc-mods/reauth)
[Bad Wither No Cookie - Reloaded (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)
[Origins: Classes (Forge) (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/origins-classes-forge)
[Towers of the Wild: Additions (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/towers-of-the-wild-additions)
[Harder Natural Healing (by MacTso)](https://www.curseforge.com/minecraft/mc-mods/harder-natural-healing)
[PneumaticCraft: Repressurized (by desht_08)](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized)
[Player Companions (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/player-companions)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Crossbowverhaul (by dertoaster_98)](https://www.curseforge.com/minecraft/mc-mods/crossbowverhaul)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Epic Knights: Shields, Armor and Weapons [Fabric & Forge] (by magistu_)](https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons)
[Charm of Undying (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/charm-of-undying)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[CullLessLeaves Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/culllessleaves-reforged)
[Sky Villages [Forge] (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/sky-villages-forge)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Paxi (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/paxi)
[MoreJS (by Lytho)](https://www.curseforge.com/minecraft/mc-mods/morejs)
[Dusk[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dusk)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[AtomicStryker's Infernal Mobs (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-infernal-mobs)
[Dimension Stages (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dimension-stages)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Building Gadgets (by Direwolf20)](https://www.curseforge.com/minecraft/mc-mods/building-gadgets)
[Entity Collision FPS Fix (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix)
[Pluto (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/pluto)
[Raised (by yurisuika)](https://www.curseforge.com/minecraft/mc-mods/raised)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Tough As Nails (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/tough-as-nails)
[Repurposed Structures (Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
[Runelic (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/runelic)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[ReBlured (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/reblured)
[Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[BetterF3 (by cominixo)](https://www.curseforge.com/minecraft/mc-mods/betterf3)
[Tool Belt (by gigaherz)](https://www.curseforge.com/minecraft/mc-mods/tool-belt)
[Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
[Structurize (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/structurize)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Elytra Physics (by ImJ0shh_)](https://www.curseforge.com/minecraft/mc-mods/elytra-physics)
[More Powerful Game Rules (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/custom-game-rules)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Ars Creo (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-creo)
[Starter Kit (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
[FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
[Born in Chaos (by mongoose_artist)](https://www.curseforge.com/minecraft/mc-mods/born-in-chaos)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[Better Animations Collection (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/better-animations-collection)
[ItemPhysic Full (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/itemphysic)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[End Remastered (by jack_bagel)](https://www.curseforge.com/minecraft/mc-mods/endremastered)
[Annotated DI (Forge) (by The_Fireplace)](https://www.curseforge.com/minecraft/mc-mods/annotated-di-forge)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[MemoryLeakFix (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
[Integrated Dungeons and Structures (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/idas)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Vertical Slabs Compat (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/vertical-slabs-compat)
[Tetra (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/tetra)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Light Overlay (Rift/Forge/Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/light-overlay)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[BlockUI (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Stalwart Dungeons (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/stalwart-dungeons)
[Bedrock Miner (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/bedrock-miner)
[Nether Skeletons (by GlitchedMastery)](https://www.curseforge.com/minecraft/mc-mods/nether-skeletons)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Nether Depths Upgrade (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/nether-depths-upgrade)
[Explorify – Dungeons & Structures (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/explorify)
[Loot Integrations[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/loot-integrations)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Hammer Lib (by Zeitheron)](https://www.curseforge.com/minecraft/mc-mods/hammer-lib)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
[Durability Tooltip (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/durability-tooltip)
[Konkrete [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Chunky (Forge) (by pop4959)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator-forge)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Forbidden and Arcanus (by cesar_zorak)](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
[Applied Energistics 2 (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[VanillaTweaks [Fabric & Forge] (by StrikerRocker)](https://www.curseforge.com/minecraft/mc-mods/vanillatweaks)
[Iron Bows (FORGE) (by popcornman200)](https://www.curseforge.com/minecraft/mc-mods/iron-bows-forge)
[mutil (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/mutil)
[Pane In The Glass (by MongoTheElder)](https://www.curseforge.com/minecraft/mc-mods/pane-in-the-glass)
[Applied Mekanistics (by ramidzkh)](https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics)
[Healing Campfire (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/healing-campfire)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Little Logistics (by Sveid_)](https://www.curseforge.com/minecraft/mc-mods/little-logistics)
[Round Trees (by Motschen)](https://www.curseforge.com/minecraft/texture-packs/round-trees-mc-vanilla-1-8-1-13)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[More Villager Trades (by TrueRealCursed_Warrior)](https://www.curseforge.com/minecraft/mc-mods/more-villager-trades)
[The Abyss II - The Other Side (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii)
[ServerConfig Updater (by Darkere)](https://www.curseforge.com/minecraft/mc-mods/serverconfig-updater)
[In Control! (by McJty)](https://www.curseforge.com/minecraft/mc-mods/in-control)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Pig Pen Cipher (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher)
[Better Animals Plus (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Open Parties and Claims (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims)
[Forgiving World - Dimension Stacking[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/forgiving-world)
[Lapis Reserve (by sfort__)](https://www.curseforge.com/minecraft/mc-mods/lapis-reserve)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Kiwi 🥝 (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/kiwi)
[Common Capabilities (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/common-capabilities)
[Domestication Innovation (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/domestication-innovation)
[Snow! Real Magic! ⛄ (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic)
[Magnesium/Rubidium Dynamic Lights (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[Solar Flux Reborn (by Zeitheron)](https://www.curseforge.com/minecraft/mc-mods/solar-flux-reborn)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
[Dungeon Crawl (by xiroc_)](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl)
[Login Protection[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/login-protection)
[My Server Is Compatible (by Focamacho)](https://www.curseforge.com/minecraft/mc-mods/my-server-is-compatible)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[JICKLUS (by Jicklus)](https://www.curseforge.com/minecraft/texture-packs/jicklus)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[Inventory HUD+ (by dmitrylovin)](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge)
[Default Options (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/default-options)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Rough Tweaks Revamped (by selfdeprecativeX)](https://www.curseforge.com/minecraft/mc-mods/rough-tweaks-revamped)
[CameraOverhaul (Forge) (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/camera-overhaul-forge)

**Comment by P3pp3rF1y** [comment]
Looks like I fixed this with a report on bucket behaving in the same way when battery upgrade was in backpack. Looks like I had a bug in there since the battery upgrade was added. It's fixed now in 1.18 / 1.19 sophisticated core.

**Comment by liopyu** [comment]
thank you!!
