### ISSUE TITLE
[Bug] I'm having this issue and seeing this mod getting affected

### ISSUE THREAD

**Issue by Ninezel** [P3pp3rF1y/SophisticatedBackpacks#75]
https://gist.github.com/Admiral-Sebastian/42ae4f068d4c3c7bd970df0fbe8a45e3

**Comment by Ninezel** [comment]
This a server crash log

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this. I wasn't aware that addition of treasure maps in loot actually causes the treasures to be generated in the world. I will change this to only generate the loot when player actually opens the backpack. 

However the reason why it took so long to generate treasure in your case isn't clear to me, I would guess you have some other mod that's heavy on world gen which caused the world gen take much longer than it should.

**Comment by P3pp3rF1y** [comment]
the fix is now released in the latest version

**Comment by Ninezel** [comment]
Thank you 👍🏼
