### ISSUE TITLE
Reset sophisticatedbackpacks.dat

### ISSUE THREAD

**Issue by bigenergy** [P3pp3rF1y/SophisticatedBackpacks#753]
**Describe the bug**
My server hang while saving backpacks, and after launch, all backpacks were reset to zero

https://gist.github.com/bigenergy/17d10557e52b1e1a74edaed967649d3a

**Versions**
sophisticatedbackpacks-1.19.2-3.18.44.815
sophisticatedcore-1.19.2-0.5.49.245

**Comment by P3pp3rF1y** [comment]
yeah, there's nothing I can do about your server crashing when it's supposed to save the backpacks. it is using the same data saving as part of vanilla stuff and many other mods. I may look into completely revamping this to a different system in the future, but really if you use backups you can recover from crash like that and backpacks saving in a different way isn't going to solve for the other mods that use the same data saving.

**Comment by bigenergy** [comment]
> yeah, there's nothing I can do about your server crashing when it's supposed to save the backpacks. it is using the same data saving as part of vanilla stuff and many other mods. I may look into completely revamping this to a different system in the future, but really if you use backups you can recover from crash like that and backpacks saving in a different way isn't going to solve for the other mods that use the same data saving.

This has happened on my server 6 or 7 times already, I'm tired of hearing negative feedback every time because of a mistake in your mod, sorry, I have to remove it.

This is most likely due to the fact that some players stack a huge number of items with large NBT tags and a fakap occurs when saving such an item, then the file with the data of all backpacks is simply reset.

**Comment by bigenergy** [comment]
I think you should rewrite the backpack storage system. For example, split them into several, instead of one large file.
