### ISSUE TITLE
Pickup items to Backpack From other storages with hold SHIFT doesnt work

### ISSUE THREAD

**Issue by Quayron** [P3pp3rF1y/SophisticatedBackpacks#757]
**Describe the bug**
so i am currently using this mod on V19 on a downcraft modpack, and i read and watch some tutorials, came to a conclusion it says if i hold left shift button while i am picking up items from chest or other storages instead of item movig to my inventoriy, it automatically moves  to the backpack, and that option can be changed from backpack options, (while all this happening backpack is equipped on backpack slot of character)

but that does not work no matter how i tried it.

**To Reproduce**
1. Open a chest
2. triy to get the item to the backpack directly by using left SHIFT button
3. it wont go to backpack , will go to inventory instead

**Expected behavior**
taking item from other storages ,directly to the backpack thats currently on equipped slot on the character 

**Versions**
game version should be v19.2

**Comment by P3pp3rF1y** [comment]
There's no functionality like that and definitely not intended. You may be confusing this for what restock upgrade can do when you have it in a backpack and shift right click inventory with backpack in hand (or press inventory interaction key you have set in your controls with backpack anywhere in your inventory). There's also an option of right clicking on items with backpack on your cursor or right clicking backpack with an item on your cursor which makes such items go into backpack.
