### ISSUE TITLE
Forge 1.19.4 Version?

### ISSUE THREAD

**Issue by Aetrnl94** [P3pp3rF1y/SophisticatedBackpacks#758]
Hi, this mod looks really cool! Is there any chance you can let us know if an update for 1.19.4 is going to be released, and if so, when we might be able to expect it? Thanks a lot and I can't wait to try it out!

**Comment by P3pp3rF1y** [comment]
I may do it at some point or just jump right to 1.20 when that is released. I just can't support too many versions at the same time.
