### ISSUE TITLE
[Bug] Dyeing backpacks with multiple colours 

### ISSUE THREAD

**Issue by SynfulChaot** [P3pp3rF1y/SophisticatedBackpacks#76]
When dyeing backpacks with the new system, any additional dye past the first you place in the crafting grid after placing the backpack causes the recipe output to disappear rather than update with the new output.  You can get the updated output to reappear by removing and then re-adding the backpack to the crafting grid.

Basically it only works with multiple dyes so long as the backpack is the last item placed in the crafting grid.

Mod Version: 1.16.4-2.2.5.197
Forge Version: 1.16.5-36.0.13

**Comment by P3pp3rF1y** [comment]
That appears to be a mod interaction issue. Definitely doesn't happen in the dev environment where I have limited number of mods and I don't see anything wrong with the recipe. But I can see it happening in Enigmatica 6 modpack so I wonder if fast workbench is doing something weird here.

**Comment by P3pp3rF1y** [comment]
this is a bug in fastworkbench, I have just added a note in there with potential fix as well https://github.com/Shadows-of-Fire/FastWorkbench/issues/58
