### ISSUE TITLE
game disconects when opening any backpack

### ISSUE THREAD

**Issue by razgriz5000** [P3pp3rF1y/SophisticatedBackpacks#760]
**Describe the bug**
[crash.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11348615/crash.txt)
Game disconnects me whenever I open any backpack.  I can create a new backpack and still get disconnected.  Error message shown in game: Internal Exception: java.lang.runtimeexception: Tried to read NBT tag that was too big; tried to allocate: 2097153bytes where max allowed: 2097152.

If it helps, I can also provide my world folder.  

**To Reproduce**
1. Open backpack
2. See error

**Expected behavior**
Bag to open.  

**Versions**
FTB Skies 1.06.  Mod version that you're using. Version of forge may also be helpful in some cases
Sophisticated Backpacks 1.19.2-3.18.43.801
Sophisticated Core 1.19.2-0.5.47.234

Image of the error
![2023-04-27 (1)](https://user-images.githubusercontent.com/10761855/235012435-f6eb615f-0434-4be8-8552-8bf70907334f.png)

**Comment by P3pp3rF1y** [comment]
Looks like you have put something with way too much nbt in your backpack. try placing that backpack in world and get stuff out of it using pipes or hopper. Most probable cause I would say is create contraption or something similar

**Comment by razgriz5000** [comment]
already tried that.  Even if I make a new bag my games kicks me out.

**Comment by P3pp3rF1y** [comment]
ok in that case could you share your `sophisticatedbackpacks.dat` file and UUID of your backpack? (visible with advanced tooltips). if you can't even view that uuid to take screen of it then I would need your playerdata. Basically the only way I can see what's going on for you here is by going to the data saved and seeing what data you have saved there.

**Comment by razgriz5000** [comment]
Here it is.  

[sophisticatedbackpacks.dat.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11358576/sophisticatedbackpacks.dat.txt)
![2023-04-29_03 05 46](https://user-images.githubusercontent.com/10761855/235288964-5ad91879-7689-46a0-a27d-0af40fe48d9f.png)
UUID: 251b9fcd-eec4-4b19-b8ef-f1d3d1d341a9
[06a2937e-6d78-4147-ac53-1d6160840fc0.dat.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11358592/06a2937e-6d78-4147-ac53-1d6160840fc0.dat.txt)

**Comment by P3pp3rF1y** [comment]
So there's nothing wrong with this file - backpack contents nowhere close to max limit. could you also share `sophisticatedbackpacks_settings_templates.dat` if you have used the functionality of saving memory slots it could have that data saved there and potentially have an item with way too much nbt

**Comment by razgriz5000** [comment]
I don't have that file.  I don't think I've used saving memory slots or any filters.

**Comment by P3pp3rF1y** [comment]
ahh, I can see what's going on - you have armory cabinet in your inventory with a ton of items and all of that nbt needs to sync with that bit of backpack nbt probably tipping it over the edge. try removing that from your inventory and you should be good.

**Comment by razgriz5000** [comment]
That is exactly it.  Thank you for the help.

**Comment by P3pp3rF1y** [comment]
ok, glad that worked, I was getting worried there's some hard to debug issue with backpacks
