### ISSUE TITLE
Fabric port

### ISSUE THREAD

**Issue by BurgerGlen** [P3pp3rF1y/SophisticatedBackpacks#761]
I created a Github account to say this:

Hello there! I hope you're doing well. I've been a big fan of your mod for a while now and I really appreciate all the hard work you've put into it. I recently made the switch from Forge to Fabric because I found that Fabric has many mods that offer more flexibility and features that I really enjoy.

However, I was disappointed to find that your mod is not currently available on Fabric. I believe that your mod has a lot of potential on the Fabric platform and I think it could attract a new audience who are looking for mods like yours.

I understand that you may have already made it clear that you won't be porting your mod to Fabric, but I wanted to respectfully ask if you would reconsider. I really enjoy using your mod and I believe that many other Fabric players would too. Thank you for your time and consideration.

**Comment by P3pp3rF1y** [comment]
I don't have that much time to be able to work on and then support fabric version so I am sticking to forge and updating the mod there. I may do the port in the future if my situation changes, but find it very unlikely at the moment.
