### ISSUE TITLE
Potions not going into tank upgrades 

### ISSUE THREAD

**Issue by npc8769** [P3pp3rF1y/SophisticatedBackpacks#765]
Was testing out the mod in a mod pack I've been playing with, tried putting potions into the tank and it wouldn't accept the bottles so I attempted to pump the potions in, which made the tank full of uncraftable potion

After that I went to the discord and asked about it, tested it in a new instance with just the backpack mod and got the same results with the back pack not accepting bottles at all

Core version is 0.5.52.256
Backpack version is 3.18.46.821
Game version is 18.2

**Comment by P3pp3rF1y** [comment]
How are you able to pump potions? they are not fluid containers in vanilla, they are just special items and that's it so SB doesn't have any idea what to do with them if you try to put them into the tank. 
I am guessing you may be using mod like create and pumping their potion liquid into the tank. And at that point whatever liquid is being pumped in will show up in the tank.

**Comment by npc8769** [comment]
> How are you able to pump potions? they are not fluid containers in vanilla, they are just special items and that's it so SB doesn't have any idea what to do with them if you try to put them into the tank.

Yes, I was originally using create to pump the potions in after seeing it not accept normal potion bottles, forgot to mention that here, however it didn't work when I made an entirely new folder with no mods aside from the back pack mod and core either

**Comment by P3pp3rF1y** [comment]
well as I said there's nothing that could work there - potions do not contain any fluid unless some mod makes them like that so you will see nothing happening when you try to "drain" potion into tank. In the future I may add similar implementation to how create makes them into fluid containers, but I am not even decided that I want to do it given that other mods already do it. I am closing this one as there's nothing to fix here.
