### ISSUE TITLE
[BUG] Strange behavior with hoppers (white backpack)

### ISSUE THREAD

**Issue by L9Tigrotto** [P3pp3rF1y/SophisticatedBackpacks#766]
Placing any backpack with shift + right click over a hopper will make a new invisible backpack appear (visible when any near block is updated) without any slots inside. I also installed the Canary mod (https://www.curseforge.com/minecraft/mc-mods/canary), which in the latest changelog claims to have changed the hopper code to optimize it (- Replace @Redirect with @Inject to optimize hopper code.) and already sometimes the game is crashed using the hopper connected to other mod's blocks.

I don't know if this bug is caused by the canary mod or by this mod, or maybe by a lack of compatibility between the two mods given the recent hopper code update.

Here's the video where I show what I said above: https://drive.google.com/file/d/1vEEFiJ9LGNQkllIYkx0rUTGroVu3AbWk/view?usp=sharing.

**Mods**
Sophisticated Backpacks: sophisticatedbackpacks-1.19.2-3.18.45.819.
Canary: canary-mc1.19.2-0.1.10.
Forge: Forge - 43.2.10.
There are other mods but they don't interfere with hoppers or backpacks.

**Comment by P3pp3rF1y** [comment]
This just works without any issue for me, just tested that in ATM8 which is a huge modpack so I would rule out that this is SB issue. You will need to report that to Canary as they very likely fiddle with block interaction code or something similar which causes your issue.
