### ISSUE TITLE
Adding tank upgrade to 2nd BP dups 1st One with upgrade

### ISSUE THREAD

**Issue by DemonSeedxp** [P3pp3rF1y/SophisticatedBackpacks#770]
**Describe the bug**
When adding the tank upgrade to a new backpack while already owning another one the entire contents of the first backpack is duped into the new backpack receiving the second upgrade. In my instance it duped an entire backpack of other backpacks and all of their contents.

**To Reproduce**
1. Install tank into a backpack + give it inventory contents
2. Open a different backpack then install another tank upgrade
3. See error

**Expected behavior**
New backpack gain tank and thats all

**Versions**
sophisticatedbackpacks-1.19.2-3.18.45.819  
Forge-43.2.11

**Comment by DemonSeedxp** [comment]
This is just one instance I've had it dupe items, and one I saw happen and knew how to reproduce.
I've had others I found after the fact that I didnt witness happen as well, but don't know what the trigger was so can't say how to recreate.

**Comment by P3pp3rF1y** [comment]
I am unable to recreate. Have you tried this with just sophisticated backpacks (and core) in the pack? if not can you figure out what minimal set of mods is required to recreate the bug?

**Comment by DemonSeedxp** [comment]
ohhhh, shoot. ha, well i'm currently playing from a heavily tweaked version of direwolf 20's 1.19 FTB pack with around 366 mods in the folder so yeah.... probably not such an easy task.
 If it doesn't display the bug on it's own then there's no telling what i could be running that's contributing to the error.

So I'd say just sweep this under the rug and forget about it. Sorry for wasting your time.

**Comment by P3pp3rF1y** [comment]
closing...
