### ISSUE TITLE
upgrading backpack in Valhelsia5 does not increase number of slots

### ISSUE THREAD

**Issue by phbbc** [P3pp3rF1y/SophisticatedBackpacks#771]
**Describe the bug**
On crafting a backpack and upgrading to iron/gold, the inventory size (27 slots) did not increase. In all documentation/videos I see that it was supposed to increase.

**To Reproduce**
1. Upgrade backpack to iron
2. Open backpack
3. Suffer

**Expected behavior**
It should have increased in size.

**Screenshots**
Added

**Versions**
Forge 43.2.10, MC 1.19.2 with the Valhelsia5 modpack on Survival.
![2023-05-20_10 29 18](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/134132753/26b9637c-5496-4dce-8d0c-20db5a284fa9)

**Comment by P3pp3rF1y** [comment]
that's exactly how the backpacks are setup in configs in that pack so you will need to report that to pack author if you want that changed
