### ISSUE TITLE
Crash when an item is crafted

### ISSUE THREAD

**Issue by splatchoot** [P3pp3rF1y/SophisticatedBackpacks#776]
**Describe the bug**
Crash log if it's a crash.
Info on what other mods you're using that may cause a conflict here if applicable.
https://mclo.gs/F7zO0y8
Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. craft any item (upgrade backpack, craft items from other mods)
2. Crash

**Expected behavior**
the game not to crash

**Screenshots**

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases

**Comment by P3pp3rF1y** [comment]
you need to update backpacks as well not only core as now you have newer version of core that's not supported by the older version of backpacks
