### ISSUE TITLE
[Feature Request] Ability to lock slots in a backpack to prevent move on auto-sort

### ISSUE THREAD

**Issue by jengendler** [P3pp3rF1y/SophisticatedBackpacks#78]
I find it useful to use certain backpack slots (like bottom row) for specific items, usually other nested backpacks. I would love to lock/unlock those slots at will so that I can still auto-sort the rest of the contents.

**Comment by zanecek** [comment]
Necessary function, I am voting for.

**Comment by P3pp3rF1y** [comment]
This is now included in the latest release

**Comment by jengendler** [comment]
Thank you!
