### ISSUE TITLE
Java lang error

### ISSUE THREAD

**Issue by iamtyroon** [P3pp3rF1y/SophisticatedBackpacks#781]
error when loading mod on 1.19.2 
![Screenshot 2023-05-29 005912](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/105237183/4a1352a0-8ebc-49b2-a59b-21df2b537f31)

**Comment by P3pp3rF1y** [comment]
I can't do pretty much anything with error like that, but make sure you have latest versions for the given version of minecraft
