### ISSUE TITLE
The game crashes trying to render the backpack in the curios menu

### ISSUE THREAD

**Issue by Darkem08** [P3pp3rF1y/SophisticatedBackpacks#782]
When opening the curios menu, with the backback on the back slot, the game freezes for a couple of seconds and then crashes, with error code -1

I'm also going to upload the crash report, in case that is needed
[crash-2023-06-02_18.12.50-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11637149/crash-2023-06-02_18.12.50-client.txt)

**Comment by Darkem08** [comment]
Turns out by just downloading the latest version everything worked again, my bad

**Comment by Darkem08** [comment]
It started again, even after updating everything, im going to reupload the error in case it is needed
[crash-2023-06-10_22.03.38-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11713228/crash-2023-06-10_22.03.38-client.txt)

**Comment by P3pp3rF1y** [comment]
that's optifine for you removing stuff it shouldn't be, just drop it and the issue is solved
