### ISSUE TITLE
Massive compacting error(gives way more than it should)

### ISSUE THREAD

**Issue by BonyHeight** [P3pp3rF1y/SophisticatedBackpacks#786]
When using the compacting upgrade(advanced), it will give a whole stack of blocks when it should only give one, or only a few(like a stack of coal becomes ~a stack of coal blocks)

To Reproduce**
1. put an advanced compacting upgrade on a backpack(I used a netherite backpack)
2. get a stack of iron ingots(works most consistently with this it seems for some reason, with coal and gold sometimes it did not compact at all, specifically after it had worked as above once)
3. I shift clicked them in, upon initial discovery, not testing, it seemed to also work on coal collected via magnet
4. That's it, should give you way more blocks than would be expected

**Expected behavior**
A number of blocks and remaining items equivalent to the amount placed into backpack

**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/111785308/23fb1a37-a789-4c7d-bbad-5460c7c7b94e)

**Versions**
minecraft 19.2, forge 43.2.11, mod .847

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release
