### ISSUE TITLE
Crash when loading a world that has a backpack with the inception upgrade

### ISSUE THREAD

**Issue by InqGilgamesh** [P3pp3rF1y/SophisticatedBackpacks#787]
**Describe the bug**
Exactly as it says on the tin; opening a world where a backpack has an inception upgrade causes it to either crash, or remain frozen without rendering anything.  This issue doesn't occur on the immediately previous versions of SB and Core.  This issue happens regardless of if the upgrade is set to use the main or sub backpack inventories first, but doesn't happen if the upgrade is disabled.

Crash log: [crash-2023-06-04_20.17.50-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11647785/crash-2023-06-04_20.17.50-server.txt)

**To Reproduce**
1. Get a backpack
2. Put an inception upgrade in the backpack.
3. Close the backpack.
4. Become unable to open the backpack again.
5. Attempt to drag the backpack to somewhere else in your inventory.
6. Crash.
7. Reopen the world.
8. Crash or freeze (I get crashes most often when not full screened, and vice versa for freezes).
9. Backport to sophisticatedbackpacks-1.19.2-3.18.47.836.jar and sophisticatedcore-1.19.2-0.5.57.275.jar
10. Reopen the world.
11. Don't crash or freeze.

**Expected behavior**
No crash/freeze when a backpack has the inception upgrade active.

**Screenshots**
I'll do you one better, here's a video of the crash setup: https://youtu.be/NN3MuiuuP3U

**Versions**
SB: sophisticatedbackpacks-1.19.2-3.18.50.847.jar
Core: sophisticatedcore-1.19.2-0.5.66.299.jar
Forge: 43.2.11

**Comment by InqGilgamesh** [comment]
Another find after backporting again: it looks like the crash causes whichever backpack you clicked on in step 5 to get deleted; I'd originally had 7 backpacks total (1 main, 6 incepted) but in the video I only have 6 total, and after backporting again I'm down to 5.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release of sophisticated core. As for the lost backpacks there's unfortunately nothing i can do code wise, but you should still be able to retrieve them using `/sbp list` and `/sbp give` commands.
