### ISSUE TITLE
Advanced Compacting Upgrade not working with Lapis

### ISSUE THREAD

**Issue by Jomeaga** [P3pp3rF1y/SophisticatedBackpacks#79]
I have the advanced compacting upgrade set to a blank blacklist. It seems to be compacting most vanilla and modded materials. However it just doesn't seem to want to work with Lapis. I've tried taking it out and inserting it several times, I fiddled with the settings and it even uncompacted regular lapis into some modded shards; but it won't compact it into the blocks.

![image](https://user-images.githubusercontent.com/31868004/111018357-5895ca00-8386-11eb-96b5-d509265cc325.png)

**Comment by P3pp3rF1y** [comment]
It definitely works in my dev environment and works in enigmatica 6 modpack that I play as well. So I am guess that in your modpack you have some special recipes for lapis, probably the uncrafting one doesn't uncraft lapis block back into lapis. Check the recipes in JEI and try to change the mode to compact anything which should compact the lapis even if uncrafting the block doesn't produce lapis. If there are regular crafting recipes for lapis into lapis block and lapis block into 9 lapis pieces then I will need more info on how to recreate this as I am unable to.

**Comment by Jomeaga** [comment]
It's in Stacia Expert. Lapis has 3 sizes and crafting recipes between all.

Small Lapis <-> Lapis <-> Lapis Blocks

If I set the backpack to compact anything then it just explodes the lapis into the small one lol It is really bizarre.

**Comment by P3pp3rF1y** [comment]
there is a recipe to craft 4 lapis into those small parts and because the pack uses outdated version of mod it doesn't have fix that was release for it almost 2 weeks ago. just update it.
