### ISSUE TITLE
[1.19.2] crash when shift+click

### ISSUE THREAD

**Issue by coco875** [P3pp3rF1y/SophisticatedBackpacks#790]
**Describe the bug**
Some time Shift+click crash the game
[crash-2023-06-11_13.57.00-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11715337/crash-2023-06-11_13.57.00-client.txt)

**To Reproduce**
1. Open backpack
2. Shift+click on item
3. Crash

**Expected behavior**
work x)

**Screenshots**
any

**Versions**
mc:1.19.2
forge:43.2.14
sophisticated backpack:1.19.2-3.18.50.849
sophisticated core: 1.19.2-0.5.69.311

**Comment by P3pp3rF1y** [comment]
that's smoothswapping crashing you so they have to fix this bug.
