### ISSUE TITLE
Client crash when opening backpack

### ISSUE THREAD

**Issue by Vitaaliyy** [P3pp3rF1y/SophisticatedBackpacks#793]
My client is crashing upon opening any backpack, it worked fine like 2 minutes ago, I just put an inception upgrade in one backpack in creative to test it out, and now I can't open ANY backpack, none of the others have inception, so I don't get it, my crash reports are all different too. 
(This is also definitely client-side because no one on the server has the same problem with their backpacks right now and they could even put the inception upgrade without problems.)

[crash-2023-06-13_01.36.42-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11729154/crash-2023-06-13_01.36.42-client.txt)
[crash-2023-06-13_01.40.46-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11729155/crash-2023-06-13_01.40.46-client.txt)

[crash-2023-06-13_01.53.38-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11729145/crash-2023-06-13_01.53.38-client.txt)

**To Reproduce**
1. Put inception upgrade in a backpack
2. Try to open the backpack
3. Crash

**Expected behavior**
Open the backpack with no crash. 

**Versions**
Minecraft 1.18.2
 Forge 40.2.9
 Version of the mod: 846, but tried downgrading to the one I was previously on aka 818, doesn't work either.

**Comment by P3pp3rF1y** [comment]
please update to the latest core and backpacks where this has been solved for some time
