### ISSUE TITLE
You can access other players bags when they are wearing them

### ISSUE THREAD

**Issue by RoyalReject** [P3pp3rF1y/SophisticatedBackpacks#798]
**Describe the bug**
You are able to open other players backpacks when they are wearing them.

**To Reproduce**
1. Have one player wear a back pack.
2. Have second player shift click players back.
3. they are able to open the players bag

**Expected behavior**
I do not think you should have access to others players bags

**Versions**
1.19.2-3.18.45.819
Forge: 43.2.11

**Comment by P3pp3rF1y** [comment]
that is a feature that you can turn off per backpack / for all backpacks or it can be turned off server wide in config so that works as expected.

**Comment by 0xicl33n** [comment]
IMO, it should be disabled for your backpack by default.
