### ISSUE TITLE
Memory leak? 

### ISSUE THREAD

**Issue by Vitaaliyy** [P3pp3rF1y/SophisticatedBackpacks#799]
**Describe the bug**
Seems like there is a memory leak somewhere. My ram usage slowly builds up with the mod until it crashes with error 137. Without the mod my server seems to stay at around 4-5gb of ram. I would love to keep using the mod, do you know a solution for this? Or is this mod well known for incompatibilities with other mods perhaps? 

For info, my server has 8gb of ram which should be more than enough. Tried with 10gb as well and same thing it builds up 'til it crashes. 
Tried the command /sbp removeNonPlayer false, didn't change much either. 

**To Reproduce**
1. Start server with mod
2. RAM slowly going up til it crashes with error 137. 

**Expected behavior**
Ram shouldn't build up. Not crash the server 

**Screenshots**

**Versions**
sophisticatedbackpacks-1.18.2-3.18.45.818 ; 

sophisticatedcore-1.18.2-0.5.50.250

Minecraft version 1.18.2.

Forge version: 40.2.0

**Comment by P3pp3rF1y** [comment]
This doesn't seem to be happening to others as it is the first time I am hearing about a memory leak. I assume you have other mods in the pack, mind sharing what mods those are? There are some that actually change SB code and I can't vouch for what they are doing.

**Comment by Vitaaliyy** [comment]
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Emotecraft (Forge) (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/emotecraft-forge)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Incapacitated (by CartoonishVillain)](https://www.curseforge.com/minecraft/mc-mods/incapacitated)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Untamed Wilds (by raytrace82)](https://www.curseforge.com/minecraft/mc-mods/untamedwilds)
[JEITweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/jeitweaker)
[Vanishmod (by MasterPerki)](https://www.curseforge.com/minecraft/mc-mods/vanishmod)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Paragliders (by Tictim)](https://www.curseforge.com/minecraft/mc-mods/paragliders)
[Dark Utilities (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-utilities)
[Konkrete [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Pig Pen Cipher (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher)
[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Runelic (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/runelic)
[Modern Life (by Darimus)](https://www.curseforge.com/minecraft/mc-mods/modern-life)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Item Highlighter [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-highlighter)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Corail Tombstone (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone)
[Skin Swapper (by cobrasrock)](https://www.curseforge.com/minecraft/mc-mods/skin-swapper)
[Alcocraft: Beer & Stuff (by hadrus91)](https://www.curseforge.com/minecraft/mc-mods/alcocraft-beer-and-stuff)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[XercaMod (by xerca0)](https://www.curseforge.com/minecraft/mc-mods/xercamod)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Camera Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/camera-mod)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Dynamic View[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)
+ Ai improvements

I only have around 60 mods

**Comment by P3pp3rF1y** [comment]
I have profiled this using different ways and can't see anything that would be leaking so I will need more info here. 
What you could potentially do is use JFR to get a recording of what's happening specifically with your server
`jcmd [PID] JFR.start filename=inflight-recording.jfr dumponexit=true`. just need to replace `[PID]` with the process id of your minecraft instance running on the server. Then once you shut down the server there will be the jfr recording there that I can take a look at and see what's being allocated. The recording will have quite a few mb so would need to be put on some file sharing service.

**Comment by P3pp3rF1y** [comment]
closing given no follow up
