### ISSUE TITLE
[BUG] [1.20.1] Match Backpack Contents Filter Not Working

### ISSUE THREAD

**Issue by Zedrimar** [P3pp3rF1y/SophisticatedBackpacks#800]
**Describe the bug**
Match backpack contents filter doesn't work. If selected, and the upgrade is active, ANY item dropped will be put into the backpack regardless of if it is already in the pack or not. I tested this with the mod by itself too. Anything that has a filter for "match backpack contents" will pick up anything, even if backpack contents is empty. Or it will simply ignore what's in the first slot, if there is something that matches, any other items that match will not go in. Move item to second slot and suddenly everything is picked up. I tried removing and replacing the filter upgrade, sometimes it will pick up nothing at all, other times it will pick up anything and everything

**To Reproduce**
1. Open backpack
2. Drop in the advanced pickup upgrade (and or the advanced magnet upgrade).
3. Drop an item on the ground not already in the backpack
4. Open backpack again (item(s) will be there)

**Expected behavior**
When match backpack contents filter is selected, only what is already in the backpack should go in. Nothing not already in the backpack should go in it, and instead go to player inventory

Not sure if it helps (I didn't see anything obvious personally), but here are both the latest and debug logs.
[Latest.log (Pastebin)](https://pastebin.com/4BcmKiJh)
[Debug.log (Pastebin)](https://pastebin.com/xV4K6mxP)

**Screenshots**
N/A

**Versions**
Sophisticated backpacks 1.20.1 - 3.18.50.853
Sophisticated Core 1.20.1 - 0.5.69.322
Tested on Forge(s): 1.20.1 - 47.0.15 and 47.0.18 (same issue occurs on both)

To rule out any mod interaction weirdness, I tested this with only the following:

- JEI
- Sophisticated Backpacks
- Sophisticated Core
- Sophisticated Storage (not specific for this test, just wanted to play around with it as well, away from my main modpack)

**Comment by P3pp3rF1y** [comment]
this is fixed in the latest version on CF
