### ISSUE TITLE
1.20.1 forge version crash the game

### ISSUE THREAD

**Issue by GXFOS** [P3pp3rF1y/SophisticatedBackpacks#808]
**Describe the bug**
**1.20.1 FORGE** version of the mod not working and crash the game instantly

**To Reproduce**
1. Open curseforge, press AllTheMods9 modpack
2. Click on 'PLAY' tab inside minecraft launcher
3. the launcher try load the game

**Expected behavior**
The game cannot be executed, press play and crash instantly

**Screenshots**
https://imgur.com/a/FdR5Plh

**Versions**
1.20.1

**Comment by P3pp3rF1y** [comment]
sounds like you have a problem with the modpack in general you will need to follow up on that on modpack discord or their github with more details. I would guess you may not have enough memory allocated, but that's just a guess as there's almost no info to use here.
