### ISSUE TITLE
Backpack not opening and immediately kicking you out of the server

### ISSUE THREAD

**Issue by TwoReverse** [P3pp3rF1y/SophisticatedBackpacks#811]
Every time I try to open the backpack I get kicked from the server with the message ''io.netty.handler.codec.decoderexception received unexpected null component''
I am playing on an Aternos server with two other people. who do not experience this error.  I've tried reinstalling the mods and updating java to fix the issue but haven't had any luck so far.

**Expected behavior**
Opening the backpack normally without getting kicked.

**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/115188770/2d6ac88f-3ae8-46f7-b4cd-ab23f040b762)

**Versions**
1.20.1

**Comment by P3pp3rF1y** [comment]
Could you share crash log or if there's none for this check what's being logged in the log at the time it happens? Looks like you may have an issue with some item with too much nbt in your backpack, but hard to tell from this screen alone

**Comment by TotalSync** [comment]
I am having a similar issue. I just unpacked the dat file, and there does not seem to be anything alarming. Something worth noting, is that I am unable to open _any_ backpack. Regardless of its storage. This includes newly crafted backpacks.

I do get an entirely different error with new backpacks though.

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/5209243/f88b5030-f4b2-432e-abf7-d2fb9e4d861f)

Other players in the server can access my backpacks without issue.

Edit: 
I have been unsuccessful in duplicating the bug.
This happened in the 1.19.2 version

Edit 2:
All upgrades still function appropriately, based off of what I can interact with (Adv. Deposit, Adv. Auto Feeding, Stack Upgrade (3), Adv. Pickup, Adv. Compacting).

I can attach/link my player data and the sophisticated_backpacks.dat if you would like.  If there are logs, I can retrieve those as well.

**Comment by P3pp3rF1y** [comment]
@TotalSync could you share actual crashlog / part of the log where this is reported - that gui message doesn't help much and given that you say it affects all your backpacks it doesn't sound like it's a problem with backpack contents.

**Comment by TotalSync** [comment]
I connected to the server, walked around a bit, then opened the backpack.
I open the backpack around 18:44.24. Please let me know if you need anything else or this is the wrong file, and I will remedy it ASAP.

[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/11986677/latest.log)

Edit: The server owner decided to add a couple mods to the server tonight, and I am no longer having the issue mentioned above 0-o.

**Comment by LunaTheWolf072** [comment]
I'm also having this problem except it makes my game completely crash. I've been trying to use it on a 1.18.2 server and it always crashes without fail. And then i get the error message:

java.lang.NoSuchMethodError: 'void net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.setSlotLimit(int)'

Anyone know a fix?

**Comment by P3pp3rF1y** [comment]
you likely have outdated sophisticatedcore @LunaTheWolf072 so just update that, best to update both core and backpacks to the latest version

**Comment by P3pp3rF1y** [comment]
@TotalSync that is the correct file, but for some reason doesn't show anything at the time you tried to open the backpack, maybe it did show something on the server, but given that it works now I would consider that "fixed" for you. if you happen to get the issue again please let me know and at that point I may need what was logged on the server at the time

**Comment by TotalSync** [comment]
We did look for what was logged on the server as well as we figured it was a server-side issue, but there was nothing on the server, it simply just said I disconnected. I believe why I am able to use the backpacks now is because we had to update our mod profiles, and when that happened, something must have gotten overwritten. I will for sure let you know if I encounter it again.

Thanks for the help!

**Comment by LunaTheWolf072** [comment]
> you likely have outdated sophisticatedcore @LunaTheWolf072 so just update that, best to update both core and backpacks to the latest version

I did that and it is exactly what the problem was, thanks for the help. Now I don't have to give my backpack away to someone else on the server.
