### ISSUE TITLE
Missing backpack slots as if tank was in backpack

### ISSUE THREAD

**Issue by Nathrexeio** [P3pp3rF1y/SophisticatedBackpacks#815]
**Describe the bug**
Missing slots, as if there was a tank in the backpack, but it still allows 2 tanks ontop of those extra missing slots

All forge mods in the running mod folder:
alexsmobs-1.21.1.jar, appleskin-forge-mc1.19-2.4.2.jar, architectury-6.5.85-forge.jar, ars_nouveau-1.19.2-3.15.1.jar, automobility-0.4.1!.19.2-forge.jar, AutoRegLib-1.8.2-55.jar, baritone-api-forge-1.9.4.jar, BetterTridents-v4.0.2-1.19.2-Forge.jar, Bookshelf-Forge-1.19.2-16.3.20.jar, carryon-forge-1.19.2-2.0.5.16.jar, cfm-7.0.0-pre35-1.19.2.jar, citadel-2.1.4-1.19.jar, cloth-config-8.2.88-forge.jar, Clumps-forge-1.19.2-9.0.0!4.jar, CNB-1.19-1.5.4.jar, collective-1.19.2-6.57.jar, comforts-forge-6.0.5!.19.2.jar, CreativeCore_FORGE_v2.9.3_mc1.19.2.jar, creeperoverhaul-2.0.9-forge.jar, curios-forge-1.19.2-5.1.4.1.jar, deeperdarker-forge-1.1.6-forge.jar, do-a-barrel-roll-2.6.11.19.2-forge.jar, EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar, endertrigon-1.0.jar, epicsamurai-0.0.11.jar, FarmersDelight-1.19-1.2.1.jar, ferritecore-5.0.3-forge.jar, freecam-forge-1.1.6!.19.jar, friendsandfoes-forge-mc1.19.2-1.8.2.jar, geckolib-forge-1.19-3.1.40.jar, gravestone-1.19.2-1.0.1.jar, healingcampfire-1.19.2-5.1.jar, huskspawn-1.19.2-3.3.jar, jei-1.19.2-forge-11.6.0.1015.jar, journeymap-1.19.2-5.9.7-forge.jar, lucky-block-forge-1.19.2-13.0.jar, L_Enders_Cataclysm-0.84-1.19.2.jar, mahoutsukai-1.19.2-v1.34.46.jar, moonlight-1.19.2-2.2.38-forge.jar, mooshroomspawn-1.19.2-3.3.jar, moremobvariants-forge_1.19.2-1.1.0.jar, OPF-15.jar, OptiFine_1.19.2_HD_U_I1_MOD.jar, Patchouli-1.19.2-77.jar, PureSuffering-1.19.2-1.4.0R.jar, PuzzlesLib-v4.4.2-1.19.2-Forge.jar, Quark-3.4-402.jar, QuarkOddities-1.18.jar, randommobsizes-forge-1.19.2-1.1.jar, resourcefulconfig-forge-1.19.2-1.0.20.jar, SereneSeasons-1.19.2-8.1.0.24.jar, smallships-forge-1.19.2-2.0.0-a2.3.jar, sophisticatedbackpacks-1.19.2-3.18.50.849.jar, sophisticatedcore-1.19.2-0.5.69.311.jar, strayspawn-1.19.2-3.3.jar, subterrestrial-forge-1.19.2-2.0.0.jar, supplementaries-1.19.2-2.3.17.jar, swingthroughgrass-1.19.2-1.10.0.jar, TA-0.9.5-1.19.2.jar, The_Undergarden-1.19.2-0.8.3.jar, twilightforest-1.19.2-4.2.1518-universal.jar, UnusualEnd1.19.2_V1.4.3.jar, vc_gliders-1.0.2-forge.jar, vinery-forge-1.2.11.jar, wardenhorn-1.1-forge-mc1.19.2.jar, zombiehorsespawn-1.19.2-4.6.jar, [1.19.2-forge]-Epic-Knights-7.11.jar, [1.19.2] SecurityCraft v1.9.6.1.jar, [1.19.2]-Medieval-Siege-Machines-v1.10.jar. 

**Expected behavior**
this empty area should not exist

**Screenshots**
![javaw_uSNexCGU46](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/138328996/a39bdb2c-ced6-4c95-ad83-7f059b6e3f78)

![2023-07-01_16 14 05](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/138328996/a98e12be-c5e4-4842-95eb-ae3d948980c1)
All of the Diamond backpacks which are working properly I have, have this white pixel sticking out, some of the ones that are not working properly do not
![javaw_peJ0lStgV3](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/138328996/b4123293-924e-4fa1-9691-f36366d84726)

Missing white pixel in backpack with problem (but not always in each broken backpack)
![javaw_VcK8iJfSfX](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/138328996/8e1caba3-ace3-4a3a-b99f-de5585b21154)

**Versions**
sophisticatedbackpacks-1.19.2-3.18.50.849.jar. 

**To Reproduce**
It seems to only happen to backpacks that have had a tank in them and it was removed, then at some point the server was shut down and then turned back on but this isn't consistant 

I haven't put a tank in this backpack in awhile or the parrent backpack (several days now), this backpack is inside of another backpack, this is only happening to 1 of my backpacks, I have moved the contents into a new backpack.
this was the first time I opened the backpack since the server started aswell

**Comment by F-a-y-t-h** [comment]
Versions
sophisticatedcore-1.20.1-0.5.83.395.jar
sophisticatedbackpacks-1.20.1-3.18.56.890.jar


I had this issue, and managed to repeat it semireliably
Inception Upgrade
Open a nested backpack,
Remove battery and or tank upgrade(s) and do not reopen the backpack (tested using two tanks and a battery)
Restart server/world

Looking at the backpack savefile 'accessLogRecords' only seem to get updated when the backpack is opened, not closed
This bug wont happen if you reopen the backpack again after changing upgrades

**Comment by Puffle2K** [comment]
Versions
Sophisticated Core 0.5.89.425
Sophisticated Backpacks 3.18.59.909
Forge 47.1.3
Minecraft 1.20.1

I have this issue, and I believe it is repeatable:
Place pump and two tank upgrades into a backpack
Fill both tanks and double click on one of them while the other is in the upgrade slot
They will stack, removing the tank from the upgrade slot, but the backpack will not give the inventory slots back. It will still allow you to put two tanks in the backpack, but will just keep removing slots. Trying to put a tank in a backpack that doesn't have enough slots to remove will cause the game to crash.

**Comment by Puffle2K** [comment]
It seems as though this can be fixed by shift left clicking a stack of tank upgrades into the backpack with the slots available, and then manually removing the tanks.

**Comment by Nathrexeio** [comment]
It worked! ok thats good to know, I managed to do it with 8 tanks instead of 16, ima see how low I can get it

**Comment by P3pp3rF1y** [comment]
I fixed the issue that caused this in the latest releases but if backpack was already borked I am afraid a new one would need to crafted/spawned in.
