### ISSUE TITLE
Unable to add items to backpack item blacklist

### ISSUE THREAD

**Issue by LandofHeros2234** [P3pp3rF1y/SophisticatedBackpacks#817]
**Describe the bug**
Whenever I try to add any item to the item the text shows red and does not allow it. (I am using the Configured mod)
Edit: I also can't change it via editing the server config file directly, as it causes the world to get stuck loading
**Versions**
sophisticatedbackpacks-1.19.2-3.18.53.868

**Comment by P3pp3rF1y** [comment]
What value are you putting in the config exactly? Sounds like it is invalid and that's why it is not allowed.

**Comment by P3pp3rF1y** [comment]
closing given no feedback to the question
