### ISSUE TITLE
jukebox upgrade multiplayer server

### ISSUE THREAD

**Issue by skunozer** [P3pp3rF1y/SophisticatedBackpacks#821]
i have a problem with the jukebox upgrade im playing on a multiplayer server when i click play nothing happens
im playing on downcraft mod pack         forge version is 40.2.9    version 1.18.2

i hope you can help me because most of the things in this modpack dosent work on multiplayer servers

**Comment by P3pp3rF1y** [comment]
I can't help you with that without more specifics, like what exact disc and can this disc be played in regular jukebox. 
My best guess is that the disc you have in the jukebox only exists on server and doesn't have a sound to it on client or something similar. 
And seeing that there are other multiplayer issues with the server it sounds like you need to follow up with either the server owner or modpack maker first before pinging individual mod makers

**Comment by P3pp3rF1y** [comment]
closing given long time of no response
