### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by skellitor301** [P3pp3rF1y/SophisticatedBackpacks#826]
**Describe the bug**
Crash on startup.
[Crashlog](https://gist.github.com/skellitor301/fa21116ce352dd185ee45cdf7f77a0f1)

**To Reproduce**
Start Minecraft with the modlist show in the crashlog.

**Versions**
Minecraft: 1.20.1
Forge: 47.1.0
Sophisticated Backpacks: 1.20.1-3.18.55.884
Sophisticated Core: 1.20.1-0.5.78.366

**Comment by skellitor301** [comment]
After some testing I've found that it's Optifine that's the culprit, and it's not playing nice with several other mods as well.

**Comment by zinerith** [comment]
I am using optifine with backpacks and having no such issues on 1.19.2, using most recent versions of both.
