### ISSUE TITLE
[1.19.x Forge] Backpack items should return false for canFitInsideContainerItems method

### ISSUE THREAD

**Issue by TelepathicGrunt** [P3pp3rF1y/SophisticatedBackpacks#828]
I am the developer of Bumblezone and I have a Honey Cocoon item that acts like a mini Shulker Box. What a player found is because Sophisticated Backpacks does not return false for canFitInsideContainerItems method in the backpack item, the Shulker Box slot I use will not reject the backpack. 

This slot (patched by Forge to check canFitInsideContainerItems ) will prevent Shulker Boxes from being stored in themselves or in my block and vice versa to prevent infinite storage.

What this means is infinite storage can be obtained by putting a backpack into a Shulker Box or my block because canFitInsideContainerItems returns true for the backpacks. Example is shown in this video with using just Sophisticated Backpack and vanilla Shulker Boxes:

https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/40846040/3bae0051-1097-477c-9a50-859e801b6471

**Comment by P3pp3rF1y** [comment]
I have added configs for both backpack reporting to other container items if it can go in them (by default it can't so returns false in the method you have suggested). and there's also config for whether container items can go in the backpack (by default they are allowed in the backpack). this is now released on CF
