### ISSUE TITLE
shift clicking in crafting tab dupes items

### ISSUE THREAD

**Issue by MatthiasMann** [P3pp3rF1y/SophisticatedBackpacks#83]
Using sophisticatedbackpacks-1.16.4-2.2.6.207 with a crafting upgrade and the stone cutter upgrade.

In both of these upgrades using shift click on the crafting result slot puts one stack into the player inventory (arrow points downwards) but only uses one set of crafting ingredients.

In the stone cutter I tested with stone -> stone bricks and stone bricks -> stone brick stairs.

For crafting I crafted Bloodmagic blank runes which uses an orb that is not consumed while crafting.

**Comment by P3pp3rF1y** [comment]
The dupe issue is actually fixed in the latest version (209). But looking at this I have broken shift clicking recipes (now only clicks out single result instead of crafting as much as possible from ingredients in the crafting matrix) so I will use this issue to track fixing of that.

**Comment by P3pp3rF1y** [comment]
The issue with shift click in crafting result only doing one craft is now fixed in the version that's on CF.
