### ISSUE TITLE
Bug - Backpack resets everything (Color, items, upgrades, etc.) when changing its slot in the inventory

### ISSUE THREAD

**Issue by NoozyOficial** [P3pp3rF1y/SophisticatedBackpacks#835]
**Describe the bug**
I've had a server for 10 days, everything was just fine, but starting tomorrow, my players discovered a "bug". When you pick up a backpack and move it to a slot, it resets everything, only the materials remain the same. I've tried this in singleplayer mode and it doesn't happen there.

**To Reproduce**

1. Click on the Backpack item in the inventory.
2. Move it to another slot (sometimes it needs more than one try to happen, sometimes it happens on the first swap).
3. See the error.

**Expected behavior**
The backpack should remain the same.

**Versions**
Sophisticated Backpacks 3.18.40.777
Forge 1.18.2 40.2.4
Sophisticated Core 0.5.37.202

**Video**
https://youtu.be/vFuOExknIQo

**Note**
I'm using a hybrid version of Forge/Bukkit, Magma. But I don't think that could be the problem, since we've been playing for 10 straight days and this issue hasn't occurred before.

Is there a way to reset everything from Sophisticated Backpacks? Like, literally everything, without resetting the world?

**Comment by P3pp3rF1y** [comment]
Something is resetting the backpacks nbt that's the cause of this issue for you, the only thing I can suggest is try narrowing it down to what combination of mods or perhaps the server itself is causing this and let me know. Very likely will be for them resolve, but I would like to understand what can be causing this as well as it may come up again

**Comment by P3pp3rF1y** [comment]
and yeah this is Magma issue - see this https://git.magmafoundation.org/magmafoundation/Magma/-/issues/600
