### ISSUE TITLE
Bug - Backpack resets when changing inventory slot

### ISSUE THREAD

**Issue by ezetwd** [P3pp3rF1y/SophisticatedBackpacks#836]
Describe the bug
I have a server 4 months ago. The backpack mod always worked normally, but since yesterday all players are experiencing resetting problems with their backpacks when moving them from the slots in the inventory. The same thing happens when crafting them or taking them out of creative mode

To Reproduce
1- Open the backpack and store items
2- Move backpacks to any inventory slot
3- The backpack resets, even changing to the default color and losing all its upgrades

Expected behavior
That this error does not happen :(

Versions:
sophisticatedbackpacks-1.18.2-3.18.40.773
sophisticatedcore-1.18.2-0.5.36.199
Minecraft: 1.18.2 Forge

VIDEO: https://www.youtube.com/watch?v=1sNEofBOMkY

**Comment by P3pp3rF1y** [comment]
another player just reported same issue, are you also running this on Magma server? if not again my advice will be to figure out with what combination of mods this is happening as it's basically caused by something removing nbt from backpacks.

**Comment by P3pp3rF1y** [comment]
If you are running this on Magma they definitely have this issue - see https://git.magmafoundation.org/magmafoundation/Magma/-/issues/600

**Comment by ezetwd** [comment]
yes, my server runs on Magma.  Do you think that an update of it has caused this error?  And how can I downgrade the update?

**Comment by ezetwd** [comment]
yes, my server runs on Magma.  Do you think that an update of it has caused this error?  And how can I downgrade the update?

**Comment by P3pp3rF1y** [comment]
I had no idea that anything like Magma existed until this was reported so I can't help you with that you will need to work with developers of that server

**Comment by ezetwd** [comment]
Fixed.  I downgraded the latest Magma update (installed a server.jar from days ago) and set auto-update (magma.yml) to false.  Everything works fine again
