### ISSUE TITLE
My backpack disappeared in the Void (even with Everlasting Upgrade)

### ISSUE THREAD

**Issue by WolfMethod** [P3pp3rF1y/SophisticatedBackpacks#839]
**Describe the bug**
Well... I fell into the Void in the End, but my backpack had the Everlasting Upgrade, and when I went to where I died thank to JourneyMap marker, I didn't find my backpack.

**Versions**
I used the latest version available for minecraft 1.20.1.
My forge version is 47.1.0

**Comment by WolfMethod** [comment]
Up

**Comment by P3pp3rF1y** [comment]
There was an incorrect y level used for the end here so now I have this fixed for next release

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
