### ISSUE TITLE
[Feature Request] Support for JEI's drag and drop for filters.

### ISSUE THREAD

**Issue by Jvs34** [P3pp3rF1y/SophisticatedBackpacks#84]
In mods like refined storage and immersive engineering whenever an item slot only acts as a filter, JEI allows to drag and drop the item definition from it's own panel rather than having to own the item in question.

When hovering an item on JEI the filter slots turn green signifying that drag and drop is available for that slot.
This feature would make setting up upgrade filters less of a pain.
![image](https://user-images.githubusercontent.com/1412812/111453518-f46f5f00-8713-11eb-82a9-0629ce8036a0.png)
![image](https://user-images.githubusercontent.com/1412812/111459391-ea049380-871a-11eb-8f4e-dde8db0c4ce9.png)

**Comment by P3pp3rF1y** [comment]
Took a look at this and it was very simple to implement so I just added it right away.
