### ISSUE TITLE
crafting upgrade wont output crafted item

### ISSUE THREAD

**Issue by draco137955** [P3pp3rF1y/SophisticatedBackpacks#843]
**Describe the bug**
im ot sure if its becuase of the other mods i have on but for some reason when using the crafting upgrade i cant grab the crafted item, it shows the item it is suposed to craft just like normal but when going to grab it wont even click or pick up. it worked before and even with more mods than i currently have. i tried downsizing and seeing if it was maybe just a compatability thing but im not sure. and sometimes it will work but then five minutes later it wont but i have yet to experience it working again after, ive had to restart multipule times for the chance that it works again, usually after shuffleing mods around.
the other mods that i have on are as follows (all in version 1.20.1)
sophisticated core, sophisticated backpacks, sophisticaket storage, just enough items, appleskin, curios api, balm, waystones, create, mouse tweaks, crafting tweaks, create ore excavation, create enchantment, create sifting, create mechanical spawner, xaero's minimap, xearo's world map, jade, jade addons, silent lib, scaling health, ht's treechop, armor points ++, functional armor trim.

**To Reproduce**
1. Open backpack
2. open crafting upgrade interface
3. input crafting recipe ingredients
4. go to grab crafted item, item wont come out

**Expected behavior**
i figured that when i go to craft and put the ingreidients in i should be able to grab the crafted item.

**Screenshots**

**Versions**
forge, 1.20.1

**Comment by P3pp3rF1y** [comment]
Could you check logs and see if there's something getting logged there when this happens?

**Comment by draco137955** [comment]
> Could you check logs and see if there's something getting logged there when this happens?

i would but to be honest i dont know how. im not much of a programmer or anything, i mainly just use TLuancher. if you tell me how i might be able to find it or maybe i could send them to you?

**Comment by P3pp3rF1y** [comment]
sorry I don't support tlauncher, if you can retest with different launcher and let me know if it works / what you're experiencing there I can take a look

**Comment by draco137955** [comment]
i actually recently moved over to curseforge luancher and it still does the same thing, i havent noticed any difference when useing it between the two luanchers so i dont think it was part of the problem.

**Comment by P3pp3rF1y** [comment]
I haven't responded to this in a very long time, but given that so many players use crafting upgrade in multiple versions without any issue this was something specific to the pack / setup. I am going to close, if you happen to encounter this again feel free to create a new issue with steps how to recreate.
