### ISSUE TITLE
Gold Backpack missing slots. 

### ISSUE THREAD

**Issue by MattRidge** [P3pp3rF1y/SophisticatedBackpacks#844]
**Describe the bug**
Gold Backpack not showing 81 slots. 

Mods - Valhesia 5

**To Reproduce**
1. Open backpack
2. Don't see added slots for inventory. 

**Expected behavior**
To have 81 slots in the backpack. 

**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/13275219/cffe917b-b0a7-4265-9552-bdd6b22b812d)

**Versions**
Mod version: 1.19.2-3.18.53.868
Forge Version: 43.2.21

**Comment by P3pp3rF1y** [comment]
Are you perhaps playing a modpack? Which one is it? And have you checked if the modpack is changing backpack sizes?

**Comment by flibdev** [comment]
This is just how the backpacks are configured in the Valhesia modpack, they're always 27 slots, they just get more upgrades

**Comment by MattRidge** [comment]
> This is just how the backpacks are configured in the Valhesia modpack, they're always 27 slots, they just get more upgrades

The Valhesia 5 mod pack has "All The Mods 8" in it. Based off of this video: https://www.youtube.com/watch?v=7nMSeLqptP4

It shows in ATM8 should allow the 81 slots. A Gold backpack has three upgrade slots. My backpack has three upgrade slots too... so I am unsure exactly what you mean "That is how they are configured"

**Comment by MattRidge** [comment]
> Are you perhaps playing a modpack? Which one is it? And have you checked if the modpack is changing backpack sizes?

Valhesia modpack, which has All The Mods 8 built into it. I don't know if they change it or not, but it seems odd that the size doesn't change but the mod parts do.

**Comment by flibdev** [comment]
Valhesia 5 doesn't have All The Mods 8 in it, they're two completely separate modpacks.

The backpacks not getting bigger was a design choice by the creator of the Valhesia modpack (albeit a stupid one).

**Comment by P3pp3rF1y** [comment]
Closing as this is clearly how backpacks are setup in Valhesia
