### ISSUE TITLE
Upgrade toggle switches incorrectly aligned

### ISSUE THREAD

**Issue by flibdev** [P3pp3rF1y/SophisticatedBackpacks#845]
**Describe the bug**
The toggle switches for backpack upgrades are aligned incorrectly when backpacks are configured to have fewer rows than default.

Initially noticed on the Valhesia 5 modpack, but replicated on a vanilla Forge server with only Sophisticated Backpacks (and Sophisticated Core) installed.

**To Reproduce**
1. Set up Forge server and add Sophisticated Backpacks and Core mods
2. Add a `defaultconfigs/sophisticatedbackpacks-server.toml` config file and change the `inventorySlotCount` for a backpack to something smaller than the default. For the screenshots, I used this configuration:
  ```toml
[server]
	[server.netheriteBackpack]
		inventorySlotCount = 27
		upgradeSlotCount = 7
  ```
3. Open game, add upgrades to altered backpack
4. See toggle switches do not align with their upgrades

**Expected behavior**
The toggle switches should align to their upgrades, but seem to be assuming their container will be higher up.

**Screenshots**
| Unmodified Diamond Backpack | Modified Netherite Backpack |
| --- | --- |
| ![base_diamond](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/6767042/81e6534d-1b29-4893-b4d1-b5f628717e18) | ![edit_netherite](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/6767042/026ff52f-8a00-4e86-8606-c60494c9f486) |

**Versions**
```
Minecraft 1.20.1
forge-1.20.1-47.1.0
sophisticatedcore-1.20.1-0.5.83.395
sophisticatedbackpacks-1.20.1-3.18.56.890
```

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version of sophisticated core where the upgrade part of the gui has been redesigned
