### ISSUE TITLE
Backpack Inventory Wipes When Upgrading Backpack

### ISSUE THREAD

**Issue by sharkweekthings** [P3pp3rF1y/SophisticatedBackpacks#847]
**Describe the bug**
The Backpack seems to wipe itself after each "Bag Upgrade"

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Craft a Leather Backpack
2. Put Items in the backpack
3. Upgrade that backpack to Iron
4. Contents of the bag are deleted
5. Add new items to the Iron bag
6. Update it to Gold
7. Items are again wiped
8. I imagine I can continue this cycle all the way up to the last tier of Backpack. 

**Expected behavior**
the Backapack data should be stored, and not wipe when the bag is upgraded to the next tier

**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/134178249/2edd6898-dfae-4fa3-9fec-9517e9fde9dc)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/134178249/6dd26429-cef2-4e96-8862-8a5ddbef1f2a)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/134178249/cf716052-210c-43d0-97ea-3d775fccd350)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/134178249/7f2285b8-9868-4d62-898e-c279f1fec6c3)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/134178249/0355591a-0d52-46cb-b080-0f199112abc7)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/134178249/2ada99d7-4d33-4502-9839-b8eafcf7b56e)

**Versions**
Forge 1.19.2 / 43.2.21
sophisticatedbackpacks-1.19.2-3.18.55.889
sophisticatedcore-1.19.2-0.5.83.394

Problem present in my Modpack current version 1.14 (unsure about past versions as this is a new issue that came up)
https://www.curseforge.com/minecraft/modpacks/plastek

**Comment by P3pp3rF1y** [comment]
You need to use the correct recipe type when changing the recipes - `"type": "sophisticatedbackpacks:backpack_upgrade"`

**Comment by sharkweekthings** [comment]
Thanks! 

I came back to say that I looked at the recipe in the mod JAR file and saw my mistake. Got everything working appropriately, now. Can close this out!
