### ISSUE TITLE
Crash when using hotbar hotkey on backpack item

### ISSUE THREAD

**Issue by moon-st0ne** [P3pp3rF1y/SophisticatedBackpacks#848]
**Describe the bug**
Game crashes when attempting to hotkey an item out of the backpack to the hotbar using 1-9 keys.

Crash report:
https://mclo.gs/ZGDv3ql

**To Reproduce**
1. Open backpack
2. Press 1-9 to move an item directly to the hotbar
3. Game crashes with index out of bounds of array

**Expected behavior**
Should behave like vanilla

**Versions**
Sophisticated Backpacks: 1.19.2-3.18.55.889
Sophisticated Core: 1.19.2-0.5.83.394

**Comment by P3pp3rF1y** [comment]
smoothswapping is crashing you, please report to them or don't use that mod if you want to use backpacks.
