### ISSUE TITLE
Upgrade Slot Configuration not working or not displaying it

### ISSUE THREAD

**Issue by deBearN** [P3pp3rF1y/SophisticatedBackpacks#850]
**Describe the bug**
After changing the Server Config to allow Netherite Backpacks to hold 10 Upgrades it doesn't work or doesn't update, Restart world, Restart game, /reload, still stays with it's default 7 slots

**To Reproduce**
1. Open mods configuration
2. Click on 'Sophisticated Backpacks' tab
3. Click on 'Config' tab
4. Click on 'Server' tab
5. Click on 'Netherite Backpack' tab
6. Change the Upgrade slot value from 7 to 10
7. Save it and open Netherite Backpack

**Expected behavior**
On my end it keeps the regular 7 slots on the left side same happens if i try to decrease the amount of slots of the backpack to a lower or higher value such as 50 even thought i would understand it was supposed to change

**Screenshots**
[Server configuration for the Netherite Backpack](https://prnt.sc/5f1uH0fopC3F)
[How it looks after Saving and opening the backpack](https://prnt.sc/H3AlKC9g3K_U)

**Versions**
1.19.2-3.18.55.889
Forge  1.19.2-43.2.21

**Comment by P3pp3rF1y** [comment]
Is this with backpack that already existed before the change? Have you tried crafting a new one?

**Comment by deBearN** [comment]
> Is this with backpack that already existed before the change? Have you tried crafting a new one?

Solved... i'm stupid

**Comment by P3pp3rF1y** [comment]
I guess I will close this ticket then :D
