### ISSUE TITLE
Disabling upgrades won't working

### ISSUE THREAD

**Issue by xmateusdf** [P3pp3rF1y/SophisticatedBackpacks#851]
Disabled some upgrades in my server but it still possible to craft everything.

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/125936049/58919b6c-0a1c-4e17-81b0-7bc83acda8b8)
config with disable upgrades

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/125936049/a82c816a-7ad5-4212-92af-48966ed9eb5a)
crafting upgrade, enable on client and disabled on server, appearing on JEI and craftable

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/125936049/619b51a3-ad68-45a4-844a-e1c0f7ff9db4)
feeding upgrade, disabled on server and client, won't appear on JEI but still craftable

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/125936049/78994254-9cc5-436b-aa98-11bf3e1b2950)
both crafted and working normally

Using
Sophisticated Core 1.20.1 - 0.5.83.395
Sophisticated Backpacks 1.20.1 - 3.18.56.890
Forge 47.1.0

**Comment by P3pp3rF1y** [comment]
ahh yeah, I will need to move where this is being enabled/disabled back to common config as apparently server config gets synchronized way too late for it to be used in recipes

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
