### ISSUE TITLE
[1.19.2] Bundles don't show contents in menu

### ISSUE THREAD

**Issue by Darkmega18** [P3pp3rF1y/SophisticatedBackpacks#857]
**Describe the bug**
When in the backpack screen, vanilla bundles contents aren't being displayed. This began occurring with the most recent versions released a few days ago this month.

Does happen in:
sophisticatedbackpacks-1.19.2-3.18.58.907.jar
sophisticatedcore-1.19.2-0.5.87.417.jar

didn't happen in: (the versions prior)
sophisticatedbackpacks-1.19.2-3.18.55.889.jar
sophisticatedcore-1.19.2-0.5.83.394.jar

The bug in a backpack.
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/8104689/f0a26b6a-3b7c-4f3a-a3e8-4e302bd4853d)

not having the bug in a cyclic crate for example. or anywhere else I could check offhand.
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/8104689/d54caa5f-92e8-40cd-ba8e-c0eb220d4721)

**To Reproduce**

Put stuff in a vanilla bundle. Quark enables them, corail tombstones has them as rare drops.
Open backpack and try to view it's content. Their sprites don't render properly. But the numbers remain. but thats not overly helpful.

**Expected behavior**
Can see sprites, like in the previous versions like so:
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/8104689/f810ceb5-b6d2-4615-9c5f-961935a97376)

**Screenshots**
In the above areas. :V

**Versions**
Eh. in the above areas. :V

**Comment by CubeTwo** [comment]
https://github.com/P3pp3rF1y/SophisticatedCore/issues/164

**Comment by Darkmega18** [comment]
ah. similar issue. thanks. I just searched bundle and left it at that. always forget shulkers... I've never had the need or care to use one with all the possible portable storage mods like this one around. :V

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge

**Comment by Darkmega18** [comment]
Thanks! :)

**Comment by Twisted-Code** [comment]
Thanks everyone, I was just about to report this while playing ATM8!
