### ISSUE TITLE
When using the Advanced Refill Upgrade, the item disappears

### ISSUE THREAD

**Issue by frxndo** [P3pp3rF1y/SophisticatedBackpacks#860]
When using the version "sophisticatedbackpacks-1.19.2-3.18.55.889.jar" when I put the advanced refill upgrade and select some totens, when I am playing those totens at the backpack. They disappear! I've neven seen them again after that XD
![Screenshot_1379](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/145397256/ae6962b5-cc6c-484b-924c-b2f7b106c0d1)

**Comment by P3pp3rF1y** [comment]
The upgrade works correctly for me so my guess is that it's related specifically to the items from the mod you're using there. What's the name of that mod? I can try to retest with it and see what's going on there.

**Comment by P3pp3rF1y** [comment]
Closing given no response
