### ISSUE TITLE
minecraft crash when opening backpack

### ISSUE THREAD

**Issue by Cinim159** [P3pp3rF1y/SophisticatedBackpacks#862]
Good afternoon, I'm having a problem with the mod Sophisticated Backpacks, every time I try to open the backpack the game crashes and an error appears, when the backpack is empty an error appears that I forgot to take a screenshot of, I just wrote down what appeared that is **(Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(5) + length(4) exceeds writer Index(5) PooledUnsafeDirectByteBuf(ridx: 5, widx: 5, cap: 5) )**, when there is an item inside, the error appears in the attached image, I wanted to know if anyone could help me, I have several other MODs together, I will leave a print of all of them too.

![xHexdGh](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/146406089/fa0d4f6a-6b9d-484a-a2d8-a3ca482b5184)
![5PjaiO2](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/146406089/eaeb94e2-703e-4cf2-b738-0bc8a2778522)

**Comment by P3pp3rF1y** [comment]
Could you share the full crash report as attachment or through pastebin.com?

**Comment by Cinim159** [comment]
I managed to find the problem, it was Sophisticated Core, an add-on for Backpacks, which was outdated and I hadn't seen it, I updated it to the latest version and now it's working perfectly, thanks for your attention
