### ISSUE TITLE
Open backpack hotkey modifiers being ignored

### ISSUE THREAD

**Issue by NekoSpirits** [P3pp3rF1y/SophisticatedBackpacks#866]
**Describe the bug**
Hotkey modifiers (alt, shift), are ignored by the open backpack setting. For example, if the control is saved as "SHIFT + e", both "e" and "SHIFT + e" will open the backpack.

**To Reproduce**
1. Open controls
2. Change control to include modifier
3. Test control

**Expected behavior**
Backpack should only open when correct control is pressed.
**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/20034469/c3ff9f8e-4eb8-4c49-8524-c75747d2a3eb)

**Versions**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/20034469/b2dfc4ee-7743-4743-a657-f6dc144d3c9b)

**Comment by P3pp3rF1y** [comment]
This just plain works correctly for me (when I set open backpack as SHIFT + e I have to press shift otherwise the backpack won't open) and checking in code proper call is being made which includes mandatory check for modifier key (shift/alt/ctrl). So my guess is that you have a mod included in the modpack that breaks this behavior.  You will need to find out which one that is and report to them that they are breaking this behavior.

**Comment by NekoSpirits** [comment]
I think I caused some confusion with my original post. As stated in my previous comment, I am only using the backpack mod. Attached below is a video, with keyboard presses shown to better explain.

https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/20034469/ecd107b7-b66f-4ec0-952a-ab21fffeebd3

**Comment by P3pp3rF1y** [comment]
So I couldn't recreate, but once I updated forge to your version now I can. It appears to be bug in for for which neoforge has an open fix https://github.com/neoforged/NeoForge/pull/171. Anyway it appears that if you don't have conflicting keybinds (that is in your case not have anything else bound to E in any kind of combination with modifier key which I am guessing will be difficult) the modifiers will work correctly. If you want them to work correctly without resolving these conflicts you will need to downgrade to one of the earlier versions of forge
