### ISSUE TITLE
Backpack disappears when sorting inventory in curios tab

### ISSUE THREAD

**Issue by Lockhart3195GC** [P3pp3rF1y/SophisticatedBackpacks#869]
I had my backpack in the back slot of my curios tab and accidentally hit my middle mouse button (sort inventory) and the backpack disappeared. nowhere to be found. not on the ground, not in my inventory, not in the trash can. no idea what to do to get it back. currently using Direwolf20's mod pack

**Comment by P3pp3rF1y** [comment]
Sounds like sorting mod sorted curios inventory and deleted the backpack. You will need to report that issue to the modpack's maker as there's nothing I can do about that one

**Comment by P3pp3rF1y** [comment]
Though looking at the rest of your message you can spawn in backpack you had using /sbp list and /sbp give commands
