### ISSUE TITLE
Crash when killed wearing the backpack

### ISSUE THREAD

**Issue by NuclearKiwi** [P3pp3rF1y/SophisticatedBackpacks#871]
When dying while using or having items in the backpack the game instantly crashes, I can't seem to figure out why this is.

Crash log is attached as file

To Reproduce
1. Open backpack
2. Put any item in backpack
3. Die in any way
4. Crash / See Error

**Versions**
Using Mod version 1.20.1 FORGE with Forge-47.2.0

_
[crash-2023-10-17_19.53.05-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/12937808/crash-2023-10-17_19.53.05-server.txt)

**Comment by P3pp3rF1y** [comment]
that's a DeathChestMod crash can't help you with that so you will need to report this issue to that mod.
