### ISSUE TITLE
Tank upgrade not showing and not working

### ISSUE THREAD

**Issue by CDucatti** [P3pp3rF1y/SophisticatedBackpacks#872]
None of the tank upgrades are showing on my backpack. I put it on the slot of upgrades but there are no slots on the backpack being "consumed"/disappearing to give space for the tank. It just opens a tab on the right 

**To Reproduce**
1. Open backpack
2. Put the upgrade
3. Nothing changes at the backpack

**Expected behavior**
Tank showing up and taking up space in the backpack

**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/148473262/84aa1e6e-9219-4eb2-b7f4-443ea73d0b82)

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/148473262/21f9d8b9-50a3-435a-8c6b-3087abda0597)

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/148473262/034b0d93-f61e-46d5-a2ce-e24e281d8de0)

(The screenshots are from a creative world I created just to test stuff, but the problem happens regardless of the world. 

**Versions**
From the screenshots the version is 1.19.2 but I also had problem in another modpack where the version was 1.18.2

**Comment by P3pp3rF1y** [comment]
From the screenshots I can only see you putting in pump upgrades, no tank upgrade. Have you actually tried using tank upgrade?

**Comment by CDucatti** [comment]
> From the screenshots I can only see you putting in pump upgrades, no tank upgrade. Have you actually tried using tank upgrade?

I'm an idiot 🤦‍♀️. Thanks,  that was it. I'm so embarrassed...
