### ISSUE TITLE
Backpack bind not working

### ISSUE THREAD

**Issue by FarFar501** [P3pp3rF1y/SophisticatedBackpacks#873]
So by the mod's description and the controls, i should be able to open the backpack by just clicking the default bind B. 

So far tried to do it in just having the backpack in my inventory, chestplate slot, backpack slot, but it dosent work on any slots, 

is the open by bind broken or its an upgrade or something?

**Comment by FarFar501** [comment]
Got it fixed.
I rebinded it to something that dosent have any binds on it yet, so no overlapping binds or so, fixed the problem

**Comment by P3pp3rF1y** [comment]
that would be an issue for any keybind - if you have conflicts then it really matters which one is going to react to the press first and the others will very likely just not do anything
