### ISSUE TITLE
Game crashes upon pressing "e' to open my inventory

### ISSUE THREAD

**Issue by wonkers27** [P3pp3rF1y/SophisticatedBackpacks#877]
**Describe the bug**
I'm playing on a personal modpack and whenever I attempt to open my inventory the game freezes and crashes. I'm fairly certain this a problem with Sophisticated backpacks as there don't seem to be any other mods that should be incompatible with it. 
Here's the crash log: 
[crash-2023-10-20_15.30.14-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13058835/crash-2023-10-20_15.30.14-client.txt)

**To Reproduce**

1. Open game
2. load world
3. press e
4. crash

**Expected behavior**
My inventory should open as usual

**Versions**
Sophisticated Backpacks version 3.18.59.909
Forge version 47.2.0
Minecraft 1.20.1

**Comment by P3pp3rF1y** [comment]
You need to update sophisticated backpacks to latest version given that you have updated sophisticated core
