### ISSUE TITLE
1.16.5 Void upgrade

### ISSUE THREAD

**Issue by 2929762171** [P3pp3rF1y/SophisticatedBackpacks#878]
What is the meaning of this?
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/98941945/6de2fdaa-f02c-4bab-bbae-5b84ac16cf99)
If I set to 'Only works with other upgrades/automation' + 'Void Any' + 'Block' mode, then I won't be able to get anything except dirt. 
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/98941945/d56fafc6-3912-47e3-b7cd-c8abb3b8332e)

Why the void upgrade can pick up items in **Void OverFolw** mode without pickup upgrade?
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/98941945/7fe6fce5-d541-4463-82ca-d7b851176984)

Does this mean that the void upgrade includes the function of forcibly picking up items to the backpack?
I think the problem stems from 'Only works with other upgrades/automation', this setting did not achieve the expected effect.

sophisticatedbackpacks-1.16.5-3.15.20.755
forge 36.2.39

**Comment by P3pp3rF1y** [comment]
that setting only says that it will work with other upgrades vs working with those + in the gui as well when you toggle it. And in 1.16.5 void upgrade also picks up items yes, that is changed in 1.18 + where you need pickup to go with it, but that's definitely one of the changes I am not going to backport into version I don't support for more than a year now
