### ISSUE TITLE
Refill Upgrade deletes items when backpack is "full"

### ISSUE THREAD

**Issue by coolepicgaymer** [P3pp3rF1y/SophisticatedBackpacks#879]
**Describe the bug**
When all slots in the backpack are occupied and you have at least two slots in the backpack with the middle-clicked item, the item in your hand disappears completely if the first instance of the middle-clicked item in the backpack has more than a stack and there is at least one other instance of the item in the backpack containing less than a stack.

**To Reproduce**
1. Get a backpack with a refill upgrade and a stack upgrade.
2. Occupy all backpack slots with items.
3. In at least two of the backpack slots, put a middle-clickable block (e.g. Grass Blocks). The first of these must be more than a stack. The second slot must be less than or equal to a stack. Example below.
4. Middle-click the item from step 3 while holding an item not already in the backpack.

**Expected behavior**
Item should either not refill or move the held item to player inventory.

**Screenshots**
Example of backpack:
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/67607635/392f0f49-3f42-4c80-86a9-6085353a7988)

https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/67607635/52c5c6c0-5f15-4c16-91e7-f246e15cfa8a

**Versions**
Forge 40.2.9
Sophisticated Core 1.18.2-0.5.98.458
Sophisticated Backpacks 1.18.2-3.18.65.933

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release
