### ISSUE TITLE
crafting upgrade in backpack dont work (recipes)

### ISSUE THREAD

**Issue by SOLORFA** [P3pp3rF1y/SophisticatedBackpacks#880]
Hello! 

I'm having problems with the recipes because I can't craft them using the upgrade in my backpack.

Can anyone help me fix this?
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/148632832/5ebb9f65-0551-4a49-92a5-da0329b4ce65)

**Comment by P3pp3rF1y** [comment]
Have you got backpack open before opening this screen? And that's not JEI right? which mod are you using for the recipes

**Comment by SOLORFA** [comment]
> Have you got backpack open before opening this screen? And that's not JEI right? which mod are you using for the recipes

You are right... thats REI, not JEI.... I already fix it. i am so dumb :(

**Comment by P3pp3rF1y** [comment]
glad you fixed it
