### ISSUE TITLE
Entangled Backpacks visual bug+ Dupplication/erasure bug

### ISSUE THREAD

**Issue by Pillow51** [P3pp3rF1y/SophisticatedBackpacks#881]
**Describe the bug**
Inside my Main backpack with inception upgrade, 2 of my sub backpacks seem to be linked. Most of the time it is a visual bug in the  UI, but sometimes one of the back pack's contents will get erased to get filled with a duplicate inventory of the other one.

On Modpack "Chosen's Modded Adventure" v0.3.3 (with Alex's Caves Mod manually added) 

**To Reproduce**
VISUAL BUG:
Unclear why the bug happens in the first place. But once it happens ;
1. Open backpack
2. Shift hover on Backpack#1 (B1)
3. Shift hover on Backpack#2 (B2)and notice the inventories are shown to be the same(when in reality they have different content)
4. Opening the backpacks works normally
5. modifying the content of the backpack which inventory isnt showing correctly with the shift hover will change the entaglement
6. Now the visual bug has swapped and will show the inventory of the modified backpack for both of them

DUPPLICATION BUG:
1.When B2 has the visual bug and shows with shift hover that it's content is B1's content.
2.Move the backpack inside your UI to another inventory slot
4. Now it's content transformed into B1's

**Expected behavior**
You will have a backpack with the content of another. But the back pack itself doesnt change (color/name)

**Screenshots**
![B1hover1](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/148654492/e3edf4c0-e72d-4784-a68b-b1438bf9842d)
Hovering backpack 1

![B1content1](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/148654492/c5408b16-a354-4db0-8cd7-667405d8a8be)
Content of Backpack 1

![B2hover1](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/148654492/c2a5ac3d-fae0-41ae-ade3-a4c9ec20f5c4)
Hovering backpack 2

![B2content1](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/148654492/30c4a7c0-b5a3-4cc2-b6f5-848baf6a93c3)
Content of Backpack 2

After dupplication bug, B2's content get's transformed into B1's and it's content is now : 
![B2content2](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/148654492/661a9e65-0e4a-4132-af91-2e4f8a9d3bba)

**Versions**
with sophisticatedbackpacks-1.20.1-3.18.59.909
on forge 47.1.3

**Comment by P3pp3rF1y** [comment]
could you turn on advanced tooltips and check UUID of the two backpacks, looks like it is going to be the same

**Comment by Pillow51** [comment]
Yep they are the same

**Comment by P3pp3rF1y** [comment]
well, not sure how you got those but that's your issue. The only legit way I know of is through Apotheosis loot pinata, other than that these can only be duplicated in creative or potentially if someone is giving these out in quests or some chests with UUID already included. But there's also deduplication logic included so you must have put the first one in the backpack before getting second one in your inventory otherwise it would dedupe. Anyway to fix this you need to put both in your inventory and one of them will reset its uuid and they will no longer have this issue

**Comment by Pillow51** [comment]
Thank you !
