### ISSUE TITLE
Create contraptions inventory delete issue (EDIT)

### ISSUE THREAD

**Issue by Pyrotheus** [P3pp3rF1y/SophisticatedBackpacks#885]
Started using a diamond backpack in place of chests to store items from my crop harvester. (CREATE MOD)  Items are deleted in two ways. However I was able to reproduce both issues.

**To Reproduce**

**Steps to reproduce the behavior: VERSION 1**
1. place backpack onto incomplete contraption [inventory unharmed]
2. form contraption via cart assembler [inventory unharmed]
3. let contraption complete its task and deform back into only blocks (incomplete contraption) [inventory unharmed]
4. destroy and pick backpack up [inventory is deleted]

**Steps to reproduce the behavior: VERSION 2**
1. place backpack on contraption
2. make contraption via cart assembler
3. unmake contraption via cart assembler (back to individual blocks)
4. leave the server and rejoin (make the server unload the chunks)
5. rejoin and backpack is empty (still placed down)

Create mods way of making contraptions may in some way duplicate UUID and only becomes prevalent when the item is reloaded in some way. Duplicate UUID is momentary and never gets reassigned.

**Screenshots**

![2023-10-23_13 33 05](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/51934376/c4fe8cd9-faed-415a-902a-c68f6ad5926d)
![2023-10-23_13 33 29](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/51934376/95840c5d-ac62-4d6b-965a-432c30f7db56)

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
CREATE 0.6.1.e
SOPHISTICATED CORE 0.5.89.425
FORGE 47.2.1

**Comment by Pyrotheus** [comment]
Incase other mods are relavent this is the whole modpack
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/51934376/44f31402-e11c-44cf-bcfc-25a3dec08237)

**Comment by Pyrotheus** [comment]
Looked into other issues about data synchronization and I am unable to retrieve items by clicking their slots, items are deleted.

**Comment by P3pp3rF1y** [comment]
Sure, but there's nothing I can fix here. 
It's the create logic that is making these changes and I am not going to change their code through mixins as that would be extremely fragile and could also create issues that would be reported to them when my code was the real culprit. 
The real fix for this needs to be done on Create side or backpacks need to be blacklisted from being used on contraptions which again is something for create if there isn't a config already. So you will need to report to them if you want this fixed.

**Comment by Pyrotheus** [comment]
ooo okay makes sense. Yeah probably too much trouble to make the two mods talk nice. Thanks for the quick response!
