### ISSUE TITLE
Item Copying

### ISSUE THREAD

**Issue by zecheki** [P3pp3rF1y/SophisticatedBackpacks#886]
When you use pickup upgrade, if you acquire a large amount of items, the items are replicated.

**To Reproduce**
1. Equip the backpack and pickup upgrade
2. Drop 1024 redstone and pickup
3. See a lot of redstone

**Expected behavior**
Only 1024 redstone

**Screenshots**
https://drive.google.com/file/d/1fNEUHG1GhHTnnyYBbglq9rWPKZz-j-2Y/view?usp=sharing

**Versions**
Minecraft 1.20.1
Forge 47.2.1
sophisticatedbackpacks-1.20.1-3.18.65.935

**Comment by zecheki** [comment]
I found a clearer condition.
It occurs when used with the staaaaaaaaaaaaaack mode.

**Comment by P3pp3rF1y** [comment]
Is that some kind of mod that chnages max stack size of stacks that can exist in the world? I can't find anything on that. Anyway if a mod changes max stack size of item entities you want to report to them first as its very likely they are not handling that correctly. In this case very likely incorrectly triggering/handling player pickup event

**Comment by P3pp3rF1y** [comment]
I am closing this but feel free to reopen in case they have a clear indication my mod is at fault
