### ISSUE TITLE
Ticking entity crash Single player

### ISSUE THREAD

**Issue by debitfett** [P3pp3rF1y/SophisticatedBackpacks#887]
**Describe the bug**
Mod appears to be causing a ticking entity crash that has hard locked my save.
https://pastebin.com/6snTqfuB

**To Reproduce**
crash on world load
**Expected behavior**
not crash on world loaD

**Screenshots**

**Versions**
ATM 7 0.4.22
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/70710645/3ae8ff75-7eea-4ead-a637-1969df16f76e)

**Comment by P3pp3rF1y** [comment]
You're playing with pack update that's way more than year old, please update and feel free to report here if you see any issue with SB after update
