### ISSUE TITLE
Misspelling in pl_pl.json

### ISSUE THREAD

**Issue by Polarni** [P3pp3rF1y/SophisticatedBackpacks#890]
https://github.com/P3pp3rF1y/SophisticatedBackpacks/blob/d4d6eafcc24ed41419cf3c417dd81e0dae33f657/src/main/resources/assets/sophisticatedbackpacks/lang/pl_pl.json#L93C1-L93C69

Instead of "Otwórz plecam" it should be "Otwórz plecak". "Plecam" doesn't mean anything. "Otwórz plecak" mean open backpack.

**Comment by P3pp3rF1y** [comment]
This apparently was reported twice. have this fixed in 1.21 dev so it will be correct from there on.
