### ISSUE TITLE
Incompatibility with the Oculus mod - crash client

### ISSUE THREAD

**Issue by Malganis1** [P3pp3rF1y/SophisticatedBackpacks#891]
**Describe the bug**
Hello! I apologize in advance for my English, I use a translator.

When loading the client it crashes. Using the calculation method, I determined that this was due to the mod “**oculus-mc1.20.1-1.6.9**” (an unofficial fork of Iris for the Forge). There may be a rendering error, but with another backpack mod everything works fine (**TravelersBackpack-1.20.1-9.1.7**).

I'm putting together my own build to complete it and I like your backpack mod the most. I don’t want to start the walkthrough without this mod and I ask you to write me an answer as soon as possible!
[crash-2023-11-04_11.12.36-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13256142/crash-2023-11-04_11.12.36-client.txt)

**Expected behavior**
Solve the crash problem as soon as possible! Please!

**Versions**
Java Minecraft 1.20.1 Forge

**Comment by P3pp3rF1y** [comment]
Why would you think this is related to sophisticated backpacks? I don't see anywhere in that crash log that SB is mentioned. Given that it happens when Oculus config is being loaded it seems much rather like some error with some config library or something similar to that.

**Comment by P3pp3rF1y** [comment]
looks like this error is shown under some circumstances when dependency is missing. Have you got sophisticated core in your pack?

**Comment by Malganis1** [comment]
> Why would you think this is related to sophisticated backpacks? I don't see anywhere in that crash log that SB is mentioned. Given that it happens when Oculus config is being loaded it seems much rather like some error with some config library or something similar to that.

When I delete your mod the client stops crashing. 

Here is a list of all mods in the pack:
![UxK2xSB](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/113822934/54b5b133-612a-4c08-9a3b-3198ed7c0766)

**Comment by P3pp3rF1y** [comment]
Scanning this quickly I don't see sophisticated core there

**Comment by Malganis1** [comment]
Thank you very much, I downloaded Sophisticated Core and the crash problem went away!

I also want to thank you for your quick help, it is very important to me!

But I would like to ask you to write on **CourseForge** information that **Sophisticated Backpacks** require **Sophisticated Core**. Best wishes!

**Comment by P3pp3rF1y** [comment]
The dependency is there on cf, launchers will automatically add it. 
And a missing dependency is automatically shown by forge on startup but in this case some mod is preventing that from happening. Anyway closing as this was just missing dep.
