### ISSUE TITLE
Using shortcut to insert battery upgrade causes client crash

### ISSUE THREAD

**Issue by AweiMC** [P3pp3rF1y/SophisticatedBackpacks#894]
**Describe the bug**
Using shortcut to insert battery upgrade causes client crash.

**To Reproduce**
BUG-1:
1.Open the GUI of the Netherite Backpack.
2.Insert 6 Stack Upgrade Tier 4 items.
3.Use the Shift shortcut to place the Battery Upgrade into the Netherite Backpack.
4.Client crashes.

BUG-2:
1.Open the GUI of the Netherite Backpack.
2.Use the Shift shortcut to place the Battery Upgrade into the Netherite Backpack. Although it doesn't crash instantly, it occupies an 3.inventory slot unnecessarily.
4.Repeated clicking leads to client crashes.

Note: These issues cause the backpack to remain inaccessible even after restarting and result in further crashes.

crash-reports : https://mclo.gs/6jjtGLb
latest : https://mclo.gs/3qlNa2V

**Expected behavior**
BUG-1:
When I place 6 Stack Upgrade Tier 4 items into the Netherite Backpack and then use the shortcut Shift + left-click to insert the Battery Upgrade, it leads to a client crash.

BUG-2
I expect that inserting the Battery Upgrade into the Netherite Backpack should display the Battery GUI, but it doesn't. Instead, it occupies extra space on the interface.

**Screenshots**
BUG-1
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/122848147/003a2691-c99e-4cb1-b1c3-29eaa4c00909)

BUG-2
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/122848147/e294120e-1620-4cec-8188-a7df8c9e1508)

**Versions**
1.20.1-Forge_47.2.4
sophisticatedbackpacks-1.20.1-3.18.65.935
sophisticatedcore-1.20.1-0.5.100.457

**Comment by P3pp3rF1y** [comment]
Just a small clarification - seems to happen only with shift clicking stack of more than 1 so under normal circumstances where people usually craft single battery upgrade it's not going to happe, but yes it is something that shouldn't crash either way so I am going to fix for one of the next releases.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF
