### ISSUE TITLE
Crash upon opening any Sophisticated storage option

### ISSUE THREAD

**Issue by CloWnicide** [P3pp3rF1y/SophisticatedBackpacks#895]
**Describe the bug**
Trying to open any backpack/chest/barrel is causing an Internal Execption.

**To Reproduce**
1. Open backpack/chest/barrel
2. See error

**Expected behavior**
No crash

**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/27911500/f04b364a-04f1-46d6-8a41-9c45afd76e89)

**Versions**
Forge 47.1.3
Sophisticated Backpacks 1.20.1-3.18.65.935
Sophisticated Storage 1.20.1-0.8.55.626
Sophisticated Core 1.20.1-0.5.89.425

**Comment by CloWnicide** [comment]
Log
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13292710/latest.log)

**Comment by CloWnicide** [comment]
I found the issue. While having SophCore storages attached to a Create contraction while inside your inventory will cause this specific issue. Putting the contraption down and/or removing any upgraded barrels or crates from the contraption will stop the issue.

**Comment by P3pp3rF1y** [comment]
I don't see any error related to sophisticated anything in that log, do you have crash log or any other log that shows some error? or is this just silently not working?

**Comment by CloWnicide** [comment]
There is no crash, this error just happens, takes me to the above screenshot, and then to the multiplayer menu, even though this is a sp world.

**Comment by P3pp3rF1y** [comment]
ahh sorry, I haven't read this correctly before I see what's going on - create has way too much data on the item for a basic vanilla gui sync logic to work. They likely modify the base vanilla logic to work in vanilla screens, but that doesn't help with sophisticated ones and I have seen this one a few times before so I am going to add a way to sync much more data to client for items like that.

**Comment by P3pp3rF1y** [comment]
the limit on packets is gone in 1.21 Neoforge so this won't happen from there on and I am closing this issue.
