### ISSUE TITLE
Crashing from limited upgrade shift clicking

### ISSUE THREAD

**Issue by Fnige** [P3pp3rF1y/SophisticatedBackpacks#896]
**Describe the bug**
When shift clicking in upgrades, (Where said upgrade has an upgrade limit less than whats in the backpack and it isnt at max upgrades yet) will crash the game

Crash log if it's a crash.
https://gist.github.com/Fnige/4d470660d19fe93f2f129e39ef423898

**To Reproduce**
1. Grab all the items you need. For this example, I got a netherite backpack and a stack of tank upgrades
2. Open up the backpack
3. Shift-click the tank upgrades into the backpack

**Expected behavior**
The tank upgrades shouldve maxed out and either put the rest in the backpack or leave it within the player's inventory

**Screenshots**
N/A

**Versions**
Minecraft: 1.20.1
Forge: 47.2.4
Embeddium: 0.2.7
Sophisticated Backpacks: 3.18.65.935
Sophisticated Core: 0.5.100.457

**Comment by P3pp3rF1y** [comment]
Fixed in the latest version on CF
