### ISSUE TITLE
Tool Swapper Upgrade doesn't swap tools [1.20.1]

### ISSUE THREAD

**Issue by Conga0** [P3pp3rF1y/SophisticatedBackpacks#897]
**Describe the bug**
When creating a Tool Swapper upgrade and placing it into my backpack upgrade slot, pickaxes from my backpack, inventory and toolbar aren't automatically swapped into my hand when I go to punch stone.

**To Reproduce**
1. Open backpack
2. Insert Tool Swapper Upgrade
3. Fill inventory & backpack with pick axes
4. Go to punch stone
5. Tool will not be swapped into hand

**Screenshots**
https://cdn.discordapp.com/attachments/263822906528628736/1172080351041028137/2023-11-09_17.18.18.png
https://cdn.discordapp.com/attachments/263822906528628736/1172080351515000852/2023-11-09_17.18.27.png

**Versions**
Minecraft version: 1.20.1
Mod Version: 3.18.65.935
Forge version: 47.1.3

**Comment by P3pp3rF1y** [comment]
you need to have a weapon or another tool in hand. It's supposed to swap tool that you have in hand that is not good at breaking the block you're trying to mine with one that is good at mining that block.

**Comment by Conga0** [comment]
I see, perhaps it could be changed to work with an empty hand then?
If I already have my tools on my hotbar to hold them, I don't see much value in having them be swapped into my hand after the fact.

My main goal was to use the swapper tool upgrade to afk mine cobblestone; having it automatically swap a new pickaxe into my hand when the last one breaks.

If not, maybe the description could be changed to be more accurate to it's behaviour, perhaps something like:
"When holding a tool, automatically swap the tool for the most effective one for the block/entity being left clicked on; Does not work on empty hands"

**Comment by RarePlutonian** [comment]
It only works if you have a tool in hand then something it can swap with in your backpack, don't think you can use an empty hand or non tool, that should solve your problem

**Comment by sardharavineet** [comment]
i applied advanced tool upgrade to my backpack and then with a sword in hand, tried to break cobblestone. It did not swap to the pickaxe that i had put in my backpack
