### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by O1Assassin** [P3pp3rF1y/SophisticatedBackpacks#90]
Me and my friend found a glitch to duplicate items into stacks.

1. Open backpack
2. Place a stackable item such as redstone into the blackpack
3. Place one of the same item into your inventory
4. Shift click the item from the backpack into your inventory
5. The item duplicates into a stack

Screenshots
![2021-03-18_16 05 09](https://user-images.githubusercontent.com/80910678/111658003-dc770880-8803-11eb-8053-16f00a868304.png)
![2021-03-18_16 05 15](https://user-images.githubusercontent.com/80910678/111657999-dbde7200-8803-11eb-98d2-fa5d309de6f3.png)

My Mods
![Screenshot 2021-03-18 160657](https://user-images.githubusercontent.com/80910678/111658156-fdd7f480-8803-11eb-9f89-ee99bdae5613.png)

Version
1.16.4-2.2.6.205

**Comment by P3pp3rF1y** [comment]
Yes that version had this issue. I fixed it in a version released two days ago. Just download latest version and you are set. Btw your version of the mod is hidden on cf exactly for this reason.
