### ISSUE TITLE
Wasn't there advanced refill upgrade?

### ISSUE THREAD

**Issue by vatum20** [P3pp3rF1y/SophisticatedBackpacks#903]
I remember that there was advanced refill upgrade, but now it's gone. What happened and is it coming back?
My version: sophisticatedbackpacks-1.16.5-3.15.20.755.jar

**Comment by P3pp3rF1y** [comment]
there's no advanced refill in 1.16.5, that version is long not supported and the advanced version is only available in 1.18+
