### ISSUE TITLE
[1.19.2] Tool Swapper Stops Working After Using Tetra Hammer

### ISSUE THREAD

**Issue by ChucklesMcFuckles** [P3pp3rF1y/SophisticatedBackpacks#904]
**Describe the bug**
I am able to swap freely between Tetra's modified tools in my backpack using the tool swapping upgrade, however after I use Tetra's hammer on anything, both to break and/or to do right-click functionality, the tool swapper no longer works. Even if I put the hammer in the backpack, or put the hammer away in a different storage.

**To Reproduce**
1. Open backpack
2. Place Tetra tools inside bag
3. Use advanced tool swapper upgrade
4. Use Tetra hammer for anything
5. Tool swapper stops working

**Expected behavior**
Tool swapper will swap the tools after using the hammer

**Screenshots**
N/A

**Versions**
forge 43.3.5
tetra-1.19.2-5.5.1
sophisticatedbackpacks-1.19.2-3.18.63.934
shopisticatedcore-1.19.2-0.5.98.459

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
