### ISSUE TITLE
Can't auto feed item with durability

### ISSUE THREAD

**Issue by AlexTheFixer** [P3pp3rF1y/SophisticatedBackpacks#905]
I am currently playing a pack that shares the mod create confectionary and this one. Within create confectionary there is a item called the full chocolate bar which when eaten lowers the durability. However for whatever reason I cannot use this on the auto feeder upgrade. I am not sure whether or not this is a bug or a feature request.

Thank you for your time.

**Comment by P3pp3rF1y** [comment]
I have never responded to this one, but any item that properly implements food attributes can be fed to player. So the chocolate bar in this case isn't food at least in terms of the code and has some custom implementation. Adding compat for that would be pretty niche thing and the mod is closed source so I am not interested in doing that and going to close.
