### ISSUE TITLE
Game crashes and won't load in due to water bucket being placed in tank upgrade slot

### ISSUE THREAD

**Issue by MedalMarkk** [P3pp3rF1y/SophisticatedBackpacks#906]
My game keeps on crashing whenever I use the tank upgrade. It happens when I have the tank upgrade on a backpack and if I put a water bucket inside the slot to put in liquids it just crashes and now I can't join my world. I made a new world to test if it crashes there and it does. I really don't want to lose my world I spent quite a while on it. this is the crash report I always get after it crashes.
[crash-2023-11-13_23.31.43-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/13377721/crash-2023-11-13_23.31.43-client.txt)

I play on Curse Forge 1.19.2 and I have  around 15 mods I don't think the problem is with the other mods but than again I'm not entirely sure.

**Comment by MedalMarkk** [comment]
Oh also  I forgot to mention in order to recreate this is this:
1. place tank upgrade in backpack.
2. put water bucket in slot for liquid.
3. crash instantly occurs.
4. try reloading world and crash again on reloading.
5. have a crisis due to the many hours you spent on that world.

**Comment by P3pp3rF1y** [comment]
This is optifine crash, they should have already fixed that so make sure you are using the latest optifine. If that doesn't help removing optifine will fix it, there's no way I can fix that on my side as Optifine is in this case removing functionality with no regard for mods using it.

**Comment by MedalMarkk** [comment]
Ok thank you so much.
