### ISSUE TITLE
Defining the energy source for the auto smelting upgrade 

### ISSUE THREAD

**Issue by Bexy-Lyn** [P3pp3rF1y/SophisticatedBackpacks#911]
Hi, 
I just crafted the auto smelting upgrade for the first time and had the issue, that I am not able to select which blocks to use as fuel. By default the smelter pulls every item that can be used as fuel, which is unfortunate, if I have scaffolding, fishing rods, planks, etc. in my backpack. I would expect that I can select more appropriate fuels like coal, blaze rods and lava buckets, similar to the other filters. 
That would be awesome :) Thank you. This is a great mod overall!

**Comment by P3pp3rF1y** [comment]
the 4 filter slots at the bottom are there for selecting what fuel is supposed to be used.
