### ISSUE TITLE
I can't remove dyeing recipe of backpacks

### ISSUE THREAD

**Issue by Exzept1on** [P3pp3rF1y/SophisticatedBackpacks#914]
**Describe the bug**
Using KubeJS, I can't delete the backpack coloring recipe. I can't do it not by output, not by type, absolutely not.

**To Reproduce**
1. Install KJS, Backpacks
2. Try to remove dyeing recipe
3. Nothing!

**Expected behavior**
The recipe should have been deleted.

**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/52341158/6a49b3f8-670c-43d3-8168-69e9bdb84de4)

**Versions**
1.20.1, Forge 47.2.6
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/52341158/ee10e446-6147-4161-9847-8705b47639da)

**Comment by P3pp3rF1y** [comment]
I was pretty sure I added a question here but somehow I can't see it so here we go:

Could you explain to me the reason you would want dye recipes to not exist? I mean with pretty much any other recipe I understand that there may be reasons to not allow crafting something but in this case you seem to want to just remove an option to give backpack a bit of additional style / differentiation and I don't get why / how that could be beneficial to a pack.

**Comment by Exzept1on** [comment]
I didn't want to delete them, I just tried to do it and found that it was impossible. Perhaps in some situation someone, like me, would like to change the recipes for painting backpacks in such a way that they can only be painted in some kind of mechanism or something, without using a workbench.

**Comment by P3pp3rF1y** [comment]
Changing color of backpacks is non trivial. I was wondering about potentially supporting removal / change of the recipe, but given how complex it could turn into and at the same time not having anyone who actually needs it I am going to just close until I hear about anyone who would have a use for custom recipe.
