### ISSUE TITLE
[1.16.5] Crash with Crafting Tweaks Recipe Refill 

### ISSUE THREAD

**Issue by NielsPilgaard** [P3pp3rF1y/SophisticatedBackpacks#92]
**Describe the bug**
> I was crafting with a diamond sophisticated backpack, had the majority of crafting ingredients inside the backpack and the last ingredient (lava bucket) was inside my personal inventory, I pressed tab to refill the crafting recipe and my game proceeded to freeze for about a minute, save progress and crash.

**To Reproduce**
1. Open backpack that has Crafting Upgrade
2. Insert 8 planks for a chest in the grid
3. Have more planks in your inventory
4. Press tab to refill with the mod Crafting Tweaks
5. Crash

**Expected behavior**
No crash

**Versions**
- Forge-1.16.5-36.0.46
- CraftingTweaks_1.16.3-12.2.0
- sophisticatedbackpacks-1.16.4-2.2.7.213

**Comment by P3pp3rF1y** [comment]
I have a "fix" for this but it involves disabling refill altogether as there isn't a way I can provide a real fix on my side without a change on CT side that would allow me to implement compatibility for refill similar to how it allows implementing compatibility for all the other actions.

**Comment by NielsPilgaard** [comment]
That works for me, thanks!

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
