### ISSUE TITLE
Backpack Inception Upgrade not working with with crafting using the subbackpacks

### ISSUE THREAD

**Issue by ImJBe** [P3pp3rF1y/SophisticatedBackpacks#922]
I am playing on the latest 1.18.2 version of Sophisticated Backpacks and recently got the backpack inception upgrade. From what I read on the curse forge/wiki websites apparently:

Only allows this on one level so no backpack in backpack in backpack
Upgrades in these backpacks will also work so you can have for example pickup upgrade in one of these picking up items directly into it
Upgrades in the main backpack can access inventory of the subbackpacks and there's an option that defines whether they use inventory in subbackpacks first or the main one first
Filter upgrade in subbackpacks can be used to limit what items get inserted / pulled from them
Backpacks in backpack can be open using open backpack keybind when cursor is over them

However when I attempt to use the crafting upgrade to craft things, the crafting upgrade is unable to pull items from the subbackpacks despite it stating that; "Upgrades in the main backpack can access inventory of the subbackpacks"

just wondering if this is an intended feature or if this is an issue on my end/mods end

**Comment by P3pp3rF1y** [comment]
I don't believe that was intended so I will take a look at whether I can switch it over to using all subbackpacks as well there may have been some limitation there but I don't recall it now

**Comment by P3pp3rF1y** [comment]
I looked into the logic but this would be complex to add and given the complexity and that inception upgrade is super powerful as is I am not going to add this functionality.
