### ISSUE TITLE
Backpack allows unstackable items to be pulled out in stacks

### ISSUE THREAD

**Issue by MuteTiefling** [P3pp3rF1y/SophisticatedBackpacks#925]
**Describe the bug**
Original report: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/693
If a backpack has stack upgrades in it and is storing unstackable items (potions), it will allow the extraction of more than 1 item as a stack. In this case, Thermal Pulverizers are able to extract a full stack of 64 potions from the backpack
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/9543430/1fdb4217-e787-4965-9144-b472029a126a)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/9543430/4b11f73f-ab08-4c4c-abe7-76eb34dbddbf)

**To Reproduce**
1. Place backpack in world
2. insert stack upgrades
3. put a bunch of  Lingering Regen II potions in there
4. set a thermal pulverizer to extract the potions so it can process them. It will grab them in alternating stacks of 64 and 1

Note, you'll obviously need custom recipes for this as these aren't default. For simplicity, you can see the issue in Enigmatica 9 Expert

**Expected behavior**
Items that are otherwise unstackable should not be allowed to be extracted at greater stacks than 1

**Screenshots**
See above

**Versions**
sophisticatedbackpacks-1.19.2-3.19.1.960

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release on curseforge.
