### ISSUE TITLE
Keybind crash in ATM9

### ISSUE THREAD

**Issue by aAndrew3030** [P3pp3rF1y/SophisticatedBackpacks#930]
Version .978 of the mod in ATM9 (version .31 of the pack) seems to be causing a crash when opening the backpack with the backpack keybind. 
https://github.com/AllTheMods/ATM-9/issues/997

I do not have a crash file or log, but I can try to create a new one if needed

**Comment by P3pp3rF1y** [comment]
Yeah I would need crash log or info from log file when this happens

**Comment by P3pp3rF1y** [comment]
Also I am not able to recreate in ATM9 and the other thing I noticed is that traveller's backpack uses the same keybind by default so check if you have both of them set to B and if the backpack you are trying to open is actually sophisticated one

**Comment by aAndrew3030** [comment]
Sorry, I got the versions mixed up, it was .30 of the pack with the issue. Version .31 updated Sophisticated Backpacks to version .978, and the issue seems to be fixed.

**Comment by P3pp3rF1y** [comment]
well both those versions of the modpack seem to use the same that is latest version of SB so the issue must have been somewhere else. Anyway closing this now given that there's no issue.
