### ISSUE TITLE
Magnet upgrade not working properly

### ISSUE THREAD

**Issue by MysteryKit66** [P3pp3rF1y/SophisticatedBackpacks#932]
**Describe the bug**
Using a magnet upgrade on the backpack it picks up items but doesn't stack them correctly filling your backpack up in no time. So harvesting stuff it creates stacks of 3/4 items in every empty slot and once all slots are filled it goes into your inventory. Only fixing for it atm is to click on ''sort backpack'' and evverything goes into a neat 64 stack for the time being.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Use the Magnet upgrade turn it on.
2. Mine, harvest lots of blocks/plants.
3. Notice stuff going into your inventory.
4. Open backpack and see whats wrong.

**Expected behavior**
When sing the magnet it should put all the items you gather into stacks without filling extra slots making it appear to be ''full''. But creating neat stacks of 64 til it's actually full.

**Screenshots**
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/89144000/ef9a8465-8bc9-4759-b4f8-c097a759ec57)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/89144000/b0f3d353-0e8a-4cb2-8795-1c7883725c69)

**Versions**
Minecraft 1.18.2
Sophisticated Backpacks: 1.18.2-3.19.1.9559.jar

**Comment by P3pp3rF1y** [comment]
you must have some mod in your pack that attaches data to stacks that's cleared off after so when they are being inserted they are different than the ones in the backpack, if you can figure out what mod that is let me know and I can find out if there's anything I can do about that.
I am sure this isn't reproducible with just SB in the pack as I am using this in multiple packs and have no issues with items stacking.

**Comment by MysteryKit66** [comment]
Well, took a bit to figure it out with some testing but. Even with all the mods on unactive the stacking doesn't seem to go as it should be.

This modpack is from a server i'm currently playing on tested it in single player. Maybe config files might be the problem? Or the Forge one i'm not sure.

Screenshot of the unactive/active mods.
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/89144000/c7069caf-1236-4278-a2dc-ea5697af5f47)

Results.
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/89144000/0b250a20-0b5b-49b3-a1ff-8773c7f68204)

Forge: 40.2.0?

**Comment by P3pp3rF1y** [comment]
I am unable to recreate that, tried with field of wheat and breaking masses of wheat and nothing. Everything will just stack properly.

So I will need to understand steps to recreate. 

Maybe CF isn't properly disabling those mods or not all of them are disabled?
Or are you potentially running this on a server? (there were issues before where some servers had modified versions of forge running which caused a number of issues)

**Comment by MysteryKit66** [comment]
I created a modpack with just the mod same versions of forge and SB and indeed no issues works like it should.

So i suppose it has to do with the server files then. The modpack they created we had to ''import'' it so files and all most likely.
The screenshots i tested it in a singleplayer world but the modpack is from a server not sure if that would give on the same result but suppose it does.

So i guess they are using a modified version of forge then? Not sure how that all works.

**Comment by P3pp3rF1y** [comment]
Well if you tested that in singleplayer then that modified version of server forge doesn't apply, I am pretty sure you only had a regular one there. But it's more likely that the mod that is causing these issues was enabled despite the fact that ui told you otherwise. Best way to tell is going into `mods` folder in the pack and seeing which ones still have `.jar` as an extension instead of ending with `.disabled` (which is what I believe CF launcher does when you disable).

**Comment by E420S** [comment]
Hello, I play on the same server. After removing the CustomNPC mod from the pack in singleplayer it was fixed. https://discord.com/channels/151785576557707264/423946043395407882/1161038425500160051
https://discord.gg/Bdarxs3Jgf
This is the discord for the mod and the file that is being used for the server. (Attached screenshot to show exact version of mod).
![Screenshot_42](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/154575558/065ce11a-68fd-43e1-b375-75bcf4435ca9)

**Comment by MysteryKit66** [comment]
Guess, that CF didn't put all mods on inactive then when i tested it out. Sorry late reply was inactive for few days because holidays approuching^

But suppose we have found the issue then^

**Comment by P3pp3rF1y** [comment]
> Guess, that CF didn't put all mods on inactive then when i tested it out. Sorry late reply was inactive for few days because holidays approuching^
> 
> But suppose we have found the issue then^

Yup and you will need to follow up on this with customNPCs they are adding something to the stacks (probably in capability data) but because this is just alpha builds and they are closed source there's not much more I can figure out here without spending a lot of time trying to dig through decompiled sources.
