### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by Lemoniakpl** [P3pp3rF1y/SophisticatedBackpacks#933]
**Describe the bug**
Hey, when i was playing your fantastic mod i see a litle problem with translation. I;m playing on polish translation and in the key binds there a little misspelling with word backpack. In english version is open backpack but now it is "otwórz plecam" and there is a key. Thre need to be a "otwórz plecak"
Goodbey

**To Reproduce**
1. Open sethings
2. Click on control/ key binds
3. go to your section of mode in polish version
4. See misspelling

**Expected behavior**
I expected to change it. I known it was a small issues but when you repair it i was very grateful, because at least once time someone listen me.

**Screenshots**
![obraz](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/154276666/8ca63be6-d0d5-4101-a494-27eab36e4f95)

**Versions**
forge 1.20.1

**Comment by P3pp3rF1y** [comment]
fixed this in 1.21 dev so from there on this will be fixed
