### ISSUE TITLE
"No tool was found that works on block"

### ISSUE THREAD

**Issue by Minxxinthegarden** [P3pp3rF1y/SophisticatedBackpacks#935]
I'm using the RAD 2 modpack. I have the advanced tool swapper upgrade for my backpack and I'm trying to make it so that when I press a specific key it will automatically set that tool as the proper one. However whenever I do go to use this it always says "no tool was found that works on block". This only started happening after I upgraded to the advanced version and it works fine on the base version. The only blocks that this doesn't affect are very specific blocks, such as grass blocks or wooden logs, but that only seems to work less than half the time.

Additionally, despite having a slot for a paxel, no paxel can be equipped.

**Comment by P3pp3rF1y** [comment]
I no longer support 1.16.5 version with any fixes other than pontetialy really critical ones, but this swapping is only meant for wrench like tools, basically items that do something with blocks on right click so just make sure that's what you are trying to do. left click action based swapping should work with plain old left click.

**Comment by P3pp3rF1y** [comment]
closing as 1.16.5 is unsupported and there doesn't seem to be follow up needed
