### ISSUE TITLE
Items vanish after server restart

### ISSUE THREAD

**Issue by LilliPJs** [P3pp3rF1y/SophisticatedBackpacks#938]
**Describe the bug**
Items within backpacks don't save after shutting down dedicated server

**To Reproduce**
1. Place items in backpack
2. Log off of server right after
3. Restart server
4. Join and open backpack
(Might take a couple tries)

**Expected behavior**
Items are expected to be in the backpack upon logging back in

**Versions**
Version: 3.19.4.978 NeoForge: 47.1.79

My guess is that the mod isnt saving the backpack as often as it should, as well as not saving when the server shuts down

**Comment by P3pp3rF1y** [comment]
It is definitely saving as soon as there's any kind of change otherwise this tracker would be swamped with this kind of bug reports. What server are you using?

**Comment by P3pp3rF1y** [comment]
closing given no response
