### ISSUE TITLE
Possible incompatibility with Iron's Spells or Presence Footsteps on 1.18.2

### ISSUE THREAD

**Issue by ssspons** [P3pp3rF1y/SophisticatedBackpacks#948]
**Describe the bug**
An entity spawns in with a backpack and a potion effect applied to it. Game crashes shortly afterwards.
Crashlog: https://pastebin.com/eYWaiDfg
Playing on a slightly modified CABIN (Create: Above & Beyond in Newer Versions) modpack. Tried updating Sophisticated Backpacks and Core to the newest 1.18.2 version and also tried upgrading to .939 of Sophisticated backpacks but the crash remains the same. I suspect it's an Iron's Spells incompatibility because I could join my world again once I removed Iron's Spells but I could not reproduce the bug in a clean minecraft instance with only the prerequisites and Sophisticated Backpacks and Iron's Spells. 

Edit: Removal of Presence Footsteps allows me to rejoin the world as well. Honestly I'm just going through that mixin stacktrace removing any mentioned mods one by one to check what the cause is but I'm way out of my depth here.

**To Reproduce**
1. Install Caelus API and Iron's Spells on CABIN and its prerequisites
2. Have an entity spawn in with a backpack and potion effect applied to it.

**Expected behavior**
Either an immediate crash or the Minecraft instance stops working, forcing the user to kill it.

**Screenshots**
n/a

**Versions**
Mod Version 1.18.2-3.18.60.906
Forge Version 40.2.17

**Comment by P3pp3rF1y** [comment]
This has nothing to do with Sophisticated Backpacks. It appears that one of the mods int he pack is removing forge code `PotionAddedEvent` or somehow causing it to not load. And as Sophisticated Backpacks or Core doesn't have any mixin at all it can't be the cause of this issue. You will also likely get the same crash when a potion gets applied to a mob in any other way (like throwing splash potion on them). The only way to have this fixed is figure out what mod is causing the code to be missing by removing mods until doesn't happen anymore.

**Comment by ssspons** [comment]
Good to know, thanks! I'll keep testing then.
