### ISSUE TITLE
sophisticated backpacks and atlantics crash question

### ISSUE THREAD

**Issue by Tsumiki129** [P3pp3rF1y/SophisticatedBackpacks#953]
hi i have been getting a crash part of a mod pack i test for relating to your mod and Atlantis mod the crash is as followed for replicating 

backpack in chest slot all other slots with there respective Armor of any type must be complete set helmet legs and boots with bag taking up chest slot spawned in Atlantis armor part of any type then game crashes with a class conflict

im more asking if this could be something relating to your mod or if you might agree with me and another that was looking at the crash reports on it weather this is actually an isue with Atlantis mod or not i alredy posted to them as a bug but got a prity pore attitude in return from them blaming it on your mod. 

here is the crash log to assits in seeing if its what we think being an isue with his or if it posibly could be yours though we do not believe its your mod to blame.

[crash-2024-01-18_23.49.27-server.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14001861/crash-2024-01-18_23.49.27-server.txt)

**Comment by P3pp3rF1y** [comment]
Just commented on that other issue. Clearly issue on their side that they need to fix. They will have an issue with any item that can go into armor slot that is not an armor. But I guess if you don't use their armor it should be good because in that case their logic won't run and thus won't crash.

**Comment by Tsumiki129** [comment]
cool thank you for the respons and confirming what i bereaved whas the isue someone that playes it axidentily trigerd the crash befor took time to fix but thanks again for the look into and quick responce
