### ISSUE TITLE
Client-side crashes when transferring items from the backpack

### ISSUE THREAD

**Issue by Wiliminlv** [P3pp3rF1y/SophisticatedBackpacks#955]
My game crashes when I transfer items inside the backpack while holding shift, it doesn't when I manually move items.
I'm in 1.19.2 with the Create+ [FORGE] mod pack, loaded with Curseforge on an Aternos server.

**To Reproduce**
1. Open backpack
2. Transfer any item inside in any way
3. Transfer it back to any inventory by holding shift and clicking
4. Crash (only client-side)

**Expected behavior**
The item transferring to my inventory without crashing

**Versions**
1.19.2-3.19.4.977

**Comment by P3pp3rF1y** [comment]
I will need the crash log to really know what's going on but sounds like just another case of smooth swapping mod to me

**Comment by Wiliminlv** [comment]
Yes it is, thanks, I'll delete smooth swapping
