### ISSUE TITLE
mouseevent crash after shift-clicking items OUT of crafting upgrade backpack, PLUS cannot "close" backpack with ESC after opening

### ISSUE THREAD

**Issue by hiimrickross** [P3pp3rF1y/SophisticatedBackpacks#957]
**Describe the bug**
https://pastebin.com/8NYd2ndV crashlog of when it happened

some other problems --- SmoothSwapping animation doesn't play, and cannot close the backpack without going into quest menu from it or similar first. Was trying to swap over to sophisticated storage & backpack, from travelers & iron chests: restocked, but having this severe crash from the get-go. Seems incompatible with something. I am using EMI+JEI. Also just saw it's incompatible with Apotheosis too.

This GUI crash happens on any of the ones - ie. magnet settings or block or smelting setting, etc. But if you just 'click' it with left click and pull it out manually, it doesn't crash. The magnet + pickup feature itself actually works, but yeah the mod + storage mod is like half functional for some reason

**To Reproduce**
1. Open backpack
2. Click on crafting upgrade tab.
3. Put items in manually, then shift-click them out. OR Open backpack, attempt to close backpack with Esc.
4. Game crashes, OR backpack doesn't close.

**Expected behavior**
SmoothSwapping animations to play with items in and out, crafting table to not crash, backpack to close.

**Versions**
47.2.6 forge, latest sophisticateds

**Comment by hiimrickross** [comment]
It seems this is a problem on BOTH Sophisticated mods - backpack and storage.

I also cannot exit out of Sophisticated Storage barrels, and likely will run into crash problems trying to explore their mods and upgrades later. Sophisticated Storage containers also don't play SmoothSwapping animation when putting items in and out. Seems like there is something(s) I have that is wildly incompatible with the Sophisticated Mods... a damn shame.

**Comment by P3pp3rF1y** [comment]
Smoothswapping doesn't seem to intend to fix their mod so it is incompatible with sophisticated mods. You will need to ask them to fix it or remove it.

**Comment by hiimrickross** [comment]
> Smoothswapping doesn't seem to intend to fix their mod so it is incompatible with sophisticated mods. You will need to ask them to fix it or remove it.

Ok so the issue IS indeed smoothswapping? thank you i will remove it and test everything again. theres also another mod named Flow that changes how the inventory opens with an animation, ie sliding in, sliding out. D you think that causes issues with Sophisticated too? maybe thats why the UI's won't close? After your response I went to the smoothswapping page and realized there was indeed other reports of problems with Sophistcated but couldn't see mentions of being unable to exit out of inventories which is what i was experiencing too. either way thank you for confirming the main culprit (SS), it is cool but I can go without it.

**Comment by P3pp3rF1y** [comment]
I didn't realize you had issues with closing UI, that's first time I am hearing about something like that but if you have a mod that changes how UIs open/close I would guess that's the culprit

**Comment by hiimrickross** [comment]
[sophisticatednaturesalexcaves.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14123193/sophisticatednaturesalexcaves.txt)

> I didn't realize you had issues with closing UI, that's first time I am hearing about something like that but if you have a mod that changes how UIs open/close I would guess that's the culprit

Yup it works and can close if I disable the "Ease Out" animation / closing animation for Flow. So I guess these mods / sophisticated suite just doesn't play well with things that alter inventory animation guis and things like that. Well, no biggy. SmoothSwapping & Flow were cool to have but more for show than anything. If I remove those two; the Sophisticated appears to work as intended. And definitely no crashing when shift-clicking things out of crafting/smelting GUI after removing Smooth Swapping.

The only thing I've run into problem wise after the fact is recipes in the backpack's crafting ui not yielding the right result, or not being able to be Polymorph changed into the right recipe. For example for some reason Iron Ingot x1 doesn't = Iron nuggets, but instead a Cincinninite (I can't remember the spelling.. is from Better Nether) Button, when attempted in the backpack.

**Comment by P3pp3rF1y** [comment]
Yeah that would be because sophisticated at the moment doesn't have support for multiple results so it just shows the first result it gets. I will likely add native support for multiple recipe results even when polymorph isn't around.
