### ISSUE TITLE
Crash on startup with latest Chipped

### ISSUE THREAD

**Issue by DelviousCrafts** [P3pp3rF1y/SophisticatedBackpacks#958]
**Describe the bug**
Chipped latest update causes crash on startup due when sophisticated backpacks and/or sophisticated storage is installed.

[Crash with Sophisticated Storage](https://gist.github.com/DelviousCrafts/50c7e6c304ee7b59e5fe532f42e69cf9)
[Crash without Sophisticated Storage](https://gist.github.com/DelviousCrafts/39ee051816098c8b4bbdf8f6353bcc55)

[Latest With](https://gist.github.com/DelviousCrafts/e44fb4e60c3ad7129400d4e8974400e7)
[Latest Without](https://gist.github.com/DelviousCrafts/d5b3d6d228d326de58290820bc91d44e)

**To Reproduce**
1. Install latest version of Chipped
2. launch game
3. crash

**Expected behavior**
The game not to crash on startup.

**Screenshots**
N/A

**Versions**
- Minecraft: 1.20.1
- Forge: 47.2.20
- Sophisticated Core: 0.5.113.524
- Sophisticated Backpacks: 3.19.5.988
- Sophisticated Storage: 0.8.65.680
- Athena: 3.1.1
- Resourceful Lib: 2.1.21
- Chipped: 3.0.2

**Comment by ModernGamingWorld** [comment]
Same crashes on server after updating Chipped

**Comment by drakray** [comment]
disabling `sophisticatedbackpacks:chipped/*TABLE*_upgrade` in `sophisticatedcore-common.toml` doesn't allow for loading either

**Comment by ghost** [comment]
I looked at the crash-report it's the Botanist Workbench Upgrade Type for Sophisticated Backpacks.

**Comment by P3pp3rF1y** [comment]
one of Chipped developers has reached out and they are doing refactoring, you can't get around this by disabling the upgrades. The only way is to either downgrade Chipped or sophisticated. I should hopefully get to this today and push a fixed release out

**Comment by drakray** [comment]
> one of Chipped developers has reached out and they are doing refactoring, you can't get around this by disabling the upgrades. The only way is to either downgrade Chipped or sophisticated. I should hopefully get to this today and push a fixed release out

Figured as much, I thought maybe disabling them would directly disable all integration, It was worth a try XD
I downgraded Chipped until SB is ready
Thank you for your good work :D

**Comment by P3pp3rF1y** [comment]
new release with fixed compat is out so you can just update both to latest
