### ISSUE TITLE
[1.18.2] Crash on death with backpack on

### ISSUE THREAD

**Issue by InteJason** [P3pp3rF1y/SophisticatedBackpacks#959]
**Describe the bug**
Server crashed when players die with a backpack on. Possibly caused by incompatibility between Epic Fight and Sophisticated Backpack?
https://mclo.gs/2E7W10O

**Versions**
Forge - 40.2.17
Sophisticated Backpack - 3.19.5.990
Sophisticated Core -0.5.111.526

**Comment by P3pp3rF1y** [comment]
Could you include crash log from crash-reports folder?

**Comment by InteJason** [comment]
https://mclo.gs/oL9f95G Should be this one

**Comment by P3pp3rF1y** [comment]
Looks like you will need to follow up with dawncraft_tweaks on that or dawncraft pack (no idea if tweaks are related). There's something going on with their code accessing backpack items during the time the backpack is dropped on death. Looks like they are trying to access it after it was dropped or it possibly is removed while they are trying to access it. Anyway this is definitely not for me to figure out as that's custom code injected in vanilla at the time when accessing items may be fragile especially with so many mods trying to change vanilla logic there. Let me know if they have more info that would point to some issue on my side, but I doubt it given how many packs and players run with the mod without any issue on death.

**Comment by P3pp3rF1y** [comment]
closing given no response
