### ISSUE TITLE
Backpack crashes game upon inventory opening (in Curious API slot)

### ISSUE THREAD

**Issue by DarkRift3r** [P3pp3rF1y/SophisticatedBackpacks#96]
So im playing on Valhelsia 3 and added the mod onto the modpack and it seems when i placed the backpack in the curious api slot it now crashes my game the instant i press e to open my inventory.

**Comment by P3pp3rF1y** [comment]
There's not much I can do with this report, I will need at the very least a crash log

**Comment by DarkRift3r** [comment]
[crash-2021-03-23_22.44.39-client.txt](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/6196870/crash-2021-03-23_22.44.39-client.txt)
Here's the crash log

**Comment by P3pp3rF1y** [comment]
The issue is with mod that only expects items of type ArmorItem to be rendered in armor slots while many other items can go in there. So it needs to be fixed there.

Looks to be Wildfire's Gender Mod which doesn't seem to be part of Valhesia

**Comment by DarkRift3r** [comment]
Yeah i had that added on to myself but if it's problem causing i'll remove it.
