### ISSUE TITLE
1.18.2 config

### ISSUE THREAD

**Issue by lolpowerluke** [P3pp3rF1y/SophisticatedBackpacks#966]
in the latest update, you made it so the backpacks can only have 1 type of furnace upgrade equiped
you also said that this can be changed in the config, but if i open the config I only see this (2nd img)
what do I have to add to make it so I can have multiple furnace upgrades again?
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/47672899/8946b026-6c83-4eaa-865e-b6c0261db043)
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/47672899/905aeb92-b224-4275-8987-0491ba2349dc)

**Comment by P3pp3rF1y** [comment]
You need to look in server config that in single player is in your save's serverconfigs folder
