### ISSUE TITLE
backpacks work when worn on entities?

### ISSUE THREAD

**Issue by CheryMarie** [P3pp3rF1y/SophisticatedBackpacks#968]
im using a mod where you hire a follower with emeralds he can equip armour and sword. I  just checked this out but if he wears the backpack i cant access it when it is on his back and magnet upgrades ect do not work. it would be really good if he could carry things while following me so i can use my inventory for things i need?

**Comment by P3pp3rF1y** [comment]
In terms of upgrades working that would be up to the other mod to make items tickable that are in armor slots (at least that's my guess that's where you're putting the upgrade). 
As for opening that would be tough to do in general as the backpack can be worn by many different entities and in all so far it's not supposed to be open by player so there would need to be some way of configuring that it can be open on entity and there would also need to be some way of configuring how high / in what rotation it's supposed to be open. I feel like this would require a lot of fiddling and a lot of time spent on making it work for what is a very minor thing really.

**Comment by CheryMarie** [comment]
the backpack renders fine on the mob but ill mention it to the devs x
thank you x

**Comment by P3pp3rF1y** [comment]
Closing this one as the only open question of backpacks ticking needs to be solved by the other mod.
