### ISSUE TITLE
Stack Upgrade duplication bug - using the Quark extract inventory button.

### ISSUE THREAD

**Issue by uLLeticaL** [P3pp3rF1y/SophisticatedBackpacks#97]
**Describe the bug**
Able to duplicate items with the Stack Upgrade, using Quark's extract inventory button.
It will duplicate anything that is above the stack size.

**To Reproduce**
1. Insert the Stack Upgrade.
2. Add 1 stack of any item type, eg. stone.
3. Add 1 more stone to the stack in the backpack -> 65 stone.
4. Use the extract button.
5. You now have 64+1 stone in your normal inventory, and 1 in the backpack -> 66 stone total.

**Screenshots**
1. Example with 2 stone stacks.
![image](https://user-images.githubusercontent.com/6973857/112555668-eb902480-8dc8-11eb-9273-1d982d5572c8.png)

2. Duped a full stack.
![image](https://user-images.githubusercontent.com/6973857/112555688-f64ab980-8dc8-11eb-8c29-c397b91e148f.png)

**Versions**
Tested on Forge `36.0.58` and `36.1.2`
Mods
```
sophisticatedbackpacks-1.16.4-2.2.7.222.jar
AutoRegLib-1.6-47.jar
Quark-r2.4-308.jar
jei-1.16.5-7.6.1.75.jar
```

**Comment by P3pp3rF1y** [comment]
This is an issue in Quark where it puts the full 128 item stack into players inventory and then only extracts a maximum of 64 from backpack. (so yeah however big that stack is the transfer button will always try to transfer the whole thing and then only extract 64. 
https://github.com/Vazkii/Quark/blob/3fb58edebd949b82da808720e2daebfac71a7025/src/main/java/vazkii/quark/base/handler/InventoryTransferHandler.java#L231-L235

Unfortunately there isn't a way I can provide a compatibility for this as Quark only supports transfer compatibility implementations for TileEntities and obviously item backpack can't be a tile entity.

I will see if there's a way for me to ban these buttons in backpack screen then.

**Comment by P3pp3rF1y** [comment]
This is now fixed by disabling the quark buttons (unfortunately all of them) in backpack screen. I will release the build with fix probably later today.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF
