### ISSUE TITLE
Slot memory and No Sort Slot setting

### ISSUE THREAD

**Issue by alejandrois22** [P3pp3rF1y/SophisticatedBackpacks#977]
**Describe the bug**
There's a bug when using inception upgrade and setting backpacks inside the main backpack with no sort or memory slot settings that causes to lose the ability to see if an item is in one of the backpacks or can put item inside the backpack using right click. This only happens when the backpacks are selected using memory or no sort slot settings. It's pretty annoying because if I want to sort my main backpack and don't want to move the other backpacks inside of it then I can't add items to the backpacks in the main one because doesn't show the plus (+) symbol nor can see what's in them when hovering.

**To Reproduce**
1. Open backpack
2. Click on no sort tab
3. Select backpacks inside main backpacks
4. See error when dragging up an item to the backpacks with no sort setting or memory slot.

**Expected behavior**
Selecting the backpacks inside of a main backpack with the no sort setting or memory setting for it to not move when sorting should still let the player know if an item can be added to the subsequent backpacks showing the plus sign (+) and let the player put the item inside of the desired backpack

**Screenshots**
In this image the backpacks with the plus sign are not selected with the memory slot or no sort setting.
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/99363658/62aed322-3952-438a-9d57-35eef6ff1b4f)

In this second image the backpacks are selected as backpacks not to sort and the plus sign dissapeared even with an item on mouse.
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/99363658/83b59c42-9607-44d9-bd7d-1eb1e5b73e88)

**Versions**
Forge version 3.19.8.1000

**Comment by P3pp3rF1y** [comment]
This was fixed with the last SB release on curseforge
