### ISSUE TITLE
Crash when "shift+left click" on an item or free slot in backpack and storage

### ISSUE THREAD

**Issue by Tony2407** [P3pp3rF1y/SophisticatedBackpacks#978]
Hi,

I'm playing Minecraft with a modpack on Curseforge with the name: "Create+ [Forge]" which has the following version: v5.0 - 1.19.2.
This modpack has the backpacks and storage of the sophisticated mod.

**Issue:**

1. When I press `shift + left click` on an item in the backpack or storage it immediately causes a crash.
2. In addition to that, sometimes also crashes when I just `Shift+L-Click` in a **free backpack or storage slot**. But I can't replicate this bug every time so I don't know why it crashes her too.

Sometimes vanilla items will not cause a crash, just items from every other mod or items I found in chests for example in the nether.
So 98% of the items are kicking me out of the game xD

**Settings of the sophisticated mod:**
In the "storage settings" of the storage and the backpack, it is set to "Player" and "Shift Click Into Open Tab First".
As you can see in the picture below. I believe that this is still set like it was in default and I didn't change anything else in sophisticated.

![grafik](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/86288661/32b483cd-64d9-46aa-a030-f314e6bb4504)

We are 3 people on the server and every one of us has the same problem.

Here is my crash-report:
[https://pastebin.com/Gy39Fj8N](https://pastebin.com/Gy39Fj8N)

Hope someone here has some idea how to fix this!
Thanks in advance.

Toni = )

**Comment by P3pp3rF1y** [comment]
remove smoothswapping and issue is solved, they crash sophisticated and need to fix this bug, but haven't in so many months now

**Comment by Tony2407** [comment]
Perfect! Thank you so much! = D
