### ISSUE TITLE
how do I disable stack upgrade limit?? 1.18.2

### ISSUE THREAD

**Issue by jaydee54** [P3pp3rF1y/SophisticatedBackpacks#980]
**Describe the bug**
I'm getting an error message every time I try to add more than 3 stack upgrades to a backpack or to sophisticated storage. how do i disable that because my config only contains this:

#Common Settings
[common]
	#Turns on/off loot added to various vanilla chest loot tables
	chestLootEnabled = true

mobs also no longer spawn with backpacks, and the setting to configure which mobs get one is gone as well.

im using the latest version of 1.18.2

**Comment by P3pp3rF1y** [comment]
`maxUpgradesPerStorage` in SB server config the other stuff is there as well
