### ISSUE TITLE
Copper backpack can't be washed in water cauldron

### ISSUE THREAD

**Issue by drakray** [P3pp3rF1y/SophisticatedBackpacks#981]
**Describe the bug**
As the title says, Copper Backpack can't be washed in cauldron when right-clicking a water cauldron, unlike Regular, Iron, et.

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Get Copper Backpack from random mob
2. Get water cauldron
3. Try to wash to remove dye
4. ???
5. No profit

**Expected behavior**
For backpack to be clean from mob usage

**Screenshots**

**Versions**
Minecraft 1.20.1
Neoforge 47.1.100
sophisticatedcore-1.20.1-0.6.3.553
sophisticatedbackpacks-1.20.1-3.20.1.1012
ManyMoreMods™
On dedicated server

**Comment by P3pp3rF1y** [comment]
This was fixed with release a few days back
