### ISSUE TITLE
Backpack Dissapears With Immersive Portals

### ISSUE THREAD

**Issue by Wolf-206** [P3pp3rF1y/SophisticatedBackpacks#982]
When I try to go through a nether portal with the immersive portals mod enabled, the backpack pretty much vanishes. It is in the back's slot of another mod I forgot the name of, but I think it had to do with an elytra slot or a totem slot, and it allowed an elytra (or any chest piece) to be worn at the same time as armor, along with a few other slots I'm yet to find what do, as I've just been playing survival with them. I wouldn't be surprised to find this error has to do with the immersive portals mod, or that other mod giving the extra slots, rather than the sophisticated backpacks mod, so I plan to post this there as well, assuming it isn't already posted there. This is in the version 1.20.1, as that is the version I've been playing in, as it is the current latest version compatible with the projecte mod.

**Comment by P3pp3rF1y** [comment]
Yup, I don't do anything with moving backpack between slots / adding / removing it from player. The only logic that exists in backpacks related to these slots is the lookup that allows you to open backpack in those slots using keybind. So you will need to report that to immersive portals / curios (though I would say curios is pretty much for sure in a clear here given how widely it is used and I am not aware of issues like this). It's probably immersive portals overriding some vanilla / forge logic which makes curios not restore stacks in it when player passes through portal.

**Comment by P3pp3rF1y** [comment]
Anyway I am going to close this one, feel free to reopen if they have some info that clearly points at sophisticated being the culprit.
