### ISSUE TITLE
[1.20.1] Download For a Server

### ISSUE THREAD

**Issue by Madajel** [P3pp3rF1y/SophisticatedBackpacks#985]
With both API & mod on the server's mod folder, i'm not able to launch the server.
Compatibility issues.

I would like to understand if i did something wrong about this or not.

Thank you !

![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/141425428/5856d3ae-c13b-41fe-b361-17c78396551a)

MC Version : 1.20.1
Forge version : 1.20.1-47.2.0

**Comment by P3pp3rF1y** [comment]
You have ancient version of backpacks there and the most up to date version of core that's not going to work. Just update backpacks to latest as well

**Comment by Madajel** [comment]
It's the last version i can have on minecraft-france.fr, just for you to know.

Thank you for your answer, have a good day !

**Comment by P3pp3rF1y** [comment]
Just don't use that site in that case. I and almost all other mod developers only post new versions of our mods on curseforge and some also post them on modrinth. All the other sites are in the better case linking to the official places and many are even worse - they repost the files taking away any kind of rewards from mod developers and some even include malware in the downloads
