### ISSUE TITLE
weird bug causing memory issue

### ISSUE THREAD

**Issue by Vadewolf** [P3pp3rF1y/SophisticatedBackpacks#990]
**Describe the bug**
Crash log if it's a crash.
Info on what other mods you're using that may cause a conflict here if applicable.

all ik is this issue happened after the mod update for 3/4/2024

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Open backpack
2. Click on '....' tab
3. Do something
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14489130/latest.log)

**Expected behavior**

**Screenshots**

**Versions**
Mod version that you're using. Version of forge may also be helpful in some cases
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/18257282/8c3823fe-c679-42e1-a7dd-6e8ed12cbf93)

**Comment by P3pp3rF1y** [comment]
What is '....' tab? I don't have anything like that in my mod.

**Comment by Vadewolf** [comment]
huh? wat mod are u talking bout

**Comment by Vadewolf** [comment]
btw feel free to ping me in discord my name is CharliePratt on there

**Comment by Vadewolf** [comment]
btw found out the only "tab" mod i have is L2tabs but idk wat mod its from

**Comment by P3pp3rF1y** [comment]
all I need to understand is what is '....' tab? that's not a sophisticated thing as sophisticated uses icons and I don't know of any that would look like 3 dots.
Maybe just share screenshot of that so that I can understand what that might be

**Comment by Vadewolf** [comment]
idek wat it is tho also something with the versions from 3/4/2024 update are causing a massive memory leak issue

**Comment by Vadewolf** [comment]
@P3pp3rF1y are u talking bout this ?
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/18257282/ed86771b-bd83-4b2d-b7ae-8b92a479b6ee)

**Comment by P3pp3rF1y** [comment]
yeah I don't know what that tab is and the other thing is how do you know that something is causing massive memory issue? Also that error that's mentioned in #4 is something with JER, nothing I can do about that

**Comment by Vadewolf** [comment]
ok so that tab thing was wat was listed on the bug report thing i never added that so idk also when i go to exit game my game takes forever to close to the point of my memory going above the 8gb ive given it and ik its something with the latest versions of SS SB and SC but idk wat or how to find it

**Comment by Vadewolf** [comment]
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/18257282/beba2a1b-0507-4fe0-b0cc-2de4f0ff9158)


its causing this on memory to go way to high

**Comment by Vadewolf** [comment]
![image](https://github.com/P3pp3rF1y/SophisticatedBackpacks/assets/18257282/bbcf644c-dbd9-4079-8cbd-aa0eb830da3c)

btw this is with it running before the latest versions for all 3 mods

**Comment by Vadewolf** [comment]
https://spark.lucko.me/ERbxPcLIxR

spark profile idk how this will help since its simething with the latest versions on SC SS and SB thats causing it

**Comment by P3pp3rF1y** [comment]
That link appears to be invalid - doesn't show any result

Try using `/spark heapsummary` when a lot of memory is used and see what that produces.

**Comment by Vadewolf** [comment]
ill try but as i said in discord idk wat im doing so

**Comment by Vadewolf** [comment]
https://spark.lucko.me/L05hvRrw7t

heres this but idk wat im doing tho

**Comment by Vadewolf** [comment]
[latest.log](https://github.com/P3pp3rF1y/SophisticatedBackpacks/files/14526809/latest.log)

latest as of 3/7/2024 so hopefully u can figure out y the latest versions break my game pls

**Comment by Vadewolf** [comment]
btw if it helps i did test this same issue without updating SB and i still had the issue so its something with SS or SC

**Comment by P3pp3rF1y** [comment]
I was never able to see any memory leak, the highest memory allocation I found is a bit of logic in rendering that could get its allocation reduced from 1MB to 250kB which is nowhere close to 1GB that you were seeing for some reason in your pack. And I haven't got any other report of any memory leak so I am closing this.
