### ISSUE TITLE
Inventory of Backpacks not being backed up correctly when restoring a server backup. 

### ISSUE THREAD

**Issue by Spoon0fDisaster** [P3pp3rF1y/SophisticatedBackpacks#991]
So I run a server using Bisect hosting, and someone accidentally went through the end portal before we were going to fight the dragon. So, I used an automatic backup save and restored the server to that, the backup being from 3 hours before the incident. When we loaded back into the server some items were just completely missing, these were items that were taken out of the backpack and placed into a player's inventory after the automatic backup was created. I'm unsure of how to get these items back, and why the sophisticated backpack data isn't saved along with the backup. The missing items were 100% in the backpacks when the backup save was created, so shouldn't that data be restored with everything else?? I have a few other mods on the server and I don't see how any of them would cause this issue. 

For reference, I play on 19.2 and have never had this issue happen or at least never noticed it.

**Comment by ElectricVersion** [comment]
Most likely when restoring a backup it didn't copy the <worldname>/data/sophisticatedbackpacks.dat file from the backup to the server - in my experience using FTBBackups it should by default be saved along with the rest of the backup, but if you're doing backups through the host it would depend on how they handle it. Either way I would check that file

**Comment by P3pp3rF1y** [comment]
Right, sophisticatedbackpacks.dat contains all of the backpack contents. You need to make sure it's being restored with the backup. 
I am going to leave this here for a bit in case you have some additional feedback you can provide, but this really sounds like the case of just copying the file over or the worse case of backup potentially not backing up the file, but in that case you would need to follow up with the backup mod.

**Comment by P3pp3rF1y** [comment]
closing given no additional follow up
