### ISSUE TITLE
Access to backpack in Curios slot[1.19.2]

### ISSUE THREAD

**Issue by Orangejewce92** [P3pp3rF1y/SophisticatedBackpacks#993]
**Describe the bug**
Player wearing a backpack in their Curios slot .
Anyone has access to. ( by right clicking )

Please go to [Discussions](https://github.com/P3pp3rF1y/SophisticatedBackpacks/discussions) to add new feature requests / suggestions or comment on existing ones.

**To Reproduce**
1. Wear Backpack on Curios
2. Another player access by right click

**Expected behavior**
Not to be able to open

**Screenshots**

**Versions**
Backpack: 3.20.1.1013
Forge 1.19.2 43.3.8

**Comment by Orangejewce92** [comment]
https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbXJqcnJlYmZ4MmZqY2hzNnNza2Q4ODdrOGpkYzhhMTZ3NGV5OHJ5dCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/pwYpke7upPREeJ5Lav/giphy.gif

**Comment by P3pp3rF1y** [comment]
Yes that's a feature and so is setting in backpack settings that allows turning this off for that specific backpack or all backpacks of the player and there's also config that allows turning it off for all backpacks.

**Comment by Orangejewce92** [comment]
Thanks for the clarification!
